/* tslint:disable */
require("./EmployeeDirectory.module.css");
const styles = {
  container: 'container_fbbd9e16',
  toolbar: 'toolbar_fbbd9e16',
  searchBox: 'searchBox_fbbd9e16',
  filterDropdown: 'filterDropdown_fbbd9e16',
  viewToggle: 'viewToggle_fbbd9e16',
  viewBtn: 'viewBtn_fbbd9e16',
  viewBtnActive: 'viewBtnActive_fbbd9e16',
  clearBtn: 'clearBtn_fbbd9e16',
  exportExcelBtn: 'exportExcelBtn_fbbd9e16',
  alphabetBar: 'alphabetBar_fbbd9e16',
  letterBtn: 'letterBtn_fbbd9e16',
  active: 'active_fbbd9e16',
  resultMeta: 'resultMeta_fbbd9e16',
  paginationInline: 'paginationInline_fbbd9e16',
  filterBadge: 'filterBadge_fbbd9e16',
  grid: 'grid_fbbd9e16',
  size_small: 'size_small_fbbd9e16',
  size_medium: 'size_medium_fbbd9e16',
  size_large: 'size_large_fbbd9e16',
  card: 'card_fbbd9e16',
  chatBtn: 'chatBtn_fbbd9e16',
  cardHeader: 'cardHeader_fbbd9e16',
  avatarWrap: 'avatarWrap_fbbd9e16',
  presenceDot: 'presenceDot_fbbd9e16',
  avatar: 'avatar_fbbd9e16',
  initials: 'initials_fbbd9e16',
  cardBody: 'cardBody_fbbd9e16',
  userName: 'userName_fbbd9e16',
  jobTitle: 'jobTitle_fbbd9e16',
  statusBadges: 'statusBadges_fbbd9e16',
  statusBadge: 'statusBadge_fbbd9e16',
  statusDisabled: 'statusDisabled_fbbd9e16',
  statusGuest: 'statusGuest_fbbd9e16',
  cardDetails: 'cardDetails_fbbd9e16',
  detail: 'detail_fbbd9e16',
  detailIcon: 'detailIcon_fbbd9e16',
  link: 'link_fbbd9e16',
  listTable: 'listTable_fbbd9e16',
  listHead: 'listHead_fbbd9e16',
  listTh: 'listTh_fbbd9e16',
  listRow: 'listRow_fbbd9e16',
  listTd: 'listTd_fbbd9e16',
  listNameCell: 'listNameCell_fbbd9e16',
  listAvatarWrap: 'listAvatarWrap_fbbd9e16',
  listAvatar: 'listAvatar_fbbd9e16',
  listInitials: 'listInitials_fbbd9e16',
  listName: 'listName_fbbd9e16',
  listCell: 'listCell_fbbd9e16',
  listLink: 'listLink_fbbd9e16',
  listCustomAttrCell: 'listCustomAttrCell_fbbd9e16',
  listChatBtn: 'listChatBtn_fbbd9e16',
  srOnly: 'srOnly_fbbd9e16',
  centered: 'centered_fbbd9e16',
  errorMsg: 'errorMsg_fbbd9e16',
  noResults: 'noResults_fbbd9e16',
  pagination: 'pagination_fbbd9e16',
  pageBtn: 'pageBtn_fbbd9e16',
  pageInfo: 'pageInfo_fbbd9e16',
  themeMinimal: 'themeMinimal_fbbd9e16',
  themeCorporate: 'themeCorporate_fbbd9e16',
  themeCustom: 'themeCustom_fbbd9e16',
  themeDark: 'themeDark_fbbd9e16'
};

export default styles;
/* tslint:enable */