define([], function () {
  return {
    // ── Property pane: pane header / groups ──
    PropertyPane_HeaderDescription: 'إعدادات Smart Org Chart',
    PropertyPane_Group_General: 'عام',
    PropertyPane_Group_Branding: 'العلامة التجارية',
    PropertyPane_Group_VisualStyle: 'النمط المرئي',
    PropertyPane_Group_DataSource: 'مصدر البيانات',
    PropertyPane_Group_CustomAttributes: 'السمات المخصصة',
    PropertyPane_Group_UserFilters: 'عوامل تصفية المستخدمين',
    PropertyPane_Group_OrgChart: 'المخطط التنظيمي',
    PropertyPane_Group_OrgChartFeatures: 'ميزات المخطط التنظيمي',
    PropertyPane_Group_Directory: 'الدليل',
    PropertyPane_Group_Demo: 'العرض التوضيحي',

    // ── Property pane: General ──
    PropertyPane_DefaultView_Label: 'العرض الافتراضي',

    // ── Property pane: Branding ──
    PropertyPane_AppTitle_Label: 'عنوان التطبيق',
    PropertyPane_AppTitle_Placeholder: 'Contoso Org Chart',
    PropertyPane_AppTitle_Description: 'يظهر في شريط الرأس بجانب اسم العرض',
    PropertyPane_LogoUrl_Label: 'عنوان URL للشعار',
    PropertyPane_LogoUrl_Placeholder: 'https://contoso.sharepoint.com/sites/yoursite/SiteAssets/logo.png',
    PropertyPane_LogoUrl_Description: 'عنوان URL كامل لصورة بتنسيق PNG أو SVG أو JPG. تلميح: افتح ملف الصورة في المستعرض وانسخ العنوان من شريط العنوان. روابط المشاركة من نوع "نسخ الارتباط" لن تعمل.',
    PropertyPane_DirectoryLabel_Label: 'تسمية عرض دليل الموظفين',
    PropertyPane_OrgChartLabel_Label: 'تسمية عرض المخطط التنظيمي',
    PropertyPane_ViewLabel_Description: 'اتركه فارغًا لاستخدام الاسم الافتراضي، أو اكتب "[blank]" لإخفاء التسمية تمامًا.',

    // ── Property pane: Visual Style ──
    PropertyPane_ChartTheme_Label: 'سمة المخطط',
    PropertyPane_Theme_Modern: 'عصري — ألوان الأقسام على خلفية بيضاء',
    PropertyPane_Theme_Minimal: 'بسيط — تباين منخفض ومسطح',
    PropertyPane_Theme_Corporate: 'مؤسسي — أزرق موحّد',
    PropertyPane_Theme_Dark: 'داكن — خلفية كحلية داكنة',
    PropertyPane_Theme_Custom: 'مخصص — اختر لونك الخاص',
    PropertyPane_AccentColor_Label: 'لون التمييز المخصص',
    PropertyPane_AccentColor_PickerAriaLabel: 'أداة اختيار لون التمييز',
    PropertyPane_AccentColor_HexLabel: 'Hex',
    PropertyPane_AccentColor_HexAriaLabel: 'القيمة السداسية العشرية للون التمييز',
    PropertyPane_AccentColor_RgbLabel: 'RGB',
    PropertyPane_AccentColor_ChannelAriaLabel: 'قناة {name} (من 0 إلى 255)',
    PropertyPane_AccentColor_ContrastWithWhite: 'التباين مع الأبيض: {ratio}:1 ({passes})',
    PropertyPane_AccentColor_PassesAA: 'يجتاز معيار AA',
    PropertyPane_AccentColor_LargeTextOnly: 'للنص الكبير فقط',
    PropertyPane_AccentColor_LowContrast: 'تباين منخفض',
    PropertyPane_AccentColor_DarkTextNote: 'سيتم استخدام نص داكن فوق هذا اللون لتحسين قابلية القراءة.',
    PropertyPane_AccentColor_DarkerShadeNote: 'ستستخدم العناوين والروابط درجة أغمق ({hex}) لتحسين قابلية القراءة.',
    PropertyPane_AccentColor_InvalidHex: '"{typed}" ليس لونًا سداسيًا عشريًا صالحًا. استخدم قيمة مثل #0078d4 أو #07d.',
    PropertyPane_DefaultFontSize_Label: 'حجم الخط الافتراضي',
    PropertyPane_FontSize_75: '75% — صغير جدًا',
    PropertyPane_FontSize_85: '85% — صغير',
    PropertyPane_FontSize_100: '100% — عادي',
    PropertyPane_FontSize_115: '115% — كبير',
    PropertyPane_FontSize_130: '130% — كبير جدًا',
    PropertyPane_FontSize_150: '150% — XXL',
    PropertyPane_FontSize_175: '175% — XXXL',
    PropertyPane_DefaultLayout_Label: 'التخطيط الافتراضي للمخطط التنظيمي',
    PropertyPane_Layout_Drill: 'التنقّل التدريجي',
    PropertyPane_Layout_Vertical: 'من الأعلى إلى الأسفل',
    PropertyPane_Layout_Horizontal: 'من اليسار إلى اليمين',

    // ── Property pane: Data Source ──
    PropertyPane_DataSource_Label: 'من أين يتم تحميل بيانات المستخدمين والمؤسسة',
    PropertyPane_DataSource_Auto: 'تلقائي — Microsoft Graph، مع الرجوع إلى بحث SharePoint',
    PropertyPane_DataSource_Graph: 'Microsoft Graph — بيانات Azure AD مباشرة (بدون تأخير الفهرسة)',
    PropertyPane_DataSource_Search: 'بحث SharePoint — السلوك التقليدي',
    PropertyPane_DataSource_Note: 'يُوصى باستخدام Microsoft Graph. فهو يقرأ البيانات مباشرة من Azure Active Directory بحيث يظهر المستخدمون الجدد وتغييرات المديرين فورًا. يتطلب الموافقة على أذونات Microsoft Graph في كتالوج تطبيقات SharePoint.',

    // ── Property pane: Custom Attributes ──
    PropertyPane_CustomAttributes_Note: 'تتطلب السمات المخصصة استخدام Microsoft Graph (مصدر البيانات: Graph أو تلقائي). لا تتوفر في بحث SharePoint طريقة عامة لقراءة سمات Entra ID.',
    PropertyPane_CustomAttributes_Heading: 'إدارة السمات المخصصة',
    PropertyPane_CustomAttributes_Empty: 'لم يتم تكوين أي سمات مخصصة.',
    PropertyPane_CustomAttributes_AddButton: '+ إضافة سمة',
    PropertyPane_CustomAttributes_MaxTooltip: 'الحد الأقصى {max} من السمات المخصصة',
    PropertyPane_CustomAttributes_FieldNameLabel: 'اسم السمة',
    PropertyPane_CustomAttributes_FieldPlaceholder: 'مثال: companyName',
    PropertyPane_CustomAttributes_FieldError: 'استخدم employeeId أو companyName أو city أو ... أو extensionAttribute1-15',
    PropertyPane_CustomAttributes_DisplayLabelLabel: 'تسمية العرض',
    PropertyPane_CustomAttributes_LabelPlaceholder: 'مثال: مركز التكلفة',
    PropertyPane_CustomAttributes_RemoveTitle: 'إزالة السمة',
    PropertyPane_CustomAttributes_RemoveAriaLabel: 'إزالة السمة {ordinal}',
    PropertyPane_CustomAttributes_ShowInDirectory: 'إظهار في الدليل',
    PropertyPane_CustomAttributes_ShowInOrgChart: 'إظهار في المخطط التنظيمي',

    // ── Property pane: User Filters ──
    PropertyPane_ExcludedAccounts_Label: 'استبعاد الحسابات',
    PropertyPane_ExcludedAccounts_Placeholder: 'conf-room, noreply, admin@, Service Account',
    PropertyPane_ExcludedAccounts_Description: 'كلمات أو أنماط مفصولة بفواصل (بدون تمييز بين الأحرف الكبيرة والصغيرة). سيتم إخفاء أي مستخدم يحتوي اسمه المعروض أو بريده الإلكتروني أو UPN الخاص به على أحد هذه العناصر من جميع طرق العرض.',
    PropertyPane_RestrictTenant_Label: 'إظهار مستخدمي المستأجر فقط',
    PropertyPane_RestrictTenant_On: 'تشغيل — إخفاء الحسابات ذات نطاقات البريد الإلكتروني الخارجية (مثل gmail.com وhotmail.com)',
    PropertyPane_RestrictTenant_Off: 'إيقاف — يتم إظهار جميع المستخدمين بغض النظر عن نطاق البريد الإلكتروني',
    PropertyPane_HideGuest_Label: 'إخفاء حسابات الضيوف في Azure AD',
    PropertyPane_HideGuest_On: 'تشغيل — حسابات الضيوف مخفية',
    PropertyPane_HideGuest_Off: 'إيقاف — حسابات الضيوف ظاهرة (تظهر بشارة ضيف)',
    PropertyPane_HideDisabled_Label: 'إخفاء الحسابات المعطّلة',
    PropertyPane_HideDisabled_On: 'تشغيل — الحسابات المحظور تسجيل دخولها مخفية',
    PropertyPane_HideDisabled_Off: 'إيقاف — الحسابات المعطّلة ظاهرة (تظهر بشارة معطّل)',
    PropertyPane_HideDisabled_Note: 'ملاحظة: يتطلب اكتشاف حسابات الضيوف والحسابات المعطّلة مصدر بيانات Microsoft Graph. لا يعيد بحث SharePoint هذه المعلومات، لذا لا تأثير لهذين الفلترين (وشارتي ضيف/معطّل) عندما تأتي البيانات من البحث.',
    PropertyPane_HideNoJobTitle_Label: 'إخفاء الحسابات التي لا تحتوي على مسمى وظيفي',
    PropertyPane_HideNoJobTitle_On: 'تشغيل — الحسابات بلا مسمى وظيفي مخفية',
    PropertyPane_HideNoJobTitle_Off: 'إيقاف — تظهر جميع الحسابات بغض النظر عن المسمى الوظيفي',
    PropertyPane_HideNoDept_Label: 'إخفاء الحسابات التي لا تحتوي على قسم',
    PropertyPane_HideNoDept_On: 'تشغيل — الحسابات بلا قسم مخفية',
    PropertyPane_HideNoDept_Off: 'إيقاف — تظهر جميع الحسابات بغض النظر عن القسم',

    // ── Property pane: Org Chart ──
    PropertyPane_TopLevelUser_Label: 'المستخدم في المستوى الأعلى (UPN أو البريد الإلكتروني)',
    PropertyPane_TopLevelUser_Placeholder: 'ceo@yourcompany.com',
    PropertyPane_TopLevelUser_Description: 'الشخص الذي يظهر عند جذر المخطط التنظيمي',
    PropertyPane_LevelsBelow_Label: 'عدد المستويات المطلوب تحميلها أسفل الجذر',
    PropertyPane_DottedLine_Label: 'سمة المدير ذي الخط المتقطع',
    PropertyPane_DottedLine_Placeholder: 'extensionAttribute10',
    PropertyPane_DottedLine_Description: 'اختياري. اسم سمة Azure AD الموسّعة المحلية (extensionAttribute1-15) التي تخزّن البريد الإلكتروني أو UPN لمدير ثانوي بخط "متقطع". تظهر علاقات الخط المتقطع في بطاقات الملفات الشخصية. يتطلب مصدر بيانات Microsoft Graph.',
    PropertyPane_DefaultZoom_Label: 'التكبير/التصغير الافتراضي للمخطط التنظيمي',
    PropertyPane_Zoom_Auto: 'افتراضي (احتواء تلقائي)',
    PropertyPane_Zoom_50: '50%',
    PropertyPane_Zoom_75: '75%',
    PropertyPane_Zoom_100: '100%',
    PropertyPane_Zoom_125: '125%',
    PropertyPane_Zoom_150: '150%',

    // ── Property pane: Org Chart Features ──
    PropertyPane_FeatureToggles_Note: 'إظهار أو إخفاء أزرار شريط الأدوات في عرض المخطط التنظيمي.',
    PropertyPane_FindMe_Label: 'زر البحث عن موقعي',
    PropertyPane_LayoutToggle_Label: 'تبديل التخطيط (تدريجي/رأسي/أفقي)',
    PropertyPane_Stats_Label: 'شريط إحصاءات المؤسسة',
    PropertyPane_DeptFilter_Label: 'عامل تصفية القسم',
    PropertyPane_UserFilter_Label: 'عامل تصفية نوع المستخدم (أعضاء/ضيوف)',
    PropertyPane_Visible: 'ظاهر',
    PropertyPane_Hidden: 'مخفي',

    // ── Property pane: Directory ──
    PropertyPane_PageSize_Label: 'الحد الأقصى للموظفين في كل صفحة',
    PropertyPane_PageSize_AriaLabel: 'الحد الأقصى للموظفين في كل صفحة (من 10 إلى 200)',
    PropertyPane_PageSize_Note: 'يتم تعيين حجم البطاقة والحقول الظاهرة وتفضيلات العرض الأخرى لكل مستخدم عبر رمز الإعدادات في التطبيق.',

    // ── Property pane: Demo ──
    PropertyPane_UseDemoData_Label: 'استخدام بيانات العرض التوضيحي',
    PropertyPane_UseDemoData_On: 'تشغيل — عرض موظفين تجريبيين',
    PropertyPane_UseDemoData_Off: 'إيقاف — بيانات Microsoft 365 المباشرة',

    // ── Presence status labels ──
    Presence_Available: 'متوفر',
    Presence_Busy: 'مشغول',
    Presence_DoNotDisturb: 'عدم الإزعاج',
    Presence_BeRightBack: 'سأعود بعد قليل',
    Presence_Away: 'بعيد',
    Presence_Offline: 'غير متصل',

    // ── Header / top bar ──
    Header_DirectoryLabel: 'دليل الموظفين',
    Header_OrgChartLabel: 'المخطط التنظيمي',
    Header_SwitchToView: 'التبديل إلى {view}',
    Header_CompanyLogoAlt: 'شعار الشركة',
    Header_RefreshingAria: 'جارٍ تحديث البيانات',
    Header_RefreshAria: 'تحديث البيانات',
    Header_RefreshTitle: 'تحديث البيانات (آخر تحديث {when})',
    Header_NotLoadedYet: 'لم يتم التحميل بعد',
    Header_JustNow: 'الآن',
    Header_MinutesAgo: 'قبل {mins} دقيقة',
    Header_HoursAgo: 'قبل {hours} ساعة',
    Header_PreferencesTitle: 'التفضيلات',
    Header_PreferencesAria: 'فتح لوحة التفضيلات',

    // ── Employee Directory ──
    Directory_LoadingLabel: 'جارٍ تحميل الموظفين...',
    Directory_LoadFailedFallback: 'تأكد من أن جزء الويب يمتلك إذن User.Read.All.',
    Directory_LoadFailedPrefix: 'فشل تحميل الموظفين. {detail}',
    Directory_AllDepartments: 'كل الأقسام',
    Directory_AllOffices: 'كل المكاتب',
    Directory_StatusDisabled: 'معطّل',
    Directory_StatusGuest: 'ضيف',
    Directory_PresenceStatus: 'الحالة: {status}',
    Directory_ChatInTeams: 'الدردشة في Teams',
    Directory_ChatWithInTeams: 'الدردشة مع {name} في Teams',
    Directory_ManagesCount: 'يدير {direct}',
    Directory_ManagesCountWithTotal: 'يدير {direct} (الإجمالي {total})',
    Directory_ReportsCountWithTotal: '{direct} (الإجمالي {total})',
    Directory_ColumnName: 'الاسم',
    Directory_ColumnJobTitle: 'المسمى الوظيفي',
    Directory_ColumnDepartment: 'القسم',
    Directory_ColumnOffice: 'المكتب',
    Directory_ColumnEmail: 'البريد الإلكتروني',
    Directory_ColumnPhone: 'الهاتف',
    Directory_ColumnReports: 'التابعون',
    Directory_ColumnChat: 'الدردشة',
    Directory_PrevPage: 'السابق',
    Directory_NextPage: 'التالي',
    Directory_PreviousPageAria: 'الصفحة السابقة',
    Directory_NextPageAria: 'الصفحة التالية',
    Directory_SearchPlaceholder: 'البحث بالاسم أو المسمى الوظيفي أو البريد الإلكتروني أو القسم...',
    Directory_SearchAria: 'البحث عن أشخاص',
    Directory_FilterByDepartmentAria: 'التصفية حسب القسم',
    Directory_FilterByOfficeAria: 'التصفية حسب المكتب',
    Directory_ClearSearchTitle: 'مسح البحث وجميع عوامل التصفية',
    Directory_ClearButton: 'مسح',
    Directory_ClearFiltersButton: 'مسح عوامل التصفية',
    Directory_ExportCsvTitle: 'تصدير جميع النتائج المصفّاة إلى ملف CSV (يُفتح في Excel)',
    Directory_ExportCsvButton: 'تصدير CSV',
    Directory_ViewModeAria: 'وضع العرض',
    Directory_CardViewTitle: 'عرض البطاقات',
    Directory_ListViewTitle: 'عرض القائمة',
    Directory_AlphabetFilterAria: 'التصفية الأبجدية',
    Directory_ShowAllTitle: 'إظهار الكل',
    Directory_OtherLettersTitle: 'التصفية حسب الأسماء التي تبدأ برقم أو حرف آخر',
    Directory_FilterByLetterTitle: 'التصفية حسب {letter}',
    Directory_ResultCountSingular: 'شخص',
    Directory_ResultCountPlural: 'أشخاص',
    Directory_PageOf: ' · الصفحة {page} من {totalPages}',
    Directory_FilterActiveSingular: '{count} عامل تصفية نشط',
    Directory_FilterActivePlural: '{count} عوامل تصفية نشطة',
    Directory_NoResults: 'لم يتم العثور على أي شخص',
    Directory_PaginationAria: 'ترقيم الصفحات',

    // ── Org chart toolbar / shared chart chrome ──
    Chart_Layout_Drill: 'التنقّل التدريجي',
    Chart_Layout_Vertical: 'من الأعلى إلى الأسفل',
    Chart_Layout_Horizontal: 'من اليسار إلى اليمين',
    Chart_SearchPlaceholder: 'البحث عن أشخاص...',
    Chart_SearchAria: 'البحث عن أشخاص',
    Chart_MatchSingular: 'تطابق في الشجرة',
    Chart_MatchPlural: 'تطابقات في الشجرة',
    Chart_ResultsListAria: 'الأشخاص',
    Chart_ExpandAll: 'توسيع الكل',
    Chart_CollapseAll: 'طي الكل',
    Chart_Expanding: 'جارٍ التوسيع…',
    Chart_Loading: 'جارٍ التحميل…',
    Chart_FindMeTitle: 'البحث عن موقعي في المخطط التنظيمي',
    Chart_ViewLayoutButton: 'عرض',
    Chart_ViewLayoutTitle: 'تبديل تخطيط العرض',
    Chart_ViewLayoutPanelTitle: 'تخطيط العرض',
    Chart_StatsSummaryTitle: 'ملخص إحصاءات المؤسسة',
    Chart_FilterByDepartmentTitle: 'التصفية حسب القسم',
    Chart_FilterByDepartmentWithCountAria: 'التصفية حسب القسم (تم تحديد {count})',
    Chart_FilterByDepartmentPanelTitle: 'التصفية حسب القسم',
    Chart_ClearAllFilters: 'مسح جميع عوامل التصفية',
    Chart_FilterUserTypesTitle: 'تصفية أنواع المستخدمين',
    Chart_DownloadPdfTitle: 'تنزيل بتنسيق PDF',
    Chart_DownloadCsvTitle: 'تنزيل كجدول بيانات CSV',
    Chart_ResetRootTitle: 'إعادة التعيين إلى الجذر الافتراضي',
    Chart_ViewFromPersonPlaceholder: 'عرض من شخص…',
    Chart_ViewFromPersonAria: 'عرض المخطط التنظيمي بدءًا من شخص معيّن',
    Chart_ZoomOutTitle: 'تصغير',
    Chart_ZoomInTitle: 'تكبير',
    Chart_ZoomResetTitle: 'إعادة تعيين التكبير/التصغير',
    Chart_ShowInChartAria: 'إظهار في المخطط',
    Chart_ShowInChartTitle: 'إظهار في المخطط',
    Chart_FilterMembers: 'الأعضاء العاديون',
    Chart_FilterGuests: 'المستخدمون الضيوف',
    Chart_FilterDisabled: 'الحسابات المعطّلة',
    Chart_SetupTitle: 'إعداد المخطط التنظيمي',
    Chart_SetupSubtitle: 'أدخل البريد الإلكتروني أو UPN الخاص بالشخص في المستوى الأعلى للبدء.',
    Chart_SetupPlaceholder: 'ceo@company.com',
    Chart_SetupInputAria: 'البريد الإلكتروني أو UPN الخاص بالشخص في المستوى الأعلى',
    Chart_SetupLoadButton: 'تحميل',
    Chart_SetupHint: 'يمكنك أيضًا تعيين هذا بشكل دائم في إعدادات جزء الويب (للمسؤول).',
    Chart_BuildingLabel: 'جارٍ إنشاء المخطط التنظيمي...',
    Chart_RetryButton: 'إعادة المحاولة',
    Chart_NotFoundFromSetup: 'لم يتم العثور على المستخدم "{identifier}".',
    Chart_NotFoundWithSettings: 'لم يتم العثور على المستخدم "{identifier}". تحقق من UPN أو البريد الإلكتروني في الإعدادات.',
    Chart_LoadFailedGeneric: 'فشل تحميل المخطط التنظيمي.{detail}',
    Chart_LoadFailedPermissions: ' تحقق من الأذونات.',
    Chart_LoadFailedForPerson: 'فشل تحميل المخطط التنظيمي لهذا الشخص.',
    Chart_FindMeNotFound: 'لم يتم العثور على حسابك في هذه المؤسسة.',
    Chart_StatPeople: 'الأشخاص',
    Chart_StatMembers: 'الأعضاء',
    Chart_StatGuests: 'الضيوف',
    Chart_StatDepts: 'الأقسام',
    Chart_ReportingLineAria: 'خط التبعية',
    Chart_BackToFullOrgTitle: 'العودة إلى المخطط التنظيمي الكامل',
    Chart_FullOrgLabel: 'المؤسسة الكاملة',
    Chart_FocusOnPerson: 'التركيز على {name}',
    Chart_OrgChartAria: 'المخطط التنظيمي',
    Chart_ExportNote_DrillLevel: 'مستوى التنقّل التدريجي الحالي (مستوى واحد من التابعين المباشرين)',
    Chart_ExportNote_PartialLevels: 'يتضمن المستويات المحمّلة فقط — استخدم "توسيع الكل" قبل التصدير لتضمين المستويات الأعمق',
    Chart_AllowPopupsForPdf: 'يُرجى السماح بالنوافذ المنبثقة لتصدير ملف PDF.',

    // ── Person card ──
    PersonCard_ProfileAria: 'الملف الشخصي: {name}',
    PersonCard_CloseTitle: 'إغلاق',
    PersonCard_CloseAria: 'إغلاق الملف الشخصي',
    PersonCard_StatusDisabled: 'معطّل',
    PersonCard_StatusGuest: 'ضيف',
    PersonCard_DirectReportSingular: '{count} تابع مباشر',
    PersonCard_DirectReportPlural: '{count} من التابعين المباشرين',
    PersonCard_TotalSuffix: ' · الإجمالي {total}',
    PersonCard_CopyEmailTitle: 'نسخ عنوان البريد الإلكتروني',
    PersonCard_EmailCopiedAria: 'تم نسخ عنوان البريد الإلكتروني',
    PersonCard_ReportsTo: 'يرفع تقاريره إلى',
    PersonCard_FocusOnPerson: 'التركيز على {name}',
    PersonCard_FocusOrgChartOnPerson: 'تركيز المخطط التنظيمي على {name}',
    PersonCard_DottedLine: 'خط متقطع',
    PersonCard_DottedLineManager: 'مدير الخط المتقطع: {name}',
    PersonCard_DottedLineReport: 'تابع الخط المتقطع: {name}',
    PersonCard_ChatButton: 'دردشة',
    PersonCard_EmailButton: 'بريد إلكتروني',
    PersonCard_FocusButton: 'تركيز',
    PersonCard_FocusTitle: 'تركيز المخطط التنظيمي على هذا الشخص',

    // ── Org node card ──
    OrgNode_ViewProfile: 'عرض الملف الشخصي لـ {name}',
    OrgNode_FocusOrgChartOn: 'تركيز المخطط التنظيمي على {name}',
    OrgNode_Collapse: 'طي',
    OrgNode_Expand: 'توسيع',
    OrgNode_DirectReportsSuffix: 'التابعون المباشرون لـ {name}',
    OrgNode_StatusDisabled: 'معطّل',
    OrgNode_StatusGuest: 'ضيف',
    OrgNode_TotalReportsAcrossLevels: '{count} شخصًا على جميع المستويات أسفل {name}',

    // ── Drill view ──
    Drill_ReportingLineAria: 'خط التبعية',
    Drill_BackToTopTitle: 'العودة إلى الأعلى',
    Drill_BackToTopAria: 'العودة إلى أعلى المخطط التنظيمي',
    Drill_GoBackTo: 'الرجوع إلى {name}',
    Drill_ViewProfileTitle: 'عرض الملف الشخصي',
    Drill_ViewProfileAria: 'عرض الملف الشخصي لـ {name}',
    Drill_ProfileButton: 'الملف الشخصي',
    Drill_LoadingLabel: 'جارٍ التحميل...',
    Drill_DirectReports: 'التابعون المباشرون',
    Drill_DirectReportsOfAria: 'التابعون المباشرون لـ {name}',
    Drill_DirectReportsAria: 'التابعون المباشرون',
    Drill_ViewPersonProfile: 'عرض الملف الشخصي لـ {name}',
    Drill_ShowPersonReports: 'إظهار التابعين المباشرين لـ {name}',
    Drill_NoDirectReports: 'لا يوجد تابعون مباشرون',

    // ── Settings panel ──
    Settings_AlphabetFirstName: 'الاسم الأول',
    Settings_AlphabetLastName: 'اسم العائلة',
    Settings_CardSizeSmall: 'صغير — مضغوط، مع إظهار بطاقات أكثر',
    Settings_CardSizeMedium: 'متوسط — متوازن',
    Settings_CardSizeLarge: 'كبير — واسع، مع بطاقات أقل',
    Settings_HeaderText: 'التفضيلات',
    Settings_SaveButton: 'حفظ',
    Settings_CancelButton: 'إلغاء',
    Settings_DiscardButton: 'تجاهل التغييرات',
    Settings_SectionDirectory: 'الدليل',
    Settings_AlphabetFilterByLabel: 'التصفية الأبجدية حسب',
    Settings_CardSizeLabel: 'حجم البطاقة',
    Settings_FontSizeLabel: 'حجم الخط',
    Settings_SectionCardsAndFields: 'البطاقات والحقول',
    Settings_ShowOnCardsLabel: 'إظهار في بطاقات الموظفين:',
    Settings_EmailAddressLabel: 'عنوان البريد الإلكتروني',
    Settings_PhoneNumberLabel: 'رقم الهاتف',
    Settings_DepartmentLabel: 'القسم',
    Settings_OfficeLocationLabel: 'موقع المكتب',
    Settings_SectionOrgChart: 'المخطط التنظيمي',
    Settings_ManagerLevelsLabel: 'عدد مستويات المديرين المعروضة عند التركيز على شخص: {levels}',
    Settings_CompactCardsLabel: 'بطاقات مضغوطة',
    Settings_CompactCardsOn: 'تشغيل — بطاقات أصغر، مع إظهار المزيد في الوقت نفسه',
    Settings_CompactCardsOff: 'إيقاف — الحجم القياسي',
    Settings_Hint: 'يتم حفظ هذه التفضيلات في المستعرض الخاص بك وتنطبق عليك فقط. يتم تكوين سمة المخطط والعرض الافتراضي والتخطيط بواسطة مسؤول SharePoint الخاص بك.',
    Settings_SectionDemoData: 'بيانات العرض التوضيحي',
    Settings_DatasetSizeLabel: 'حجم مجموعة البيانات',
    Settings_PeopleCountSuffix: '{count} شخص',

    // ── Export (CSV / PDF) ──
    Export_ColumnName: 'الاسم',
    Export_ColumnJobTitle: 'المسمى الوظيفي',
    Export_ColumnDepartment: 'القسم',
    Export_ColumnOffice: 'المكتب',
    Export_ColumnEmail: 'البريد الإلكتروني',
    Export_ColumnPhone: 'الهاتف',
    Export_ColumnManager: 'المدير',
    Export_ColumnLevel: 'المستوى',
    Export_PdfDocumentTitle: 'المخطط التنظيمي',
    Export_PdfHeading: 'المخطط التنظيمي',
    Export_PdfRootLabel: 'الجذر: {name}',
  };
});
