define([], function () {
  return {
    // ── Property pane: pane header / groups ──
    PropertyPane_HeaderDescription: 'Nastavení Smart Org Chart',
    PropertyPane_Group_General: 'Obecné',
    PropertyPane_Group_Branding: 'Branding',
    PropertyPane_Group_VisualStyle: 'Vizuální styl',
    PropertyPane_Group_DataSource: 'Zdroj dat',
    PropertyPane_Group_CustomAttributes: 'Vlastní atributy',
    PropertyPane_Group_UserFilters: 'Filtry uživatelů',
    PropertyPane_Group_OrgChart: 'Organizační schéma',
    PropertyPane_Group_OrgChartFeatures: 'Funkce organizačního schématu',
    PropertyPane_Group_Directory: 'Adresář',
    PropertyPane_Group_Demo: 'Ukázka',

    // ── Property pane: General ──
    PropertyPane_DefaultView_Label: 'Výchozí zobrazení',

    // ── Property pane: Branding ──
    PropertyPane_AppTitle_Label: 'Název aplikace',
    PropertyPane_AppTitle_Placeholder: 'Organizační schéma Contoso',
    PropertyPane_AppTitle_Description: 'Zobrazí se v horní liště vedle názvu zobrazení',
    PropertyPane_LogoUrl_Label: 'Adresa URL loga',
    PropertyPane_LogoUrl_Placeholder: 'https://contoso.sharepoint.com/sites/yoursite/SiteAssets/logo.png',
    PropertyPane_LogoUrl_Description: 'Úplná adresa URL obrázku ve formátu PNG, SVG nebo JPG. Tip: otevřete soubor obrázku v prohlížeči a zkopírujte adresu z panelu adresy. Adresy URL získané pomocí možnosti "Kopírovat odkaz" nebudou fungovat.',
    PropertyPane_DirectoryLabel_Label: 'Popisek zobrazení Adresář zaměstnanců',
    PropertyPane_OrgChartLabel_Label: 'Popisek zobrazení Organizační schéma',
    PropertyPane_ViewLabel_Description: 'Ponechte prázdné, chcete-li použít výchozí název, nebo zadejte „[blank]“, chcete-li popisek zcela skrýt.',

    // ── Property pane: Visual Style ──
    PropertyPane_ChartTheme_Label: 'Motiv schématu',
    PropertyPane_Theme_Modern: 'Moderní – barvy oddělení na bílém pozadí',
    PropertyPane_Theme_Minimal: 'Minimalistický – plochý a s nízkým kontrastem',
    PropertyPane_Theme_Corporate: 'Firemní – jednotná modrá',
    PropertyPane_Theme_Dark: 'Tmavý – tmavě námořnické pozadí',
    PropertyPane_Theme_Custom: 'Vlastní – zvolte si vlastní barvu',
    PropertyPane_AccentColor_Label: 'Vlastní zvýrazňující barva',
    PropertyPane_AccentColor_PickerAriaLabel: 'Výběr zvýrazňující barvy',
    PropertyPane_AccentColor_HexLabel: 'Hex',
    PropertyPane_AccentColor_HexAriaLabel: 'Hexadecimální hodnota zvýrazňující barvy',
    PropertyPane_AccentColor_RgbLabel: 'RGB',
    PropertyPane_AccentColor_ChannelAriaLabel: 'Kanál {name} (0 až 255)',
    PropertyPane_AccentColor_ContrastWithWhite: 'Kontrast vůči bílé: {ratio}:1 ({passes})',
    PropertyPane_AccentColor_PassesAA: 'splňuje úroveň AA',
    PropertyPane_AccentColor_LargeTextOnly: 'jen pro velký text',
    PropertyPane_AccentColor_LowContrast: 'nízký kontrast',
    PropertyPane_AccentColor_DarkTextNote: 'Text na této barvě bude kvůli čitelnosti tmavý.',
    PropertyPane_AccentColor_DarkerShadeNote: 'Nadpisy a odkazy budou kvůli čitelnosti používat tmavší odstín ({hex}).',
    PropertyPane_AccentColor_InvalidHex: '„{typed}“ není platná hexadecimální barva. Použijte hodnotu jako #0078d4 nebo #07d.',
    PropertyPane_DefaultFontSize_Label: 'Výchozí velikost písma',
    PropertyPane_FontSize_75: '75 % – velmi malé',
    PropertyPane_FontSize_85: '85 % – malé',
    PropertyPane_FontSize_100: '100 % – normální',
    PropertyPane_FontSize_115: '115 % – velké',
    PropertyPane_FontSize_130: '130 % – velmi velké',
    PropertyPane_FontSize_150: '150 % – XXL',
    PropertyPane_FontSize_175: '175 % – XXXL',
    PropertyPane_DefaultLayout_Label: 'Výchozí rozložení organizačního schématu',
    PropertyPane_Layout_Drill: 'Postupné procházení',
    PropertyPane_Layout_Vertical: 'Shora dolů',
    PropertyPane_Layout_Horizontal: 'Zleva doprava',

    // ── Property pane: Data Source ──
    PropertyPane_DataSource_Label: 'Odkud načítat data o uživatelích a organizaci',
    PropertyPane_DataSource_Auto: 'Automaticky – Graph API, s návratem na vyhledávání SharePoint',
    PropertyPane_DataSource_Graph: 'Graph API – živá data ze služby Azure AD (bez zpoždění indexování)',
    PropertyPane_DataSource_Search: 'Vyhledávání SharePoint – starší způsob chování',
    PropertyPane_DataSource_Note: 'Doporučuje se rozhraní Graph API. Načítá data přímo ze služby Azure Active Directory, takže se noví uživatelé a změny nadřízených projeví okamžitě. Vyžaduje schválení oprávnění Microsoft Graph v katalogu aplikací SharePoint.',

    // ── Property pane: Custom Attributes ──
    PropertyPane_CustomAttributes_Note: 'Vlastní atributy vyžadují Microsoft Graph (zdroj dat: Graph nebo Automaticky). Vyhledávání SharePoint nemá obecný způsob, jak číst atributy Entra ID.',
    PropertyPane_CustomAttributes_Heading: 'Správa vlastních atributů',
    PropertyPane_CustomAttributes_Empty: 'Nejsou nakonfigurovány žádné vlastní atributy.',
    PropertyPane_CustomAttributes_AddButton: '+ Přidat atribut',
    PropertyPane_CustomAttributes_MaxTooltip: 'Maximálně {max} vlastních atributů',
    PropertyPane_CustomAttributes_FieldNameLabel: 'Název atributu',
    PropertyPane_CustomAttributes_FieldPlaceholder: 'např. companyName',
    PropertyPane_CustomAttributes_FieldError: 'Použijte employeeId, companyName, city, ... nebo extensionAttribute1-15',
    PropertyPane_CustomAttributes_DisplayLabelLabel: 'Zobrazovaný popisek',
    PropertyPane_CustomAttributes_LabelPlaceholder: 'např. Nákladové středisko',
    PropertyPane_CustomAttributes_RemoveTitle: 'Odebrat atribut',
    PropertyPane_CustomAttributes_RemoveAriaLabel: 'Odebrat atribut {ordinal}',
    PropertyPane_CustomAttributes_ShowInDirectory: 'Zobrazit v adresáři',
    PropertyPane_CustomAttributes_ShowInOrgChart: 'Zobrazit v organizačním schématu',

    // ── Property pane: User Filters ──
    PropertyPane_ExcludedAccounts_Label: 'Vyloučit účty',
    PropertyPane_ExcludedAccounts_Placeholder: 'conf-room, noreply, admin@, Servisní účet',
    PropertyPane_ExcludedAccounts_Description: 'Slova nebo vzory oddělené čárkou (nerozlišuje velikost písmen). Každý uživatel, jehož zobrazované jméno, e-mail nebo UPN obsahuje některý z nich, bude skrytý ve všech zobrazeních.',
    PropertyPane_RestrictTenant_Label: 'Zobrazovat jen uživatele tenanta',
    PropertyPane_RestrictTenant_On: 'Zapnuto – skryje účty s externími e-mailovými doménami (např. gmail.com, hotmail.com)',
    PropertyPane_RestrictTenant_Off: 'Vypnuto – zobrazí se všichni uživatelé bez ohledu na e-mailovou doménu',
    PropertyPane_HideGuest_Label: 'Skrýt hostující účty Azure AD',
    PropertyPane_HideGuest_On: 'Zapnuto – hostující účty jsou skryté',
    PropertyPane_HideGuest_Off: 'Vypnuto – hostující účty jsou viditelné (označené štítkem Host)',
    PropertyPane_HideDisabled_Label: 'Skrýt deaktivované účty',
    PropertyPane_HideDisabled_On: 'Zapnuto – účty s blokovaným přihlášením jsou skryté',
    PropertyPane_HideDisabled_Off: 'Vypnuto – deaktivované účty jsou viditelné (označené štítkem Deaktivováno)',
    PropertyPane_HideDisabled_Note: 'Poznámka: rozpoznání hostujících a deaktivovaných účtů vyžaduje zdroj dat Graph API. Vyhledávání SharePoint tyto informace nevrací, takže tyto dva filtry (a štítky Host/Deaktivováno) nemají žádný účinek, pokud data pocházejí z vyhledávání.',
    PropertyPane_HideNoJobTitle_Label: 'Skrýt účty bez pracovní pozice',
    PropertyPane_HideNoJobTitle_On: 'Zapnuto – účty bez pracovní pozice jsou skryté',
    PropertyPane_HideNoJobTitle_Off: 'Vypnuto – zobrazí se všechny účty bez ohledu na pracovní pozici',
    PropertyPane_HideNoDept_Label: 'Skrýt účty bez oddělení',
    PropertyPane_HideNoDept_On: 'Zapnuto – účty bez oddělení jsou skryté',
    PropertyPane_HideNoDept_Off: 'Vypnuto – zobrazí se všechny účty bez ohledu na oddělení',

    // ── Property pane: Org Chart ──
    PropertyPane_TopLevelUser_Label: 'Uživatel na nejvyšší úrovni (UPN nebo e-mail)',
    PropertyPane_TopLevelUser_Placeholder: 'ceo@yourcompany.com',
    PropertyPane_TopLevelUser_Description: 'Osoba zobrazená v kořeni organizačního schématu',
    PropertyPane_LevelsBelow_Label: 'Počet úrovní k načtení pod kořenem',
    PropertyPane_DottedLine_Label: 'Atribut nadřízeného v přerušované linii',
    PropertyPane_DottedLine_Placeholder: 'extensionAttribute10',
    PropertyPane_DottedLine_Description: 'Volitelné. Název atributu místního rozšíření Azure AD (extensionAttribute1-15), do kterého se ukládá e-mail nebo UPN sekundárního nadřízeného v „přerušované linii“. Vztahy v přerušované linii se zobrazují na profilových kartách. Vyžaduje zdroj dat Graph API.',
    PropertyPane_DefaultZoom_Label: 'Výchozí přiblížení organizačního schématu',
    PropertyPane_Zoom_Auto: 'Výchozí (automatické přizpůsobení)',
    PropertyPane_Zoom_50: '50 %',
    PropertyPane_Zoom_75: '75 %',
    PropertyPane_Zoom_100: '100 %',
    PropertyPane_Zoom_125: '125 %',
    PropertyPane_Zoom_150: '150 %',

    // ── Property pane: Org Chart Features ──
    PropertyPane_FeatureToggles_Note: 'Zobrazit nebo skrýt tlačítka na panelu nástrojů v zobrazení organizačního schématu.',
    PropertyPane_FindMe_Label: 'Tlačítko Najít mě',
    PropertyPane_LayoutToggle_Label: 'Přepínač rozložení (procházení / svislé / vodorovné)',
    PropertyPane_Stats_Label: 'Panel statistik organizace',
    PropertyPane_DeptFilter_Label: 'Filtr oddělení',
    PropertyPane_UserFilter_Label: 'Filtr typu uživatele (členové / hosté)',
    PropertyPane_Visible: 'Viditelné',
    PropertyPane_Hidden: 'Skryté',

    // ── Property pane: Directory ──
    PropertyPane_PageSize_Label: 'Maximální počet zaměstnanců na stránku',
    PropertyPane_PageSize_AriaLabel: 'Maximální počet zaměstnanců na stránku (10 až 200)',
    PropertyPane_PageSize_Note: 'Velikost karty, viditelná pole a další zobrazovací předvolby se nastavují pro každého uživatele zvlášť pomocí ikony nastavení v aplikaci.',

    // ── Property pane: Demo ──
    PropertyPane_UseDemoData_Label: 'Používat ukázková data',
    PropertyPane_UseDemoData_On: 'Zapnuto – zobrazují se ukázkoví zaměstnanci',
    PropertyPane_UseDemoData_Off: 'Vypnuto – živá data z Microsoft 365',

    // ── Presence status labels ──
    Presence_Available: 'K dispozici',
    Presence_Busy: 'Zaneprázdněno',
    Presence_DoNotDisturb: 'Nerušit',
    Presence_BeRightBack: 'Hned budu zpět',
    Presence_Away: 'Nepřítomen',
    Presence_Offline: 'Offline',

    // ── Header / top bar ──
    Header_DirectoryLabel: 'Adresář zaměstnanců',
    Header_OrgChartLabel: 'Organizační schéma',
    Header_SwitchToView: 'Přepnout na {view}',
    Header_CompanyLogoAlt: 'Logo společnosti',
    Header_RefreshingAria: 'Obnovování dat',
    Header_RefreshAria: 'Obnovit data',
    Header_RefreshTitle: 'Obnovit data (naposledy aktualizováno {when})',
    Header_NotLoadedYet: 'zatím nenačteno',
    Header_JustNow: 'právě teď',
    Header_MinutesAgo: 'před {mins} min',
    Header_HoursAgo: 'před {hours} h',
    Header_PreferencesTitle: 'Předvolby',
    Header_PreferencesAria: 'Otevřít panel předvoleb',

    // ── Employee Directory ──
    Directory_LoadingLabel: 'Načítání zaměstnanců...',
    Directory_LoadFailedFallback: 'Ujistěte se, že webová část má oprávnění User.Read.All.',
    Directory_LoadFailedPrefix: 'Načtení zaměstnanců se nezdařilo. {detail}',
    Directory_AllDepartments: 'Všechna oddělení',
    Directory_AllOffices: 'Všechny kanceláře',
    Directory_StatusDisabled: 'Deaktivováno',
    Directory_StatusGuest: 'Host',
    Directory_PresenceStatus: 'Stav: {status}',
    Directory_ChatInTeams: 'Chatovat v Teams',
    Directory_ChatWithInTeams: 'Chatovat s uživatelem {name} v Teams',
    Directory_ManagesCount: 'Podřízených: {direct}',
    Directory_ManagesCountWithTotal: 'Podřízených: {direct} (celkem {total})',
    Directory_ReportsCountWithTotal: '{direct} (celkem {total})',
    Directory_ColumnName: 'Jméno',
    Directory_ColumnJobTitle: 'Pracovní pozice',
    Directory_ColumnDepartment: 'Oddělení',
    Directory_ColumnOffice: 'Kancelář',
    Directory_ColumnEmail: 'E-mail',
    Directory_ColumnPhone: 'Telefon',
    Directory_ColumnReports: 'Podřízení',
    Directory_ColumnChat: 'Chat',
    Directory_PrevPage: 'Předchozí',
    Directory_NextPage: 'Další',
    Directory_PreviousPageAria: 'Předchozí stránka',
    Directory_NextPageAria: 'Další stránka',
    Directory_SearchPlaceholder: 'Hledat podle jména, pozice, e-mailu nebo oddělení...',
    Directory_SearchAria: 'Hledat osoby',
    Directory_FilterByDepartmentAria: 'Filtrovat podle oddělení',
    Directory_FilterByOfficeAria: 'Filtrovat podle kanceláře',
    Directory_ClearSearchTitle: 'Vymazat hledání a všechny filtry',
    Directory_ClearButton: 'Vymazat',
    Directory_ClearFiltersButton: 'Vymazat filtry',
    Directory_ExportCsvTitle: 'Exportovat všechny filtrované výsledky do souboru CSV (otevře se v Excelu)',
    Directory_ExportCsvButton: 'Exportovat CSV',
    Directory_ViewModeAria: 'Režim zobrazení',
    Directory_CardViewTitle: 'Zobrazení karet',
    Directory_ListViewTitle: 'Zobrazení seznamu',
    Directory_AlphabetFilterAria: 'Abecední filtr',
    Directory_ShowAllTitle: 'Zobrazit vše',
    Directory_OtherLettersTitle: 'Filtrovat jména začínající číslicí nebo jiným znakem',
    Directory_FilterByLetterTitle: 'Filtrovat podle písmene {letter}',
    Directory_ResultCountSingular: 'osoba',
    Directory_ResultCountPlural: 'osob',
    Directory_PageOf: ' · stránka {page} z {totalPages}',
    Directory_FilterActiveSingular: '{count} aktivní filtr',
    Directory_FilterActivePlural: '{count} aktivních filtrů',
    Directory_NoResults: 'Nebyly nalezeny žádné osoby',
    Directory_PaginationAria: 'Stránkování',

    // ── Org chart toolbar / shared chart chrome ──
    Chart_Layout_Drill: 'Postupné procházení',
    Chart_Layout_Vertical: 'Shora dolů',
    Chart_Layout_Horizontal: 'Zleva doprava',
    Chart_SearchPlaceholder: 'Hledat osoby...',
    Chart_SearchAria: 'Hledat osoby',
    Chart_MatchSingular: 'shoda ve stromu',
    Chart_MatchPlural: 'shody ve stromu',
    Chart_ResultsListAria: 'Osoby',
    Chart_ExpandAll: 'Rozbalit vše',
    Chart_CollapseAll: 'Sbalit vše',
    Chart_Expanding: 'Rozbaluje se…',
    Chart_Loading: 'Načítání…',
    Chart_FindMeTitle: 'Najít mě v organizačním schématu',
    Chart_ViewLayoutButton: 'Zobrazení',
    Chart_ViewLayoutTitle: 'Přepnout rozložení zobrazení',
    Chart_ViewLayoutPanelTitle: 'Rozložení zobrazení',
    Chart_StatsSummaryTitle: 'Souhrn statistik organizace',
    Chart_FilterByDepartmentTitle: 'Filtrovat podle oddělení',
    Chart_FilterByDepartmentWithCountAria: 'Filtrovat podle oddělení (vybráno: {count})',
    Chart_FilterByDepartmentPanelTitle: 'Filtrovat podle oddělení',
    Chart_ClearAllFilters: 'Vymazat všechny filtry',
    Chart_FilterUserTypesTitle: 'Filtrovat typy uživatelů',
    Chart_DownloadPdfTitle: 'Stáhnout jako PDF',
    Chart_DownloadCsvTitle: 'Stáhnout jako tabulku CSV',
    Chart_ResetRootTitle: 'Obnovit výchozí kořen',
    Chart_ViewFromPersonPlaceholder: 'Zobrazit od osoby…',
    Chart_ViewFromPersonAria: 'Zobrazit organizační schéma od zadané osoby',
    Chart_ZoomOutTitle: 'Oddálit',
    Chart_ZoomInTitle: 'Přiblížit',
    Chart_ZoomResetTitle: 'Obnovit přiblížení',
    Chart_ShowInChartAria: 'Zobrazit ve schématu',
    Chart_ShowInChartTitle: 'Zobrazit ve schématu',
    Chart_FilterMembers: 'Běžní členové',
    Chart_FilterGuests: 'Hostující uživatelé',
    Chart_FilterDisabled: 'Deaktivované účty',
    Chart_SetupTitle: 'Nastavit organizační schéma',
    Chart_SetupSubtitle: 'Začněte zadáním e-mailu nebo UPN osoby na nejvyšší úrovni.',
    Chart_SetupPlaceholder: 'ceo@company.com',
    Chart_SetupInputAria: 'E-mail nebo UPN osoby na nejvyšší úrovni',
    Chart_SetupLoadButton: 'Načíst',
    Chart_SetupHint: 'Toto můžete také trvale nastavit v nastavení webové části (správce).',
    Chart_BuildingLabel: 'Sestavuje se organizační schéma...',
    Chart_RetryButton: 'Zkusit znovu',
    Chart_NotFoundFromSetup: 'Uživatel „{identifier}“ nebyl nalezen.',
    Chart_NotFoundWithSettings: 'Uživatel „{identifier}“ nebyl nalezen. Zkontrolujte UPN nebo e-mail v nastavení.',
    Chart_LoadFailedGeneric: 'Načtení organizačního schématu se nezdařilo.{detail}',
    Chart_LoadFailedPermissions: ' Zkontrolujte oprávnění.',
    Chart_LoadFailedForPerson: 'Načtení organizačního schématu pro tuto osobu se nezdařilo.',
    Chart_FindMeNotFound: 'Váš účet nebyl v této organizaci nalezen.',
    Chart_StatPeople: 'Osoby',
    Chart_StatMembers: 'Členové',
    Chart_StatGuests: 'Hosté',
    Chart_StatDepts: 'Oddělení',
    Chart_ReportingLineAria: 'Linie nadřízenosti',
    Chart_BackToFullOrgTitle: 'Zpět na celé organizační schéma',
    Chart_FullOrgLabel: 'Celá organizace',
    Chart_FocusOnPerson: 'Zaměřit na {name}',
    Chart_OrgChartAria: 'Organizační schéma',
    Chart_ExportNote_DrillLevel: 'Aktuální úroveň procházení (jedna úroveň přímých podřízených)',
    Chart_ExportNote_PartialLevels: 'Obsahuje pouze načtené úrovně – před exportem použijte Rozbalit vše, chcete-li zahrnout hlubší úrovně',
    Chart_AllowPopupsForPdf: 'Pro export do PDF prosím povolte vyskakovací okna.',

    // ── Person card ──
    PersonCard_ProfileAria: 'Profil: {name}',
    PersonCard_CloseTitle: 'Zavřít',
    PersonCard_CloseAria: 'Zavřít profil',
    PersonCard_StatusDisabled: 'Deaktivováno',
    PersonCard_StatusGuest: 'Host',
    PersonCard_DirectReportSingular: '{count} přímý podřízený',
    PersonCard_DirectReportPlural: '{count} přímých podřízených',
    PersonCard_TotalSuffix: ' · celkem {total}',
    PersonCard_CopyEmailTitle: 'Kopírovat e-mailovou adresu',
    PersonCard_EmailCopiedAria: 'E-mailová adresa zkopírována',
    PersonCard_ReportsTo: 'Podřízený komu',
    PersonCard_FocusOnPerson: 'Zaměřit na {name}',
    PersonCard_FocusOrgChartOnPerson: 'Zaměřit organizační schéma na {name}',
    PersonCard_DottedLine: 'Přerušovaná linie',
    PersonCard_DottedLineManager: 'Nadřízený v přerušované linii: {name}',
    PersonCard_DottedLineReport: 'Podřízený v přerušované linii: {name}',
    PersonCard_ChatButton: 'Chat',
    PersonCard_EmailButton: 'E-mail',
    PersonCard_FocusButton: 'Zaměřit',
    PersonCard_FocusTitle: 'Zaměřit organizační schéma na tuto osobu',

    // ── Org node card ──
    OrgNode_ViewProfile: 'Zobrazit profil osoby {name}',
    OrgNode_FocusOrgChartOn: 'Zaměřit organizační schéma na {name}',
    OrgNode_Collapse: 'Sbalit',
    OrgNode_Expand: 'Rozbalit',
    OrgNode_DirectReportsSuffix: 'Přímí podřízení osoby {name}',
    OrgNode_StatusDisabled: 'Deaktivováno',
    OrgNode_StatusGuest: 'Host',
    OrgNode_TotalReportsAcrossLevels: '{count} osob na všech úrovních pod osobou {name}',

    // ── Drill view ──
    Drill_ReportingLineAria: 'Linie nadřízenosti',
    Drill_BackToTopTitle: 'Zpět nahoru',
    Drill_BackToTopAria: 'Zpět na začátek organizačního schématu',
    Drill_GoBackTo: 'Vrátit se k osobě {name}',
    Drill_ViewProfileTitle: 'Zobrazit profil',
    Drill_ViewProfileAria: 'Zobrazit profil osoby {name}',
    Drill_ProfileButton: 'Profil',
    Drill_LoadingLabel: 'Načítání...',
    Drill_DirectReports: 'Přímí podřízení',
    Drill_DirectReportsOfAria: 'Přímí podřízení osoby {name}',
    Drill_DirectReportsAria: 'Přímí podřízení',
    Drill_ViewPersonProfile: 'Zobrazit profil osoby {name}',
    Drill_ShowPersonReports: 'Zobrazit přímé podřízené osoby {name}',
    Drill_NoDirectReports: 'Žádní přímí podřízení',

    // ── Settings panel ──
    Settings_AlphabetFirstName: 'Křestní jméno',
    Settings_AlphabetLastName: 'Příjmení',
    Settings_CardSizeSmall: 'Malá – kompaktní, zobrazí se více karet',
    Settings_CardSizeMedium: 'Střední – vyvážená',
    Settings_CardSizeLarge: 'Velká – prostornější, méně karet',
    Settings_HeaderText: 'Předvolby',
    Settings_SaveButton: 'Uložit',
    Settings_CancelButton: 'Zrušit',
    Settings_DiscardButton: 'Zahodit změny',
    Settings_SectionDirectory: 'Adresář',
    Settings_AlphabetFilterByLabel: 'Abecední filtr podle',
    Settings_CardSizeLabel: 'Velikost karty',
    Settings_FontSizeLabel: 'Velikost písma',
    Settings_SectionCardsAndFields: 'Karty a pole',
    Settings_ShowOnCardsLabel: 'Zobrazit na kartách zaměstnanců:',
    Settings_EmailAddressLabel: 'E-mailová adresa',
    Settings_PhoneNumberLabel: 'Telefonní číslo',
    Settings_DepartmentLabel: 'Oddělení',
    Settings_OfficeLocationLabel: 'Umístění kanceláře',
    Settings_SectionOrgChart: 'Organizační schéma',
    Settings_ManagerLevelsLabel: 'Počet úrovní nadřízených zobrazených při zaměření na osobu: {levels}',
    Settings_CompactCardsLabel: 'Kompaktní karty',
    Settings_CompactCardsOn: 'Zapnuto – menší karty, více jich je vidět najednou',
    Settings_CompactCardsOff: 'Vypnuto – standardní velikost',
    Settings_Hint: 'Tyto předvolby se ukládají do vašeho prohlížeče a platí jen pro vás. Motiv schématu, výchozí zobrazení a rozložení nastavuje správce SharePointu.',
    Settings_SectionDemoData: 'Ukázková data',
    Settings_DatasetSizeLabel: 'Velikost datové sady',
    Settings_PeopleCountSuffix: '{count} osob',

    // ── Export (CSV / PDF) ──
    Export_ColumnName: 'Jméno',
    Export_ColumnJobTitle: 'Pracovní pozice',
    Export_ColumnDepartment: 'Oddělení',
    Export_ColumnOffice: 'Kancelář',
    Export_ColumnEmail: 'E-mail',
    Export_ColumnPhone: 'Telefon',
    Export_ColumnManager: 'Nadřízený',
    Export_ColumnLevel: 'Úroveň',
    Export_PdfDocumentTitle: 'Organizační schéma',
    Export_PdfHeading: 'Organizační schéma',
    Export_PdfRootLabel: 'Kořen: {name}',
  };
});
