define([], function () {
  return {
    // ── Property pane: pane header / groups ──
    PropertyPane_HeaderDescription: 'Indstillinger for Smart Org Chart',
    PropertyPane_Group_General: 'Generelt',
    PropertyPane_Group_Branding: 'Branding',
    PropertyPane_Group_VisualStyle: 'Visuel stil',
    PropertyPane_Group_DataSource: 'Datakilde',
    PropertyPane_Group_CustomAttributes: 'Brugerdefinerede attributter',
    PropertyPane_Group_UserFilters: 'Brugerfiltre',
    PropertyPane_Group_OrgChart: 'Organisationsdiagram',
    PropertyPane_Group_OrgChartFeatures: 'Funktioner i organisationsdiagram',
    PropertyPane_Group_Directory: 'Katalog',
    PropertyPane_Group_Demo: 'Demo',

    // ── Property pane: General ──
    PropertyPane_DefaultView_Label: 'Standardvisning',

    // ── Property pane: Branding ──
    PropertyPane_AppTitle_Label: 'Apptitel',
    PropertyPane_AppTitle_Placeholder: 'Contoso Organisationsdiagram',
    PropertyPane_AppTitle_Description: 'Vises i overskriftslinjen sammen med visningsnavnet',
    PropertyPane_LogoUrl_Label: 'Logo-URL',
    PropertyPane_LogoUrl_Placeholder: 'https://contoso.sharepoint.com/sites/yoursite/SiteAssets/logo.png',
    PropertyPane_LogoUrl_Description: 'Fuld URL til et PNG/SVG/JPG-billede. Tip: Åbn billedfilen i din browser, og kopiér URL-en fra adresselinjen. Delings-URL-er fra "Kopiér link" virker ikke.',
    PropertyPane_DirectoryLabel_Label: 'Visningsnavn for medarbejderkatalog',
    PropertyPane_OrgChartLabel_Label: 'Visningsnavn for organisationsdiagram',
    PropertyPane_ViewLabel_Description: 'Lad feltet stå tomt for at bruge standardnavnet, eller skriv "[blank]" for at skjule etiketten helt.',

    // ── Property pane: Visual Style ──
    PropertyPane_ChartTheme_Label: 'Diagramtema',
    PropertyPane_Theme_Modern: 'Moderne – afdelingsfarver på hvid baggrund',
    PropertyPane_Theme_Minimal: 'Minimalistisk – fladt design med lav kontrast',
    PropertyPane_Theme_Corporate: 'Virksomhed – ensartet blå',
    PropertyPane_Theme_Dark: 'Mørk – mørkeblå baggrund',
    PropertyPane_Theme_Custom: 'Brugerdefineret – vælg din egen farve',
    PropertyPane_AccentColor_Label: 'Brugerdefineret accentfarve',
    PropertyPane_AccentColor_PickerAriaLabel: 'Vælger til accentfarve',
    PropertyPane_AccentColor_HexLabel: 'Hex',
    PropertyPane_AccentColor_HexAriaLabel: 'Hex-værdi for accentfarve',
    PropertyPane_AccentColor_RgbLabel: 'RGB',
    PropertyPane_AccentColor_ChannelAriaLabel: '{name}-kanal (0 til 255)',
    PropertyPane_AccentColor_ContrastWithWhite: 'Kontrast mod hvid: {ratio}:1 ({passes})',
    PropertyPane_AccentColor_PassesAA: 'opfylder AA',
    PropertyPane_AccentColor_LargeTextOnly: 'kun stor tekst',
    PropertyPane_AccentColor_LowContrast: 'lav kontrast',
    PropertyPane_AccentColor_DarkTextNote: 'Tekst på denne farve vises med mørk skrift for bedre læsbarhed.',
    PropertyPane_AccentColor_DarkerShadeNote: 'Overskrifter og links vil bruge en mørkere nuance ({hex}) for bedre læsbarhed.',
    PropertyPane_AccentColor_InvalidHex: '"{typed}" er ikke en gyldig hex-farve. Brug en værdi som #0078d4 eller #07d.',
    PropertyPane_DefaultFontSize_Label: 'Standard skriftstørrelse',
    PropertyPane_FontSize_75: '75 % – Ekstra lille',
    PropertyPane_FontSize_85: '85 % – Lille',
    PropertyPane_FontSize_100: '100 % – Normal',
    PropertyPane_FontSize_115: '115 % – Stor',
    PropertyPane_FontSize_130: '130 % – Ekstra stor',
    PropertyPane_FontSize_150: '150 % – XXL',
    PropertyPane_FontSize_175: '175 % – XXXL',
    PropertyPane_DefaultLayout_Label: 'Standardlayout for organisationsdiagram',
    PropertyPane_Layout_Drill: 'Drilldown',
    PropertyPane_Layout_Vertical: 'Oppefra og ned',
    PropertyPane_Layout_Horizontal: 'Fra venstre mod højre',

    // ── Property pane: Data Source ──
    PropertyPane_DataSource_Label: 'Hvor bruger- og organisationsdata skal indlæses fra',
    PropertyPane_DataSource_Auto: 'Automatisk – Graph API, med SharePoint-søgning som reserveløsning',
    PropertyPane_DataSource_Graph: 'Graph API – realtidsdata fra Azure AD (ingen indekseringsforsinkelse)',
    PropertyPane_DataSource_Search: 'SharePoint-søgning – ældre funktionsmåde',
    PropertyPane_DataSource_Note: 'Graph API anbefales. Det læser direkte fra Azure Active Directory, så nye brugere og ændringer af leder vises med det samme. Kræver, at Microsoft Graph-tilladelser er godkendt i SharePoint-appkataloget.',

    // ── Property pane: Custom Attributes ──
    PropertyPane_CustomAttributes_Note: 'Brugerdefinerede attributter kræver Microsoft Graph (datakilde: Graph eller Automatisk). SharePoint-søgning har ingen generisk måde at læse Entra ID-attributter på.',
    PropertyPane_CustomAttributes_Heading: 'Administrer brugerdefinerede attributter',
    PropertyPane_CustomAttributes_Empty: 'Ingen brugerdefinerede attributter er konfigureret.',
    PropertyPane_CustomAttributes_AddButton: '+ Tilføj attribut',
    PropertyPane_CustomAttributes_MaxTooltip: 'Højst {max} brugerdefinerede attributter',
    PropertyPane_CustomAttributes_FieldNameLabel: 'Attributnavn',
    PropertyPane_CustomAttributes_FieldPlaceholder: 'f.eks. companyName',
    PropertyPane_CustomAttributes_FieldError: 'Brug employeeId, companyName, city, ... eller extensionAttribute1-15',
    PropertyPane_CustomAttributes_DisplayLabelLabel: 'Visningsnavn',
    PropertyPane_CustomAttributes_LabelPlaceholder: 'f.eks. Omkostningssted',
    PropertyPane_CustomAttributes_RemoveTitle: 'Fjern attribut',
    PropertyPane_CustomAttributes_RemoveAriaLabel: 'Fjern attribut {ordinal}',
    PropertyPane_CustomAttributes_ShowInDirectory: 'Vis i katalog',
    PropertyPane_CustomAttributes_ShowInOrgChart: 'Vis i organisationsdiagram',

    // ── Property pane: User Filters ──
    PropertyPane_ExcludedAccounts_Label: 'Ekskluder konti',
    PropertyPane_ExcludedAccounts_Placeholder: 'conf-room, noreply, admin@, Servicekonto',
    PropertyPane_ExcludedAccounts_Description: 'Kommaseparerede ord eller mønstre (der skelnes ikke mellem store og små bogstaver). Enhver bruger, hvis visningsnavn, e-mail eller UPN indeholder et af disse, skjules i alle visninger.',
    PropertyPane_RestrictTenant_Label: 'Vis kun brugere fra denne organisation',
    PropertyPane_RestrictTenant_On: 'Til – skjuler konti med eksterne e-maildomæner (f.eks. gmail.com, hotmail.com)',
    PropertyPane_RestrictTenant_Off: 'Fra – alle brugere vises uanset e-maildomæne',
    PropertyPane_HideGuest_Label: 'Skjul Azure AD-gæstekonti',
    PropertyPane_HideGuest_On: 'Til – gæstekonti skjules',
    PropertyPane_HideGuest_Off: 'Fra – gæstekonti vises (med mærket Gæst)',
    PropertyPane_HideDisabled_Label: 'Skjul deaktiverede konti',
    PropertyPane_HideDisabled_On: 'Til – konti med blokeret logon skjules',
    PropertyPane_HideDisabled_Off: 'Fra – deaktiverede konti vises (med mærket Deaktiveret)',
    PropertyPane_HideDisabled_Note: 'Bemærk: Registrering af gæste- og deaktiverede konti kræver datakilden Graph API. SharePoint-søgning returnerer ikke disse oplysninger, så disse to filtre (og mærkerne Gæst/Deaktiveret) har ingen effekt, når data kommer fra søgning.',
    PropertyPane_HideNoJobTitle_Label: 'Skjul konti uden stillingsbetegnelse',
    PropertyPane_HideNoJobTitle_On: 'Til – konti uden stillingsbetegnelse skjules',
    PropertyPane_HideNoJobTitle_Off: 'Fra – alle konti vises uanset stillingsbetegnelse',
    PropertyPane_HideNoDept_Label: 'Skjul konti uden afdeling',
    PropertyPane_HideNoDept_On: 'Til – konti uden afdeling skjules',
    PropertyPane_HideNoDept_Off: 'Fra – alle konti vises uanset afdeling',

    // ── Property pane: Org Chart ──
    PropertyPane_TopLevelUser_Label: 'Topniveaubruger (UPN eller e-mail)',
    PropertyPane_TopLevelUser_Placeholder: 'ceo@yourcompany.com',
    PropertyPane_TopLevelUser_Description: 'Personen, der vises øverst i organisationsdiagrammet',
    PropertyPane_LevelsBelow_Label: 'Antal niveauer, der skal indlæses under roden',
    PropertyPane_DottedLine_Label: 'Attribut for stiplet-linje-leder',
    PropertyPane_DottedLine_Placeholder: 'extensionAttribute10',
    PropertyPane_DottedLine_Description: "Valgfrit. Navnet på den lokale Azure AD-udvidelsesattribut (extensionAttribute1-15), der indeholder e-mail eller UPN for en sekundær leder via \"stiplet linje\". Stiplet-linje-relationer vises på profilkort. Kræver datakilden Graph API.",
    PropertyPane_DefaultZoom_Label: 'Standardzoom for organisationsdiagram',
    PropertyPane_Zoom_Auto: 'Standard (Automatisk tilpasning)',
    PropertyPane_Zoom_50: '50 %',
    PropertyPane_Zoom_75: '75 %',
    PropertyPane_Zoom_100: '100 %',
    PropertyPane_Zoom_125: '125 %',
    PropertyPane_Zoom_150: '150 %',

    // ── Property pane: Org Chart Features ──
    PropertyPane_FeatureToggles_Note: 'Vis eller skjul værktøjslinjeknapper i organisationsdiagrammets visning.',
    PropertyPane_FindMe_Label: 'Knappen Find mig',
    PropertyPane_LayoutToggle_Label: 'Skift af layout (drilldown/lodret/vandret)',
    PropertyPane_Stats_Label: 'Statistiklinje for organisation',
    PropertyPane_DeptFilter_Label: 'Afdelingsfilter',
    PropertyPane_UserFilter_Label: 'Filter for brugertype (medlemmer/gæster)',
    PropertyPane_Visible: 'Synlig',
    PropertyPane_Hidden: 'Skjult',

    // ── Property pane: Directory ──
    PropertyPane_PageSize_Label: 'Maks. antal medarbejdere pr. side',
    PropertyPane_PageSize_AriaLabel: 'Maks. antal medarbejdere pr. side (10 til 200)',
    PropertyPane_PageSize_Note: 'Kortstørrelse, synlige felter og andre visningsindstillinger angives pr. bruger via indstillingsikonet (tandhjulet) i appen.',

    // ── Property pane: Demo ──
    PropertyPane_UseDemoData_Label: 'Brug demodata',
    PropertyPane_UseDemoData_On: 'Til – viser eksempelmedarbejdere',
    PropertyPane_UseDemoData_Off: 'Fra – live Microsoft 365-data',

    // ── Presence status labels ──
    Presence_Available: 'Tilgængelig',
    Presence_Busy: 'Optaget',
    Presence_DoNotDisturb: 'Forstyr ikke',
    Presence_BeRightBack: 'Straks tilbage',
    Presence_Away: 'Ikke til stede',
    Presence_Offline: 'Offline',

    // ── Header / top bar ──
    Header_DirectoryLabel: 'Medarbejderkatalog',
    Header_OrgChartLabel: 'Organisationsdiagram',
    Header_SwitchToView: 'Skift til {view}',
    Header_CompanyLogoAlt: 'Virksomhedens logo',
    Header_RefreshingAria: 'Opdaterer data',
    Header_RefreshAria: 'Opdater data',
    Header_RefreshTitle: 'Opdater data (senest opdateret {when})',
    Header_NotLoadedYet: 'endnu ikke indlæst',
    Header_JustNow: 'lige nu',
    Header_MinutesAgo: '{mins} min. siden',
    Header_HoursAgo: '{hours} t siden',
    Header_PreferencesTitle: 'Indstillinger',
    Header_PreferencesAria: 'Åbn ruden med indstillinger',

    // ── Employee Directory ──
    Directory_LoadingLabel: 'Indlæser medarbejdere...',
    Directory_LoadFailedFallback: 'Kontroller, at webdelen har tilladelsen User.Read.All.',
    Directory_LoadFailedPrefix: 'Det lykkedes ikke at indlæse medarbejdere. {detail}',
    Directory_AllDepartments: 'Alle afdelinger',
    Directory_AllOffices: 'Alle kontorer',
    Directory_StatusDisabled: 'Deaktiveret',
    Directory_StatusGuest: 'Gæst',
    Directory_PresenceStatus: 'Status: {status}',
    Directory_ChatInTeams: 'Chat i Teams',
    Directory_ChatWithInTeams: 'Chat med {name} i Teams',
    Directory_ManagesCount: 'Er leder for {direct}',
    Directory_ManagesCountWithTotal: 'Er leder for {direct} ({total} i alt)',
    Directory_ReportsCountWithTotal: '{direct} ({total} i alt)',
    Directory_ColumnName: 'Navn',
    Directory_ColumnJobTitle: 'Stillingsbetegnelse',
    Directory_ColumnDepartment: 'Afdeling',
    Directory_ColumnOffice: 'Kontor',
    Directory_ColumnEmail: 'E-mail',
    Directory_ColumnPhone: 'Telefon',
    Directory_ColumnReports: 'Underordnede',
    Directory_ColumnChat: 'Chat',
    Directory_PrevPage: 'Forrige',
    Directory_NextPage: 'Næste',
    Directory_PreviousPageAria: 'Forrige side',
    Directory_NextPageAria: 'Næste side',
    Directory_SearchPlaceholder: 'Søg efter navn, titel, e-mail eller afdeling...',
    Directory_SearchAria: 'Søg efter personer',
    Directory_FilterByDepartmentAria: 'Filtrer efter afdeling',
    Directory_FilterByOfficeAria: 'Filtrer efter kontor',
    Directory_ClearSearchTitle: 'Ryd søgning og alle filtre',
    Directory_ClearButton: 'Ryd',
    Directory_ClearFiltersButton: 'Ryd filtre',
    Directory_ExportCsvTitle: 'Eksporter alle filtrerede resultater til en CSV-fil (åbnes i Excel)',
    Directory_ExportCsvButton: 'Eksporter CSV',
    Directory_ViewModeAria: 'Visningstilstand',
    Directory_CardViewTitle: 'Kortvisning',
    Directory_ListViewTitle: 'Listevisning',
    Directory_AlphabetFilterAria: 'Alfabetfilter',
    Directory_ShowAllTitle: 'Vis alle',
    Directory_OtherLettersTitle: 'Filtrer efter navne, der starter med et tal eller andet tegn',
    Directory_FilterByLetterTitle: 'Filtrer efter {letter}',
    Directory_ResultCountSingular: 'person',
    Directory_ResultCountPlural: 'personer',
    Directory_PageOf: ' · side {page} af {totalPages}',
    Directory_FilterActiveSingular: '{count} filter aktivt',
    Directory_FilterActivePlural: '{count} filtre aktive',
    Directory_NoResults: 'Ingen personer fundet',
    Directory_PaginationAria: 'Sideinddeling',

    // ── Org chart toolbar / shared chart chrome ──
    Chart_Layout_Drill: 'Drilldown',
    Chart_Layout_Vertical: 'Oppefra og ned',
    Chart_Layout_Horizontal: 'Fra venstre mod højre',
    Chart_SearchPlaceholder: 'Søg efter personer...',
    Chart_SearchAria: 'Søg efter personer',
    Chart_MatchSingular: 'resultat i træet',
    Chart_MatchPlural: 'resultater i træet',
    Chart_ResultsListAria: 'Personer',
    Chart_ExpandAll: 'Udvid alle',
    Chart_CollapseAll: 'Skjul alle',
    Chart_Expanding: 'Udvider…',
    Chart_Loading: 'Indlæser…',
    Chart_FindMeTitle: 'Find mig i organisationsdiagrammet',
    Chart_ViewLayoutButton: 'Vis',
    Chart_ViewLayoutTitle: 'Skift visningslayout',
    Chart_ViewLayoutPanelTitle: 'Visningslayout',
    Chart_StatsSummaryTitle: 'Oversigt over organisationsstatistik',
    Chart_FilterByDepartmentTitle: 'Filtrer efter afdeling',
    Chart_FilterByDepartmentWithCountAria: 'Filtrer efter afdeling ({count} valgt)',
    Chart_FilterByDepartmentPanelTitle: 'Filtrer efter afdeling',
    Chart_ClearAllFilters: 'Ryd alle filtre',
    Chart_FilterUserTypesTitle: 'Filtrer brugertyper',
    Chart_DownloadPdfTitle: 'Download som PDF',
    Chart_DownloadCsvTitle: 'Download som CSV-regneark',
    Chart_ResetRootTitle: 'Nulstil til standardrod',
    Chart_ViewFromPersonPlaceholder: 'Vis fra person…',
    Chart_ViewFromPersonAria: 'Vis organisationsdiagrammet fra en person',
    Chart_ZoomOutTitle: 'Zoom ud',
    Chart_ZoomInTitle: 'Zoom ind',
    Chart_ZoomResetTitle: 'Nulstil zoom',
    Chart_ShowInChartAria: 'Vis i diagram',
    Chart_ShowInChartTitle: 'Vis i diagram',
    Chart_FilterMembers: 'Almindelige medlemmer',
    Chart_FilterGuests: 'Gæstebrugere',
    Chart_FilterDisabled: 'Deaktiverede konti',
    Chart_SetupTitle: 'Konfigurer organisationsdiagrammet',
    Chart_SetupSubtitle: 'Angiv e-mail eller UPN for topniveaupersonen for at komme i gang.',
    Chart_SetupPlaceholder: 'ceo@company.com',
    Chart_SetupInputAria: 'Topniveaupersonens e-mail eller UPN',
    Chart_SetupLoadButton: 'Indlæs',
    Chart_SetupHint: 'Du kan også angive dette permanent i webdelens indstillinger (administrator).',
    Chart_BuildingLabel: 'Opbygger organisationsdiagram...',
    Chart_RetryButton: 'Prøv igen',
    Chart_NotFoundFromSetup: 'Brugeren "{identifier}" blev ikke fundet.',
    Chart_NotFoundWithSettings: 'Brugeren "{identifier}" blev ikke fundet. Kontroller UPN eller e-mail i indstillingerne.',
    Chart_LoadFailedGeneric: 'Det lykkedes ikke at indlæse organisationsdiagrammet.{detail}',
    Chart_LoadFailedPermissions: ' Kontroller tilladelser.',
    Chart_LoadFailedForPerson: 'Det lykkedes ikke at indlæse organisationsdiagrammet for denne person.',
    Chart_FindMeNotFound: 'Din konto blev ikke fundet i denne organisation.',
    Chart_StatPeople: 'Personer',
    Chart_StatMembers: 'Medlemmer',
    Chart_StatGuests: 'Gæster',
    Chart_StatDepts: 'Afd.',
    Chart_ReportingLineAria: 'Referencelinje',
    Chart_BackToFullOrgTitle: 'Tilbage til fuldt organisationsdiagram',
    Chart_FullOrgLabel: 'Fuld organisation',
    Chart_FocusOnPerson: 'Fokuser på {name}',
    Chart_OrgChartAria: 'Organisationsdiagram',
    Chart_ExportNote_DrillLevel: 'Nuværende drilldown-niveau (ét niveau af direkte underordnede)',
    Chart_ExportNote_PartialLevels: 'Inkluderer kun indlæste niveauer – brug Udvid alle før eksport for at inkludere dybere niveauer',
    Chart_AllowPopupsForPdf: 'Tillad pop op-vinduer for at eksportere PDF.',

    // ── Person card ──
    PersonCard_ProfileAria: 'Profil: {name}',
    PersonCard_CloseTitle: 'Luk',
    PersonCard_CloseAria: 'Luk profil',
    PersonCard_StatusDisabled: 'Deaktiveret',
    PersonCard_StatusGuest: 'Gæst',
    PersonCard_DirectReportSingular: '{count} direkte underordnet',
    PersonCard_DirectReportPlural: '{count} direkte underordnede',
    PersonCard_TotalSuffix: ' · {total} i alt',
    PersonCard_CopyEmailTitle: 'Kopiér e-mailadresse',
    PersonCard_EmailCopiedAria: 'E-mailadresse kopieret',
    PersonCard_ReportsTo: 'Refererer til',
    PersonCard_FocusOnPerson: 'Fokuser på {name}',
    PersonCard_FocusOrgChartOnPerson: 'Fokuser organisationsdiagrammet på {name}',
    PersonCard_DottedLine: 'Stiplet linje',
    PersonCard_DottedLineManager: 'Stiplet-linje-leder: {name}',
    PersonCard_DottedLineReport: 'Stiplet-linje-underordnet: {name}',
    PersonCard_ChatButton: 'Chat',
    PersonCard_EmailButton: 'E-mail',
    PersonCard_FocusButton: 'Fokuser',
    PersonCard_FocusTitle: 'Fokuser organisationsdiagrammet på denne person',

    // ── Org node card ──
    OrgNode_ViewProfile: 'Vis {name}s profil',
    OrgNode_FocusOrgChartOn: 'Fokuser organisationsdiagrammet på {name}',
    OrgNode_Collapse: 'Skjul',
    OrgNode_Expand: 'Udvid',
    OrgNode_DirectReportsSuffix: '{name}s direkte underordnede',
    OrgNode_StatusDisabled: 'Deaktiveret',
    OrgNode_StatusGuest: 'Gæst',
    OrgNode_TotalReportsAcrossLevels: '{count} personer på tværs af alle niveauer under {name}',

    // ── Drill view ──
    Drill_ReportingLineAria: 'Referencelinje',
    Drill_BackToTopTitle: 'Tilbage til toppen',
    Drill_BackToTopAria: 'Tilbage til toppen af organisationsdiagrammet',
    Drill_GoBackTo: 'Gå tilbage til {name}',
    Drill_ViewProfileTitle: 'Vis profil',
    Drill_ViewProfileAria: 'Vis {name}s profil',
    Drill_ProfileButton: 'Profil',
    Drill_LoadingLabel: 'Indlæser...',
    Drill_DirectReports: 'Direkte underordnede',
    Drill_DirectReportsOfAria: 'Direkte underordnede af {name}',
    Drill_DirectReportsAria: 'Direkte underordnede',
    Drill_ViewPersonProfile: 'Vis {name}s profil',
    Drill_ShowPersonReports: 'Vis {name}s direkte underordnede',
    Drill_NoDirectReports: 'Ingen direkte underordnede',

    // ── Settings panel ──
    Settings_AlphabetFirstName: 'Fornavn',
    Settings_AlphabetLastName: 'Efternavn',
    Settings_CardSizeSmall: 'Lille – kompakt, flere kort synlige',
    Settings_CardSizeMedium: 'Mellem – afbalanceret',
    Settings_CardSizeLarge: 'Stor – rummelig, færre kort',
    Settings_HeaderText: 'Indstillinger',
    Settings_SaveButton: 'Gem',
    Settings_CancelButton: 'Annuller',
    Settings_DiscardButton: 'Kassér ændringer',
    Settings_SectionDirectory: 'Katalog',
    Settings_AlphabetFilterByLabel: 'Alfabetfilter efter',
    Settings_CardSizeLabel: 'Kortstørrelse',
    Settings_FontSizeLabel: 'Skriftstørrelse',
    Settings_SectionCardsAndFields: 'Kort og felter',
    Settings_ShowOnCardsLabel: 'Vis på medarbejderkort:',
    Settings_EmailAddressLabel: 'E-mailadresse',
    Settings_PhoneNumberLabel: 'Telefonnummer',
    Settings_DepartmentLabel: 'Afdeling',
    Settings_OfficeLocationLabel: 'Kontorplacering',
    Settings_SectionOrgChart: 'Organisationsdiagram',
    Settings_ManagerLevelsLabel: 'Lederniveauer vist ved fokus på en person: {levels}',
    Settings_CompactCardsLabel: 'Kompakte kort',
    Settings_CompactCardsOn: 'Til – mindre kort, flere synlige på én gang',
    Settings_CompactCardsOff: 'Fra – standardstørrelse',
    Settings_Hint: 'Disse indstillinger gemmes i din browser og gælder kun for dig. Diagramtema, standardvisning og layout konfigureres af din SharePoint-administrator.',
    Settings_SectionDemoData: 'Demodata',
    Settings_DatasetSizeLabel: 'Datasætstørrelse',
    Settings_PeopleCountSuffix: '{count} personer',

    // ── Export (CSV / PDF) ──
    Export_ColumnName: 'Navn',
    Export_ColumnJobTitle: 'Stillingsbetegnelse',
    Export_ColumnDepartment: 'Afdeling',
    Export_ColumnOffice: 'Kontor',
    Export_ColumnEmail: 'E-mail',
    Export_ColumnPhone: 'Telefon',
    Export_ColumnManager: 'Leder',
    Export_ColumnLevel: 'Niveau',
    Export_PdfDocumentTitle: 'Organisationsdiagram',
    Export_PdfHeading: 'Organisationsdiagram',
    Export_PdfRootLabel: 'Rod: {name}',
  };
});
