define([], function () {
  return {
    // ── Property pane: pane header / groups ──
    PropertyPane_HeaderDescription: 'Ρυθμίσεις Smart Org Chart',
    PropertyPane_Group_General: 'Γενικά',
    PropertyPane_Group_Branding: 'Εταιρική ταυτότητα',
    PropertyPane_Group_VisualStyle: 'Οπτικό στυλ',
    PropertyPane_Group_DataSource: 'Πηγή δεδομένων',
    PropertyPane_Group_CustomAttributes: 'Προσαρμοσμένα χαρακτηριστικά',
    PropertyPane_Group_UserFilters: 'Φίλτρα χρηστών',
    PropertyPane_Group_OrgChart: 'Οργανόγραμμα',
    PropertyPane_Group_OrgChartFeatures: 'Λειτουργίες οργανογράμματος',
    PropertyPane_Group_Directory: 'Κατάλογος',
    PropertyPane_Group_Demo: 'Επίδειξη',

    // ── Property pane: General ──
    PropertyPane_DefaultView_Label: 'Προεπιλεγμένη προβολή',

    // ── Property pane: Branding ──
    PropertyPane_AppTitle_Label: 'Τίτλος εφαρμογής',
    PropertyPane_AppTitle_Placeholder: 'Οργανόγραμμα Contoso',
    PropertyPane_AppTitle_Description: 'Εμφανίζεται στη γραμμή κεφαλίδας δίπλα στο όνομα της προβολής',
    PropertyPane_LogoUrl_Label: 'URL λογότυπου',
    PropertyPane_LogoUrl_Placeholder: 'https://contoso.sharepoint.com/sites/yoursite/SiteAssets/logo.png',
    PropertyPane_LogoUrl_Description: 'Πλήρες URL για εικόνα PNG/SVG/JPG. Συμβουλή: ανοίξτε το αρχείο εικόνας στο πρόγραμμα περιήγησης και αντιγράψτε το URL από τη γραμμή διευθύνσεων. Τα URL κοινής χρήσης «Αντιγραφή συνδέσμου» δεν θα λειτουργήσουν.',
    PropertyPane_DirectoryLabel_Label: 'Ετικέτα προβολής Καταλόγου εργαζομένων',
    PropertyPane_OrgChartLabel_Label: 'Ετικέτα προβολής Οργανογράμματος',
    PropertyPane_ViewLabel_Description: 'Αφήστε το κενό για χρήση του προεπιλεγμένου ονόματος, ή πληκτρολογήστε "[blank]" για πλήρη απόκρυψη της ετικέτας.',

    // ── Property pane: Visual Style ──
    PropertyPane_ChartTheme_Label: 'Θέμα οργανογράμματος',
    PropertyPane_Theme_Modern: 'Μοντέρνο — χρώματα τμημάτων σε λευκό φόντο',
    PropertyPane_Theme_Minimal: 'Μινιμαλιστικό — επίπεδο και χαμηλής αντίθεσης',
    PropertyPane_Theme_Corporate: 'Εταιρικό — ενιαίο μπλε',
    PropertyPane_Theme_Dark: 'Σκούρο — σκούρο μπλε φόντο',
    PropertyPane_Theme_Custom: 'Προσαρμοσμένο — επιλέξτε δικό σας χρώμα',
    PropertyPane_AccentColor_Label: 'Προσαρμοσμένο χρώμα έμφασης',
    PropertyPane_AccentColor_PickerAriaLabel: 'Επιλογέας χρώματος έμφασης',
    PropertyPane_AccentColor_HexLabel: 'Hex',
    PropertyPane_AccentColor_HexAriaLabel: 'Τιμή hex χρώματος έμφασης',
    PropertyPane_AccentColor_RgbLabel: 'RGB',
    PropertyPane_AccentColor_ChannelAriaLabel: 'Κανάλι {name} (0 έως 255)',
    PropertyPane_AccentColor_ContrastWithWhite: 'Αντίθεση με το λευκό: {ratio}:1 ({passes})',
    PropertyPane_AccentColor_PassesAA: 'πληροί το επίπεδο AA',
    PropertyPane_AccentColor_LargeTextOnly: 'μόνο για μεγάλο κείμενο',
    PropertyPane_AccentColor_LowContrast: 'χαμηλή αντίθεση',
    PropertyPane_AccentColor_DarkTextNote: 'Το κείμενο πάνω σε αυτό το χρώμα θα χρησιμοποιεί σκούρο χρώμα γραμματοσειράς για καλύτερη αναγνωσιμότητα.',
    PropertyPane_AccentColor_DarkerShadeNote: 'Οι τίτλοι και οι σύνδεσμοι θα χρησιμοποιούν μια πιο σκούρα απόχρωση ({hex}) για καλύτερη αναγνωσιμότητα.',
    PropertyPane_AccentColor_InvalidHex: 'Το «{typed}» δεν είναι έγκυρο δεκαεξαδικό χρώμα. Χρησιμοποιήστε μια τιμή όπως #0078d4 ή #07d.',
    PropertyPane_DefaultFontSize_Label: 'Προεπιλεγμένο μέγεθος γραμματοσειράς',
    PropertyPane_FontSize_75: '75% — πολύ μικρό',
    PropertyPane_FontSize_85: '85% — μικρό',
    PropertyPane_FontSize_100: '100% — κανονικό',
    PropertyPane_FontSize_115: '115% — μεγάλο',
    PropertyPane_FontSize_130: '130% — πολύ μεγάλο',
    PropertyPane_FontSize_150: '150% — XXL',
    PropertyPane_FontSize_175: '175% — XXXL',
    PropertyPane_DefaultLayout_Label: 'Προεπιλεγμένη διάταξη οργανογράμματος',
    PropertyPane_Layout_Drill: 'Ανάλυση κατά επίπεδο',
    PropertyPane_Layout_Vertical: 'Από πάνω προς τα κάτω',
    PropertyPane_Layout_Horizontal: 'Από αριστερά προς τα δεξιά',

    // ── Property pane: Data Source ──
    PropertyPane_DataSource_Label: 'Από πού θα φορτώνονται τα δεδομένα χρηστών και οργανισμού',
    PropertyPane_DataSource_Auto: 'Αυτόματο — Graph API, με επιστροφή σε αναζήτηση SharePoint',
    PropertyPane_DataSource_Graph: 'Graph API — δεδομένα Azure AD σε πραγματικό χρόνο (χωρίς καθυστέρηση ευρετηρίασης)',
    PropertyPane_DataSource_Search: 'Αναζήτηση SharePoint — παλαιότερη συμπεριφορά',
    PropertyPane_DataSource_Note: 'Συνιστάται η χρήση του Graph API. Διαβάζει απευθείας από το Azure Active Directory, επομένως οι νέοι χρήστες και οι αλλαγές προϊσταμένων εμφανίζονται αμέσως. Απαιτεί έγκριση των δικαιωμάτων Microsoft Graph στον Κατάλογο εφαρμογών του SharePoint.',

    // ── Property pane: Custom Attributes ──
    PropertyPane_CustomAttributes_Note: 'Τα προσαρμοσμένα χαρακτηριστικά απαιτούν Microsoft Graph (Πηγή δεδομένων: Graph ή Αυτόματο). Η αναζήτηση SharePoint δεν διαθέτει γενικό τρόπο ανάγνωσης χαρακτηριστικών Entra ID.',
    PropertyPane_CustomAttributes_Heading: 'Διαχείριση προσαρμοσμένων χαρακτηριστικών',
    PropertyPane_CustomAttributes_Empty: 'Δεν έχουν διαμορφωθεί προσαρμοσμένα χαρακτηριστικά.',
    PropertyPane_CustomAttributes_AddButton: '+ Προσθήκη χαρακτηριστικού',
    PropertyPane_CustomAttributes_MaxTooltip: 'Έως {max} προσαρμοσμένα χαρακτηριστικά',
    PropertyPane_CustomAttributes_FieldNameLabel: 'Όνομα χαρακτηριστικού',
    PropertyPane_CustomAttributes_FieldPlaceholder: 'π.χ. companyName',
    PropertyPane_CustomAttributes_FieldError: 'Χρησιμοποιήστε employeeId, companyName, city, ... ή extensionAttribute1-15',
    PropertyPane_CustomAttributes_DisplayLabelLabel: 'Ετικέτα εμφάνισης',
    PropertyPane_CustomAttributes_LabelPlaceholder: 'π.χ. Κέντρο κόστους',
    PropertyPane_CustomAttributes_RemoveTitle: 'Κατάργηση χαρακτηριστικού',
    PropertyPane_CustomAttributes_RemoveAriaLabel: 'Κατάργηση χαρακτηριστικού {ordinal}',
    PropertyPane_CustomAttributes_ShowInDirectory: 'Εμφάνιση στον Κατάλογο',
    PropertyPane_CustomAttributes_ShowInOrgChart: 'Εμφάνιση στο Οργανόγραμμα',

    // ── Property pane: User Filters ──
    PropertyPane_ExcludedAccounts_Label: 'Εξαίρεση λογαριασμών',
    PropertyPane_ExcludedAccounts_Placeholder: 'αίθουσα συσκέψεων, noreply, admin@, λογαριασμός υπηρεσίας',
    PropertyPane_ExcludedAccounts_Description: 'Λέξεις ή μοτίβα χωρισμένα με κόμμα (χωρίς διάκριση πεζών-κεφαλαίων). Κάθε χρήστης του οποίου το όνομα εμφάνισης, το email ή το UPN περιέχει ένα από αυτά θα αποκρύπτεται από όλες τις προβολές.',
    PropertyPane_RestrictTenant_Label: 'Εμφάνιση μόνο χρηστών του μισθωτή',
    PropertyPane_RestrictTenant_On: 'Ενεργό — αποκρύπτει λογαριασμούς με εξωτερικούς τομείς email (π.χ. gmail.com, hotmail.com)',
    PropertyPane_RestrictTenant_Off: 'Ανενεργό — εμφανίζονται όλοι οι χρήστες, ανεξαρτήτως τομέα email',
    PropertyPane_HideGuest_Label: 'Απόκρυψη λογαριασμών επισκεπτών Azure AD',
    PropertyPane_HideGuest_On: 'Ενεργό — οι λογαριασμοί επισκεπτών αποκρύπτονται',
    PropertyPane_HideGuest_Off: 'Ανενεργό — οι λογαριασμοί επισκεπτών εμφανίζονται (με ένδειξη Επισκέπτης)',
    PropertyPane_HideDisabled_Label: 'Απόκρυψη απενεργοποιημένων λογαριασμών',
    PropertyPane_HideDisabled_On: 'Ενεργό — οι λογαριασμοί με αποκλεισμένη σύνδεση αποκρύπτονται',
    PropertyPane_HideDisabled_Off: 'Ανενεργό — οι απενεργοποιημένοι λογαριασμοί εμφανίζονται (με ένδειξη Απενεργοποιημένος)',
    PropertyPane_HideDisabled_Note: 'Σημείωση: ο εντοπισμός λογαριασμών επισκεπτών και απενεργοποιημένων λογαριασμών απαιτεί την πηγή δεδομένων Graph API. Η αναζήτηση SharePoint δεν επιστρέφει αυτές τις πληροφορίες, επομένως αυτά τα δύο φίλτρα (και οι ενδείξεις Επισκέπτης/Απενεργοποιημένος) δεν έχουν καμία επίδραση όταν τα δεδομένα προέρχονται από την Αναζήτηση.',
    PropertyPane_HideNoJobTitle_Label: 'Απόκρυψη λογαριασμών χωρίς τίτλο θέσης εργασίας',
    PropertyPane_HideNoJobTitle_On: 'Ενεργό — οι λογαριασμοί χωρίς τίτλο θέσης εργασίας αποκρύπτονται',
    PropertyPane_HideNoJobTitle_Off: 'Ανενεργό — εμφανίζονται όλοι οι λογαριασμοί, ανεξαρτήτως τίτλου θέσης εργασίας',
    PropertyPane_HideNoDept_Label: 'Απόκρυψη λογαριασμών χωρίς τμήμα',
    PropertyPane_HideNoDept_On: 'Ενεργό — οι λογαριασμοί χωρίς τμήμα αποκρύπτονται',
    PropertyPane_HideNoDept_Off: 'Ανενεργό — εμφανίζονται όλοι οι λογαριασμοί, ανεξαρτήτως τμήματος',

    // ── Property pane: Org Chart ──
    PropertyPane_TopLevelUser_Label: 'Χρήστης ανώτατου επιπέδου (UPN ή email)',
    PropertyPane_TopLevelUser_Placeholder: 'ceo@yourcompany.com',
    PropertyPane_TopLevelUser_Description: 'Το άτομο που εμφανίζεται στη ρίζα του οργανογράμματος',
    PropertyPane_LevelsBelow_Label: 'Επίπεδα προς φόρτωση κάτω από τη ρίζα',
    PropertyPane_DottedLine_Label: 'Χαρακτηριστικό διακεκομμένης γραμμής προϊσταμένου',
    PropertyPane_DottedLine_Placeholder: 'extensionAttribute10',
    PropertyPane_DottedLine_Description: 'Προαιρετικό. Το όνομα του χαρακτηριστικού επέκτασης του Azure AD για εγκατάσταση εντός εγκαταστάσεων (extensionAttribute1-15) που αποθηκεύει το email ή το UPN ενός δευτερεύοντος προϊσταμένου «διακεκομμένης γραμμής». Οι σχέσεις διακεκομμένης γραμμής εμφανίζονται στις κάρτες προφίλ. Απαιτεί την πηγή δεδομένων Graph API.',
    PropertyPane_DefaultZoom_Label: 'Προεπιλεγμένη εστίαση οργανογράμματος',
    PropertyPane_Zoom_Auto: 'Προεπιλογή (αυτόματη προσαρμογή)',
    PropertyPane_Zoom_50: '50%',
    PropertyPane_Zoom_75: '75%',
    PropertyPane_Zoom_100: '100%',
    PropertyPane_Zoom_125: '125%',
    PropertyPane_Zoom_150: '150%',

    // ── Property pane: Org Chart Features ──
    PropertyPane_FeatureToggles_Note: 'Εμφάνιση ή απόκρυψη κουμπιών της γραμμής εργαλείων στην προβολή οργανογράμματος.',
    PropertyPane_FindMe_Label: 'Κουμπί «Βρες με»',
    PropertyPane_LayoutToggle_Label: 'Εναλλαγή διάταξης (ανάλυση κατά επίπεδο / κατακόρυφη / οριζόντια)',
    PropertyPane_Stats_Label: 'Γραμμή στατιστικών οργανισμού',
    PropertyPane_DeptFilter_Label: 'Φίλτρο τμήματος',
    PropertyPane_UserFilter_Label: 'Φίλτρο τύπου χρήστη (μέλη / επισκέπτες)',
    PropertyPane_Visible: 'Ορατό',
    PropertyPane_Hidden: 'Κρυφό',

    // ── Property pane: Directory ──
    PropertyPane_PageSize_Label: 'Μέγιστος αριθμός εργαζομένων ανά σελίδα',
    PropertyPane_PageSize_AriaLabel: 'Μέγιστος αριθμός εργαζομένων ανά σελίδα (10 έως 200)',
    PropertyPane_PageSize_Note: 'Το μέγεθος καρτών, τα ορατά πεδία και άλλες προτιμήσεις εμφάνισης ορίζονται ανά χρήστη μέσω του εικονιδίου ρυθμίσεων (γρανάζι) στην εφαρμογή.',

    // ── Property pane: Demo ──
    PropertyPane_UseDemoData_Label: 'Χρήση δεδομένων επίδειξης',
    PropertyPane_UseDemoData_On: 'Ενεργό — εμφάνιση δειγματικών εργαζομένων',
    PropertyPane_UseDemoData_Off: 'Ανενεργό — δεδομένα Microsoft 365 σε πραγματικό χρόνο',

    // ── Presence status labels ──
    Presence_Available: 'Διαθέσιμος',
    Presence_Busy: 'Απασχολημένος',
    Presence_DoNotDisturb: 'Μην ενοχλείτε',
    Presence_BeRightBack: 'Θα επιστρέψω αμέσως',
    Presence_Away: 'Απουσιάζω',
    Presence_Offline: 'Εκτός σύνδεσης',

    // ── Header / top bar ──
    Header_DirectoryLabel: 'Κατάλογος εργαζομένων',
    Header_OrgChartLabel: 'Οργανόγραμμα',
    Header_SwitchToView: 'Εναλλαγή σε {view}',
    Header_CompanyLogoAlt: 'Λογότυπο εταιρείας',
    Header_RefreshingAria: 'Ανανέωση δεδομένων',
    Header_RefreshAria: 'Ανανέωση δεδομένων',
    Header_RefreshTitle: 'Ανανέωση δεδομένων (τελευταία ενημέρωση {when})',
    Header_NotLoadedYet: 'δεν έχει φορτωθεί ακόμη',
    Header_JustNow: 'μόλις τώρα',
    Header_MinutesAgo: 'πριν από {mins} λεπτά',
    Header_HoursAgo: 'πριν από {hours} ώρες',
    Header_PreferencesTitle: 'Προτιμήσεις',
    Header_PreferencesAria: 'Άνοιγμα πίνακα προτιμήσεων',

    // ── Employee Directory ──
    Directory_LoadingLabel: 'Φόρτωση εργαζομένων...',
    Directory_LoadFailedFallback: 'Βεβαιωθείτε ότι το web part διαθέτει το δικαίωμα User.Read.All.',
    Directory_LoadFailedPrefix: 'Η φόρτωση των εργαζομένων απέτυχε. {detail}',
    Directory_AllDepartments: 'Όλα τα τμήματα',
    Directory_AllOffices: 'Όλα τα γραφεία',
    Directory_StatusDisabled: 'Απενεργοποιημένος',
    Directory_StatusGuest: 'Επισκέπτης',
    Directory_PresenceStatus: 'Κατάσταση: {status}',
    Directory_ChatInTeams: 'Συνομιλία στο Teams',
    Directory_ChatWithInTeams: 'Συνομιλία με {name} στο Teams',
    Directory_ManagesCount: 'Διοικεί {direct}',
    Directory_ManagesCountWithTotal: 'Διοικεί {direct} ({total} σύνολο)',
    Directory_ReportsCountWithTotal: '{direct} ({total} σύνολο)',
    Directory_ColumnName: 'Όνομα',
    Directory_ColumnJobTitle: 'Τίτλος θέσης',
    Directory_ColumnDepartment: 'Τμήμα',
    Directory_ColumnOffice: 'Γραφείο',
    Directory_ColumnEmail: 'Email',
    Directory_ColumnPhone: 'Τηλέφωνο',
    Directory_ColumnReports: 'Υφιστάμενοι',
    Directory_ColumnChat: 'Συνομιλία',
    Directory_PrevPage: 'Προηγ.',
    Directory_NextPage: 'Επόμ.',
    Directory_PreviousPageAria: 'Προηγούμενη σελίδα',
    Directory_NextPageAria: 'Επόμενη σελίδα',
    Directory_SearchPlaceholder: 'Αναζήτηση κατά όνομα, τίτλο, email ή τμήμα...',
    Directory_SearchAria: 'Αναζήτηση ατόμων',
    Directory_FilterByDepartmentAria: 'Φιλτράρισμα κατά τμήμα',
    Directory_FilterByOfficeAria: 'Φιλτράρισμα κατά γραφείο',
    Directory_ClearSearchTitle: 'Απαλοιφή αναζήτησης και όλων των φίλτρων',
    Directory_ClearButton: 'Απαλοιφή',
    Directory_ClearFiltersButton: 'Απαλοιφή φίλτρων',
    Directory_ExportCsvTitle: 'Εξαγωγή όλων των φιλτραρισμένων αποτελεσμάτων σε αρχείο CSV (ανοίγει στο Excel)',
    Directory_ExportCsvButton: 'Εξαγωγή CSV',
    Directory_ViewModeAria: 'Λειτουργία προβολής',
    Directory_CardViewTitle: 'Προβολή καρτών',
    Directory_ListViewTitle: 'Προβολή λίστας',
    Directory_AlphabetFilterAria: 'Αλφαβητικό φίλτρο',
    Directory_ShowAllTitle: 'Εμφάνιση όλων',
    Directory_OtherLettersTitle: 'Φιλτράρισμα ονομάτων που ξεκινούν με αριθμό ή άλλο χαρακτήρα',
    Directory_FilterByLetterTitle: 'Φιλτράρισμα κατά {letter}',
    Directory_ResultCountSingular: 'άτομο',
    Directory_ResultCountPlural: 'άτομα',
    Directory_PageOf: ' · σελίδα {page} από {totalPages}',
    Directory_FilterActiveSingular: '{count} ενεργό φίλτρο',
    Directory_FilterActivePlural: '{count} ενεργά φίλτρα',
    Directory_NoResults: 'Δεν βρέθηκαν άτομα',
    Directory_PaginationAria: 'Σελιδοποίηση',

    // ── Org chart toolbar / shared chart chrome ──
    Chart_Layout_Drill: 'Ανάλυση κατά επίπεδο',
    Chart_Layout_Vertical: 'Από πάνω προς τα κάτω',
    Chart_Layout_Horizontal: 'Από αριστερά προς τα δεξιά',
    Chart_SearchPlaceholder: 'Αναζήτηση ατόμων...',
    Chart_SearchAria: 'Αναζήτηση ατόμων',
    Chart_MatchSingular: 'αποτέλεσμα στο δέντρο',
    Chart_MatchPlural: 'αποτελέσματα στο δέντρο',
    Chart_ResultsListAria: 'Άτομα',
    Chart_ExpandAll: 'Ανάπτυξη όλων',
    Chart_CollapseAll: 'Σύμπτυξη όλων',
    Chart_Expanding: 'Ανάπτυξη…',
    Chart_Loading: 'Φόρτωση…',
    Chart_FindMeTitle: 'Εύρεση της θέσης μου στο οργανόγραμμα',
    Chart_ViewLayoutButton: 'Προβολή',
    Chart_ViewLayoutTitle: 'Εναλλαγή διάταξης προβολής',
    Chart_ViewLayoutPanelTitle: 'Διάταξη προβολής',
    Chart_StatsSummaryTitle: 'Σύνοψη στατιστικών οργανισμού',
    Chart_FilterByDepartmentTitle: 'Φιλτράρισμα κατά τμήμα',
    Chart_FilterByDepartmentWithCountAria: 'Φιλτράρισμα κατά τμήμα ({count} επιλεγμένα)',
    Chart_FilterByDepartmentPanelTitle: 'Φιλτράρισμα κατά τμήμα',
    Chart_ClearAllFilters: 'Απαλοιφή όλων των φίλτρων',
    Chart_FilterUserTypesTitle: 'Φιλτράρισμα τύπων χρηστών',
    Chart_DownloadPdfTitle: 'Λήψη ως PDF',
    Chart_DownloadCsvTitle: 'Λήψη ως υπολογιστικό φύλλο CSV',
    Chart_ResetRootTitle: 'Επαναφορά στην προεπιλεγμένη ρίζα',
    Chart_ViewFromPersonPlaceholder: 'Προβολή από άτομο…',
    Chart_ViewFromPersonAria: 'Προβολή του οργανογράμματος από ένα άτομο',
    Chart_ZoomOutTitle: 'Σμίκρυνση',
    Chart_ZoomInTitle: 'Μεγέθυνση',
    Chart_ZoomResetTitle: 'Επαναφορά εστίασης',
    Chart_ShowInChartAria: 'Εμφάνιση στο οργανόγραμμα',
    Chart_ShowInChartTitle: 'Εμφάνιση στο οργανόγραμμα',
    Chart_FilterMembers: 'Κανονικά μέλη',
    Chart_FilterGuests: 'Χρήστες επισκέπτες',
    Chart_FilterDisabled: 'Απενεργοποιημένοι λογαριασμοί',
    Chart_SetupTitle: 'Ρύθμιση του οργανογράμματος',
    Chart_SetupSubtitle: 'Εισαγάγετε το email ή το UPN του ατόμου ανώτατου επιπέδου για να ξεκινήσετε.',
    Chart_SetupPlaceholder: 'ceo@company.com',
    Chart_SetupInputAria: 'Email ή UPN του ατόμου ανώτατου επιπέδου',
    Chart_SetupLoadButton: 'Φόρτωση',
    Chart_SetupHint: 'Μπορείτε επίσης να το ορίσετε μόνιμα στις ρυθμίσεις του web part (διαχειριστής).',
    Chart_BuildingLabel: 'Δημιουργία οργανογράμματος...',
    Chart_RetryButton: 'Επανάληψη',
    Chart_NotFoundFromSetup: 'Ο χρήστης «{identifier}» δεν βρέθηκε.',
    Chart_NotFoundWithSettings: 'Ο χρήστης «{identifier}» δεν βρέθηκε. Ελέγξτε το UPN ή το email στις Ρυθμίσεις.',
    Chart_LoadFailedGeneric: 'Η φόρτωση του οργανογράμματος απέτυχε.{detail}',
    Chart_LoadFailedPermissions: ' Ελέγξτε τα δικαιώματα.',
    Chart_LoadFailedForPerson: 'Η φόρτωση του οργανογράμματος για αυτό το άτομο απέτυχε.',
    Chart_FindMeNotFound: 'Ο λογαριασμός σας δεν βρέθηκε σε αυτόν τον οργανισμό.',
    Chart_StatPeople: 'Άτομα',
    Chart_StatMembers: 'Μέλη',
    Chart_StatGuests: 'Επισκέπτες',
    Chart_StatDepts: 'Τμήματα',
    Chart_ReportingLineAria: 'Ιεραρχική γραμμή αναφοράς',
    Chart_BackToFullOrgTitle: 'Επιστροφή στο πλήρες οργανόγραμμα',
    Chart_FullOrgLabel: 'Πλήρης οργανισμός',
    Chart_FocusOnPerson: 'Εστίαση σε {name}',
    Chart_OrgChartAria: 'Οργανόγραμμα',
    Chart_ExportNote_DrillLevel: 'Τρέχον επίπεδο ανάλυσης (ένα επίπεδο άμεσων υφισταμένων)',
    Chart_ExportNote_PartialLevels: 'Περιλαμβάνει μόνο τα φορτωμένα επίπεδα — χρησιμοποιήστε την «Ανάπτυξη όλων» πριν από την εξαγωγή για να συμπεριληφθούν βαθύτερα επίπεδα',
    Chart_AllowPopupsForPdf: 'Επιτρέψτε τα αναδυόμενα παράθυρα για την εξαγωγή σε PDF.',

    // ── Person card ──
    PersonCard_ProfileAria: 'Προφίλ: {name}',
    PersonCard_CloseTitle: 'Κλείσιμο',
    PersonCard_CloseAria: 'Κλείσιμο προφίλ',
    PersonCard_StatusDisabled: 'Απενεργοποιημένος',
    PersonCard_StatusGuest: 'Επισκέπτης',
    PersonCard_DirectReportSingular: '{count} άμεσος υφιστάμενος',
    PersonCard_DirectReportPlural: '{count} άμεσοι υφιστάμενοι',
    PersonCard_TotalSuffix: ' · {total} σύνολο',
    PersonCard_CopyEmailTitle: 'Αντιγραφή διεύθυνσης email',
    PersonCard_EmailCopiedAria: 'Η διεύθυνση email αντιγράφηκε',
    PersonCard_ReportsTo: 'Αναφέρεται σε',
    PersonCard_FocusOnPerson: 'Εστίαση σε {name}',
    PersonCard_FocusOrgChartOnPerson: 'Εστίαση οργανογράμματος σε {name}',
    PersonCard_DottedLine: 'Διακεκομμένη γραμμή',
    PersonCard_DottedLineManager: 'Προϊστάμενος διακεκομμένης γραμμής: {name}',
    PersonCard_DottedLineReport: 'Υφιστάμενος διακεκομμένης γραμμής: {name}',
    PersonCard_ChatButton: 'Συνομιλία',
    PersonCard_EmailButton: 'Email',
    PersonCard_FocusButton: 'Εστίαση',
    PersonCard_FocusTitle: 'Εστίαση οργανογράμματος σε αυτό το άτομο',

    // ── Org node card ──
    OrgNode_ViewProfile: 'Προβολή του προφίλ του/της {name}',
    OrgNode_FocusOrgChartOn: 'Εστίαση οργανογράμματος σε {name}',
    OrgNode_Collapse: 'Σύμπτυξη',
    OrgNode_Expand: 'Ανάπτυξη',
    OrgNode_DirectReportsSuffix: 'Άμεσοι υφιστάμενοι του/της {name}',
    OrgNode_StatusDisabled: 'Απενεργοποιημένος',
    OrgNode_StatusGuest: 'Επισκέπτης',
    OrgNode_TotalReportsAcrossLevels: '{count} άτομα σε όλα τα επίπεδα κάτω από {name}',

    // ── Drill view ──
    Drill_ReportingLineAria: 'Ιεραρχική γραμμή αναφοράς',
    Drill_BackToTopTitle: 'Επιστροφή στην κορυφή',
    Drill_BackToTopAria: 'Επιστροφή στην κορυφή του οργανογράμματος',
    Drill_GoBackTo: 'Επιστροφή σε {name}',
    Drill_ViewProfileTitle: 'Προβολή προφίλ',
    Drill_ViewProfileAria: 'Προβολή του προφίλ του/της {name}',
    Drill_ProfileButton: 'Προφίλ',
    Drill_LoadingLabel: 'Φόρτωση...',
    Drill_DirectReports: 'Άμεσοι υφιστάμενοι',
    Drill_DirectReportsOfAria: 'Άμεσοι υφιστάμενοι του/της {name}',
    Drill_DirectReportsAria: 'Άμεσοι υφιστάμενοι',
    Drill_ViewPersonProfile: 'Προβολή του προφίλ του/της {name}',
    Drill_ShowPersonReports: 'Εμφάνιση των άμεσων υφισταμένων του/της {name}',
    Drill_NoDirectReports: 'Δεν υπάρχουν άμεσοι υφιστάμενοι',

    // ── Settings panel ──
    Settings_AlphabetFirstName: 'Όνομα',
    Settings_AlphabetLastName: 'Επώνυμο',
    Settings_CardSizeSmall: 'Μικρό — συμπαγές, περισσότερες κάρτες ορατές',
    Settings_CardSizeMedium: 'Μεσαίο — ισορροπημένο',
    Settings_CardSizeLarge: 'Μεγάλο — ευρύχωρο, λιγότερες κάρτες',
    Settings_HeaderText: 'Προτιμήσεις',
    Settings_SaveButton: 'Αποθήκευση',
    Settings_CancelButton: 'Ακύρωση',
    Settings_DiscardButton: 'Απόρριψη αλλαγών',
    Settings_SectionDirectory: 'Κατάλογος',
    Settings_AlphabetFilterByLabel: 'Αλφαβητικό φιλτράρισμα κατά',
    Settings_CardSizeLabel: 'Μέγεθος κάρτας',
    Settings_FontSizeLabel: 'Μέγεθος γραμματοσειράς',
    Settings_SectionCardsAndFields: 'Κάρτες και πεδία',
    Settings_ShowOnCardsLabel: 'Εμφάνιση στις κάρτες εργαζομένων:',
    Settings_EmailAddressLabel: 'Διεύθυνση email',
    Settings_PhoneNumberLabel: 'Αριθμός τηλεφώνου',
    Settings_DepartmentLabel: 'Τμήμα',
    Settings_OfficeLocationLabel: 'Τοποθεσία γραφείου',
    Settings_SectionOrgChart: 'Οργανόγραμμα',
    Settings_ManagerLevelsLabel: 'Επίπεδα προϊσταμένων που εμφανίζονται κατά την εστίαση σε ένα άτομο: {levels}',
    Settings_CompactCardsLabel: 'Συμπαγείς κάρτες',
    Settings_CompactCardsOn: 'Ενεργό — μικρότερες κάρτες, περισσότερες ορατές ταυτόχρονα',
    Settings_CompactCardsOff: 'Ανενεργό — κανονικό μέγεθος',
    Settings_Hint: 'Αυτές οι προτιμήσεις αποθηκεύονται στο πρόγραμμα περιήγησής σας και ισχύουν μόνο για εσάς. Το θέμα οργανογράμματος, η προεπιλεγμένη προβολή και η διάταξη διαμορφώνονται από τον διαχειριστή SharePoint.',
    Settings_SectionDemoData: 'Δεδομένα επίδειξης',
    Settings_DatasetSizeLabel: 'Μέγεθος συνόλου δεδομένων',
    Settings_PeopleCountSuffix: '{count} άτομα',

    // ── Export (CSV / PDF) ──
    Export_ColumnName: 'Όνομα',
    Export_ColumnJobTitle: 'Τίτλος θέσης',
    Export_ColumnDepartment: 'Τμήμα',
    Export_ColumnOffice: 'Γραφείο',
    Export_ColumnEmail: 'Email',
    Export_ColumnPhone: 'Τηλέφωνο',
    Export_ColumnManager: 'Προϊστάμενος',
    Export_ColumnLevel: 'Επίπεδο',
    Export_PdfDocumentTitle: 'Οργανόγραμμα',
    Export_PdfHeading: 'Οργανόγραμμα',
    Export_PdfRootLabel: 'Ρίζα: {name}',
  };
});
