define([], function () {
  return {
    // ── Property pane: pane header / groups ──
    PropertyPane_HeaderDescription: 'Smart Org Chart Settings',
    PropertyPane_Group_General: 'General',
    PropertyPane_Group_Branding: 'Branding',
    PropertyPane_Group_VisualStyle: 'Visual Style',
    PropertyPane_Group_DataSource: 'Data Source',
    PropertyPane_Group_CustomAttributes: 'Custom Attributes',
    PropertyPane_Group_UserFilters: 'User Filters',
    PropertyPane_Group_OrgChart: 'Org Chart',
    PropertyPane_Group_OrgChartFeatures: 'Org Chart Features',
    PropertyPane_Group_Directory: 'Directory',
    PropertyPane_Group_Demo: 'Demo',

    // ── Property pane: General ──
    PropertyPane_DefaultView_Label: 'Default View',

    // ── Property pane: Branding ──
    PropertyPane_AppTitle_Label: 'App Title',
    PropertyPane_AppTitle_Placeholder: 'Contoso Org Chart',
    PropertyPane_AppTitle_Description: 'Displayed in the header bar alongside the view name',
    PropertyPane_LogoUrl_Label: 'Logo URL',
    PropertyPane_LogoUrl_Placeholder: 'https://contoso.sharepoint.com/sites/yoursite/SiteAssets/logo.png',
    PropertyPane_LogoUrl_Description: 'Full URL to a PNG/SVG/JPG image. Tip: open the image file in your browser and copy the address bar URL. "Copy link" sharing URLs will not work.',
    PropertyPane_DirectoryLabel_Label: 'Employee Directory View Label',
    PropertyPane_OrgChartLabel_Label: 'Org Chart View Label',
    PropertyPane_ViewLabel_Description: 'Leave blank to use the default name, or type "[blank]" to hide the label entirely.',

    // ── Property pane: Visual Style ──
    PropertyPane_ChartTheme_Label: 'Chart Theme',
    PropertyPane_Theme_Modern: 'Modern — dept colors on white',
    PropertyPane_Theme_Minimal: 'Minimal — flat & low contrast',
    PropertyPane_Theme_Corporate: 'Corporate — unified blue',
    PropertyPane_Theme_Dark: 'Dark — dark navy background',
    PropertyPane_Theme_Custom: 'Custom — pick your own color',
    PropertyPane_AccentColor_Label: 'Custom Accent Color',
    PropertyPane_AccentColor_PickerAriaLabel: 'Accent color picker',
    PropertyPane_AccentColor_HexLabel: 'Hex',
    PropertyPane_AccentColor_HexAriaLabel: 'Accent color hex value',
    PropertyPane_AccentColor_RgbLabel: 'RGB',
    PropertyPane_AccentColor_ChannelAriaLabel: '{name} channel (0 to 255)',
    PropertyPane_AccentColor_ContrastWithWhite: 'Contrast with white: {ratio}:1 ({passes})',
    PropertyPane_AccentColor_PassesAA: 'passes AA',
    PropertyPane_AccentColor_LargeTextOnly: 'large text only',
    PropertyPane_AccentColor_LowContrast: 'low contrast',
    PropertyPane_AccentColor_DarkTextNote: 'Text on this color will use dark text for readability.',
    PropertyPane_AccentColor_DarkerShadeNote: 'Titles and links will use a darker shade ({hex}) for readability.',
    PropertyPane_AccentColor_InvalidHex: '"{typed}" is not a valid hex color. Use a value like #0078d4 or #07d.',
    PropertyPane_DefaultFontSize_Label: 'Default Font Size',
    PropertyPane_FontSize_75: '75% — Extra Small',
    PropertyPane_FontSize_85: '85% — Small',
    PropertyPane_FontSize_100: '100% — Normal',
    PropertyPane_FontSize_115: '115% — Large',
    PropertyPane_FontSize_130: '130% — Extra Large',
    PropertyPane_FontSize_150: '150% — XXL',
    PropertyPane_FontSize_175: '175% — XXXL',
    PropertyPane_DefaultLayout_Label: 'Default Org Chart Layout',
    PropertyPane_Layout_Drill: 'Drill-Down',
    PropertyPane_Layout_Vertical: 'Top Down',
    PropertyPane_Layout_Horizontal: 'Left to Right',

    // ── Property pane: Data Source ──
    PropertyPane_DataSource_Label: 'Where to load user & org data from',
    PropertyPane_DataSource_Auto: 'Auto — Graph API, fall back to SharePoint Search',
    PropertyPane_DataSource_Graph: 'Graph API — live Azure AD data (no indexing delay)',
    PropertyPane_DataSource_Search: 'SharePoint Search — legacy behavior',
    PropertyPane_DataSource_Note: 'Graph API is recommended. It reads directly from Azure Active Directory so new users and manager changes appear immediately. Requires Microsoft Graph permissions to be approved in the SharePoint App Catalog.',

    // ── Property pane: Custom Attributes ──
    PropertyPane_CustomAttributes_Note: 'Custom attributes require Microsoft Graph (Data source: Graph or Auto). SharePoint Search has no generic way to read Entra ID attributes.',
    PropertyPane_CustomAttributes_Heading: 'Manage custom attributes',
    PropertyPane_CustomAttributes_Empty: 'No custom attributes configured.',
    PropertyPane_CustomAttributes_AddButton: '+ Add attribute',
    PropertyPane_CustomAttributes_MaxTooltip: 'Maximum of {max} custom attributes',
    PropertyPane_CustomAttributes_FieldNameLabel: 'Attribute name',
    PropertyPane_CustomAttributes_FieldPlaceholder: 'e.g. companyName',
    PropertyPane_CustomAttributes_FieldError: 'Use employeeId, companyName, city, ... or extensionAttribute1-15',
    PropertyPane_CustomAttributes_DisplayLabelLabel: 'Display label',
    PropertyPane_CustomAttributes_LabelPlaceholder: 'e.g. Cost Center',
    PropertyPane_CustomAttributes_RemoveTitle: 'Remove attribute',
    PropertyPane_CustomAttributes_RemoveAriaLabel: 'Remove attribute {ordinal}',
    PropertyPane_CustomAttributes_ShowInDirectory: 'Show in Directory',
    PropertyPane_CustomAttributes_ShowInOrgChart: 'Show in Org Chart',

    // ── Property pane: User Filters ──
    PropertyPane_ExcludedAccounts_Label: 'Exclude accounts',
    PropertyPane_ExcludedAccounts_Placeholder: 'conf-room, noreply, admin@, Service Account',
    PropertyPane_ExcludedAccounts_Description: 'Comma-separated words or patterns (case-insensitive). Any user whose display name, email, or UPN contains one of these will be hidden from all views.',
    PropertyPane_RestrictTenant_Label: 'Only show tenant users',
    PropertyPane_RestrictTenant_On: 'On — hides accounts with external email domains (e.g. gmail.com, hotmail.com)',
    PropertyPane_RestrictTenant_Off: 'Off — all users shown regardless of email domain',
    PropertyPane_HideGuest_Label: 'Hide Azure AD guest accounts',
    PropertyPane_HideGuest_On: 'On — guest accounts hidden',
    PropertyPane_HideGuest_Off: 'Off — guest accounts visible (shown with Guest badge)',
    PropertyPane_HideDisabled_Label: 'Hide disabled accounts',
    PropertyPane_HideDisabled_On: 'On — blocked sign-in accounts hidden',
    PropertyPane_HideDisabled_Off: 'Off — disabled accounts visible (shown with Disabled badge)',
    PropertyPane_HideDisabled_Note: 'Note: guest and disabled account detection requires the Graph API data source. SharePoint Search does not return this information, so these two filters (and the Guest/Disabled badges) have no effect when data comes from Search.',
    PropertyPane_HideNoJobTitle_Label: 'Hide accounts without a job title',
    PropertyPane_HideNoJobTitle_On: 'On — accounts with no job title hidden',
    PropertyPane_HideNoJobTitle_Off: 'Off — all accounts shown regardless of job title',
    PropertyPane_HideNoDept_Label: 'Hide accounts without a department',
    PropertyPane_HideNoDept_On: 'On — accounts with no department hidden',
    PropertyPane_HideNoDept_Off: 'Off — all accounts shown regardless of department',

    // ── Property pane: Org Chart ──
    PropertyPane_TopLevelUser_Label: 'Top-Level User (UPN or Email)',
    PropertyPane_TopLevelUser_Placeholder: 'ceo@yourcompany.com',
    PropertyPane_TopLevelUser_Description: 'The person shown at the root of the org chart',
    PropertyPane_LevelsBelow_Label: 'Levels to load below root',
    PropertyPane_DottedLine_Label: 'Dotted-line manager attribute',
    PropertyPane_DottedLine_Placeholder: 'extensionAttribute10',
    PropertyPane_DottedLine_Description: 'Optional. Name of the Azure AD on-premises extension attribute (extensionAttribute1-15) that stores a secondary "dotted line" manager\'s email or UPN. Dotted-line relationships appear on profile cards. Requires the Graph API data source.',
    PropertyPane_DefaultZoom_Label: 'Default Org Chart Zoom',
    PropertyPane_Zoom_Auto: 'Default (Auto-fit)',
    PropertyPane_Zoom_50: '50%',
    PropertyPane_Zoom_75: '75%',
    PropertyPane_Zoom_100: '100%',
    PropertyPane_Zoom_125: '125%',
    PropertyPane_Zoom_150: '150%',

    // ── Property pane: Org Chart Features ──
    PropertyPane_FeatureToggles_Note: 'Show or hide toolbar buttons in the org chart view.',
    PropertyPane_FindMe_Label: 'Find Me button',
    PropertyPane_LayoutToggle_Label: 'Layout toggle (drill / vertical / horizontal)',
    PropertyPane_Stats_Label: 'Org stats bar',
    PropertyPane_DeptFilter_Label: 'Department filter',
    PropertyPane_UserFilter_Label: 'User type filter (members / guests)',
    PropertyPane_Visible: 'Visible',
    PropertyPane_Hidden: 'Hidden',

    // ── Property pane: Directory ──
    PropertyPane_PageSize_Label: 'Max employees per page',
    PropertyPane_PageSize_AriaLabel: 'Max employees per page (10 to 200)',
    PropertyPane_PageSize_Note: 'Card size, visible fields, and other display preferences are set per-user via the Settings gear in the app.',

    // ── Property pane: Demo ──
    PropertyPane_UseDemoData_Label: 'Use Demo Data',
    PropertyPane_UseDemoData_On: 'On — showing sample employees',
    PropertyPane_UseDemoData_Off: 'Off — live Microsoft 365 data',

    // ── Presence status labels ──
    Presence_Available: 'Available',
    Presence_Busy: 'Busy',
    Presence_DoNotDisturb: 'Do Not Disturb',
    Presence_BeRightBack: 'Be Right Back',
    Presence_Away: 'Away',
    Presence_Offline: 'Offline',

    // ── Header / top bar ──
    Header_DirectoryLabel: 'Employee Directory',
    Header_OrgChartLabel: 'Org Chart',
    Header_SwitchToView: 'Switch to {view}',
    Header_CompanyLogoAlt: 'Company logo',
    Header_RefreshingAria: 'Refreshing data',
    Header_RefreshAria: 'Refresh data',
    Header_RefreshTitle: 'Refresh data (last updated {when})',
    Header_NotLoadedYet: 'not loaded yet',
    Header_JustNow: 'just now',
    Header_MinutesAgo: '{mins} min ago',
    Header_HoursAgo: '{hours} hr ago',
    Header_PreferencesTitle: 'Preferences',
    Header_PreferencesAria: 'Open preferences panel',

    // ── Employee Directory ──
    Directory_LoadingLabel: 'Loading employees...',
    Directory_LoadFailedFallback: 'Ensure the web part has User.Read.All permission.',
    Directory_LoadFailedPrefix: 'Failed to load employees. {detail}',
    Directory_AllDepartments: 'All Departments',
    Directory_AllOffices: 'All Offices',
    Directory_StatusDisabled: 'Disabled',
    Directory_StatusGuest: 'Guest',
    Directory_PresenceStatus: 'Status: {status}',
    Directory_ChatInTeams: 'Chat in Teams',
    Directory_ChatWithInTeams: 'Chat with {name} in Teams',
    Directory_ManagesCount: 'Manages {direct}',
    Directory_ManagesCountWithTotal: 'Manages {direct} ({total} total)',
    Directory_ReportsCountWithTotal: '{direct} ({total} total)',
    Directory_ColumnName: 'Name',
    Directory_ColumnJobTitle: 'Job Title',
    Directory_ColumnDepartment: 'Department',
    Directory_ColumnOffice: 'Office',
    Directory_ColumnEmail: 'Email',
    Directory_ColumnPhone: 'Phone',
    Directory_ColumnReports: 'Reports',
    Directory_ColumnChat: 'Chat',
    Directory_PrevPage: 'Prev',
    Directory_NextPage: 'Next',
    Directory_PreviousPageAria: 'Previous page',
    Directory_NextPageAria: 'Next page',
    Directory_SearchPlaceholder: 'Search by name, title, email, or department...',
    Directory_SearchAria: 'Search people',
    Directory_FilterByDepartmentAria: 'Filter by department',
    Directory_FilterByOfficeAria: 'Filter by office',
    Directory_ClearSearchTitle: 'Clear search and all filters',
    Directory_ClearButton: 'Clear',
    Directory_ClearFiltersButton: 'Clear filters',
    Directory_ExportCsvTitle: 'Export all filtered results to a CSV file (opens in Excel)',
    Directory_ExportCsvButton: 'Export CSV',
    Directory_ViewModeAria: 'View mode',
    Directory_CardViewTitle: 'Card view',
    Directory_ListViewTitle: 'List view',
    Directory_AlphabetFilterAria: 'Alphabet filter',
    Directory_ShowAllTitle: 'Show all',
    Directory_OtherLettersTitle: 'Filter by names starting with a number or other character',
    Directory_FilterByLetterTitle: 'Filter by {letter}',
    Directory_ResultCountSingular: 'person',
    Directory_ResultCountPlural: 'people',
    Directory_PageOf: ' · page {page} of {totalPages}',
    Directory_FilterActiveSingular: '{count} filter active',
    Directory_FilterActivePlural: '{count} filters active',
    Directory_NoResults: 'No people found',
    Directory_PaginationAria: 'Pagination',

    // ── Org chart toolbar / shared chart chrome ──
    Chart_Layout_Drill: 'Drill-Down',
    Chart_Layout_Vertical: 'Top Down',
    Chart_Layout_Horizontal: 'Left to Right',
    Chart_SearchPlaceholder: 'Search people...',
    Chart_SearchAria: 'Search people',
    Chart_MatchSingular: 'match in tree',
    Chart_MatchPlural: 'matches in tree',
    Chart_ResultsListAria: 'People',
    Chart_ExpandAll: 'Expand All',
    Chart_CollapseAll: 'Collapse All',
    Chart_Expanding: 'Expanding…',
    Chart_Loading: 'Loading…',
    Chart_FindMeTitle: 'Find me in the org chart',
    Chart_ViewLayoutButton: 'View',
    Chart_ViewLayoutTitle: 'Switch view layout',
    Chart_ViewLayoutPanelTitle: 'View layout',
    Chart_StatsSummaryTitle: 'Org stats summary',
    Chart_FilterByDepartmentTitle: 'Filter by department',
    Chart_FilterByDepartmentWithCountAria: 'Filter by department ({count} selected)',
    Chart_FilterByDepartmentPanelTitle: 'Filter by department',
    Chart_ClearAllFilters: 'Clear all filters',
    Chart_FilterUserTypesTitle: 'Filter user types',
    Chart_DownloadPdfTitle: 'Download as PDF',
    Chart_DownloadCsvTitle: 'Download as CSV spreadsheet',
    Chart_ResetRootTitle: 'Reset to default root',
    Chart_ViewFromPersonPlaceholder: 'View from person…',
    Chart_ViewFromPersonAria: 'View the org chart from a person',
    Chart_ZoomOutTitle: 'Zoom out',
    Chart_ZoomInTitle: 'Zoom in',
    Chart_ZoomResetTitle: 'Reset zoom',
    Chart_ShowInChartAria: 'Show in chart',
    Chart_ShowInChartTitle: 'Show in chart',
    Chart_FilterMembers: 'Regular members',
    Chart_FilterGuests: 'Guest users',
    Chart_FilterDisabled: 'Disabled accounts',
    Chart_SetupTitle: 'Set Up the Org Chart',
    Chart_SetupSubtitle: 'Enter the top-level person’s email or UPN to get started.',
    Chart_SetupPlaceholder: 'ceo@company.com',
    Chart_SetupInputAria: 'Top-level person’s email or UPN',
    Chart_SetupLoadButton: 'Load',
    Chart_SetupHint: 'You can also set this permanently in the web part settings (admin).',
    Chart_BuildingLabel: 'Building org chart...',
    Chart_RetryButton: 'Retry',
    Chart_NotFoundFromSetup: 'User "{identifier}" not found.',
    Chart_NotFoundWithSettings: 'User "{identifier}" not found. Check the UPN or email in Settings.',
    Chart_LoadFailedGeneric: 'Failed to load org chart.{detail}',
    Chart_LoadFailedPermissions: ' Check permissions.',
    Chart_LoadFailedForPerson: 'Failed to load org chart for this person.',
    Chart_FindMeNotFound: 'Your account was not found in this org.',
    Chart_StatPeople: 'People',
    Chart_StatMembers: 'Members',
    Chart_StatGuests: 'Guests',
    Chart_StatDepts: 'Depts',
    Chart_ReportingLineAria: 'Reporting line',
    Chart_BackToFullOrgTitle: 'Back to full org chart',
    Chart_FullOrgLabel: 'Full org',
    Chart_FocusOnPerson: 'Focus on {name}',
    Chart_OrgChartAria: 'Org chart',
    Chart_ExportNote_DrillLevel: 'Current drill-down level (one level of direct reports)',
    Chart_ExportNote_PartialLevels: 'Includes loaded levels only — use Expand All before exporting to include deeper levels',
    Chart_AllowPopupsForPdf: 'Please allow pop-ups to export PDF.',

    // ── Person card ──
    PersonCard_ProfileAria: 'Profile: {name}',
    PersonCard_CloseTitle: 'Close',
    PersonCard_CloseAria: 'Close profile',
    PersonCard_StatusDisabled: 'Disabled',
    PersonCard_StatusGuest: 'Guest',
    PersonCard_DirectReportSingular: '{count} direct report',
    PersonCard_DirectReportPlural: '{count} direct reports',
    PersonCard_TotalSuffix: ' · {total} total',
    PersonCard_CopyEmailTitle: 'Copy email address',
    PersonCard_EmailCopiedAria: 'Email address copied',
    PersonCard_ReportsTo: 'Reports to',
    PersonCard_FocusOnPerson: 'Focus on {name}',
    PersonCard_FocusOrgChartOnPerson: 'Focus org chart on {name}',
    PersonCard_DottedLine: 'Dotted line',
    PersonCard_DottedLineManager: 'Dotted-line manager: {name}',
    PersonCard_DottedLineReport: 'Dotted-line report: {name}',
    PersonCard_ChatButton: 'Chat',
    PersonCard_EmailButton: 'Email',
    PersonCard_FocusButton: 'Focus',
    PersonCard_FocusTitle: 'Focus org chart on this person',

    // ── Org node card ──
    OrgNode_ViewProfile: 'View {name}’s profile',
    OrgNode_FocusOrgChartOn: 'Focus org chart on {name}',
    OrgNode_Collapse: 'Collapse',
    OrgNode_Expand: 'Expand',
    OrgNode_DirectReportsSuffix: '{name}’s direct reports',
    OrgNode_StatusDisabled: 'Disabled',
    OrgNode_StatusGuest: 'Guest',
    OrgNode_TotalReportsAcrossLevels: '{count} people across all levels below {name}',

    // ── Drill view ──
    Drill_ReportingLineAria: 'Reporting line',
    Drill_BackToTopTitle: 'Back to top',
    Drill_BackToTopAria: 'Back to top of the org chart',
    Drill_GoBackTo: 'Go back to {name}',
    Drill_ViewProfileTitle: 'View profile',
    Drill_ViewProfileAria: 'View {name}’s profile',
    Drill_ProfileButton: 'Profile',
    Drill_LoadingLabel: 'Loading...',
    Drill_DirectReports: 'Direct Reports',
    Drill_DirectReportsOfAria: 'Direct reports of {name}',
    Drill_DirectReportsAria: 'Direct reports',
    Drill_ViewPersonProfile: 'View {name}’s profile',
    Drill_ShowPersonReports: 'Show {name}’s direct reports',
    Drill_NoDirectReports: 'No direct reports',

    // ── Settings panel ──
    Settings_AlphabetFirstName: 'First Name',
    Settings_AlphabetLastName: 'Last Name',
    Settings_CardSizeSmall: 'Small — compact, more cards visible',
    Settings_CardSizeMedium: 'Medium — balanced',
    Settings_CardSizeLarge: 'Large — spacious, fewer cards',
    Settings_HeaderText: 'Preferences',
    Settings_SaveButton: 'Save',
    Settings_CancelButton: 'Cancel',
    Settings_DiscardButton: 'Discard Changes',
    Settings_SectionDirectory: 'Directory',
    Settings_AlphabetFilterByLabel: 'Alphabet Filter By',
    Settings_CardSizeLabel: 'Card Size',
    Settings_FontSizeLabel: 'Font Size',
    Settings_SectionCardsAndFields: 'Cards & Fields',
    Settings_ShowOnCardsLabel: 'Show on employee cards:',
    Settings_EmailAddressLabel: 'Email address',
    Settings_PhoneNumberLabel: 'Phone number',
    Settings_DepartmentLabel: 'Department',
    Settings_OfficeLocationLabel: 'Office location',
    Settings_SectionOrgChart: 'Org Chart',
    Settings_ManagerLevelsLabel: 'Manager levels shown when focusing a person: {levels}',
    Settings_CompactCardsLabel: 'Compact cards',
    Settings_CompactCardsOn: 'On — smaller cards, more visible at once',
    Settings_CompactCardsOff: 'Off — standard size',
    Settings_Hint: 'These preferences are saved to your browser and apply only to you. Chart theme, default view, and layout are configured by your SharePoint admin.',
    Settings_SectionDemoData: 'Demo Data',
    Settings_DatasetSizeLabel: 'Dataset size',
    Settings_PeopleCountSuffix: '{count} people',

    // ── Export (CSV / PDF) ──
    Export_ColumnName: 'Name',
    Export_ColumnJobTitle: 'Job Title',
    Export_ColumnDepartment: 'Department',
    Export_ColumnOffice: 'Office',
    Export_ColumnEmail: 'Email',
    Export_ColumnPhone: 'Phone',
    Export_ColumnManager: 'Manager',
    Export_ColumnLevel: 'Level',
    Export_PdfDocumentTitle: 'Org Chart',
    Export_PdfHeading: 'Organization Chart',
    Export_PdfRootLabel: 'Root: {name}',
  };
});
