define([], function () {
  return {
    // ── Property pane: pane header / groups ──
    PropertyPane_HeaderDescription: 'Configuración de Smart Org Chart',
    PropertyPane_Group_General: 'General',
    PropertyPane_Group_Branding: 'Marca',
    PropertyPane_Group_VisualStyle: 'Estilo visual',
    PropertyPane_Group_DataSource: 'Origen de datos',
    PropertyPane_Group_CustomAttributes: 'Atributos personalizados',
    PropertyPane_Group_UserFilters: 'Filtros de usuario',
    PropertyPane_Group_OrgChart: 'Organigrama',
    PropertyPane_Group_OrgChartFeatures: 'Funciones del organigrama',
    PropertyPane_Group_Directory: 'Directorio',
    PropertyPane_Group_Demo: 'Demostración',

    // ── Property pane: General ──
    PropertyPane_DefaultView_Label: 'Vista predeterminada',

    // ── Property pane: Branding ──
    PropertyPane_AppTitle_Label: 'Título de la aplicación',
    PropertyPane_AppTitle_Placeholder: 'Organigrama de Contoso',
    PropertyPane_AppTitle_Description: 'Se muestra en la barra de encabezado junto al nombre de la vista',
    PropertyPane_LogoUrl_Label: 'URL del logotipo',
    PropertyPane_LogoUrl_Placeholder: 'https://contoso.sharepoint.com/sites/yoursite/SiteAssets/logo.png',
    PropertyPane_LogoUrl_Description: 'Dirección URL completa de una imagen PNG, SVG o JPG. Sugerencia: abra el archivo de imagen en el explorador y copie la URL de la barra de direcciones. Las URL de uso compartido de "Copiar vínculo" no funcionarán.',
    PropertyPane_DirectoryLabel_Label: 'Etiqueta de la vista Directorio de empleados',
    PropertyPane_OrgChartLabel_Label: 'Etiqueta de la vista Organigrama',
    PropertyPane_ViewLabel_Description: 'Déjelo en blanco para usar el nombre predeterminado, o escriba "[blank]" para ocultar la etiqueta por completo.',

    // ── Property pane: Visual Style ──
    PropertyPane_ChartTheme_Label: 'Tema del organigrama',
    PropertyPane_Theme_Modern: 'Moderno: colores de departamento sobre blanco',
    PropertyPane_Theme_Minimal: 'Minimalista: plano y de bajo contraste',
    PropertyPane_Theme_Corporate: 'Corporativo: azul unificado',
    PropertyPane_Theme_Dark: 'Oscuro: fondo azul marino oscuro',
    PropertyPane_Theme_Custom: 'Personalizado: elija su propio color',
    PropertyPane_AccentColor_Label: 'Color de énfasis personalizado',
    PropertyPane_AccentColor_PickerAriaLabel: 'Selector de color de énfasis',
    PropertyPane_AccentColor_HexLabel: 'Hexadecimal',
    PropertyPane_AccentColor_HexAriaLabel: 'Valor hexadecimal del color de énfasis',
    PropertyPane_AccentColor_RgbLabel: 'RGB',
    PropertyPane_AccentColor_ChannelAriaLabel: 'Canal {name} (de 0 a 255)',
    PropertyPane_AccentColor_ContrastWithWhite: 'Contraste con blanco: {ratio}:1 ({passes})',
    PropertyPane_AccentColor_PassesAA: 'cumple AA',
    PropertyPane_AccentColor_LargeTextOnly: 'solo texto grande',
    PropertyPane_AccentColor_LowContrast: 'contraste bajo',
    PropertyPane_AccentColor_DarkTextNote: 'El texto sobre este color usará tipografía oscura para mejorar la legibilidad.',
    PropertyPane_AccentColor_DarkerShadeNote: 'Los títulos y los vínculos usarán un tono más oscuro ({hex}) para mejorar la legibilidad.',
    PropertyPane_AccentColor_InvalidHex: '"{typed}" no es un color hexadecimal válido. Use un valor como #0078d4 o #07d.',
    PropertyPane_DefaultFontSize_Label: 'Tamaño de fuente predeterminado',
    PropertyPane_FontSize_75: '75 %: muy pequeño',
    PropertyPane_FontSize_85: '85 %: pequeño',
    PropertyPane_FontSize_100: '100 %: normal',
    PropertyPane_FontSize_115: '115 %: grande',
    PropertyPane_FontSize_130: '130 %: muy grande',
    PropertyPane_FontSize_150: '150 %: XXL',
    PropertyPane_FontSize_175: '175 %: XXXL',
    PropertyPane_DefaultLayout_Label: 'Diseño predeterminado del organigrama',
    PropertyPane_Layout_Drill: 'Desglose',
    PropertyPane_Layout_Vertical: 'De arriba abajo',
    PropertyPane_Layout_Horizontal: 'De izquierda a derecha',

    // ── Property pane: Data Source ──
    PropertyPane_DataSource_Label: 'De dónde cargar los datos de usuarios y de la organización',
    PropertyPane_DataSource_Auto: 'Automático: API de Graph, con reserva a Búsqueda de SharePoint',
    PropertyPane_DataSource_Graph: 'API de Graph: datos en vivo de Azure AD (sin retraso de indexación)',
    PropertyPane_DataSource_Search: 'Búsqueda de SharePoint: comportamiento heredado',
    PropertyPane_DataSource_Note: 'Se recomienda la API de Graph. Lee directamente desde Azure Active Directory, por lo que los usuarios nuevos y los cambios de responsable aparecen de inmediato. Requiere que los permisos de Microsoft Graph estén aprobados en el catálogo de aplicaciones de SharePoint.',

    // ── Property pane: Custom Attributes ──
    PropertyPane_CustomAttributes_Note: 'Los atributos personalizados requieren Microsoft Graph (origen de datos: Graph o Automático). Búsqueda de SharePoint no dispone de una forma genérica de leer atributos de Entra ID.',
    PropertyPane_CustomAttributes_Heading: 'Administrar atributos personalizados',
    PropertyPane_CustomAttributes_Empty: 'No hay atributos personalizados configurados.',
    PropertyPane_CustomAttributes_AddButton: '+ Agregar atributo',
    PropertyPane_CustomAttributes_MaxTooltip: 'Máximo de {max} atributos personalizados',
    PropertyPane_CustomAttributes_FieldNameLabel: 'Nombre del atributo',
    PropertyPane_CustomAttributes_FieldPlaceholder: 'por ejemplo, companyName',
    PropertyPane_CustomAttributes_FieldError: 'Use employeeId, companyName, city, ... o extensionAttribute1-15',
    PropertyPane_CustomAttributes_DisplayLabelLabel: 'Etiqueta para mostrar',
    PropertyPane_CustomAttributes_LabelPlaceholder: 'por ejemplo, Centro de coste',
    PropertyPane_CustomAttributes_RemoveTitle: 'Quitar atributo',
    PropertyPane_CustomAttributes_RemoveAriaLabel: 'Quitar atributo {ordinal}',
    PropertyPane_CustomAttributes_ShowInDirectory: 'Mostrar en el directorio',
    PropertyPane_CustomAttributes_ShowInOrgChart: 'Mostrar en el organigrama',

    // ── Property pane: User Filters ──
    PropertyPane_ExcludedAccounts_Label: 'Excluir cuentas',
    PropertyPane_ExcludedAccounts_Placeholder: 'conf-room, noreply, admin@, Cuenta de servicio',
    PropertyPane_ExcludedAccounts_Description: 'Palabras o patrones separados por comas (sin distinción entre mayúsculas y minúsculas). Cualquier usuario cuyo nombre para mostrar, correo electrónico o UPN contenga uno de estos términos se ocultará en todas las vistas.',
    PropertyPane_RestrictTenant_Label: 'Mostrar solo usuarios del inquilino',
    PropertyPane_RestrictTenant_On: 'Activado: oculta las cuentas con dominios de correo externos (por ejemplo, gmail.com, hotmail.com)',
    PropertyPane_RestrictTenant_Off: 'Desactivado: se muestran todos los usuarios, independientemente del dominio de correo',
    PropertyPane_HideGuest_Label: 'Ocultar cuentas de invitado de Azure AD',
    PropertyPane_HideGuest_On: 'Activado: las cuentas de invitado están ocultas',
    PropertyPane_HideGuest_Off: 'Desactivado: las cuentas de invitado son visibles (se muestran con la insignia Invitado)',
    PropertyPane_HideDisabled_Label: 'Ocultar cuentas deshabilitadas',
    PropertyPane_HideDisabled_On: 'Activado: las cuentas con el inicio de sesión bloqueado están ocultas',
    PropertyPane_HideDisabled_Off: 'Desactivado: las cuentas deshabilitadas son visibles (se muestran con la insignia Deshabilitada)',
    PropertyPane_HideDisabled_Note: 'Nota: la detección de cuentas de invitado y deshabilitadas requiere el origen de datos de la API de Graph. Búsqueda de SharePoint no devuelve esta información, por lo que estos dos filtros (y las insignias Invitado/Deshabilitada) no tienen efecto cuando los datos provienen de Búsqueda.',
    PropertyPane_HideNoJobTitle_Label: 'Ocultar cuentas sin puesto de trabajo',
    PropertyPane_HideNoJobTitle_On: 'Activado: las cuentas sin puesto de trabajo están ocultas',
    PropertyPane_HideNoJobTitle_Off: 'Desactivado: se muestran todas las cuentas, independientemente del puesto de trabajo',
    PropertyPane_HideNoDept_Label: 'Ocultar cuentas sin departamento',
    PropertyPane_HideNoDept_On: 'Activado: las cuentas sin departamento están ocultas',
    PropertyPane_HideNoDept_Off: 'Desactivado: se muestran todas las cuentas, independientemente del departamento',

    // ── Property pane: Org Chart ──
    PropertyPane_TopLevelUser_Label: 'Usuario de nivel superior (UPN o correo electrónico)',
    PropertyPane_TopLevelUser_Placeholder: 'ceo@yourcompany.com',
    PropertyPane_TopLevelUser_Description: 'La persona que se muestra en la raíz del organigrama',
    PropertyPane_LevelsBelow_Label: 'Niveles que cargar debajo de la raíz',
    PropertyPane_DottedLine_Label: 'Atributo de responsable de línea punteada',
    PropertyPane_DottedLine_Placeholder: 'extensionAttribute10',
    PropertyPane_DottedLine_Description: 'Opcional. Nombre del atributo de extensión local de Azure AD (extensionAttribute1-15) que almacena el correo electrónico o el UPN de un responsable secundario de "línea punteada". Las relaciones de línea punteada aparecen en las tarjetas de perfil. Requiere el origen de datos de la API de Graph.',
    PropertyPane_DefaultZoom_Label: 'Zoom predeterminado del organigrama',
    PropertyPane_Zoom_Auto: 'Predeterminado (ajuste automático)',
    PropertyPane_Zoom_50: '50 %',
    PropertyPane_Zoom_75: '75 %',
    PropertyPane_Zoom_100: '100 %',
    PropertyPane_Zoom_125: '125 %',
    PropertyPane_Zoom_150: '150 %',

    // ── Property pane: Org Chart Features ──
    PropertyPane_FeatureToggles_Note: 'Mostrar u ocultar los botones de la barra de herramientas en la vista de organigrama.',
    PropertyPane_FindMe_Label: 'Botón Encontrarme',
    PropertyPane_LayoutToggle_Label: 'Alternancia de diseño (desglose/vertical/horizontal)',
    PropertyPane_Stats_Label: 'Barra de estadísticas de la organización',
    PropertyPane_DeptFilter_Label: 'Filtro de departamento',
    PropertyPane_UserFilter_Label: 'Filtro de tipo de usuario (miembros/invitados)',
    PropertyPane_Visible: 'Visible',
    PropertyPane_Hidden: 'Oculto',

    // ── Property pane: Directory ──
    PropertyPane_PageSize_Label: 'Máximo de empleados por página',
    PropertyPane_PageSize_AriaLabel: 'Máximo de empleados por página (de 10 a 200)',
    PropertyPane_PageSize_Note: 'El tamaño de las tarjetas, los campos visibles y otras preferencias de visualización se configuran por usuario mediante el icono de engranaje de Configuración en la aplicación.',

    // ── Property pane: Demo ──
    PropertyPane_UseDemoData_Label: 'Usar datos de demostración',
    PropertyPane_UseDemoData_On: 'Activado: se muestran empleados de ejemplo',
    PropertyPane_UseDemoData_Off: 'Desactivado: datos en vivo de Microsoft 365',

    // ── Presence status labels ──
    Presence_Available: 'Disponible',
    Presence_Busy: 'Ocupado',
    Presence_DoNotDisturb: 'No molestar',
    Presence_BeRightBack: 'Vuelvo enseguida',
    Presence_Away: 'Ausente',
    Presence_Offline: 'Sin conexión',

    // ── Header / top bar ──
    Header_DirectoryLabel: 'Directorio de empleados',
    Header_OrgChartLabel: 'Organigrama',
    Header_SwitchToView: 'Cambiar a {view}',
    Header_CompanyLogoAlt: 'Logotipo de la empresa',
    Header_RefreshingAria: 'Actualizando datos',
    Header_RefreshAria: 'Actualizar datos',
    Header_RefreshTitle: 'Actualizar datos (última actualización: {when})',
    Header_NotLoadedYet: 'aún no se han cargado',
    Header_JustNow: 'hace un momento',
    Header_MinutesAgo: 'hace {mins} min',
    Header_HoursAgo: 'hace {hours} h',
    Header_PreferencesTitle: 'Preferencias',
    Header_PreferencesAria: 'Abrir el panel de preferencias',

    // ── Employee Directory ──
    Directory_LoadingLabel: 'Cargando empleados…',
    Directory_LoadFailedFallback: 'Asegúrese de que la web part tenga el permiso User.Read.All.',
    Directory_LoadFailedPrefix: 'No se pudieron cargar los empleados. {detail}',
    Directory_AllDepartments: 'Todos los departamentos',
    Directory_AllOffices: 'Todas las oficinas',
    Directory_StatusDisabled: 'Deshabilitada',
    Directory_StatusGuest: 'Invitado',
    Directory_PresenceStatus: 'Estado: {status}',
    Directory_ChatInTeams: 'Chatear en Teams',
    Directory_ChatWithInTeams: 'Chatear con {name} en Teams',
    Directory_ManagesCount: 'Gestiona a {direct}',
    Directory_ManagesCountWithTotal: 'Gestiona a {direct} ({total} en total)',
    Directory_ReportsCountWithTotal: '{direct} ({total} en total)',
    Directory_ColumnName: 'Nombre',
    Directory_ColumnJobTitle: 'Puesto',
    Directory_ColumnDepartment: 'Departamento',
    Directory_ColumnOffice: 'Oficina',
    Directory_ColumnEmail: 'Correo electrónico',
    Directory_ColumnPhone: 'Teléfono',
    Directory_ColumnReports: 'Colaboradores',
    Directory_ColumnChat: 'Chat',
    Directory_PrevPage: 'Anterior',
    Directory_NextPage: 'Siguiente',
    Directory_PreviousPageAria: 'Página anterior',
    Directory_NextPageAria: 'Página siguiente',
    Directory_SearchPlaceholder: 'Buscar por nombre, puesto, correo electrónico o departamento…',
    Directory_SearchAria: 'Buscar personas',
    Directory_FilterByDepartmentAria: 'Filtrar por departamento',
    Directory_FilterByOfficeAria: 'Filtrar por oficina',
    Directory_ClearSearchTitle: 'Borrar la búsqueda y todos los filtros',
    Directory_ClearButton: 'Borrar',
    Directory_ClearFiltersButton: 'Borrar filtros',
    Directory_ExportCsvTitle: 'Exportar todos los resultados filtrados a un archivo CSV (se abre en Excel)',
    Directory_ExportCsvButton: 'Exportar CSV',
    Directory_ViewModeAria: 'Modo de vista',
    Directory_CardViewTitle: 'Vista de tarjetas',
    Directory_ListViewTitle: 'Vista de lista',
    Directory_AlphabetFilterAria: 'Filtro alfabético',
    Directory_ShowAllTitle: 'Mostrar todo',
    Directory_OtherLettersTitle: 'Filtrar por nombres que empiecen por un número u otro carácter',
    Directory_FilterByLetterTitle: 'Filtrar por {letter}',
    Directory_ResultCountSingular: 'persona',
    Directory_ResultCountPlural: 'personas',
    Directory_PageOf: ' · página {page} de {totalPages}',
    Directory_FilterActiveSingular: '{count} filtro activo',
    Directory_FilterActivePlural: '{count} filtros activos',
    Directory_NoResults: 'No se encontraron personas',
    Directory_PaginationAria: 'Paginación',

    // ── Org chart toolbar / shared chart chrome ──
    Chart_Layout_Drill: 'Desglose',
    Chart_Layout_Vertical: 'De arriba abajo',
    Chart_Layout_Horizontal: 'De izquierda a derecha',
    Chart_SearchPlaceholder: 'Buscar personas…',
    Chart_SearchAria: 'Buscar personas',
    Chart_MatchSingular: 'coincidencia en el árbol',
    Chart_MatchPlural: 'coincidencias en el árbol',
    Chart_ResultsListAria: 'Personas',
    Chart_ExpandAll: 'Expandir todo',
    Chart_CollapseAll: 'Contraer todo',
    Chart_Expanding: 'Expandiendo…',
    Chart_Loading: 'Cargando…',
    Chart_FindMeTitle: 'Encontrarme en el organigrama',
    Chart_ViewLayoutButton: 'Vista',
    Chart_ViewLayoutTitle: 'Cambiar el diseño de la vista',
    Chart_ViewLayoutPanelTitle: 'Diseño de la vista',
    Chart_StatsSummaryTitle: 'Resumen de estadísticas de la organización',
    Chart_FilterByDepartmentTitle: 'Filtrar por departamento',
    Chart_FilterByDepartmentWithCountAria: 'Filtrar por departamento ({count} seleccionados)',
    Chart_FilterByDepartmentPanelTitle: 'Filtrar por departamento',
    Chart_ClearAllFilters: 'Borrar todos los filtros',
    Chart_FilterUserTypesTitle: 'Filtrar tipos de usuario',
    Chart_DownloadPdfTitle: 'Descargar como PDF',
    Chart_DownloadCsvTitle: 'Descargar como hoja de cálculo CSV',
    Chart_ResetRootTitle: 'Restablecer a la raíz predeterminada',
    Chart_ViewFromPersonPlaceholder: 'Ver desde una persona…',
    Chart_ViewFromPersonAria: 'Ver el organigrama desde una persona',
    Chart_ZoomOutTitle: 'Alejar',
    Chart_ZoomInTitle: 'Acercar',
    Chart_ZoomResetTitle: 'Restablecer el zoom',
    Chart_ShowInChartAria: 'Mostrar en el organigrama',
    Chart_ShowInChartTitle: 'Mostrar en el organigrama',
    Chart_FilterMembers: 'Miembros habituales',
    Chart_FilterGuests: 'Usuarios invitados',
    Chart_FilterDisabled: 'Cuentas deshabilitadas',
    Chart_SetupTitle: 'Configurar el organigrama',
    Chart_SetupSubtitle: 'Escriba el correo electrónico o el UPN de la persona de nivel superior para empezar.',
    Chart_SetupPlaceholder: 'ceo@company.com',
    Chart_SetupInputAria: 'Correo electrónico o UPN de la persona de nivel superior',
    Chart_SetupLoadButton: 'Cargar',
    Chart_SetupHint: 'También puede configurar esto de forma permanente en la configuración de la web part (administrador).',
    Chart_BuildingLabel: 'Creando el organigrama…',
    Chart_RetryButton: 'Reintentar',
    Chart_NotFoundFromSetup: 'No se encontró el usuario "{identifier}".',
    Chart_NotFoundWithSettings: 'No se encontró el usuario "{identifier}". Compruebe el UPN o el correo electrónico en Configuración.',
    Chart_LoadFailedGeneric: 'No se pudo cargar el organigrama.{detail}',
    Chart_LoadFailedPermissions: ' Compruebe los permisos.',
    Chart_LoadFailedForPerson: 'No se pudo cargar el organigrama de esta persona.',
    Chart_FindMeNotFound: 'No se encontró su cuenta en esta organización.',
    Chart_StatPeople: 'Personas',
    Chart_StatMembers: 'Miembros',
    Chart_StatGuests: 'Invitados',
    Chart_StatDepts: 'Deptos.',
    Chart_ReportingLineAria: 'Línea jerárquica',
    Chart_BackToFullOrgTitle: 'Volver al organigrama completo',
    Chart_FullOrgLabel: 'Organización completa',
    Chart_FocusOnPerson: 'Centrar en {name}',
    Chart_OrgChartAria: 'Organigrama',
    Chart_ExportNote_DrillLevel: 'Nivel de desglose actual (un nivel de colaboradores directos)',
    Chart_ExportNote_PartialLevels: 'Incluye solo los niveles cargados; use Expandir todo antes de exportar para incluir niveles más profundos',
    Chart_AllowPopupsForPdf: 'Permita las ventanas emergentes para exportar a PDF.',

    // ── Person card ──
    PersonCard_ProfileAria: 'Perfil: {name}',
    PersonCard_CloseTitle: 'Cerrar',
    PersonCard_CloseAria: 'Cerrar el perfil',
    PersonCard_StatusDisabled: 'Deshabilitada',
    PersonCard_StatusGuest: 'Invitado',
    PersonCard_DirectReportSingular: '{count} colaborador directo',
    PersonCard_DirectReportPlural: '{count} colaboradores directos',
    PersonCard_TotalSuffix: ' · {total} en total',
    PersonCard_CopyEmailTitle: 'Copiar dirección de correo electrónico',
    PersonCard_EmailCopiedAria: 'Dirección de correo electrónico copiada',
    PersonCard_ReportsTo: 'Reporta a',
    PersonCard_FocusOnPerson: 'Centrar en {name}',
    PersonCard_FocusOrgChartOnPerson: 'Centrar el organigrama en {name}',
    PersonCard_DottedLine: 'Línea punteada',
    PersonCard_DottedLineManager: 'Responsable de línea punteada: {name}',
    PersonCard_DottedLineReport: 'Colaborador de línea punteada: {name}',
    PersonCard_ChatButton: 'Chat',
    PersonCard_EmailButton: 'Correo',
    PersonCard_FocusButton: 'Centrar',
    PersonCard_FocusTitle: 'Centrar el organigrama en esta persona',

    // ── Org node card ──
    OrgNode_ViewProfile: 'Ver el perfil de {name}',
    OrgNode_FocusOrgChartOn: 'Centrar el organigrama en {name}',
    OrgNode_Collapse: 'Contraer',
    OrgNode_Expand: 'Expandir',
    OrgNode_DirectReportsSuffix: 'Colaboradores directos de {name}',
    OrgNode_StatusDisabled: 'Deshabilitada',
    OrgNode_StatusGuest: 'Invitado',
    OrgNode_TotalReportsAcrossLevels: '{count} personas en todos los niveles debajo de {name}',

    // ── Drill view ──
    Drill_ReportingLineAria: 'Línea jerárquica',
    Drill_BackToTopTitle: 'Volver al inicio',
    Drill_BackToTopAria: 'Volver al inicio del organigrama',
    Drill_GoBackTo: 'Volver a {name}',
    Drill_ViewProfileTitle: 'Ver perfil',
    Drill_ViewProfileAria: 'Ver el perfil de {name}',
    Drill_ProfileButton: 'Perfil',
    Drill_LoadingLabel: 'Cargando…',
    Drill_DirectReports: 'Colaboradores directos',
    Drill_DirectReportsOfAria: 'Colaboradores directos de {name}',
    Drill_DirectReportsAria: 'Colaboradores directos',
    Drill_ViewPersonProfile: 'Ver el perfil de {name}',
    Drill_ShowPersonReports: 'Mostrar los colaboradores directos de {name}',
    Drill_NoDirectReports: 'Sin colaboradores directos',

    // ── Settings panel ──
    Settings_AlphabetFirstName: 'Nombre',
    Settings_AlphabetLastName: 'Apellidos',
    Settings_CardSizeSmall: 'Pequeño: compacto, más tarjetas visibles',
    Settings_CardSizeMedium: 'Mediano: equilibrado',
    Settings_CardSizeLarge: 'Grande: espacioso, menos tarjetas',
    Settings_HeaderText: 'Preferencias',
    Settings_SaveButton: 'Guardar',
    Settings_CancelButton: 'Cancelar',
    Settings_DiscardButton: 'Descartar cambios',
    Settings_SectionDirectory: 'Directorio',
    Settings_AlphabetFilterByLabel: 'Filtrar alfabéticamente por',
    Settings_CardSizeLabel: 'Tamaño de tarjeta',
    Settings_FontSizeLabel: 'Tamaño de fuente',
    Settings_SectionCardsAndFields: 'Tarjetas y campos',
    Settings_ShowOnCardsLabel: 'Mostrar en las tarjetas de empleado:',
    Settings_EmailAddressLabel: 'Dirección de correo electrónico',
    Settings_PhoneNumberLabel: 'Número de teléfono',
    Settings_DepartmentLabel: 'Departamento',
    Settings_OfficeLocationLabel: 'Ubicación de la oficina',
    Settings_SectionOrgChart: 'Organigrama',
    Settings_ManagerLevelsLabel: 'Niveles de responsables que se muestran al centrar una persona: {levels}',
    Settings_CompactCardsLabel: 'Tarjetas compactas',
    Settings_CompactCardsOn: 'Activado: tarjetas más pequeñas, se ven más a la vez',
    Settings_CompactCardsOff: 'Desactivado: tamaño estándar',
    Settings_Hint: 'Estas preferencias se guardan en el explorador y solo se aplican a usted. El tema del organigrama, la vista predeterminada y el diseño los configura el administrador de SharePoint.',
    Settings_SectionDemoData: 'Datos de demostración',
    Settings_DatasetSizeLabel: 'Tamaño del conjunto de datos',
    Settings_PeopleCountSuffix: '{count} personas',

    // ── Export (CSV / PDF) ──
    Export_ColumnName: 'Nombre',
    Export_ColumnJobTitle: 'Puesto',
    Export_ColumnDepartment: 'Departamento',
    Export_ColumnOffice: 'Oficina',
    Export_ColumnEmail: 'Correo electrónico',
    Export_ColumnPhone: 'Teléfono',
    Export_ColumnManager: 'Responsable',
    Export_ColumnLevel: 'Nivel',
    Export_PdfDocumentTitle: 'Organigrama',
    Export_PdfHeading: 'Organigrama de la organización',
    Export_PdfRootLabel: 'Raíz: {name}',
  };
});
