define([], function () {
  return {
    // ── Property pane: pane header / groups ──
    PropertyPane_HeaderDescription: 'Smart Org Chart -asetukset',
    PropertyPane_Group_General: 'Yleiset',
    PropertyPane_Group_Branding: 'Brändäys',
    PropertyPane_Group_VisualStyle: 'Visuaalinen tyyli',
    PropertyPane_Group_DataSource: 'Tietolähde',
    PropertyPane_Group_CustomAttributes: 'Mukautetut määritteet',
    PropertyPane_Group_UserFilters: 'Käyttäjäsuodattimet',
    PropertyPane_Group_OrgChart: 'Organisaatiokaavio',
    PropertyPane_Group_OrgChartFeatures: 'Organisaatiokaavion ominaisuudet',
    PropertyPane_Group_Directory: 'Hakemisto',
    PropertyPane_Group_Demo: 'Demo',

    // ── Property pane: General ──
    PropertyPane_DefaultView_Label: 'Oletusnäkymä',

    // ── Property pane: Branding ──
    PropertyPane_AppTitle_Label: 'Sovelluksen otsikko',
    PropertyPane_AppTitle_Placeholder: 'Contoso-organisaatiokaavio',
    PropertyPane_AppTitle_Description: 'Näytetään ylätunnisteessa näkymän nimen vieressä',
    PropertyPane_LogoUrl_Label: 'Logon URL-osoite',
    PropertyPane_LogoUrl_Placeholder: 'https://contoso.sharepoint.com/sites/yoursite/SiteAssets/logo.png',
    PropertyPane_LogoUrl_Description: 'PNG-, SVG- tai JPG-kuvan täydellinen URL-osoite. Vihje: avaa kuvatiedosto selaimessa ja kopioi osoiterivin URL-osoite. Jakamisen "Kopioi linkki" -toiminnolla saadut URL-osoitteet eivät toimi.',
    PropertyPane_DirectoryLabel_Label: 'Työntekijähakemisto-näkymän nimi',
    PropertyPane_OrgChartLabel_Label: 'Organisaatiokaavio-näkymän nimi',
    PropertyPane_ViewLabel_Description: 'Jätä tyhjäksi, jos haluat käyttää oletusnimeä, tai kirjoita "[blank]" piilottaaksesi otsikon kokonaan.',

    // ── Property pane: Visual Style ──
    PropertyPane_ChartTheme_Label: 'Kaavion teema',
    PropertyPane_Theme_Modern: 'Moderni – osastovärit valkoisella pohjalla',
    PropertyPane_Theme_Minimal: 'Minimalistinen – tasainen ja vähäkontrastinen',
    PropertyPane_Theme_Corporate: 'Yritystyyli – yhtenäinen sininen',
    PropertyPane_Theme_Dark: 'Tumma – tumma laivastonsininen tausta',
    PropertyPane_Theme_Custom: 'Mukautettu – valitse oma väri',
    PropertyPane_AccentColor_Label: 'Mukautettu korostusväri',
    PropertyPane_AccentColor_PickerAriaLabel: 'Korostusvärin valitsin',
    PropertyPane_AccentColor_HexLabel: 'Heksa',
    PropertyPane_AccentColor_HexAriaLabel: 'Korostusvärin heksadesimaaliarvo',
    PropertyPane_AccentColor_RgbLabel: 'RGB',
    PropertyPane_AccentColor_ChannelAriaLabel: '{name}-kanava (0–255)',
    PropertyPane_AccentColor_ContrastWithWhite: 'Kontrasti valkoiseen: {ratio}:1 ({passes})',
    PropertyPane_AccentColor_PassesAA: 'täyttää AA-tason',
    PropertyPane_AccentColor_LargeTextOnly: 'vain suurelle tekstille',
    PropertyPane_AccentColor_LowContrast: 'heikko kontrasti',
    PropertyPane_AccentColor_DarkTextNote: 'Tällä värillä teksti näytetään tummana luettavuuden parantamiseksi.',
    PropertyPane_AccentColor_DarkerShadeNote: 'Otsikoissa ja linkeissä käytetään tummempaa sävyä ({hex}) luettavuuden parantamiseksi.',
    PropertyPane_AccentColor_InvalidHex: '"{typed}" ei ole kelvollinen heksaväri. Käytä esimerkiksi arvoa #0078d4 tai #07d.',
    PropertyPane_DefaultFontSize_Label: 'Oletusfonttikoko',
    PropertyPane_FontSize_75: '75 % – erittäin pieni',
    PropertyPane_FontSize_85: '85 % – pieni',
    PropertyPane_FontSize_100: '100 % – normaali',
    PropertyPane_FontSize_115: '115 % – suuri',
    PropertyPane_FontSize_130: '130 % – erittäin suuri',
    PropertyPane_FontSize_150: '150 % – XXL',
    PropertyPane_FontSize_175: '175 % – XXXL',
    PropertyPane_DefaultLayout_Label: 'Organisaatiokaavion oletusasettelu',
    PropertyPane_Layout_Drill: 'Poraudu syvemmälle',
    PropertyPane_Layout_Vertical: 'Ylhäältä alas',
    PropertyPane_Layout_Horizontal: 'Vasemmalta oikealle',

    // ── Property pane: Data Source ──
    PropertyPane_DataSource_Label: 'Mistä käyttäjä- ja organisaatiotiedot ladataan',
    PropertyPane_DataSource_Auto: 'Automaattinen – Graph API, varmistus SharePoint-haulla',
    PropertyPane_DataSource_Graph: 'Graph API – reaaliaikaiset Azure AD -tiedot (ei indeksointiviivettä)',
    PropertyPane_DataSource_Search: 'SharePoint-haku – vanha toimintatapa',
    PropertyPane_DataSource_Note: 'Graph API on suositeltu vaihtoehto. Se lukee tiedot suoraan Azure Active Directorysta, joten uudet käyttäjät ja esihenkilömuutokset näkyvät heti. Edellyttää, että Microsoft Graph -käyttöoikeudet on hyväksytty SharePointin sovellusluettelossa.',

    // ── Property pane: Custom Attributes ──
    PropertyPane_CustomAttributes_Note: 'Mukautetut määritteet edellyttävät Microsoft Graphia (tietolähde: Graph tai Automaattinen). SharePoint-haulla ei ole yleistä tapaa lukea Entra ID -määritteitä.',
    PropertyPane_CustomAttributes_Heading: 'Hallitse mukautettuja määritteitä',
    PropertyPane_CustomAttributes_Empty: 'Mukautettuja määritteitä ei ole määritetty.',
    PropertyPane_CustomAttributes_AddButton: '+ Lisää määrite',
    PropertyPane_CustomAttributes_MaxTooltip: 'Enintään {max} mukautettua määritettä',
    PropertyPane_CustomAttributes_FieldNameLabel: 'Määritteen nimi',
    PropertyPane_CustomAttributes_FieldPlaceholder: 'esim. companyName',
    PropertyPane_CustomAttributes_FieldError: 'Käytä esim. employeeId, companyName, city, ... tai extensionAttribute1-15',
    PropertyPane_CustomAttributes_DisplayLabelLabel: 'Näyttönimi',
    PropertyPane_CustomAttributes_LabelPlaceholder: 'esim. Kustannuspaikka',
    PropertyPane_CustomAttributes_RemoveTitle: 'Poista määrite',
    PropertyPane_CustomAttributes_RemoveAriaLabel: 'Poista määrite {ordinal}',
    PropertyPane_CustomAttributes_ShowInDirectory: 'Näytä hakemistossa',
    PropertyPane_CustomAttributes_ShowInOrgChart: 'Näytä organisaatiokaaviossa',

    // ── Property pane: User Filters ──
    PropertyPane_ExcludedAccounts_Label: 'Poissuljetut tilit',
    PropertyPane_ExcludedAccounts_Placeholder: 'conf-room, noreply, admin@, Palvelutili',
    PropertyPane_ExcludedAccounts_Description: 'Pilkuilla erotetut sanat tai mallit (ei huomioi kirjainkokoa). Käyttäjät, joiden näyttönimi, sähköposti tai UPN sisältää jonkin näistä, piilotetaan kaikista näkymistä.',
    PropertyPane_RestrictTenant_Label: 'Näytä vain vuokraajan käyttäjät',
    PropertyPane_RestrictTenant_On: 'Käytössä – piilottaa tilit, joiden sähköpostin verkkotunnus on ulkoinen (esim. gmail.com, hotmail.com)',
    PropertyPane_RestrictTenant_Off: 'Ei käytössä – kaikki käyttäjät näytetään sähköpostin verkkotunnuksesta riippumatta',
    PropertyPane_HideGuest_Label: 'Piilota Azure AD -vierastilit',
    PropertyPane_HideGuest_On: 'Käytössä – vierastilit piilotettu',
    PropertyPane_HideGuest_Off: 'Ei käytössä – vierastilit näkyvissä (merkitty Vieras-merkinnällä)',
    PropertyPane_HideDisabled_Label: 'Piilota käytöstä poistetut tilit',
    PropertyPane_HideDisabled_On: 'Käytössä – tilit, joiden kirjautuminen on estetty, piilotetaan',
    PropertyPane_HideDisabled_Off: 'Ei käytössä – käytöstä poistetut tilit näkyvissä (merkitty Poistettu käytöstä -merkinnällä)',
    PropertyPane_HideDisabled_Note: 'Huomautus: vieras- ja käytöstä poistettujen tilien tunnistus edellyttää Graph API -tietolähdettä. SharePoint-haku ei palauta näitä tietoja, joten näillä kahdella suodattimella (ja Vieras/Poistettu käytöstä -merkinnöillä) ei ole vaikutusta, kun tiedot tulevat hausta.',
    PropertyPane_HideNoJobTitle_Label: 'Piilota tilit, joilla ei ole tehtävänimikettä',
    PropertyPane_HideNoJobTitle_On: 'Käytössä – tilit, joilla ei ole tehtävänimikettä, piilotetaan',
    PropertyPane_HideNoJobTitle_Off: 'Ei käytössä – kaikki tilit näytetään tehtävänimikkeestä riippumatta',
    PropertyPane_HideNoDept_Label: 'Piilota tilit, joilla ei ole osastoa',
    PropertyPane_HideNoDept_On: 'Käytössä – tilit, joilla ei ole osastoa, piilotetaan',
    PropertyPane_HideNoDept_Off: 'Ei käytössä – kaikki tilit näytetään osastosta riippumatta',

    // ── Property pane: Org Chart ──
    PropertyPane_TopLevelUser_Label: 'Ylimmän tason käyttäjä (UPN tai sähköposti)',
    PropertyPane_TopLevelUser_Placeholder: 'ceo@yourcompany.com',
    PropertyPane_TopLevelUser_Description: 'Organisaatiokaavion juuressa näytettävä henkilö',
    PropertyPane_LevelsBelow_Label: 'Juuren alapuolelta ladattavat tasot',
    PropertyPane_DottedLine_Label: 'Katkoviivaesihenkilön määrite',
    PropertyPane_DottedLine_Placeholder: 'extensionAttribute10',
    PropertyPane_DottedLine_Description: 'Valinnainen. Sen Azure AD:n paikallisen laajennusmääritteen (extensionAttribute1-15) nimi, johon on tallennettu toissijaisen "katkoviiva"-esihenkilön sähköposti tai UPN. Katkoviivasuhteet näkyvät profiilikorteissa. Edellyttää Graph API -tietolähdettä.',
    PropertyPane_DefaultZoom_Label: 'Organisaatiokaavion oletuszoomaus',
    PropertyPane_Zoom_Auto: 'Oletus (automaattinen sovitus)',
    PropertyPane_Zoom_50: '50 %',
    PropertyPane_Zoom_75: '75 %',
    PropertyPane_Zoom_100: '100 %',
    PropertyPane_Zoom_125: '125 %',
    PropertyPane_Zoom_150: '150 %',

    // ── Property pane: Org Chart Features ──
    PropertyPane_FeatureToggles_Note: 'Näytä tai piilota organisaatiokaavion työkalurivin painikkeita.',
    PropertyPane_FindMe_Label: 'Etsi minut -painike',
    PropertyPane_LayoutToggle_Label: 'Asettelun vaihto (poraus / pystysuora / vaakasuora)',
    PropertyPane_Stats_Label: 'Organisaation tilastopalkki',
    PropertyPane_DeptFilter_Label: 'Osastosuodatin',
    PropertyPane_UserFilter_Label: 'Käyttäjätyypin suodatin (jäsenet / vieraat)',
    PropertyPane_Visible: 'Näkyvissä',
    PropertyPane_Hidden: 'Piilotettu',

    // ── Property pane: Directory ──
    PropertyPane_PageSize_Label: 'Työntekijöitä enintään per sivu',
    PropertyPane_PageSize_AriaLabel: 'Työntekijöitä enintään per sivu (10–200)',
    PropertyPane_PageSize_Note: 'Kortin koko, näkyvät kentät ja muut näyttöasetukset määritetään käyttäjäkohtaisesti sovelluksen asetuskuvakkeen kautta.',

    // ── Property pane: Demo ──
    PropertyPane_UseDemoData_Label: 'Käytä esittelytietoja',
    PropertyPane_UseDemoData_On: 'Käytössä – näytetään esimerkkityöntekijöitä',
    PropertyPane_UseDemoData_Off: 'Ei käytössä – reaaliaikaiset Microsoft 365 -tiedot',

    // ── Presence status labels ──
    Presence_Available: 'Käytettävissä',
    Presence_Busy: 'Varattu',
    Presence_DoNotDisturb: 'Älä häiritse',
    Presence_BeRightBack: 'Kohta takaisin',
    Presence_Away: 'Poissa',
    Presence_Offline: 'Ei yhteyttä',

    // ── Header / top bar ──
    Header_DirectoryLabel: 'Työntekijähakemisto',
    Header_OrgChartLabel: 'Organisaatiokaavio',
    Header_SwitchToView: 'Vaihda näkymään {view}',
    Header_CompanyLogoAlt: 'Yrityksen logo',
    Header_RefreshingAria: 'Päivitetään tietoja',
    Header_RefreshAria: 'Päivitä tiedot',
    Header_RefreshTitle: 'Päivitä tiedot (viimeksi päivitetty {when})',
    Header_NotLoadedYet: 'ei vielä ladattu',
    Header_JustNow: 'juuri nyt',
    Header_MinutesAgo: '{mins} min sitten',
    Header_HoursAgo: '{hours} t sitten',
    Header_PreferencesTitle: 'Asetukset',
    Header_PreferencesAria: 'Avaa asetuspaneeli',

    // ── Employee Directory ──
    Directory_LoadingLabel: 'Ladataan työntekijöitä...',
    Directory_LoadFailedFallback: 'Varmista, että verkko-osalla on User.Read.All-käyttöoikeus.',
    Directory_LoadFailedPrefix: 'Työntekijöiden lataaminen epäonnistui. {detail}',
    Directory_AllDepartments: 'Kaikki osastot',
    Directory_AllOffices: 'Kaikki toimipisteet',
    Directory_StatusDisabled: 'Poistettu käytöstä',
    Directory_StatusGuest: 'Vieras',
    Directory_PresenceStatus: 'Tila: {status}',
    Directory_ChatInTeams: 'Keskustele Teamsissa',
    Directory_ChatWithInTeams: 'Keskustele henkilön {name} kanssa Teamsissa',
    Directory_ManagesCount: 'Alaisia: {direct}',
    Directory_ManagesCountWithTotal: 'Alaisia: {direct} (yhteensä {total})',
    Directory_ReportsCountWithTotal: '{direct} (yhteensä {total})',
    Directory_ColumnName: 'Nimi',
    Directory_ColumnJobTitle: 'Tehtävänimike',
    Directory_ColumnDepartment: 'Osasto',
    Directory_ColumnOffice: 'Toimipiste',
    Directory_ColumnEmail: 'Sähköposti',
    Directory_ColumnPhone: 'Puhelin',
    Directory_ColumnReports: 'Alaiset',
    Directory_ColumnChat: 'Keskustelu',
    Directory_PrevPage: 'Edellinen',
    Directory_NextPage: 'Seuraava',
    Directory_PreviousPageAria: 'Edellinen sivu',
    Directory_NextPageAria: 'Seuraava sivu',
    Directory_SearchPlaceholder: 'Hae nimen, tehtävänimikkeen, sähköpostin tai osaston perusteella...',
    Directory_SearchAria: 'Hae henkilöitä',
    Directory_FilterByDepartmentAria: 'Suodata osaston mukaan',
    Directory_FilterByOfficeAria: 'Suodata toimipisteen mukaan',
    Directory_ClearSearchTitle: 'Tyhjennä haku ja kaikki suodattimet',
    Directory_ClearButton: 'Tyhjennä',
    Directory_ClearFiltersButton: 'Tyhjennä suodattimet',
    Directory_ExportCsvTitle: 'Vie kaikki suodatetut tulokset CSV-tiedostoon (avautuu Excelissä)',
    Directory_ExportCsvButton: 'Vie CSV',
    Directory_ViewModeAria: 'Näkymätila',
    Directory_CardViewTitle: 'Korttinäkymä',
    Directory_ListViewTitle: 'Luettelonäkymä',
    Directory_AlphabetFilterAria: 'Aakkossuodatin',
    Directory_ShowAllTitle: 'Näytä kaikki',
    Directory_OtherLettersTitle: 'Suodata nimet, jotka alkavat numerolla tai muulla merkillä',
    Directory_FilterByLetterTitle: 'Suodata kirjaimella {letter}',
    Directory_ResultCountSingular: 'henkilö',
    Directory_ResultCountPlural: 'henkilöä',
    Directory_PageOf: ' · sivu {page}/{totalPages}',
    Directory_FilterActiveSingular: '{count} suodatin käytössä',
    Directory_FilterActivePlural: '{count} suodatinta käytössä',
    Directory_NoResults: 'Henkilöitä ei löytynyt',
    Directory_PaginationAria: 'Sivutus',

    // ── Org chart toolbar / shared chart chrome ──
    Chart_Layout_Drill: 'Poraudu syvemmälle',
    Chart_Layout_Vertical: 'Ylhäältä alas',
    Chart_Layout_Horizontal: 'Vasemmalta oikealle',
    Chart_SearchPlaceholder: 'Hae henkilöitä...',
    Chart_SearchAria: 'Hae henkilöitä',
    Chart_MatchSingular: 'osuma kaaviossa',
    Chart_MatchPlural: 'osumaa kaaviossa',
    Chart_ResultsListAria: 'Henkilöt',
    Chart_ExpandAll: 'Laajenna kaikki',
    Chart_CollapseAll: 'Tiivistä kaikki',
    Chart_Expanding: 'Laajennetaan…',
    Chart_Loading: 'Ladataan…',
    Chart_FindMeTitle: 'Etsi minut organisaatiokaaviosta',
    Chart_ViewLayoutButton: 'Näkymä',
    Chart_ViewLayoutTitle: 'Vaihda näkymän asettelua',
    Chart_ViewLayoutPanelTitle: 'Näkymän asettelu',
    Chart_StatsSummaryTitle: 'Organisaation tilastoyhteenveto',
    Chart_FilterByDepartmentTitle: 'Suodata osaston mukaan',
    Chart_FilterByDepartmentWithCountAria: 'Suodata osaston mukaan ({count} valittu)',
    Chart_FilterByDepartmentPanelTitle: 'Suodata osaston mukaan',
    Chart_ClearAllFilters: 'Tyhjennä kaikki suodattimet',
    Chart_FilterUserTypesTitle: 'Suodata käyttäjätyyppejä',
    Chart_DownloadPdfTitle: 'Lataa PDF-muodossa',
    Chart_DownloadCsvTitle: 'Lataa CSV-laskentataulukkona',
    Chart_ResetRootTitle: 'Palauta oletusjuureen',
    Chart_ViewFromPersonPlaceholder: 'Näytä henkilöstä alkaen…',
    Chart_ViewFromPersonAria: 'Näytä organisaatiokaavio tietystä henkilöstä alkaen',
    Chart_ZoomOutTitle: 'Loitonna',
    Chart_ZoomInTitle: 'Lähennä',
    Chart_ZoomResetTitle: 'Nollaa zoomaus',
    Chart_ShowInChartAria: 'Näytä kaaviossa',
    Chart_ShowInChartTitle: 'Näytä kaaviossa',
    Chart_FilterMembers: 'Tavalliset jäsenet',
    Chart_FilterGuests: 'Vieraskäyttäjät',
    Chart_FilterDisabled: 'Käytöstä poistetut tilit',
    Chart_SetupTitle: 'Määritä organisaatiokaavio',
    Chart_SetupSubtitle: 'Aloita antamalla ylimmän henkilön sähköposti tai UPN.',
    Chart_SetupPlaceholder: 'ceo@company.com',
    Chart_SetupInputAria: 'Ylimmän henkilön sähköposti tai UPN',
    Chart_SetupLoadButton: 'Lataa',
    Chart_SetupHint: 'Voit myös määrittää tämän pysyvästi verkko-osan asetuksissa (ylläpitäjä).',
    Chart_BuildingLabel: 'Luodaan organisaatiokaaviota...',
    Chart_RetryButton: 'Yritä uudelleen',
    Chart_NotFoundFromSetup: 'Käyttäjää "{identifier}" ei löytynyt.',
    Chart_NotFoundWithSettings: 'Käyttäjää "{identifier}" ei löytynyt. Tarkista UPN tai sähköposti asetuksista.',
    Chart_LoadFailedGeneric: 'Organisaatiokaavion lataaminen epäonnistui.{detail}',
    Chart_LoadFailedPermissions: ' Tarkista käyttöoikeudet.',
    Chart_LoadFailedForPerson: 'Tämän henkilön organisaatiokaavion lataaminen epäonnistui.',
    Chart_FindMeNotFound: 'Tiliäsi ei löytynyt tästä organisaatiosta.',
    Chart_StatPeople: 'Henkilöt',
    Chart_StatMembers: 'Jäsenet',
    Chart_StatGuests: 'Vieraat',
    Chart_StatDepts: 'Osastot',
    Chart_ReportingLineAria: 'Raportointiketju',
    Chart_BackToFullOrgTitle: 'Takaisin koko organisaatiokaavioon',
    Chart_FullOrgLabel: 'Koko organisaatio',
    Chart_FocusOnPerson: 'Kohdista henkilöön {name}',
    Chart_OrgChartAria: 'Organisaatiokaavio',
    Chart_ExportNote_DrillLevel: 'Nykyinen porautumistaso (yksi taso suoria alaisia)',
    Chart_ExportNote_PartialLevels: 'Sisältää vain ladatut tasot – käytä Laajenna kaikki -toimintoa ennen vientiä, jos haluat mukaan syvemmät tasot',
    Chart_AllowPopupsForPdf: 'Salli ponnahdusikkunat, jotta voit viedä PDF-tiedoston.',

    // ── Person card ──
    PersonCard_ProfileAria: 'Profiili: {name}',
    PersonCard_CloseTitle: 'Sulje',
    PersonCard_CloseAria: 'Sulje profiili',
    PersonCard_StatusDisabled: 'Poistettu käytöstä',
    PersonCard_StatusGuest: 'Vieras',
    PersonCard_DirectReportSingular: '{count} suora alainen',
    PersonCard_DirectReportPlural: '{count} suoraa alaista',
    PersonCard_TotalSuffix: ' · yhteensä {total}',
    PersonCard_CopyEmailTitle: 'Kopioi sähköpostiosoite',
    PersonCard_EmailCopiedAria: 'Sähköpostiosoite kopioitu',
    PersonCard_ReportsTo: 'Raportoi henkilölle',
    PersonCard_FocusOnPerson: 'Kohdista henkilöön {name}',
    PersonCard_FocusOrgChartOnPerson: 'Kohdista organisaatiokaavio henkilöön {name}',
    PersonCard_DottedLine: 'Katkoviiva',
    PersonCard_DottedLineManager: 'Katkoviivaesihenkilö: {name}',
    PersonCard_DottedLineReport: 'Katkoviiva-alainen: {name}',
    PersonCard_ChatButton: 'Keskustelu',
    PersonCard_EmailButton: 'Sähköposti',
    PersonCard_FocusButton: 'Kohdista',
    PersonCard_FocusTitle: 'Kohdista organisaatiokaavio tähän henkilöön',

    // ── Org node card ──
    OrgNode_ViewProfile: 'Näytä henkilön {name} profiili',
    OrgNode_FocusOrgChartOn: 'Kohdista organisaatiokaavio henkilöön {name}',
    OrgNode_Collapse: 'Tiivistä',
    OrgNode_Expand: 'Laajenna',
    OrgNode_DirectReportsSuffix: 'Henkilön {name} suorat alaiset',
    OrgNode_StatusDisabled: 'Poistettu käytöstä',
    OrgNode_StatusGuest: 'Vieras',
    OrgNode_TotalReportsAcrossLevels: '{count} henkilöä kaikilla tasoilla henkilön {name} alapuolella',

    // ── Drill view ──
    Drill_ReportingLineAria: 'Raportointiketju',
    Drill_BackToTopTitle: 'Takaisin alkuun',
    Drill_BackToTopAria: 'Takaisin organisaatiokaavion alkuun',
    Drill_GoBackTo: 'Palaa henkilöön {name}',
    Drill_ViewProfileTitle: 'Näytä profiili',
    Drill_ViewProfileAria: 'Näytä henkilön {name} profiili',
    Drill_ProfileButton: 'Profiili',
    Drill_LoadingLabel: 'Ladataan...',
    Drill_DirectReports: 'Suorat alaiset',
    Drill_DirectReportsOfAria: 'Henkilön {name} suorat alaiset',
    Drill_DirectReportsAria: 'Suorat alaiset',
    Drill_ViewPersonProfile: 'Näytä henkilön {name} profiili',
    Drill_ShowPersonReports: 'Näytä henkilön {name} suorat alaiset',
    Drill_NoDirectReports: 'Ei suoria alaisia',

    // ── Settings panel ──
    Settings_AlphabetFirstName: 'Etunimi',
    Settings_AlphabetLastName: 'Sukunimi',
    Settings_CardSizeSmall: 'Pieni – tiivis, enemmän kortteja näkyvissä',
    Settings_CardSizeMedium: 'Keskikokoinen – tasapainoinen',
    Settings_CardSizeLarge: 'Suuri – väljä, vähemmän kortteja',
    Settings_HeaderText: 'Asetukset',
    Settings_SaveButton: 'Tallenna',
    Settings_CancelButton: 'Peruuta',
    Settings_DiscardButton: 'Hylkää muutokset',
    Settings_SectionDirectory: 'Hakemisto',
    Settings_AlphabetFilterByLabel: 'Aakkossuodatuksen peruste',
    Settings_CardSizeLabel: 'Kortin koko',
    Settings_FontSizeLabel: 'Fonttikoko',
    Settings_SectionCardsAndFields: 'Kortit ja kentät',
    Settings_ShowOnCardsLabel: 'Näytä työntekijäkorteissa:',
    Settings_EmailAddressLabel: 'Sähköpostiosoite',
    Settings_PhoneNumberLabel: 'Puhelinnumero',
    Settings_DepartmentLabel: 'Osasto',
    Settings_OfficeLocationLabel: 'Toimipisteen sijainti',
    Settings_SectionOrgChart: 'Organisaatiokaavio',
    Settings_ManagerLevelsLabel: 'Näytettävät esihenkilötasot kohdistettaessa henkilöön: {levels}',
    Settings_CompactCardsLabel: 'Tiiviit kortit',
    Settings_CompactCardsOn: 'Käytössä – pienemmät kortit, enemmän näkyvissä kerralla',
    Settings_CompactCardsOff: 'Ei käytössä – vakiokoko',
    Settings_Hint: 'Nämä asetukset tallennetaan selaimeesi ja koskevat vain sinua. Kaavion teeman, oletusnäkymän ja asettelun määrittää SharePoint-ylläpitäjäsi.',
    Settings_SectionDemoData: 'Esittelytiedot',
    Settings_DatasetSizeLabel: 'Tietojoukon koko',
    Settings_PeopleCountSuffix: '{count} henkilöä',

    // ── Export (CSV / PDF) ──
    Export_ColumnName: 'Nimi',
    Export_ColumnJobTitle: 'Tehtävänimike',
    Export_ColumnDepartment: 'Osasto',
    Export_ColumnOffice: 'Toimipiste',
    Export_ColumnEmail: 'Sähköposti',
    Export_ColumnPhone: 'Puhelin',
    Export_ColumnManager: 'Esihenkilö',
    Export_ColumnLevel: 'Taso',
    Export_PdfDocumentTitle: 'Organisaatiokaavio',
    Export_PdfHeading: 'Organisaatiokaavio',
    Export_PdfRootLabel: 'Juuri: {name}',
  };
});
