define([], function () {
  return {
    // ── Property pane: pane header / groups ──
    PropertyPane_HeaderDescription: 'Paramètres de Smart Org Chart',
    PropertyPane_Group_General: 'Général',
    PropertyPane_Group_Branding: 'Image de marque',
    PropertyPane_Group_VisualStyle: 'Style visuel',
    PropertyPane_Group_DataSource: 'Source de données',
    PropertyPane_Group_CustomAttributes: 'Attributs personnalisés',
    PropertyPane_Group_UserFilters: 'Filtres utilisateur',
    PropertyPane_Group_OrgChart: 'Organigramme',
    PropertyPane_Group_OrgChartFeatures: "Fonctionnalités de l'organigramme",
    PropertyPane_Group_Directory: 'Répertoire',
    PropertyPane_Group_Demo: 'Démonstration',

    // ── Property pane: General ──
    PropertyPane_DefaultView_Label: 'Vue par défaut',

    // ── Property pane: Branding ──
    PropertyPane_AppTitle_Label: "Titre de l'application",
    PropertyPane_AppTitle_Placeholder: 'Organigramme Contoso',
    PropertyPane_AppTitle_Description: "Affiché dans la barre d'en-tête à côté du nom de la vue",
    PropertyPane_LogoUrl_Label: 'URL du logo',
    PropertyPane_LogoUrl_Placeholder: 'https://contoso.sharepoint.com/sites/yoursite/SiteAssets/logo.png',
    PropertyPane_LogoUrl_Description: "URL complète d'une image PNG, SVG ou JPG. Astuce : ouvrez le fichier image dans votre navigateur et copiez l'URL de la barre d'adresse. Les URL de partage « Copier le lien » ne fonctionneront pas.",
    PropertyPane_DirectoryLabel_Label: 'Libellé de la vue Répertoire des employés',
    PropertyPane_OrgChartLabel_Label: "Libellé de la vue Organigramme",
    PropertyPane_ViewLabel_Description: 'Laissez vide pour utiliser le nom par défaut, ou saisissez « [blank] » pour masquer complètement le libellé.',

    // ── Property pane: Visual Style ──
    PropertyPane_ChartTheme_Label: "Thème de l'organigramme",
    PropertyPane_Theme_Modern: 'Moderne : couleurs de service sur fond blanc',
    PropertyPane_Theme_Minimal: 'Minimal : plat et faible contraste',
    PropertyPane_Theme_Corporate: 'Entreprise : bleu uniforme',
    PropertyPane_Theme_Dark: 'Sombre : fond bleu marine foncé',
    PropertyPane_Theme_Custom: 'Personnalisé : choisissez votre propre couleur',
    PropertyPane_AccentColor_Label: "Couleur d'accentuation personnalisée",
    PropertyPane_AccentColor_PickerAriaLabel: "Sélecteur de couleur d'accentuation",
    PropertyPane_AccentColor_HexLabel: 'Hexadécimal',
    PropertyPane_AccentColor_HexAriaLabel: "Valeur hexadécimale de la couleur d'accentuation",
    PropertyPane_AccentColor_RgbLabel: 'RVB',
    PropertyPane_AccentColor_ChannelAriaLabel: 'Canal {name} (de 0 à 255)',
    PropertyPane_AccentColor_ContrastWithWhite: 'Contraste avec le blanc : {ratio}:1 ({passes})',
    PropertyPane_AccentColor_PassesAA: 'conforme AA',
    PropertyPane_AccentColor_LargeTextOnly: 'texte de grande taille uniquement',
    PropertyPane_AccentColor_LowContrast: 'contraste faible',
    PropertyPane_AccentColor_DarkTextNote: 'Le texte sur cette couleur utilisera une teinte foncée pour une meilleure lisibilité.',
    PropertyPane_AccentColor_DarkerShadeNote: 'Les titres et les liens utiliseront une teinte plus foncée ({hex}) pour une meilleure lisibilité.',
    PropertyPane_AccentColor_InvalidHex: "« {typed} » n'est pas une couleur hexadécimale valide. Utilisez une valeur telle que #0078d4 ou #07d.",
    PropertyPane_DefaultFontSize_Label: 'Taille de police par défaut',
    PropertyPane_FontSize_75: '75 % : très petite',
    PropertyPane_FontSize_85: '85 % : petite',
    PropertyPane_FontSize_100: '100 % : normale',
    PropertyPane_FontSize_115: '115 % : grande',
    PropertyPane_FontSize_130: '130 % : très grande',
    PropertyPane_FontSize_150: '150 % : XXL',
    PropertyPane_FontSize_175: '175 % : XXXL',
    PropertyPane_DefaultLayout_Label: "Disposition par défaut de l'organigramme",
    PropertyPane_Layout_Drill: 'Exploration',
    PropertyPane_Layout_Vertical: 'De haut en bas',
    PropertyPane_Layout_Horizontal: 'De gauche à droite',

    // ── Property pane: Data Source ──
    PropertyPane_DataSource_Label: 'Source de chargement des données utilisateur et organisationnelles',
    PropertyPane_DataSource_Auto: 'Automatique : API Graph, avec repli sur Recherche SharePoint',
    PropertyPane_DataSource_Graph: 'API Graph : données Azure AD en temps réel (sans délai d\'indexation)',
    PropertyPane_DataSource_Search: 'Recherche SharePoint : comportement hérité',
    PropertyPane_DataSource_Note: "L'API Graph est recommandée. Elle lit directement les données Azure Active Directory, ce qui permet aux nouveaux utilisateurs et aux changements de responsable d'apparaître immédiatement. Nécessite que les autorisations Microsoft Graph soient approuvées dans le catalogue d'applications SharePoint.",

    // ── Property pane: Custom Attributes ──
    PropertyPane_CustomAttributes_Note: "Les attributs personnalisés nécessitent Microsoft Graph (source de données : Graph ou Automatique). Recherche SharePoint ne dispose d'aucun moyen générique de lire les attributs Entra ID.",
    PropertyPane_CustomAttributes_Heading: 'Gérer les attributs personnalisés',
    PropertyPane_CustomAttributes_Empty: 'Aucun attribut personnalisé configuré.',
    PropertyPane_CustomAttributes_AddButton: '+ Ajouter un attribut',
    PropertyPane_CustomAttributes_MaxTooltip: 'Maximum de {max} attributs personnalisés',
    PropertyPane_CustomAttributes_FieldNameLabel: "Nom de l'attribut",
    PropertyPane_CustomAttributes_FieldPlaceholder: 'par exemple, companyName',
    PropertyPane_CustomAttributes_FieldError: 'Utilisez employeeId, companyName, city, ... ou extensionAttribute1-15',
    PropertyPane_CustomAttributes_DisplayLabelLabel: "Libellé d'affichage",
    PropertyPane_CustomAttributes_LabelPlaceholder: 'par exemple, Centre de coûts',
    PropertyPane_CustomAttributes_RemoveTitle: "Supprimer l'attribut",
    PropertyPane_CustomAttributes_RemoveAriaLabel: "Supprimer l'attribut {ordinal}",
    PropertyPane_CustomAttributes_ShowInDirectory: 'Afficher dans le répertoire',
    PropertyPane_CustomAttributes_ShowInOrgChart: "Afficher dans l'organigramme",

    // ── Property pane: User Filters ──
    PropertyPane_ExcludedAccounts_Label: 'Exclure des comptes',
    PropertyPane_ExcludedAccounts_Placeholder: 'conf-room, noreply, admin@, Compte de service',
    PropertyPane_ExcludedAccounts_Description: "Mots ou modèles séparés par des virgules (insensible à la casse). Tout utilisateur dont le nom d'affichage, l'adresse e-mail ou l'UPN contient l'un de ces éléments sera masqué dans toutes les vues.",
    PropertyPane_RestrictTenant_Label: 'Afficher uniquement les utilisateurs du locataire',
    PropertyPane_RestrictTenant_On: 'Activé : masque les comptes dont le domaine de messagerie est externe (par exemple, gmail.com, hotmail.com)',
    PropertyPane_RestrictTenant_Off: 'Désactivé : tous les utilisateurs sont affichés, quel que soit le domaine de messagerie',
    PropertyPane_HideGuest_Label: 'Masquer les comptes invités Azure AD',
    PropertyPane_HideGuest_On: 'Activé : les comptes invités sont masqués',
    PropertyPane_HideGuest_Off: 'Désactivé : les comptes invités sont visibles (affichés avec le badge Invité)',
    PropertyPane_HideDisabled_Label: 'Masquer les comptes désactivés',
    PropertyPane_HideDisabled_On: 'Activé : les comptes dont la connexion est bloquée sont masqués',
    PropertyPane_HideDisabled_Off: 'Désactivé : les comptes désactivés sont visibles (affichés avec le badge Désactivé)',
    PropertyPane_HideDisabled_Note: "Remarque : la détection des comptes invités et désactivés nécessite la source de données API Graph. Recherche SharePoint ne renvoie pas cette information ; ces deux filtres (ainsi que les badges Invité/Désactivé) n'ont donc aucun effet lorsque les données proviennent de Recherche.",
    PropertyPane_HideNoJobTitle_Label: 'Masquer les comptes sans fonction',
    PropertyPane_HideNoJobTitle_On: 'Activé : les comptes sans fonction sont masqués',
    PropertyPane_HideNoJobTitle_Off: 'Désactivé : tous les comptes sont affichés, quelle que soit la fonction',
    PropertyPane_HideNoDept_Label: 'Masquer les comptes sans service',
    PropertyPane_HideNoDept_On: 'Activé : les comptes sans service sont masqués',
    PropertyPane_HideNoDept_Off: 'Désactivé : tous les comptes sont affichés, quel que soit le service',

    // ── Property pane: Org Chart ──
    PropertyPane_TopLevelUser_Label: 'Utilisateur de premier niveau (UPN ou e-mail)',
    PropertyPane_TopLevelUser_Placeholder: 'ceo@yourcompany.com',
    PropertyPane_TopLevelUser_Description: "La personne affichée à la racine de l'organigramme",
    PropertyPane_LevelsBelow_Label: 'Niveaux à charger sous la racine',
    PropertyPane_DottedLine_Label: 'Attribut de responsable en pointillé',
    PropertyPane_DottedLine_Placeholder: 'extensionAttribute10',
    PropertyPane_DottedLine_Description: "Facultatif. Nom de l'attribut d'extension Azure AD local (extensionAttribute1-15) qui stocke l'adresse e-mail ou l'UPN d'un responsable secondaire en « pointillé ». Les relations en pointillé apparaissent sur les fiches de profil. Nécessite la source de données API Graph.",
    PropertyPane_DefaultZoom_Label: "Zoom par défaut de l'organigramme",
    PropertyPane_Zoom_Auto: 'Par défaut (ajustement automatique)',
    PropertyPane_Zoom_50: '50 %',
    PropertyPane_Zoom_75: '75 %',
    PropertyPane_Zoom_100: '100 %',
    PropertyPane_Zoom_125: '125 %',
    PropertyPane_Zoom_150: '150 %',

    // ── Property pane: Org Chart Features ──
    PropertyPane_FeatureToggles_Note: "Afficher ou masquer les boutons de la barre d'outils dans la vue de l'organigramme.",
    PropertyPane_FindMe_Label: 'Bouton Me localiser',
    PropertyPane_LayoutToggle_Label: 'Bascule de disposition (exploration/verticale/horizontale)',
    PropertyPane_Stats_Label: "Barre de statistiques de l'organisation",
    PropertyPane_DeptFilter_Label: 'Filtre par service',
    PropertyPane_UserFilter_Label: "Filtre par type d'utilisateur (membres/invités)",
    PropertyPane_Visible: 'Visible',
    PropertyPane_Hidden: 'Masqué',

    // ── Property pane: Directory ──
    PropertyPane_PageSize_Label: "Nombre maximal d'employés par page",
    PropertyPane_PageSize_AriaLabel: "Nombre maximal d'employés par page (de 10 à 200)",
    PropertyPane_PageSize_Note: "La taille des fiches, les champs visibles et d'autres préférences d'affichage sont définis par utilisateur via l'icône d'engrenage Paramètres de l'application.",

    // ── Property pane: Demo ──
    PropertyPane_UseDemoData_Label: 'Utiliser des données de démonstration',
    PropertyPane_UseDemoData_On: "Activé : affichage d'employés types",
    PropertyPane_UseDemoData_Off: 'Désactivé : données Microsoft 365 en temps réel',

    // ── Presence status labels ──
    Presence_Available: 'Disponible',
    Presence_Busy: 'Occupé',
    Presence_DoNotDisturb: 'Ne pas déranger',
    Presence_BeRightBack: 'De retour bientôt',
    Presence_Away: 'Absent',
    Presence_Offline: 'Hors connexion',

    // ── Header / top bar ──
    Header_DirectoryLabel: 'Répertoire des employés',
    Header_OrgChartLabel: 'Organigramme',
    Header_SwitchToView: 'Basculer vers {view}',
    Header_CompanyLogoAlt: "Logo de l'entreprise",
    Header_RefreshingAria: 'Actualisation des données',
    Header_RefreshAria: 'Actualiser les données',
    Header_RefreshTitle: 'Actualiser les données (dernière mise à jour : {when})',
    Header_NotLoadedYet: 'pas encore chargées',
    Header_JustNow: "à l'instant",
    Header_MinutesAgo: 'il y a {mins} min',
    Header_HoursAgo: 'il y a {hours} h',
    Header_PreferencesTitle: 'Préférences',
    Header_PreferencesAria: 'Ouvrir le panneau des préférences',

    // ── Employee Directory ──
    Directory_LoadingLabel: 'Chargement des employés…',
    Directory_LoadFailedFallback: "Vérifiez que la web part dispose de l'autorisation User.Read.All.",
    Directory_LoadFailedPrefix: 'Échec du chargement des employés. {detail}',
    Directory_AllDepartments: 'Tous les services',
    Directory_AllOffices: 'Tous les bureaux',
    Directory_StatusDisabled: 'Désactivé',
    Directory_StatusGuest: 'Invité',
    Directory_PresenceStatus: 'État : {status}',
    Directory_ChatInTeams: 'Discuter dans Teams',
    Directory_ChatWithInTeams: 'Discuter avec {name} dans Teams',
    Directory_ManagesCount: 'Gère {direct}',
    Directory_ManagesCountWithTotal: 'Gère {direct} ({total} au total)',
    Directory_ReportsCountWithTotal: '{direct} ({total} au total)',
    Directory_ColumnName: 'Nom',
    Directory_ColumnJobTitle: 'Fonction',
    Directory_ColumnDepartment: 'Service',
    Directory_ColumnOffice: 'Bureau',
    Directory_ColumnEmail: 'E-mail',
    Directory_ColumnPhone: 'Téléphone',
    Directory_ColumnReports: 'Subordonnés',
    Directory_ColumnChat: 'Chat',
    Directory_PrevPage: 'Précédent',
    Directory_NextPage: 'Suivant',
    Directory_PreviousPageAria: 'Page précédente',
    Directory_NextPageAria: 'Page suivante',
    Directory_SearchPlaceholder: 'Rechercher par nom, fonction, e-mail ou service…',
    Directory_SearchAria: 'Rechercher des personnes',
    Directory_FilterByDepartmentAria: 'Filtrer par service',
    Directory_FilterByOfficeAria: 'Filtrer par bureau',
    Directory_ClearSearchTitle: 'Effacer la recherche et tous les filtres',
    Directory_ClearButton: 'Effacer',
    Directory_ClearFiltersButton: 'Effacer les filtres',
    Directory_ExportCsvTitle: "Exporter tous les résultats filtrés vers un fichier CSV (s'ouvre dans Excel)",
    Directory_ExportCsvButton: 'Exporter en CSV',
    Directory_ViewModeAria: "Mode d'affichage",
    Directory_CardViewTitle: 'Vue en fiches',
    Directory_ListViewTitle: 'Vue en liste',
    Directory_AlphabetFilterAria: 'Filtre alphabétique',
    Directory_ShowAllTitle: 'Tout afficher',
    Directory_OtherLettersTitle: 'Filtrer les noms commençant par un chiffre ou un autre caractère',
    Directory_FilterByLetterTitle: 'Filtrer par {letter}',
    Directory_ResultCountSingular: 'personne',
    Directory_ResultCountPlural: 'personnes',
    Directory_PageOf: ' · page {page} sur {totalPages}',
    Directory_FilterActiveSingular: '{count} filtre actif',
    Directory_FilterActivePlural: '{count} filtres actifs',
    Directory_NoResults: 'Aucune personne trouvée',
    Directory_PaginationAria: 'Pagination',

    // ── Org chart toolbar / shared chart chrome ──
    Chart_Layout_Drill: 'Exploration',
    Chart_Layout_Vertical: 'De haut en bas',
    Chart_Layout_Horizontal: 'De gauche à droite',
    Chart_SearchPlaceholder: 'Rechercher des personnes…',
    Chart_SearchAria: 'Rechercher des personnes',
    Chart_MatchSingular: "correspondance dans l'arborescence",
    Chart_MatchPlural: "correspondances dans l'arborescence",
    Chart_ResultsListAria: 'Personnes',
    Chart_ExpandAll: 'Tout développer',
    Chart_CollapseAll: 'Tout réduire',
    Chart_Expanding: 'Développement en cours…',
    Chart_Loading: 'Chargement…',
    Chart_FindMeTitle: "Me localiser dans l'organigramme",
    Chart_ViewLayoutButton: 'Vue',
    Chart_ViewLayoutTitle: 'Changer la disposition de la vue',
    Chart_ViewLayoutPanelTitle: 'Disposition de la vue',
    Chart_StatsSummaryTitle: "Résumé des statistiques de l'organisation",
    Chart_FilterByDepartmentTitle: 'Filtrer par service',
    Chart_FilterByDepartmentWithCountAria: 'Filtrer par service ({count} sélectionné(s))',
    Chart_FilterByDepartmentPanelTitle: 'Filtrer par service',
    Chart_ClearAllFilters: 'Effacer tous les filtres',
    Chart_FilterUserTypesTitle: "Filtrer les types d'utilisateur",
    Chart_DownloadPdfTitle: 'Télécharger au format PDF',
    Chart_DownloadCsvTitle: 'Télécharger sous forme de feuille de calcul CSV',
    Chart_ResetRootTitle: 'Rétablir la racine par défaut',
    Chart_ViewFromPersonPlaceholder: "Voir à partir d'une personne…",
    Chart_ViewFromPersonAria: "Afficher l'organigramme à partir d'une personne",
    Chart_ZoomOutTitle: 'Zoom arrière',
    Chart_ZoomInTitle: 'Zoom avant',
    Chart_ZoomResetTitle: 'Réinitialiser le zoom',
    Chart_ShowInChartAria: "Afficher dans l'organigramme",
    Chart_ShowInChartTitle: "Afficher dans l'organigramme",
    Chart_FilterMembers: 'Membres standard',
    Chart_FilterGuests: 'Utilisateurs invités',
    Chart_FilterDisabled: 'Comptes désactivés',
    Chart_SetupTitle: "Configurer l'organigramme",
    Chart_SetupSubtitle: "Entrez l'adresse e-mail ou l'UPN de la personne de premier niveau pour commencer.",
    Chart_SetupPlaceholder: 'ceo@company.com',
    Chart_SetupInputAria: "Adresse e-mail ou UPN de la personne de premier niveau",
    Chart_SetupLoadButton: 'Charger',
    Chart_SetupHint: 'Vous pouvez également définir ce paramètre de façon permanente dans les paramètres de la web part (administrateur).',
    Chart_BuildingLabel: "Création de l'organigramme…",
    Chart_RetryButton: 'Réessayer',
    Chart_NotFoundFromSetup: 'Utilisateur « {identifier} » introuvable.',
    Chart_NotFoundWithSettings: "Utilisateur « {identifier} » introuvable. Vérifiez l'UPN ou l'adresse e-mail dans les paramètres.",
    Chart_LoadFailedGeneric: "Échec du chargement de l'organigramme.{detail}",
    Chart_LoadFailedPermissions: ' Vérifiez les autorisations.',
    Chart_LoadFailedForPerson: "Échec du chargement de l'organigramme pour cette personne.",
    Chart_FindMeNotFound: 'Votre compte est introuvable dans cette organisation.',
    Chart_StatPeople: 'Personnes',
    Chart_StatMembers: 'Membres',
    Chart_StatGuests: 'Invités',
    Chart_StatDepts: 'Services',
    Chart_ReportingLineAria: 'Ligne hiérarchique',
    Chart_BackToFullOrgTitle: "Retour à l'organigramme complet",
    Chart_FullOrgLabel: 'Organisation complète',
    Chart_FocusOnPerson: 'Centrer sur {name}',
    Chart_OrgChartAria: 'Organigramme',
    Chart_ExportNote_DrillLevel: 'Niveau d\'exploration actuel (un niveau de subordonnés directs)',
    Chart_ExportNote_PartialLevels: 'Inclut uniquement les niveaux chargés. Utilisez Tout développer avant l\'exportation pour inclure les niveaux plus profonds',
    Chart_AllowPopupsForPdf: 'Veuillez autoriser les fenêtres contextuelles pour exporter au format PDF.',

    // ── Person card ──
    PersonCard_ProfileAria: 'Profil : {name}',
    PersonCard_CloseTitle: 'Fermer',
    PersonCard_CloseAria: 'Fermer le profil',
    PersonCard_StatusDisabled: 'Désactivé',
    PersonCard_StatusGuest: 'Invité',
    PersonCard_DirectReportSingular: '{count} subordonné direct',
    PersonCard_DirectReportPlural: '{count} subordonnés directs',
    PersonCard_TotalSuffix: ' · {total} au total',
    PersonCard_CopyEmailTitle: "Copier l'adresse e-mail",
    PersonCard_EmailCopiedAria: 'Adresse e-mail copiée',
    PersonCard_ReportsTo: 'Relève de',
    PersonCard_FocusOnPerson: 'Centrer sur {name}',
    PersonCard_FocusOrgChartOnPerson: "Centrer l'organigramme sur {name}",
    PersonCard_DottedLine: 'Ligne pointillée',
    PersonCard_DottedLineManager: 'Responsable en pointillé : {name}',
    PersonCard_DottedLineReport: 'Subordonné en pointillé : {name}',
    PersonCard_ChatButton: 'Chat',
    PersonCard_EmailButton: 'E-mail',
    PersonCard_FocusButton: 'Centrer',
    PersonCard_FocusTitle: "Centrer l'organigramme sur cette personne",

    // ── Org node card ──
    OrgNode_ViewProfile: 'Voir le profil de {name}',
    OrgNode_FocusOrgChartOn: "Centrer l'organigramme sur {name}",
    OrgNode_Collapse: 'Réduire',
    OrgNode_Expand: 'Développer',
    OrgNode_DirectReportsSuffix: 'Subordonnés directs de {name}',
    OrgNode_StatusDisabled: 'Désactivé',
    OrgNode_StatusGuest: 'Invité',
    OrgNode_TotalReportsAcrossLevels: '{count} personnes sur tous les niveaux sous {name}',

    // ── Drill view ──
    Drill_ReportingLineAria: 'Ligne hiérarchique',
    Drill_BackToTopTitle: 'Retour en haut',
    Drill_BackToTopAria: "Retour en haut de l'organigramme",
    Drill_GoBackTo: 'Revenir à {name}',
    Drill_ViewProfileTitle: 'Voir le profil',
    Drill_ViewProfileAria: 'Voir le profil de {name}',
    Drill_ProfileButton: 'Profil',
    Drill_LoadingLabel: 'Chargement…',
    Drill_DirectReports: 'Subordonnés directs',
    Drill_DirectReportsOfAria: 'Subordonnés directs de {name}',
    Drill_DirectReportsAria: 'Subordonnés directs',
    Drill_ViewPersonProfile: 'Voir le profil de {name}',
    Drill_ShowPersonReports: 'Afficher les subordonnés directs de {name}',
    Drill_NoDirectReports: 'Aucun subordonné direct',

    // ── Settings panel ──
    Settings_AlphabetFirstName: 'Prénom',
    Settings_AlphabetLastName: 'Nom',
    Settings_CardSizeSmall: 'Petite : compacte, plus de fiches visibles',
    Settings_CardSizeMedium: 'Moyenne : équilibrée',
    Settings_CardSizeLarge: 'Grande : spacieuse, moins de fiches',
    Settings_HeaderText: 'Préférences',
    Settings_SaveButton: 'Enregistrer',
    Settings_CancelButton: 'Annuler',
    Settings_DiscardButton: 'Annuler les modifications',
    Settings_SectionDirectory: 'Répertoire',
    Settings_AlphabetFilterByLabel: 'Filtre alphabétique par',
    Settings_CardSizeLabel: 'Taille des fiches',
    Settings_FontSizeLabel: 'Taille de police',
    Settings_SectionCardsAndFields: 'Fiches et champs',
    Settings_ShowOnCardsLabel: 'Afficher sur les fiches employé :',
    Settings_EmailAddressLabel: 'Adresse e-mail',
    Settings_PhoneNumberLabel: 'Numéro de téléphone',
    Settings_DepartmentLabel: 'Service',
    Settings_OfficeLocationLabel: 'Lieu de bureau',
    Settings_SectionOrgChart: 'Organigramme',
    Settings_ManagerLevelsLabel: 'Niveaux de responsables affichés lors du centrage sur une personne : {levels}',
    Settings_CompactCardsLabel: 'Fiches compactes',
    Settings_CompactCardsOn: 'Activé : fiches plus petites, davantage visibles à la fois',
    Settings_CompactCardsOff: 'Désactivé : taille standard',
    Settings_Hint: "Ces préférences sont enregistrées dans votre navigateur et ne s'appliquent qu'à vous. Le thème de l'organigramme, la vue par défaut et la disposition sont configurés par votre administrateur SharePoint.",
    Settings_SectionDemoData: 'Données de démonstration',
    Settings_DatasetSizeLabel: 'Taille du jeu de données',
    Settings_PeopleCountSuffix: '{count} personnes',

    // ── Export (CSV / PDF) ──
    Export_ColumnName: 'Nom',
    Export_ColumnJobTitle: 'Fonction',
    Export_ColumnDepartment: 'Service',
    Export_ColumnOffice: 'Bureau',
    Export_ColumnEmail: 'E-mail',
    Export_ColumnPhone: 'Téléphone',
    Export_ColumnManager: 'Responsable',
    Export_ColumnLevel: 'Niveau',
    Export_PdfDocumentTitle: 'Organigramme',
    Export_PdfHeading: "Organigramme de l'organisation",
    Export_PdfRootLabel: 'Racine : {name}',
  };
});
