define([], function () {
  return {
    // ── Property pane: pane header / groups ──
    PropertyPane_HeaderDescription: 'הגדרות התרשים הארגוני החכם',
    PropertyPane_Group_General: 'כללי',
    PropertyPane_Group_Branding: 'מיתוג',
    PropertyPane_Group_VisualStyle: 'סגנון חזותי',
    PropertyPane_Group_DataSource: 'מקור נתונים',
    PropertyPane_Group_CustomAttributes: 'תכונות מותאמות אישית',
    PropertyPane_Group_UserFilters: 'מסנני משתמשים',
    PropertyPane_Group_OrgChart: 'תרשים ארגוני',
    PropertyPane_Group_OrgChartFeatures: 'תכונות התרשים הארגוני',
    PropertyPane_Group_Directory: 'ספרייה',
    PropertyPane_Group_Demo: 'הדגמה',

    // ── Property pane: General ──
    PropertyPane_DefaultView_Label: 'תצוגת ברירת מחדל',

    // ── Property pane: Branding ──
    PropertyPane_AppTitle_Label: 'כותרת האפליקציה',
    PropertyPane_AppTitle_Placeholder: 'התרשים הארגוני של Contoso',
    PropertyPane_AppTitle_Description: 'מוצג בסרגל הכותרת לצד שם התצוגה',
    PropertyPane_LogoUrl_Label: 'כתובת URL של הלוגו',
    PropertyPane_LogoUrl_Placeholder: 'https://contoso.sharepoint.com/sites/yoursite/SiteAssets/logo.png',
    PropertyPane_LogoUrl_Description: 'כתובת URL מלאה לתמונת PNG/SVG/JPG. טיפ: פתחו את קובץ התמונה בדפדפן והעתיקו את הכתובת משורת הכתובות. כתובות שיתוף מסוג "העתקת קישור" לא יעבדו.',
    PropertyPane_DirectoryLabel_Label: 'תווית התצוגה של ספריית העובדים',
    PropertyPane_OrgChartLabel_Label: 'תווית התצוגה של התרשים הארגוני',
    PropertyPane_ViewLabel_Description: 'השאירו ריק כדי להשתמש בשם ברירת המחדל, או הקלידו "[blank]" כדי להסתיר את התווית לחלוטין.',

    // ── Property pane: Visual Style ──
    PropertyPane_ChartTheme_Label: 'ערכת נושא של התרשים',
    PropertyPane_Theme_Modern: 'מודרני — צבעי מחלקות על רקע לבן',
    PropertyPane_Theme_Minimal: 'מינימלי — שטוח וניגודיות נמוכה',
    PropertyPane_Theme_Corporate: 'תאגידי — כחול אחיד',
    PropertyPane_Theme_Dark: 'כהה — רקע כחול-נייבי כהה',
    PropertyPane_Theme_Custom: 'מותאם אישית — בחרו צבע משלכם',
    PropertyPane_AccentColor_Label: 'צבע הדגשה מותאם אישית',
    PropertyPane_AccentColor_PickerAriaLabel: 'בורר צבע הדגשה',
    PropertyPane_AccentColor_HexLabel: 'Hex',
    PropertyPane_AccentColor_HexAriaLabel: 'ערך ה-Hex של צבע ההדגשה',
    PropertyPane_AccentColor_RgbLabel: 'RGB',
    PropertyPane_AccentColor_ChannelAriaLabel: 'ערוץ {name} (0 עד 255)',
    PropertyPane_AccentColor_ContrastWithWhite: 'ניגודיות עם לבן: {ratio}:1 ({passes})',
    PropertyPane_AccentColor_PassesAA: 'עומד בתקן AA',
    PropertyPane_AccentColor_LargeTextOnly: 'טקסט גדול בלבד',
    PropertyPane_AccentColor_LowContrast: 'ניגודיות נמוכה',
    PropertyPane_AccentColor_DarkTextNote: 'טקסט על גבי צבע זה יוצג בגוון כהה לשם קריאות טובה יותר.',
    PropertyPane_AccentColor_DarkerShadeNote: 'כותרות וקישורים יוצגו בגוון כהה יותר ({hex}) לשם קריאות טובה יותר.',
    PropertyPane_AccentColor_InvalidHex: '"{typed}" אינו צבע Hex תקין. השתמשו בערך כגון #0078d4 או #07d.',
    PropertyPane_DefaultFontSize_Label: 'גודל גופן ברירת מחדל',
    PropertyPane_FontSize_75: '75% — קטן במיוחד',
    PropertyPane_FontSize_85: '85% — קטן',
    PropertyPane_FontSize_100: '100% — רגיל',
    PropertyPane_FontSize_115: '115% — גדול',
    PropertyPane_FontSize_130: '130% — גדול במיוחד',
    PropertyPane_FontSize_150: '150% — XXL',
    PropertyPane_FontSize_175: '175% — XXXL',
    PropertyPane_DefaultLayout_Label: 'פריסת ברירת מחדל של התרשים הארגוני',
    PropertyPane_Layout_Drill: 'ניווט לעומק',
    PropertyPane_Layout_Vertical: 'מלמעלה למטה',
    PropertyPane_Layout_Horizontal: 'משמאל לימין',

    // ── Property pane: Data Source ──
    PropertyPane_DataSource_Label: 'מהיכן לטעון את נתוני המשתמשים והארגון',
    PropertyPane_DataSource_Auto: 'אוטומטי — Graph API, עם חזרה לחיפוש SharePoint',
    PropertyPane_DataSource_Graph: 'Graph API — נתוני Azure AD בזמן אמת (ללא עיכוב אינדוקס)',
    PropertyPane_DataSource_Search: 'חיפוש SharePoint — התנהגות מדור קודם',
    PropertyPane_DataSource_Note: 'מומלץ להשתמש ב-Microsoft Graph API. הוא קורא ישירות מ-Azure Active Directory, כך שמשתמשים חדשים ושינויים במנהלים מופיעים באופן מיידי. נדרש אישור הרשאות Microsoft Graph בקטלוג האפליקציות של SharePoint.',

    // ── Property pane: Custom Attributes ──
    PropertyPane_CustomAttributes_Note: 'תכונות מותאמות אישית מחייבות שימוש ב-Microsoft Graph (מקור נתונים: Graph או אוטומטי). לחיפוש SharePoint אין דרך גנרית לקרוא תכונות Entra ID.',
    PropertyPane_CustomAttributes_Heading: 'ניהול תכונות מותאמות אישית',
    PropertyPane_CustomAttributes_Empty: 'לא הוגדרו תכונות מותאמות אישית.',
    PropertyPane_CustomAttributes_AddButton: '+ הוספת תכונה',
    PropertyPane_CustomAttributes_MaxTooltip: 'מקסימום של {max} תכונות מותאמות אישית',
    PropertyPane_CustomAttributes_FieldNameLabel: 'שם התכונה',
    PropertyPane_CustomAttributes_FieldPlaceholder: 'לדוגמה, companyName',
    PropertyPane_CustomAttributes_FieldError: 'השתמשו ב-employeeId,‏ companyName,‏ city, ... או extensionAttribute1-15',
    PropertyPane_CustomAttributes_DisplayLabelLabel: 'תווית תצוגה',
    PropertyPane_CustomAttributes_LabelPlaceholder: 'לדוגמה, מרכז עלות',
    PropertyPane_CustomAttributes_RemoveTitle: 'הסרת תכונה',
    PropertyPane_CustomAttributes_RemoveAriaLabel: 'הסרת תכונה {ordinal}',
    PropertyPane_CustomAttributes_ShowInDirectory: 'הצג בספרייה',
    PropertyPane_CustomAttributes_ShowInOrgChart: 'הצג בתרשים הארגוני',

    // ── Property pane: User Filters ──
    PropertyPane_ExcludedAccounts_Label: 'החרגת חשבונות',
    PropertyPane_ExcludedAccounts_Placeholder: 'conf-room, noreply, admin@, Service Account',
    PropertyPane_ExcludedAccounts_Description: 'מילים או תבניות מופרדות בפסיקים (לא רגיש לרישיות). כל משתמש ששם התצוגה, כתובת הדוא״ל או ה-UPN שלו מכיל אחת מהן יוסתר מכל התצוגות.',
    PropertyPane_RestrictTenant_Label: 'הצג רק משתמשי הדייר',
    PropertyPane_RestrictTenant_On: 'מופעל — מסתיר חשבונות עם דומיינים חיצוניים של דוא״ל (למשל gmail.com,‏ hotmail.com)',
    PropertyPane_RestrictTenant_Off: 'כבוי — כל המשתמשים מוצגים ללא קשר לדומיין הדוא״ל',
    PropertyPane_HideGuest_Label: 'הסתר חשבונות אורח של Azure AD',
    PropertyPane_HideGuest_On: 'מופעל — חשבונות אורח מוסתרים',
    PropertyPane_HideGuest_Off: 'כבוי — חשבונות אורח גלויים (מוצגים עם תג אורח)',
    PropertyPane_HideDisabled_Label: 'הסתר חשבונות מושבתים',
    PropertyPane_HideDisabled_On: 'מופעל — חשבונות עם כניסה חסומה מוסתרים',
    PropertyPane_HideDisabled_Off: 'כבוי — חשבונות מושבתים גלויים (מוצגים עם תג מושבת)',
    PropertyPane_HideDisabled_Note: 'הערה: זיהוי חשבונות אורח וחשבונות מושבתים דורש מקור נתונים מסוג Graph API. חיפוש SharePoint אינו מחזיר מידע זה, כך ששני מסננים אלה (וכן תגי האורח/מושבת) אינם משפיעים כאשר הנתונים מגיעים מחיפוש.',
    PropertyPane_HideNoJobTitle_Label: 'הסתר חשבונות ללא תפקיד',
    PropertyPane_HideNoJobTitle_On: 'מופעל — חשבונות ללא תפקיד מוסתרים',
    PropertyPane_HideNoJobTitle_Off: 'כבוי — כל החשבונות מוצגים ללא קשר לתפקיד',
    PropertyPane_HideNoDept_Label: 'הסתר חשבונות ללא מחלקה',
    PropertyPane_HideNoDept_On: 'מופעל — חשבונות ללא מחלקה מוסתרים',
    PropertyPane_HideNoDept_Off: 'כבוי — כל החשבונות מוצגים ללא קשר למחלקה',

    // ── Property pane: Org Chart ──
    PropertyPane_TopLevelUser_Label: 'משתמש ברמה העליונה (UPN או דוא״ל)',
    PropertyPane_TopLevelUser_Placeholder: 'ceo@yourcompany.com',
    PropertyPane_TopLevelUser_Description: 'האדם המוצג בשורש התרשים הארגוני',
    PropertyPane_LevelsBelow_Label: 'רמות לטעינה מתחת לשורש',
    PropertyPane_DottedLine_Label: 'תכונת מנהל בקו מקווקו',
    PropertyPane_DottedLine_Placeholder: 'extensionAttribute10',
    PropertyPane_DottedLine_Description: 'אופציונלי. שם התכונה המורחבת המקומית (on-premises) של Azure AD (extensionAttribute1-15) המאחסנת את הדוא״ל או ה-UPN של מנהל משני ("קו מקווקו"). קשרי קו מקווקו מוצגים בכרטיסי הפרופיל. דורש מקור נתונים מסוג Graph API.',
    PropertyPane_DefaultZoom_Label: 'זום ברירת מחדל של התרשים הארגוני',
    PropertyPane_Zoom_Auto: 'ברירת מחדל (התאמה אוטומטית)',
    PropertyPane_Zoom_50: '50%',
    PropertyPane_Zoom_75: '75%',
    PropertyPane_Zoom_100: '100%',
    PropertyPane_Zoom_125: '125%',
    PropertyPane_Zoom_150: '150%',

    // ── Property pane: Org Chart Features ──
    PropertyPane_FeatureToggles_Note: 'הצג או הסתר כפתורי סרגל כלים בתצוגת התרשים הארגוני.',
    PropertyPane_FindMe_Label: 'כפתור "מצא אותי"',
    PropertyPane_LayoutToggle_Label: 'החלפת פריסה (ניווט לעומק / אנכי / אופקי)',
    PropertyPane_Stats_Label: 'סרגל נתוני הארגון',
    PropertyPane_DeptFilter_Label: 'מסנן מחלקות',
    PropertyPane_UserFilter_Label: 'מסנן סוג משתמש (חברים / אורחים)',
    PropertyPane_Visible: 'גלוי',
    PropertyPane_Hidden: 'מוסתר',

    // ── Property pane: Directory ──
    PropertyPane_PageSize_Label: 'מספר מרבי של עובדים בעמוד',
    PropertyPane_PageSize_AriaLabel: 'מספר מרבי של עובדים בעמוד (10 עד 200)',
    PropertyPane_PageSize_Note: 'גודל הכרטיס, השדות המוצגים והעדפות תצוגה נוספות מוגדרים לכל משתמש דרך סמל ההגדרות באפליקציה.',

    // ── Property pane: Demo ──
    PropertyPane_UseDemoData_Label: 'השתמש בנתוני הדגמה',
    PropertyPane_UseDemoData_On: 'מופעל — מוצגים עובדי דוגמה',
    PropertyPane_UseDemoData_Off: 'כבוי — נתוני Microsoft 365 בזמן אמת',

    // ── Presence status labels ──
    Presence_Available: 'זמין',
    Presence_Busy: 'עסוק',
    Presence_DoNotDisturb: 'נא לא להפריע',
    Presence_BeRightBack: 'אחזור בקרוב',
    Presence_Away: 'לא נמצא',
    Presence_Offline: 'לא מקוון',

    // ── Header / top bar ──
    Header_DirectoryLabel: 'ספריית העובדים',
    Header_OrgChartLabel: 'תרשים ארגוני',
    Header_SwitchToView: 'החלף אל {view}',
    Header_CompanyLogoAlt: 'לוגו החברה',
    Header_RefreshingAria: 'מרענן נתונים',
    Header_RefreshAria: 'רענון נתונים',
    Header_RefreshTitle: 'רענון נתונים (עודכן לאחרונה {when})',
    Header_NotLoadedYet: 'טרם נטען',
    Header_JustNow: 'הרגע',
    Header_MinutesAgo: 'לפני {mins} דק׳',
    Header_HoursAgo: 'לפני {hours} שע׳',
    Header_PreferencesTitle: 'העדפות',
    Header_PreferencesAria: 'פתיחת חלונית ההעדפות',

    // ── Employee Directory ──
    Directory_LoadingLabel: 'טוען עובדים...',
    Directory_LoadFailedFallback: 'ודאו שלרכיב האינטרנט יש הרשאת User.Read.All.',
    Directory_LoadFailedPrefix: 'טעינת העובדים נכשלה. {detail}',
    Directory_AllDepartments: 'כל המחלקות',
    Directory_AllOffices: 'כל המשרדים',
    Directory_StatusDisabled: 'מושבת',
    Directory_StatusGuest: 'אורח',
    Directory_PresenceStatus: 'סטטוס: {status}',
    Directory_ChatInTeams: 'צ׳אט ב-Teams',
    Directory_ChatWithInTeams: 'צ׳אט עם {name} ב-Teams',
    Directory_ManagesCount: 'מנהל את {direct}',
    Directory_ManagesCountWithTotal: 'מנהל את {direct} (סה״כ {total})',
    Directory_ReportsCountWithTotal: '{direct} (סה״כ {total})',
    Directory_ColumnName: 'שם',
    Directory_ColumnJobTitle: 'תפקיד',
    Directory_ColumnDepartment: 'מחלקה',
    Directory_ColumnOffice: 'משרד',
    Directory_ColumnEmail: 'דוא״ל',
    Directory_ColumnPhone: 'טלפון',
    Directory_ColumnReports: 'כפיפים',
    Directory_ColumnChat: 'צ׳אט',
    Directory_PrevPage: 'הקודם',
    Directory_NextPage: 'הבא',
    Directory_PreviousPageAria: 'העמוד הקודם',
    Directory_NextPageAria: 'העמוד הבא',
    Directory_SearchPlaceholder: 'חיפוש לפי שם, תפקיד, דוא״ל או מחלקה...',
    Directory_SearchAria: 'חיפוש אנשים',
    Directory_FilterByDepartmentAria: 'סינון לפי מחלקה',
    Directory_FilterByOfficeAria: 'סינון לפי משרד',
    Directory_ClearSearchTitle: 'ניקוי החיפוש וכל המסננים',
    Directory_ClearButton: 'ניקוי',
    Directory_ClearFiltersButton: 'ניקוי מסננים',
    Directory_ExportCsvTitle: 'ייצוא כל התוצאות המסוננות לקובץ CSV (נפתח ב-Excel)',
    Directory_ExportCsvButton: 'ייצוא CSV',
    Directory_ViewModeAria: 'מצב תצוגה',
    Directory_CardViewTitle: 'תצוגת כרטיסים',
    Directory_ListViewTitle: 'תצוגת רשימה',
    Directory_AlphabetFilterAria: 'סינון אלפביתי',
    Directory_ShowAllTitle: 'הצג הכל',
    Directory_OtherLettersTitle: 'סינון לפי שמות המתחילים במספר או בתו אחר',
    Directory_FilterByLetterTitle: 'סינון לפי {letter}',
    Directory_ResultCountSingular: 'איש',
    Directory_ResultCountPlural: 'אנשים',
    Directory_PageOf: ' · עמוד {page} מתוך {totalPages}',
    Directory_FilterActiveSingular: 'מסנן {count} פעיל',
    Directory_FilterActivePlural: '{count} מסננים פעילים',
    Directory_NoResults: 'לא נמצאו אנשים',
    Directory_PaginationAria: 'מספור עמודים',

    // ── Org chart toolbar / shared chart chrome ──
    Chart_Layout_Drill: 'ניווט לעומק',
    Chart_Layout_Vertical: 'מלמעלה למטה',
    Chart_Layout_Horizontal: 'משמאל לימין',
    Chart_SearchPlaceholder: 'חיפוש אנשים...',
    Chart_SearchAria: 'חיפוש אנשים',
    Chart_MatchSingular: 'התאמה בעץ',
    Chart_MatchPlural: 'התאמות בעץ',
    Chart_ResultsListAria: 'אנשים',
    Chart_ExpandAll: 'הרחב הכל',
    Chart_CollapseAll: 'כווץ הכל',
    Chart_Expanding: 'מרחיב…',
    Chart_Loading: 'טוען…',
    Chart_FindMeTitle: 'מצא אותי בתרשים הארגוני',
    Chart_ViewLayoutButton: 'תצוגה',
    Chart_ViewLayoutTitle: 'החלפת פריסת התצוגה',
    Chart_ViewLayoutPanelTitle: 'פריסת תצוגה',
    Chart_StatsSummaryTitle: 'סיכום נתוני הארגון',
    Chart_FilterByDepartmentTitle: 'סינון לפי מחלקה',
    Chart_FilterByDepartmentWithCountAria: 'סינון לפי מחלקה ({count} נבחרו)',
    Chart_FilterByDepartmentPanelTitle: 'סינון לפי מחלקה',
    Chart_ClearAllFilters: 'ניקוי כל המסננים',
    Chart_FilterUserTypesTitle: 'סינון סוגי משתמשים',
    Chart_DownloadPdfTitle: 'הורדה כ-PDF',
    Chart_DownloadCsvTitle: 'הורדה כגיליון CSV',
    Chart_ResetRootTitle: 'איפוס לשורש ברירת המחדל',
    Chart_ViewFromPersonPlaceholder: 'הצגה מנקודת מבט של אדם…',
    Chart_ViewFromPersonAria: 'הצגת התרשים הארגוני מנקודת מבט של אדם',
    Chart_ZoomOutTitle: 'התרחקות',
    Chart_ZoomInTitle: 'התקרבות',
    Chart_ZoomResetTitle: 'איפוס זום',
    Chart_ShowInChartAria: 'הצגה בתרשים',
    Chart_ShowInChartTitle: 'הצגה בתרשים',
    Chart_FilterMembers: 'חברים רגילים',
    Chart_FilterGuests: 'משתמשי אורח',
    Chart_FilterDisabled: 'חשבונות מושבתים',
    Chart_SetupTitle: 'הגדרת התרשים הארגוני',
    Chart_SetupSubtitle: 'הזינו את הדוא״ל או ה-UPN של האדם ברמה העליונה כדי להתחיל.',
    Chart_SetupPlaceholder: 'ceo@company.com',
    Chart_SetupInputAria: 'הדוא״ל או ה-UPN של האדם ברמה העליונה',
    Chart_SetupLoadButton: 'טעינה',
    Chart_SetupHint: 'ניתן גם להגדיר זאת לצמיתות בהגדרות רכיב האינטרנט (מנהל מערכת).',
    Chart_BuildingLabel: 'בונה את התרשים הארגוני...',
    Chart_RetryButton: 'נסה שוב',
    Chart_NotFoundFromSetup: 'המשתמש "{identifier}" לא נמצא.',
    Chart_NotFoundWithSettings: 'המשתמש "{identifier}" לא נמצא. בדקו את ה-UPN או כתובת הדוא״ל בהגדרות.',
    Chart_LoadFailedGeneric: 'טעינת התרשים הארגוני נכשלה.{detail}',
    Chart_LoadFailedPermissions: ' בדקו את ההרשאות.',
    Chart_LoadFailedForPerson: 'טעינת התרשים הארגוני עבור אדם זה נכשלה.',
    Chart_FindMeNotFound: 'החשבון שלכם לא נמצא בארגון זה.',
    Chart_StatPeople: 'אנשים',
    Chart_StatMembers: 'חברים',
    Chart_StatGuests: 'אורחים',
    Chart_StatDepts: 'מחלקות',
    Chart_ReportingLineAria: 'שרשרת דיווח',
    Chart_BackToFullOrgTitle: 'חזרה לתרשים הארגוני המלא',
    Chart_FullOrgLabel: 'ארגון מלא',
    Chart_FocusOnPerson: 'התמקדות ב-{name}',
    Chart_OrgChartAria: 'תרשים ארגוני',
    Chart_ExportNote_DrillLevel: 'רמת הניווט הנוכחית לעומק (רמה אחת של כפיפים ישירים)',
    Chart_ExportNote_PartialLevels: 'כולל רק את הרמות שנטענו — השתמשו ב"הרחב הכל" לפני הייצוא כדי לכלול רמות עמוקות יותר',
    Chart_AllowPopupsForPdf: 'אפשרו חלונות קופצים כדי לייצא PDF.',

    // ── Person card ──
    PersonCard_ProfileAria: 'פרופיל: {name}',
    PersonCard_CloseTitle: 'סגירה',
    PersonCard_CloseAria: 'סגירת הפרופיל',
    PersonCard_StatusDisabled: 'מושבת',
    PersonCard_StatusGuest: 'אורח',
    PersonCard_DirectReportSingular: '{count} כפיף ישיר',
    PersonCard_DirectReportPlural: '{count} כפיפים ישירים',
    PersonCard_TotalSuffix: ' · סה״כ {total}',
    PersonCard_CopyEmailTitle: 'העתקת כתובת הדוא״ל',
    PersonCard_EmailCopiedAria: 'כתובת הדוא״ל הועתקה',
    PersonCard_ReportsTo: 'כפוף ל-',
    PersonCard_FocusOnPerson: 'התמקדות ב-{name}',
    PersonCard_FocusOrgChartOnPerson: 'התמקדות התרשים הארגוני ב-{name}',
    PersonCard_DottedLine: 'קו מקווקו',
    PersonCard_DottedLineManager: 'מנהל בקו מקווקו: {name}',
    PersonCard_DottedLineReport: 'כפיף בקו מקווקו: {name}',
    PersonCard_ChatButton: 'צ׳אט',
    PersonCard_EmailButton: 'דוא״ל',
    PersonCard_FocusButton: 'התמקדות',
    PersonCard_FocusTitle: 'התמקדות התרשים הארגוני באדם זה',

    // ── Org node card ──
    OrgNode_ViewProfile: 'הצגת הפרופיל של {name}',
    OrgNode_FocusOrgChartOn: 'התמקדות התרשים הארגוני ב-{name}',
    OrgNode_Collapse: 'כיווץ',
    OrgNode_Expand: 'הרחבה',
    OrgNode_DirectReportsSuffix: 'הכפיפים הישירים של {name}',
    OrgNode_StatusDisabled: 'מושבת',
    OrgNode_StatusGuest: 'אורח',
    OrgNode_TotalReportsAcrossLevels: '{count} אנשים בכל הרמות מתחת ל-{name}',

    // ── Drill view ──
    Drill_ReportingLineAria: 'שרשרת דיווח',
    Drill_BackToTopTitle: 'חזרה לראש',
    Drill_BackToTopAria: 'חזרה לראש התרשים הארגוני',
    Drill_GoBackTo: 'חזרה אל {name}',
    Drill_ViewProfileTitle: 'הצגת פרופיל',
    Drill_ViewProfileAria: 'הצגת הפרופיל של {name}',
    Drill_ProfileButton: 'פרופיל',
    Drill_LoadingLabel: 'טוען...',
    Drill_DirectReports: 'כפיפים ישירים',
    Drill_DirectReportsOfAria: 'הכפיפים הישירים של {name}',
    Drill_DirectReportsAria: 'כפיפים ישירים',
    Drill_ViewPersonProfile: 'הצגת הפרופיל של {name}',
    Drill_ShowPersonReports: 'הצגת הכפיפים הישירים של {name}',
    Drill_NoDirectReports: 'אין כפיפים ישירים',

    // ── Settings panel ──
    Settings_AlphabetFirstName: 'שם פרטי',
    Settings_AlphabetLastName: 'שם משפחה',
    Settings_CardSizeSmall: 'קטן — קומפקטי, יותר כרטיסים גלויים',
    Settings_CardSizeMedium: 'בינוני — מאוזן',
    Settings_CardSizeLarge: 'גדול — מרווח, פחות כרטיסים',
    Settings_HeaderText: 'העדפות',
    Settings_SaveButton: 'שמירה',
    Settings_CancelButton: 'ביטול',
    Settings_DiscardButton: 'ביטול השינויים',
    Settings_SectionDirectory: 'ספרייה',
    Settings_AlphabetFilterByLabel: 'סינון אלפביתי לפי',
    Settings_CardSizeLabel: 'גודל כרטיס',
    Settings_FontSizeLabel: 'גודל גופן',
    Settings_SectionCardsAndFields: 'כרטיסים ושדות',
    Settings_ShowOnCardsLabel: 'הצג בכרטיסי העובדים:',
    Settings_EmailAddressLabel: 'כתובת דוא״ל',
    Settings_PhoneNumberLabel: 'מספר טלפון',
    Settings_DepartmentLabel: 'מחלקה',
    Settings_OfficeLocationLabel: 'מיקום המשרד',
    Settings_SectionOrgChart: 'תרשים ארגוני',
    Settings_ManagerLevelsLabel: 'מספר רמות המנהלים המוצגות בעת התמקדות באדם: {levels}',
    Settings_CompactCardsLabel: 'כרטיסים קומפקטיים',
    Settings_CompactCardsOn: 'מופעל — כרטיסים קטנים יותר, יותר גלויים בבת אחת',
    Settings_CompactCardsOff: 'כבוי — גודל רגיל',
    Settings_Hint: 'העדפות אלה נשמרות בדפדפן שלכם וחלות עליכם בלבד. ערכת הנושא של התרשים, תצוגת ברירת המחדל והפריסה מוגדרות על ידי מנהל ה-SharePoint שלכם.',
    Settings_SectionDemoData: 'נתוני הדגמה',
    Settings_DatasetSizeLabel: 'גודל ערכת הנתונים',
    Settings_PeopleCountSuffix: '{count} אנשים',

    // ── Export (CSV / PDF) ──
    Export_ColumnName: 'שם',
    Export_ColumnJobTitle: 'תפקיד',
    Export_ColumnDepartment: 'מחלקה',
    Export_ColumnOffice: 'משרד',
    Export_ColumnEmail: 'דוא״ל',
    Export_ColumnPhone: 'טלפון',
    Export_ColumnManager: 'מנהל',
    Export_ColumnLevel: 'רמה',
    Export_PdfDocumentTitle: 'תרשים ארגוני',
    Export_PdfHeading: 'תרשים ארגוני',
    Export_PdfRootLabel: 'שורש: {name}',
  };
});
