define([], function () {
  return {
    // ── Property pane: pane header / groups ──
    PropertyPane_HeaderDescription: 'Smart Org Chart सेटिंग्स',
    PropertyPane_Group_General: 'सामान्य',
    PropertyPane_Group_Branding: 'ब्रांडिंग',
    PropertyPane_Group_VisualStyle: 'विज़ुअल शैली',
    PropertyPane_Group_DataSource: 'डेटा स्रोत',
    PropertyPane_Group_CustomAttributes: 'कस्टम विशेषताएं',
    PropertyPane_Group_UserFilters: 'उपयोगकर्ता फ़िल्टर',
    PropertyPane_Group_OrgChart: 'Org Chart',
    PropertyPane_Group_OrgChartFeatures: 'Org Chart सुविधाएं',
    PropertyPane_Group_Directory: 'डायरेक्टरी',
    PropertyPane_Group_Demo: 'डेमो',

    // ── Property pane: General ──
    PropertyPane_DefaultView_Label: 'डिफ़ॉल्ट व्यू',

    // ── Property pane: Branding ──
    PropertyPane_AppTitle_Label: 'ऐप शीर्षक',
    PropertyPane_AppTitle_Placeholder: 'Contoso Org Chart',
    PropertyPane_AppTitle_Description: 'हेडर बार में व्यू के नाम के साथ प्रदर्शित होता है',
    PropertyPane_LogoUrl_Label: 'लोगो URL',
    PropertyPane_LogoUrl_Placeholder: 'https://contoso.sharepoint.com/sites/yoursite/SiteAssets/logo.png',
    PropertyPane_LogoUrl_Description: 'PNG/SVG/JPG इमेज का पूरा URL. सुझाव: इमेज फ़ाइल को अपने ब्राउज़र में खोलें और एड्रेस बार का URL कॉपी करें. "Copy link" शेयरिंग URL काम नहीं करेंगे.',
    PropertyPane_DirectoryLabel_Label: 'Employee Directory व्यू लेबल',
    PropertyPane_OrgChartLabel_Label: 'Org Chart व्यू लेबल',
    PropertyPane_ViewLabel_Description: 'डिफ़ॉल्ट नाम उपयोग करने के लिए खाली छोड़ें, या लेबल को पूरी तरह छिपाने के लिए "[blank]" टाइप करें.',

    // ── Property pane: Visual Style ──
    PropertyPane_ChartTheme_Label: 'चार्ट थीम',
    PropertyPane_Theme_Modern: 'मॉडर्न — सफ़ेद पर विभाग के रंग',
    PropertyPane_Theme_Minimal: 'मिनिमल — फ़्लैट और कम कंट्रास्ट',
    PropertyPane_Theme_Corporate: 'कॉर्पोरेट — एकीकृत नीला',
    PropertyPane_Theme_Dark: 'डार्क — गहरे नेवी रंग की पृष्ठभूमि',
    PropertyPane_Theme_Custom: 'कस्टम — अपना रंग चुनें',
    PropertyPane_AccentColor_Label: 'कस्टम एक्सेंट रंग',
    PropertyPane_AccentColor_PickerAriaLabel: 'एक्सेंट रंग चयनकर्ता',
    PropertyPane_AccentColor_HexLabel: 'Hex',
    PropertyPane_AccentColor_HexAriaLabel: 'एक्सेंट रंग का Hex मान',
    PropertyPane_AccentColor_RgbLabel: 'RGB',
    PropertyPane_AccentColor_ChannelAriaLabel: '{name} चैनल (0 से 255)',
    PropertyPane_AccentColor_ContrastWithWhite: 'सफ़ेद के साथ कंट्रास्ट: {ratio}:1 ({passes})',
    PropertyPane_AccentColor_PassesAA: 'AA पास करता है',
    PropertyPane_AccentColor_LargeTextOnly: 'केवल बड़े टेक्स्ट के लिए',
    PropertyPane_AccentColor_LowContrast: 'कम कंट्रास्ट',
    PropertyPane_AccentColor_DarkTextNote: 'पठनीयता के लिए इस रंग पर टेक्स्ट डार्क रंग में दिखेगा.',
    PropertyPane_AccentColor_DarkerShadeNote: 'पठनीयता के लिए शीर्षक और लिंक एक गहरे शेड ({hex}) में दिखेंगे.',
    PropertyPane_AccentColor_InvalidHex: '"{typed}" एक मान्य hex रंग नहीं है. #0078d4 या #07d जैसा मान उपयोग करें.',
    PropertyPane_DefaultFontSize_Label: 'डिफ़ॉल्ट फ़ॉन्ट आकार',
    PropertyPane_FontSize_75: '75% — अतिरिक्त छोटा',
    PropertyPane_FontSize_85: '85% — छोटा',
    PropertyPane_FontSize_100: '100% — सामान्य',
    PropertyPane_FontSize_115: '115% — बड़ा',
    PropertyPane_FontSize_130: '130% — अतिरिक्त बड़ा',
    PropertyPane_FontSize_150: '150% — XXL',
    PropertyPane_FontSize_175: '175% — XXXL',
    PropertyPane_DefaultLayout_Label: 'डिफ़ॉल्ट Org Chart लेआउट',
    PropertyPane_Layout_Drill: 'ड्रिल-डाउन',
    PropertyPane_Layout_Vertical: 'ऊपर से नीचे',
    PropertyPane_Layout_Horizontal: 'बाएं से दाएं',

    // ── Property pane: Data Source ──
    PropertyPane_DataSource_Label: 'उपयोगकर्ता और org डेटा कहां से लोड करें',
    PropertyPane_DataSource_Auto: 'ऑटो — Graph API, विफल होने पर SharePoint Search',
    PropertyPane_DataSource_Graph: 'Graph API — लाइव Azure AD डेटा (कोई इंडेक्सिंग देरी नहीं)',
    PropertyPane_DataSource_Search: 'SharePoint Search — लीगेसी व्यवहार',
    PropertyPane_DataSource_Note: 'Graph API की सिफ़ारिश की जाती है. यह सीधे Azure Active Directory से पढ़ता है, इसलिए नए उपयोगकर्ता और मैनेजर में बदलाव तुरंत दिखाई देते हैं. इसके लिए SharePoint App Catalog में Microsoft Graph अनुमतियों को स्वीकृत किया जाना आवश्यक है.',

    // ── Property pane: Custom Attributes ──
    PropertyPane_CustomAttributes_Note: 'कस्टम विशेषताओं के लिए Microsoft Graph आवश्यक है (डेटा स्रोत: Graph या ऑटो). SharePoint Search के पास Entra ID विशेषताओं को पढ़ने का कोई सामान्य तरीका नहीं है.',
    PropertyPane_CustomAttributes_Heading: 'कस्टम विशेषताएं प्रबंधित करें',
    PropertyPane_CustomAttributes_Empty: 'कोई कस्टम विशेषता कॉन्फ़िगर नहीं की गई है.',
    PropertyPane_CustomAttributes_AddButton: '+ विशेषता जोड़ें',
    PropertyPane_CustomAttributes_MaxTooltip: 'अधिकतम {max} कस्टम विशेषताएं',
    PropertyPane_CustomAttributes_FieldNameLabel: 'विशेषता का नाम',
    PropertyPane_CustomAttributes_FieldPlaceholder: 'जैसे companyName',
    PropertyPane_CustomAttributes_FieldError: 'employeeId, companyName, city, ... या extensionAttribute1-15 का उपयोग करें',
    PropertyPane_CustomAttributes_DisplayLabelLabel: 'प्रदर्शन लेबल',
    PropertyPane_CustomAttributes_LabelPlaceholder: 'जैसे Cost Center',
    PropertyPane_CustomAttributes_RemoveTitle: 'विशेषता हटाएं',
    PropertyPane_CustomAttributes_RemoveAriaLabel: 'विशेषता {ordinal} हटाएं',
    PropertyPane_CustomAttributes_ShowInDirectory: 'Directory में दिखाएं',
    PropertyPane_CustomAttributes_ShowInOrgChart: 'Org Chart में दिखाएं',

    // ── Property pane: User Filters ──
    PropertyPane_ExcludedAccounts_Label: 'खातों को बाहर रखें',
    PropertyPane_ExcludedAccounts_Placeholder: 'conf-room, noreply, admin@, Service Account',
    PropertyPane_ExcludedAccounts_Description: 'अल्पविराम से अलग किए गए शब्द या पैटर्न (केस-असंवेदनशील). जिस भी उपयोगकर्ता के प्रदर्शन नाम, ईमेल, या UPN में इनमें से कोई एक शब्द शामिल हो, वह सभी व्यू से छिपा दिया जाएगा.',
    PropertyPane_RestrictTenant_Label: 'केवल टेनेंट उपयोगकर्ता दिखाएं',
    PropertyPane_RestrictTenant_On: 'चालू — बाहरी ईमेल डोमेन वाले खाते छिपाता है (जैसे gmail.com, hotmail.com)',
    PropertyPane_RestrictTenant_Off: 'बंद — ईमेल डोमेन की परवाह किए बिना सभी उपयोगकर्ता दिखाए जाते हैं',
    PropertyPane_HideGuest_Label: 'Azure AD गेस्ट खाते छिपाएं',
    PropertyPane_HideGuest_On: 'चालू — गेस्ट खाते छिपे हुए हैं',
    PropertyPane_HideGuest_Off: 'बंद — गेस्ट खाते दिखाई देते हैं (Guest बैज के साथ दिखाए जाते हैं)',
    PropertyPane_HideDisabled_Label: 'अक्षम खाते छिपाएं',
    PropertyPane_HideDisabled_On: 'चालू — साइन-इन के लिए ब्लॉक किए गए खाते छिपे हुए हैं',
    PropertyPane_HideDisabled_Off: 'बंद — अक्षम खाते दिखाई देते हैं (Disabled बैज के साथ दिखाए जाते हैं)',
    PropertyPane_HideDisabled_Note: 'नोट: गेस्ट और अक्षम खाते की पहचान के लिए Graph API डेटा स्रोत आवश्यक है. SharePoint Search यह जानकारी नहीं देता, इसलिए जब डेटा Search से आता है तो ये दोनों फ़िल्टर (और Guest/Disabled बैज) कोई असर नहीं डालते.',
    PropertyPane_HideNoJobTitle_Label: 'बिना जॉब टाइटल वाले खाते छिपाएं',
    PropertyPane_HideNoJobTitle_On: 'चालू — बिना जॉब टाइटल वाले खाते छिपे हुए हैं',
    PropertyPane_HideNoJobTitle_Off: 'बंद — जॉब टाइटल की परवाह किए बिना सभी खाते दिखाए जाते हैं',
    PropertyPane_HideNoDept_Label: 'बिना विभाग वाले खाते छिपाएं',
    PropertyPane_HideNoDept_On: 'चालू — बिना विभाग वाले खाते छिपे हुए हैं',
    PropertyPane_HideNoDept_Off: 'बंद — विभाग की परवाह किए बिना सभी खाते दिखाए जाते हैं',

    // ── Property pane: Org Chart ──
    PropertyPane_TopLevelUser_Label: 'शीर्ष-स्तरीय उपयोगकर्ता (UPN या ईमेल)',
    PropertyPane_TopLevelUser_Placeholder: 'ceo@yourcompany.com',
    PropertyPane_TopLevelUser_Description: 'ऑर्ग चार्ट के मूल में दिखाई जाने वाली व्यक्ति',
    PropertyPane_LevelsBelow_Label: 'रूट के नीचे लोड करने के लिए स्तर',
    PropertyPane_DottedLine_Label: 'डॉटेड-लाइन मैनेजर विशेषता',
    PropertyPane_DottedLine_Placeholder: 'extensionAttribute10',
    PropertyPane_DottedLine_Description: 'वैकल्पिक. Azure AD ऑन-प्रिमाइसेस एक्सटेंशन विशेषता (extensionAttribute1-15) का नाम जो द्वितीयक "डॉटेड लाइन" मैनेजर का ईमेल या UPN संग्रहीत करती है. डॉटेड-लाइन संबंध प्रोफ़ाइल कार्ड पर दिखाई देते हैं. इसके लिए Graph API डेटा स्रोत आवश्यक है.',
    PropertyPane_DefaultZoom_Label: 'डिफ़ॉल्ट Org Chart ज़ूम',
    PropertyPane_Zoom_Auto: 'डिफ़ॉल्ट (ऑटो-फ़िट)',
    PropertyPane_Zoom_50: '50%',
    PropertyPane_Zoom_75: '75%',
    PropertyPane_Zoom_100: '100%',
    PropertyPane_Zoom_125: '125%',
    PropertyPane_Zoom_150: '150%',

    // ── Property pane: Org Chart Features ──
    PropertyPane_FeatureToggles_Note: 'ऑर्ग चार्ट व्यू में टूलबार बटन दिखाएं या छिपाएं.',
    PropertyPane_FindMe_Label: 'Find Me बटन',
    PropertyPane_LayoutToggle_Label: 'लेआउट टॉगल (ड्रिल / वर्टिकल / होरिज़ॉन्टल)',
    PropertyPane_Stats_Label: 'Org स्टैट्स बार',
    PropertyPane_DeptFilter_Label: 'विभाग फ़िल्टर',
    PropertyPane_UserFilter_Label: 'उपयोगकर्ता प्रकार फ़िल्टर (सदस्य / गेस्ट)',
    PropertyPane_Visible: 'दृश्यमान',
    PropertyPane_Hidden: 'छिपा हुआ',

    // ── Property pane: Directory ──
    PropertyPane_PageSize_Label: 'प्रति पृष्ठ अधिकतम कर्मचारी',
    PropertyPane_PageSize_AriaLabel: 'प्रति पृष्ठ अधिकतम कर्मचारी (10 से 200)',
    PropertyPane_PageSize_Note: 'कार्ड आकार, दृश्यमान फ़ील्ड और अन्य प्रदर्शन प्राथमिकताएं ऐप में Settings गियर के माध्यम से प्रति-उपयोगकर्ता सेट की जाती हैं.',

    // ── Property pane: Demo ──
    PropertyPane_UseDemoData_Label: 'डेमो डेटा उपयोग करें',
    PropertyPane_UseDemoData_On: 'चालू — नमूना कर्मचारी दिखाए जा रहे हैं',
    PropertyPane_UseDemoData_Off: 'बंद — लाइव Microsoft 365 डेटा',

    // ── Presence status labels ──
    Presence_Available: 'उपलब्ध',
    Presence_Busy: 'व्यस्त',
    Presence_DoNotDisturb: 'परेशान न करें',
    Presence_BeRightBack: 'अभी वापस आता/आती हूं',
    Presence_Away: 'दूर',
    Presence_Offline: 'ऑफ़लाइन',

    // ── Header / top bar ──
    Header_DirectoryLabel: 'Employee Directory',
    Header_OrgChartLabel: 'Org Chart',
    Header_SwitchToView: '{view} पर स्विच करें',
    Header_CompanyLogoAlt: 'कंपनी का लोगो',
    Header_RefreshingAria: 'डेटा रीफ़्रेश हो रहा है',
    Header_RefreshAria: 'डेटा रीफ़्रेश करें',
    Header_RefreshTitle: 'डेटा रीफ़्रेश करें (अंतिम बार अपडेट किया गया {when})',
    Header_NotLoadedYet: 'अभी तक लोड नहीं हुआ',
    Header_JustNow: 'अभी-अभी',
    Header_MinutesAgo: '{mins} मिनट पहले',
    Header_HoursAgo: '{hours} घंटे पहले',
    Header_PreferencesTitle: 'प्राथमिकताएं',
    Header_PreferencesAria: 'प्राथमिकता पैनल खोलें',

    // ── Employee Directory ──
    Directory_LoadingLabel: 'कर्मचारी लोड हो रहे हैं...',
    Directory_LoadFailedFallback: 'सुनिश्चित करें कि वेब पार्ट के पास User.Read.All अनुमति है.',
    Directory_LoadFailedPrefix: 'कर्मचारियों को लोड करने में विफल. {detail}',
    Directory_AllDepartments: 'सभी विभाग',
    Directory_AllOffices: 'सभी कार्यालय',
    Directory_StatusDisabled: 'अक्षम',
    Directory_StatusGuest: 'गेस्ट',
    Directory_PresenceStatus: 'स्थिति: {status}',
    Directory_ChatInTeams: 'Teams में चैट करें',
    Directory_ChatWithInTeams: '{name} के साथ Teams में चैट करें',
    Directory_ManagesCount: '{direct} प्रबंधित करता/करती है',
    Directory_ManagesCountWithTotal: '{direct} प्रबंधित करता/करती है ({total} कुल)',
    Directory_ReportsCountWithTotal: '{direct} ({total} कुल)',
    Directory_ColumnName: 'नाम',
    Directory_ColumnJobTitle: 'जॉब टाइटल',
    Directory_ColumnDepartment: 'विभाग',
    Directory_ColumnOffice: 'कार्यालय',
    Directory_ColumnEmail: 'ईमेल',
    Directory_ColumnPhone: 'फ़ोन',
    Directory_ColumnReports: 'रिपोर्ट्स',
    Directory_ColumnChat: 'चैट',
    Directory_PrevPage: 'पिछला',
    Directory_NextPage: 'अगला',
    Directory_PreviousPageAria: 'पिछला पृष्ठ',
    Directory_NextPageAria: 'अगला पृष्ठ',
    Directory_SearchPlaceholder: 'नाम, टाइटल, ईमेल, या विभाग से खोजें...',
    Directory_SearchAria: 'लोगों को खोजें',
    Directory_FilterByDepartmentAria: 'विभाग के अनुसार फ़िल्टर करें',
    Directory_FilterByOfficeAria: 'कार्यालय के अनुसार फ़िल्टर करें',
    Directory_ClearSearchTitle: 'खोज और सभी फ़िल्टर साफ़ करें',
    Directory_ClearButton: 'साफ़ करें',
    Directory_ClearFiltersButton: 'फ़िल्टर साफ़ करें',
    Directory_ExportCsvTitle: 'सभी फ़िल्टर किए गए परिणामों को CSV फ़ाइल में एक्सपोर्ट करें (Excel में खुलता है)',
    Directory_ExportCsvButton: 'CSV एक्सपोर्ट करें',
    Directory_ViewModeAria: 'व्यू मोड',
    Directory_CardViewTitle: 'कार्ड व्यू',
    Directory_ListViewTitle: 'सूची व्यू',
    Directory_AlphabetFilterAria: 'वर्णमाला फ़िल्टर',
    Directory_ShowAllTitle: 'सभी दिखाएं',
    Directory_OtherLettersTitle: 'किसी संख्या या अन्य वर्ण से शुरू होने वाले नामों के अनुसार फ़िल्टर करें',
    Directory_FilterByLetterTitle: '{letter} के अनुसार फ़िल्टर करें',
    Directory_ResultCountSingular: 'व्यक्ति',
    Directory_ResultCountPlural: 'लोग',
    Directory_PageOf: ' · पृष्ठ {page} / {totalPages}',
    Directory_FilterActiveSingular: '{count} फ़िल्टर सक्रिय',
    Directory_FilterActivePlural: '{count} फ़िल्टर सक्रिय',
    Directory_NoResults: 'कोई व्यक्ति नहीं मिला',
    Directory_PaginationAria: 'पेजिनेशन',

    // ── Org chart toolbar / shared chart chrome ──
    Chart_Layout_Drill: 'ड्रिल-डाउन',
    Chart_Layout_Vertical: 'ऊपर से नीचे',
    Chart_Layout_Horizontal: 'बाएं से दाएं',
    Chart_SearchPlaceholder: 'लोगों को खोजें...',
    Chart_SearchAria: 'लोगों को खोजें',
    Chart_MatchSingular: 'ट्री में मिलान',
    Chart_MatchPlural: 'ट्री में मिलान',
    Chart_ResultsListAria: 'लोग',
    Chart_ExpandAll: 'सभी विस्तृत करें',
    Chart_CollapseAll: 'सभी संक्षिप्त करें',
    Chart_Expanding: 'विस्तृत हो रहा है…',
    Chart_Loading: 'लोड हो रहा है…',
    Chart_FindMeTitle: 'मुझे ऑर्ग चार्ट में खोजें',
    Chart_ViewLayoutButton: 'व्यू',
    Chart_ViewLayoutTitle: 'व्यू लेआउट स्विच करें',
    Chart_ViewLayoutPanelTitle: 'व्यू लेआउट',
    Chart_StatsSummaryTitle: 'Org स्टैट्स सारांश',
    Chart_FilterByDepartmentTitle: 'विभाग के अनुसार फ़िल्टर करें',
    Chart_FilterByDepartmentWithCountAria: 'विभाग के अनुसार फ़िल्टर करें ({count} चयनित)',
    Chart_FilterByDepartmentPanelTitle: 'विभाग के अनुसार फ़िल्टर करें',
    Chart_ClearAllFilters: 'सभी फ़िल्टर साफ़ करें',
    Chart_FilterUserTypesTitle: 'उपयोगकर्ता प्रकार फ़िल्टर करें',
    Chart_DownloadPdfTitle: 'PDF के रूप में डाउनलोड करें',
    Chart_DownloadCsvTitle: 'CSV स्प्रेडशीट के रूप में डाउनलोड करें',
    Chart_ResetRootTitle: 'डिफ़ॉल्ट रूट पर रीसेट करें',
    Chart_ViewFromPersonPlaceholder: 'व्यक्ति से व्यू करें…',
    Chart_ViewFromPersonAria: 'किसी व्यक्ति से ऑर्ग चार्ट देखें',
    Chart_ZoomOutTitle: 'ज़ूम आउट करें',
    Chart_ZoomInTitle: 'ज़ूम इन करें',
    Chart_ZoomResetTitle: 'ज़ूम रीसेट करें',
    Chart_ShowInChartAria: 'चार्ट में दिखाएं',
    Chart_ShowInChartTitle: 'चार्ट में दिखाएं',
    Chart_FilterMembers: 'सामान्य सदस्य',
    Chart_FilterGuests: 'गेस्ट उपयोगकर्ता',
    Chart_FilterDisabled: 'अक्षम खाते',
    Chart_SetupTitle: 'ऑर्ग चार्ट सेट अप करें',
    Chart_SetupSubtitle: 'शुरू करने के लिए शीर्ष-स्तरीय व्यक्ति का ईमेल या UPN दर्ज करें.',
    Chart_SetupPlaceholder: 'ceo@company.com',
    Chart_SetupInputAria: 'शीर्ष-स्तरीय व्यक्ति का ईमेल या UPN',
    Chart_SetupLoadButton: 'लोड करें',
    Chart_SetupHint: 'आप इसे वेब पार्ट सेटिंग्स (एडमिन) में स्थायी रूप से भी सेट कर सकते हैं.',
    Chart_BuildingLabel: 'ऑर्ग चार्ट बनाया जा रहा है...',
    Chart_RetryButton: 'फिर से प्रयास करें',
    Chart_NotFoundFromSetup: 'उपयोगकर्ता "{identifier}" नहीं मिला.',
    Chart_NotFoundWithSettings: 'उपयोगकर्ता "{identifier}" नहीं मिला. Settings में UPN या ईमेल जांचें.',
    Chart_LoadFailedGeneric: 'ऑर्ग चार्ट लोड करने में विफल.{detail}',
    Chart_LoadFailedPermissions: ' अनुमतियां जांचें.',
    Chart_LoadFailedForPerson: 'इस व्यक्ति के लिए ऑर्ग चार्ट लोड करने में विफल.',
    Chart_FindMeNotFound: 'आपका खाता इस org में नहीं मिला.',
    Chart_StatPeople: 'लोग',
    Chart_StatMembers: 'सदस्य',
    Chart_StatGuests: 'गेस्ट',
    Chart_StatDepts: 'विभाग',
    Chart_ReportingLineAria: 'रिपोर्टिंग लाइन',
    Chart_BackToFullOrgTitle: 'पूर्ण ऑर्ग चार्ट पर वापस जाएं',
    Chart_FullOrgLabel: 'पूर्ण org',
    Chart_FocusOnPerson: '{name} पर फ़ोकस करें',
    Chart_OrgChartAria: 'ऑर्ग चार्ट',
    Chart_ExportNote_DrillLevel: 'वर्तमान ड्रिल-डाउन स्तर (प्रत्यक्ष रिपोर्ट्स का एक स्तर)',
    Chart_ExportNote_PartialLevels: 'केवल लोड किए गए स्तर शामिल हैं — गहरे स्तरों को शामिल करने के लिए एक्सपोर्ट करने से पहले सभी विस्तृत करें का उपयोग करें',
    Chart_AllowPopupsForPdf: 'कृपया PDF एक्सपोर्ट करने के लिए पॉप-अप की अनुमति दें.',

    // ── Person card ──
    PersonCard_ProfileAria: 'प्रोफ़ाइल: {name}',
    PersonCard_CloseTitle: 'बंद करें',
    PersonCard_CloseAria: 'प्रोफ़ाइल बंद करें',
    PersonCard_StatusDisabled: 'अक्षम',
    PersonCard_StatusGuest: 'गेस्ट',
    PersonCard_DirectReportSingular: '{count} प्रत्यक्ष रिपोर्ट',
    PersonCard_DirectReportPlural: '{count} प्रत्यक्ष रिपोर्ट्स',
    PersonCard_TotalSuffix: ' · {total} कुल',
    PersonCard_CopyEmailTitle: 'ईमेल पता कॉपी करें',
    PersonCard_EmailCopiedAria: 'ईमेल पता कॉपी किया गया',
    PersonCard_ReportsTo: 'रिपोर्ट करता/करती है',
    PersonCard_FocusOnPerson: '{name} पर फ़ोकस करें',
    PersonCard_FocusOrgChartOnPerson: 'ऑर्ग चार्ट को {name} पर फ़ोकस करें',
    PersonCard_DottedLine: 'डॉटेड लाइन',
    PersonCard_DottedLineManager: 'डॉटेड-लाइन मैनेजर: {name}',
    PersonCard_DottedLineReport: 'डॉटेड-लाइन रिपोर्ट: {name}',
    PersonCard_ChatButton: 'चैट',
    PersonCard_EmailButton: 'ईमेल',
    PersonCard_FocusButton: 'फ़ोकस',
    PersonCard_FocusTitle: 'ऑर्ग चार्ट को इस व्यक्ति पर फ़ोकस करें',

    // ── Org node card ──
    OrgNode_ViewProfile: '{name} की प्रोफ़ाइल देखें',
    OrgNode_FocusOrgChartOn: 'ऑर्ग चार्ट को {name} पर फ़ोकस करें',
    OrgNode_Collapse: 'संक्षिप्त करें',
    OrgNode_Expand: 'विस्तृत करें',
    OrgNode_DirectReportsSuffix: '{name} की प्रत्यक्ष रिपोर्ट्स',
    OrgNode_StatusDisabled: 'अक्षम',
    OrgNode_StatusGuest: 'गेस्ट',
    OrgNode_TotalReportsAcrossLevels: '{name} के नीचे सभी स्तरों में {count} लोग',

    // ── Drill view ──
    Drill_ReportingLineAria: 'रिपोर्टिंग लाइन',
    Drill_BackToTopTitle: 'शीर्ष पर वापस जाएं',
    Drill_BackToTopAria: 'ऑर्ग चार्ट के शीर्ष पर वापस जाएं',
    Drill_GoBackTo: '{name} पर वापस जाएं',
    Drill_ViewProfileTitle: 'प्रोफ़ाइल देखें',
    Drill_ViewProfileAria: '{name} की प्रोफ़ाइल देखें',
    Drill_ProfileButton: 'प्रोफ़ाइल',
    Drill_LoadingLabel: 'लोड हो रहा है...',
    Drill_DirectReports: 'प्रत्यक्ष रिपोर्ट्स',
    Drill_DirectReportsOfAria: '{name} की प्रत्यक्ष रिपोर्ट्स',
    Drill_DirectReportsAria: 'प्रत्यक्ष रिपोर्ट्स',
    Drill_ViewPersonProfile: '{name} की प्रोफ़ाइल देखें',
    Drill_ShowPersonReports: '{name} की प्रत्यक्ष रिपोर्ट्स दिखाएं',
    Drill_NoDirectReports: 'कोई प्रत्यक्ष रिपोर्ट नहीं',

    // ── Settings panel ──
    Settings_AlphabetFirstName: 'पहला नाम',
    Settings_AlphabetLastName: 'अंतिम नाम',
    Settings_CardSizeSmall: 'छोटा — कॉम्पैक्ट, अधिक कार्ड दिखाई देते हैं',
    Settings_CardSizeMedium: 'मध्यम — संतुलित',
    Settings_CardSizeLarge: 'बड़ा — विस्तृत, कम कार्ड',
    Settings_HeaderText: 'प्राथमिकताएं',
    Settings_SaveButton: 'सहेजें',
    Settings_CancelButton: 'रद्द करें',
    Settings_DiscardButton: 'परिवर्तन छोड़ें',
    Settings_SectionDirectory: 'डायरेक्टरी',
    Settings_AlphabetFilterByLabel: 'वर्णमाला फ़िल्टर इसके द्वारा',
    Settings_CardSizeLabel: 'कार्ड आकार',
    Settings_FontSizeLabel: 'फ़ॉन्ट आकार',
    Settings_SectionCardsAndFields: 'कार्ड और फ़ील्ड',
    Settings_ShowOnCardsLabel: 'कर्मचारी कार्ड पर दिखाएं:',
    Settings_EmailAddressLabel: 'ईमेल पता',
    Settings_PhoneNumberLabel: 'फ़ोन नंबर',
    Settings_DepartmentLabel: 'विभाग',
    Settings_OfficeLocationLabel: 'कार्यालय स्थान',
    Settings_SectionOrgChart: 'Org Chart',
    Settings_ManagerLevelsLabel: 'किसी व्यक्ति पर फ़ोकस करते समय दिखाए जाने वाले मैनेजर स्तर: {levels}',
    Settings_CompactCardsLabel: 'कॉम्पैक्ट कार्ड',
    Settings_CompactCardsOn: 'चालू — छोटे कार्ड, एक बार में अधिक दिखाई देते हैं',
    Settings_CompactCardsOff: 'बंद — मानक आकार',
    Settings_Hint: 'ये प्राथमिकताएं आपके ब्राउज़र में सहेजी जाती हैं और केवल आप पर लागू होती हैं. चार्ट थीम, डिफ़ॉल्ट व्यू, और लेआउट आपके SharePoint एडमिन द्वारा कॉन्फ़िगर किए जाते हैं.',
    Settings_SectionDemoData: 'डेमो डेटा',
    Settings_DatasetSizeLabel: 'डेटासेट आकार',
    Settings_PeopleCountSuffix: '{count} लोग',

    // ── Export (CSV / PDF) ──
    Export_ColumnName: 'नाम',
    Export_ColumnJobTitle: 'जॉब टाइटल',
    Export_ColumnDepartment: 'विभाग',
    Export_ColumnOffice: 'कार्यालय',
    Export_ColumnEmail: 'ईमेल',
    Export_ColumnPhone: 'फ़ोन',
    Export_ColumnManager: 'मैनेजर',
    Export_ColumnLevel: 'स्तर',
    Export_PdfDocumentTitle: 'Org Chart',
    Export_PdfHeading: 'ऑर्गनाइज़ेशन चार्ट',
    Export_PdfRootLabel: 'रूट: {name}',
  };
});
