define([], function () {
  return {
    // ── Property pane: pane header / groups ──
    PropertyPane_HeaderDescription: 'Smart Org Chart beállítások',
    PropertyPane_Group_General: 'Általános',
    PropertyPane_Group_Branding: 'Arculat',
    PropertyPane_Group_VisualStyle: 'Megjelenés',
    PropertyPane_Group_DataSource: 'Adatforrás',
    PropertyPane_Group_CustomAttributes: 'Egyéni attribútumok',
    PropertyPane_Group_UserFilters: 'Felhasználói szűrők',
    PropertyPane_Group_OrgChart: 'Szervezeti ábra',
    PropertyPane_Group_OrgChartFeatures: 'Szervezeti ábra funkciói',
    PropertyPane_Group_Directory: 'Címtár',
    PropertyPane_Group_Demo: 'Demó',

    // ── Property pane: General ──
    PropertyPane_DefaultView_Label: 'Alapértelmezett nézet',

    // ── Property pane: Branding ──
    PropertyPane_AppTitle_Label: 'Alkalmazás címe',
    PropertyPane_AppTitle_Placeholder: 'Contoso szervezeti ábra',
    PropertyPane_AppTitle_Description: 'A fejlécsávon jelenik meg a nézet neve mellett',
    PropertyPane_LogoUrl_Label: 'Embléma URL-je',
    PropertyPane_LogoUrl_Placeholder: 'https://contoso.sharepoint.com/sites/yoursite/SiteAssets/logo.png',
    PropertyPane_LogoUrl_Description: 'Egy PNG/SVG/JPG kép teljes URL-je. Tipp: nyissa meg a képfájlt a böngészőben, és másolja ki a címsorban látható URL-t. A „Hivatkozás másolása” megosztási URL-ek nem működnek.',
    PropertyPane_DirectoryLabel_Label: 'Munkatárs-címtár nézet felirata',
    PropertyPane_OrgChartLabel_Label: 'Szervezeti ábra nézet felirata',
    PropertyPane_ViewLabel_Description: 'Hagyja üresen az alapértelmezett név használatához, vagy írja be a "[blank]" szót a felirat teljes elrejtéséhez.',

    // ── Property pane: Visual Style ──
    PropertyPane_ChartTheme_Label: 'Ábra témája',
    PropertyPane_Theme_Modern: 'Modern — osztályszínek fehér alapon',
    PropertyPane_Theme_Minimal: 'Minimál — lapos és alacsony kontrasztú',
    PropertyPane_Theme_Corporate: 'Vállalati — egységes kék',
    PropertyPane_Theme_Dark: 'Sötét — sötét éjkék háttér',
    PropertyPane_Theme_Custom: 'Egyéni — válasszon saját színt',
    PropertyPane_AccentColor_Label: 'Egyéni kiemelőszín',
    PropertyPane_AccentColor_PickerAriaLabel: 'Kiemelőszín-választó',
    PropertyPane_AccentColor_HexLabel: 'Hex',
    PropertyPane_AccentColor_HexAriaLabel: 'Kiemelőszín hexaértéke',
    PropertyPane_AccentColor_RgbLabel: 'RGB',
    PropertyPane_AccentColor_ChannelAriaLabel: '{name} csatorna (0–255)',
    PropertyPane_AccentColor_ContrastWithWhite: 'Kontraszt fehérrel: {ratio}:1 ({passes})',
    PropertyPane_AccentColor_PassesAA: 'megfelel az AA szintnek',
    PropertyPane_AccentColor_LargeTextOnly: 'csak nagyméretű szövegnél',
    PropertyPane_AccentColor_LowContrast: 'alacsony kontraszt',
    PropertyPane_AccentColor_DarkTextNote: 'Az ezen a színen lévő szöveg az olvashatóság érdekében sötét betűszínt használ.',
    PropertyPane_AccentColor_DarkerShadeNote: 'A címek és hivatkozások az olvashatóság érdekében egy sötétebb árnyalatot ({hex}) használnak.',
    PropertyPane_AccentColor_InvalidHex: 'A(z) „{typed}” nem érvényes hexadecimális szín. Adjon meg egy ehhez hasonló értéket: #0078d4 vagy #07d.',
    PropertyPane_DefaultFontSize_Label: 'Alapértelmezett betűméret',
    PropertyPane_FontSize_75: '75% — extra kicsi',
    PropertyPane_FontSize_85: '85% — kicsi',
    PropertyPane_FontSize_100: '100% — normál',
    PropertyPane_FontSize_115: '115% — nagy',
    PropertyPane_FontSize_130: '130% — extra nagy',
    PropertyPane_FontSize_150: '150% — XXL',
    PropertyPane_FontSize_175: '175% — XXXL',
    PropertyPane_DefaultLayout_Label: 'Alapértelmezett szervezetiábra-elrendezés',
    PropertyPane_Layout_Drill: 'Lefúrás',
    PropertyPane_Layout_Vertical: 'Fentről lefelé',
    PropertyPane_Layout_Horizontal: 'Balról jobbra',

    // ── Property pane: Data Source ──
    PropertyPane_DataSource_Label: 'Honnan töltse be a felhasználói és szervezeti adatokat',
    PropertyPane_DataSource_Auto: 'Automatikus — Graph API, tartalék: SharePoint keresés',
    PropertyPane_DataSource_Graph: 'Graph API — élő Azure AD-adatok (indexelési késleltetés nélkül)',
    PropertyPane_DataSource_Search: 'SharePoint keresés — örökölt működés',
    PropertyPane_DataSource_Note: 'A Graph API használata ajánlott. Közvetlenül az Azure Active Directoryból olvas, így az új felhasználók és a vezetőváltozások azonnal megjelennek. Ehhez jóvá kell hagyni a Microsoft Graph engedélyeket a SharePoint alkalmazáskatalógusban.',

    // ── Property pane: Custom Attributes ──
    PropertyPane_CustomAttributes_Note: 'Az egyéni attribútumokhoz Microsoft Graph szükséges (Adatforrás: Graph vagy Automatikus). A SharePoint keresés nem rendelkezik általános móddal az Entra ID-attribútumok beolvasására.',
    PropertyPane_CustomAttributes_Heading: 'Egyéni attribútumok kezelése',
    PropertyPane_CustomAttributes_Empty: 'Nincs beállítva egyéni attribútum.',
    PropertyPane_CustomAttributes_AddButton: '+ Attribútum hozzáadása',
    PropertyPane_CustomAttributes_MaxTooltip: 'Legfeljebb {max} egyéni attribútum',
    PropertyPane_CustomAttributes_FieldNameLabel: 'Attribútum neve',
    PropertyPane_CustomAttributes_FieldPlaceholder: 'pl. companyName',
    PropertyPane_CustomAttributes_FieldError: 'Használjon ilyeneket: employeeId, companyName, city, ... vagy extensionAttribute1-15',
    PropertyPane_CustomAttributes_DisplayLabelLabel: 'Megjelenített felirat',
    PropertyPane_CustomAttributes_LabelPlaceholder: 'pl. Költséghely',
    PropertyPane_CustomAttributes_RemoveTitle: 'Attribútum eltávolítása',
    PropertyPane_CustomAttributes_RemoveAriaLabel: '{ordinal}. attribútum eltávolítása',
    PropertyPane_CustomAttributes_ShowInDirectory: 'Megjelenítés a címtárban',
    PropertyPane_CustomAttributes_ShowInOrgChart: 'Megjelenítés a szervezeti ábrán',

    // ── Property pane: User Filters ──
    PropertyPane_ExcludedAccounts_Label: 'Fiókok kizárása',
    PropertyPane_ExcludedAccounts_Placeholder: 'tárgyaló, noreply, admin@, szolgáltatásfiók',
    PropertyPane_ExcludedAccounts_Description: 'Vesszővel elválasztott szavak vagy minták (kis- és nagybetűre nem érzékeny). Minden olyan felhasználó, akinek a megjelenített neve, e-mail-címe vagy UPN-je tartalmazza ezek valamelyikét, el lesz rejtve minden nézetben.',
    PropertyPane_RestrictTenant_Label: 'Csak bérlőn belüli felhasználók megjelenítése',
    PropertyPane_RestrictTenant_On: 'Be — elrejti a külső e-mail-tartományú fiókokat (pl. gmail.com, hotmail.com)',
    PropertyPane_RestrictTenant_Off: 'Ki — minden felhasználó megjelenik, az e-mail-tartománytól függetlenül',
    PropertyPane_HideGuest_Label: 'Azure AD vendégfiókok elrejtése',
    PropertyPane_HideGuest_On: 'Be — a vendégfiókok el vannak rejtve',
    PropertyPane_HideGuest_Off: 'Ki — a vendégfiókok láthatók (Vendég jelvénnyel jelölve)',
    PropertyPane_HideDisabled_Label: 'Letiltott fiókok elrejtése',
    PropertyPane_HideDisabled_On: 'Be — a bejelentkezésből letiltott fiókok el vannak rejtve',
    PropertyPane_HideDisabled_Off: 'Ki — a letiltott fiókok láthatók (Letiltva jelvénnyel jelölve)',
    PropertyPane_HideDisabled_Note: 'Megjegyzés: a vendég- és letiltottfiók-felismeréshez a Graph API adatforrás szükséges. A SharePoint keresés nem adja vissza ezt az információt, ezért ez a két szűrő (és a Vendég/Letiltva jelvények) nem érvényesül, ha az adatok a keresésből származnak.',
    PropertyPane_HideNoJobTitle_Label: 'Munkakör nélküli fiókok elrejtése',
    PropertyPane_HideNoJobTitle_On: 'Be — a munkakör nélküli fiókok el vannak rejtve',
    PropertyPane_HideNoJobTitle_Off: 'Ki — minden fiók megjelenik, a munkakörtől függetlenül',
    PropertyPane_HideNoDept_Label: 'Osztály nélküli fiókok elrejtése',
    PropertyPane_HideNoDept_On: 'Be — az osztály nélküli fiókok el vannak rejtve',
    PropertyPane_HideNoDept_Off: 'Ki — minden fiók megjelenik, az osztálytól függetlenül',

    // ── Property pane: Org Chart ──
    PropertyPane_TopLevelUser_Label: 'Legfelső szintű felhasználó (UPN vagy e-mail)',
    PropertyPane_TopLevelUser_Placeholder: 'ceo@yourcompany.com',
    PropertyPane_TopLevelUser_Description: 'A szervezeti ábra gyökerénél megjelenő személy',
    PropertyPane_LevelsBelow_Label: 'Betöltendő szintek a gyökér alatt',
    PropertyPane_DottedLine_Label: 'Szaggatott vonalú vezetői attribútum',
    PropertyPane_DottedLine_Placeholder: 'extensionAttribute10',
    PropertyPane_DottedLine_Description: 'Nem kötelező. Az Azure AD helyszíni kiterjesztési attribútumának neve (extensionAttribute1-15), amely egy másodlagos, „szaggatott vonalú” vezető e-mail-címét vagy UPN-jét tárolja. A szaggatott vonalú kapcsolatok megjelennek a profilkártyákon. Ehhez a Graph API adatforrás szükséges.',
    PropertyPane_DefaultZoom_Label: 'Alapértelmezett szervezetiábra-nagyítás',
    PropertyPane_Zoom_Auto: 'Alapértelmezett (automatikus igazítás)',
    PropertyPane_Zoom_50: '50%',
    PropertyPane_Zoom_75: '75%',
    PropertyPane_Zoom_100: '100%',
    PropertyPane_Zoom_125: '125%',
    PropertyPane_Zoom_150: '150%',

    // ── Property pane: Org Chart Features ──
    PropertyPane_FeatureToggles_Note: 'Eszköztárgombok megjelenítése vagy elrejtése a szervezetiábra-nézetben.',
    PropertyPane_FindMe_Label: '„Hol vagyok?” gomb',
    PropertyPane_LayoutToggle_Label: 'Elrendezés váltása (lefúrás / függőleges / vízszintes)',
    PropertyPane_Stats_Label: 'Szervezetistatisztika-sáv',
    PropertyPane_DeptFilter_Label: 'Osztályszűrő',
    PropertyPane_UserFilter_Label: 'Felhasználótípus-szűrő (tagok / vendégek)',
    PropertyPane_Visible: 'Látható',
    PropertyPane_Hidden: 'Rejtett',

    // ── Property pane: Directory ──
    PropertyPane_PageSize_Label: 'Legfeljebb ennyi munkatárs oldalanként',
    PropertyPane_PageSize_AriaLabel: 'Legfeljebb ennyi munkatárs oldalanként (10–200)',
    PropertyPane_PageSize_Note: 'A kártyaméretet, a látható mezőket és az egyéb megjelenítési beállításokat felhasználónként, az alkalmazásban található beállítások fogaskerék ikonjával lehet megadni.',

    // ── Property pane: Demo ──
    PropertyPane_UseDemoData_Label: 'Demóadatok használata',
    PropertyPane_UseDemoData_On: 'Be — minta munkatársak megjelenítése',
    PropertyPane_UseDemoData_Off: 'Ki — élő Microsoft 365-adatok',

    // ── Presence status labels ──
    Presence_Available: 'Elérhető',
    Presence_Busy: 'Elfoglalt',
    Presence_DoNotDisturb: 'Ne zavarjanak',
    Presence_BeRightBack: 'Mindjárt jövök',
    Presence_Away: 'Távol',
    Presence_Offline: 'Nem elérhető',

    // ── Header / top bar ──
    Header_DirectoryLabel: 'Munkatárs-címtár',
    Header_OrgChartLabel: 'Szervezeti ábra',
    Header_SwitchToView: 'Váltás erre: {view}',
    Header_CompanyLogoAlt: 'Cégembléma',
    Header_RefreshingAria: 'Adatok frissítése',
    Header_RefreshAria: 'Adatok frissítése',
    Header_RefreshTitle: 'Adatok frissítése (utolsó frissítés: {when})',
    Header_NotLoadedYet: 'még nincs betöltve',
    Header_JustNow: 'éppen most',
    Header_MinutesAgo: '{mins} perce',
    Header_HoursAgo: '{hours} órája',
    Header_PreferencesTitle: 'Beállítások',
    Header_PreferencesAria: 'Beállítások panel megnyitása',

    // ── Employee Directory ──
    Directory_LoadingLabel: 'Munkatársak betöltése...',
    Directory_LoadFailedFallback: 'Győződjön meg róla, hogy a webrész rendelkezik User.Read.All engedéllyel.',
    Directory_LoadFailedPrefix: 'Nem sikerült betölteni a munkatársakat. {detail}',
    Directory_AllDepartments: 'Minden osztály',
    Directory_AllOffices: 'Minden iroda',
    Directory_StatusDisabled: 'Letiltva',
    Directory_StatusGuest: 'Vendég',
    Directory_PresenceStatus: 'Állapot: {status}',
    Directory_ChatInTeams: 'Csevegés a Teamsben',
    Directory_ChatWithInTeams: 'Csevegés vele: {name} (Teams)',
    Directory_ManagesCount: '{direct} beosztottja van',
    Directory_ManagesCountWithTotal: '{direct} beosztottja van ({total} összesen)',
    Directory_ReportsCountWithTotal: '{direct} ({total} összesen)',
    Directory_ColumnName: 'Név',
    Directory_ColumnJobTitle: 'Munkakör',
    Directory_ColumnDepartment: 'Osztály',
    Directory_ColumnOffice: 'Iroda',
    Directory_ColumnEmail: 'E-mail',
    Directory_ColumnPhone: 'Telefon',
    Directory_ColumnReports: 'Beosztottak',
    Directory_ColumnChat: 'Csevegés',
    Directory_PrevPage: 'Előző',
    Directory_NextPage: 'Következő',
    Directory_PreviousPageAria: 'Előző oldal',
    Directory_NextPageAria: 'Következő oldal',
    Directory_SearchPlaceholder: 'Keresés név, munkakör, e-mail vagy osztály szerint...',
    Directory_SearchAria: 'Munkatársak keresése',
    Directory_FilterByDepartmentAria: 'Szűrés osztály szerint',
    Directory_FilterByOfficeAria: 'Szűrés iroda szerint',
    Directory_ClearSearchTitle: 'Keresés és minden szűrő törlése',
    Directory_ClearButton: 'Törlés',
    Directory_ClearFiltersButton: 'Szűrők törlése',
    Directory_ExportCsvTitle: 'Az összes szűrt eredmény exportálása CSV-fájlba (Excelben nyílik meg)',
    Directory_ExportCsvButton: 'CSV exportálása',
    Directory_ViewModeAria: 'Nézet módja',
    Directory_CardViewTitle: 'Kártyanézet',
    Directory_ListViewTitle: 'Listanézet',
    Directory_AlphabetFilterAria: 'Ábécé szerinti szűrő',
    Directory_ShowAllTitle: 'Összes megjelenítése',
    Directory_OtherLettersTitle: 'Szűrés számmal vagy egyéb karakterrel kezdődő nevekre',
    Directory_FilterByLetterTitle: 'Szűrés erre: {letter}',
    Directory_ResultCountSingular: 'fő',
    Directory_ResultCountPlural: 'fő',
    Directory_PageOf: ' · {page}. oldal / {totalPages}',
    Directory_FilterActiveSingular: '{count} aktív szűrő',
    Directory_FilterActivePlural: '{count} aktív szűrő',
    Directory_NoResults: 'Nincs találat',
    Directory_PaginationAria: 'Lapozás',

    // ── Org chart toolbar / shared chart chrome ──
    Chart_Layout_Drill: 'Lefúrás',
    Chart_Layout_Vertical: 'Fentről lefelé',
    Chart_Layout_Horizontal: 'Balról jobbra',
    Chart_SearchPlaceholder: 'Munkatársak keresése...',
    Chart_SearchAria: 'Munkatársak keresése',
    Chart_MatchSingular: 'találat a fastruktúrában',
    Chart_MatchPlural: 'találat a fastruktúrában',
    Chart_ResultsListAria: 'Munkatársak',
    Chart_ExpandAll: 'Összes kibontása',
    Chart_CollapseAll: 'Összes összecsukása',
    Chart_Expanding: 'Kibontás…',
    Chart_Loading: 'Betöltés…',
    Chart_FindMeTitle: 'Saját magam megkeresése a szervezeti ábrán',
    Chart_ViewLayoutButton: 'Nézet',
    Chart_ViewLayoutTitle: 'Nézetelrendezés váltása',
    Chart_ViewLayoutPanelTitle: 'Nézetelrendezés',
    Chart_StatsSummaryTitle: 'Szervezeti statisztika összegzése',
    Chart_FilterByDepartmentTitle: 'Szűrés osztály szerint',
    Chart_FilterByDepartmentWithCountAria: 'Szűrés osztály szerint ({count} kiválasztva)',
    Chart_FilterByDepartmentPanelTitle: 'Szűrés osztály szerint',
    Chart_ClearAllFilters: 'Minden szűrő törlése',
    Chart_FilterUserTypesTitle: 'Felhasználótípusok szűrése',
    Chart_DownloadPdfTitle: 'Letöltés PDF-ként',
    Chart_DownloadCsvTitle: 'Letöltés CSV-táblázatként',
    Chart_ResetRootTitle: 'Visszaállítás az alapértelmezett gyökérre',
    Chart_ViewFromPersonPlaceholder: 'Nézet egy személytől…',
    Chart_ViewFromPersonAria: 'A szervezeti ábra megtekintése egy személy nézőpontjából',
    Chart_ZoomOutTitle: 'Kicsinyítés',
    Chart_ZoomInTitle: 'Nagyítás',
    Chart_ZoomResetTitle: 'Nagyítás visszaállítása',
    Chart_ShowInChartAria: 'Megjelenítés az ábrán',
    Chart_ShowInChartTitle: 'Megjelenítés az ábrán',
    Chart_FilterMembers: 'Rendes tagok',
    Chart_FilterGuests: 'Vendég felhasználók',
    Chart_FilterDisabled: 'Letiltott fiókok',
    Chart_SetupTitle: 'Szervezeti ábra beállítása',
    Chart_SetupSubtitle: 'A kezdéshez adja meg a legfelső szintű személy e-mail-címét vagy UPN-jét.',
    Chart_SetupPlaceholder: 'ceo@company.com',
    Chart_SetupInputAria: 'A legfelső szintű személy e-mail-címe vagy UPN-je',
    Chart_SetupLoadButton: 'Betöltés',
    Chart_SetupHint: 'Ezt véglegesen is beállíthatja a webrész beállításaiban (rendszergazdai).',
    Chart_BuildingLabel: 'Szervezeti ábra összeállítása...',
    Chart_RetryButton: 'Újra',
    Chart_NotFoundFromSetup: 'A(z) „{identifier}” felhasználó nem található.',
    Chart_NotFoundWithSettings: 'A(z) „{identifier}” felhasználó nem található. Ellenőrizze az UPN-t vagy az e-mail-címet a Beállításokban.',
    Chart_LoadFailedGeneric: 'Nem sikerült betölteni a szervezeti ábrát.{detail}',
    Chart_LoadFailedPermissions: ' Ellenőrizze az engedélyeket.',
    Chart_LoadFailedForPerson: 'Nem sikerült betölteni a szervezeti ábrát ehhez a személyhez.',
    Chart_FindMeNotFound: 'A fiókja nem található ebben a szervezetben.',
    Chart_StatPeople: 'Munkatársak',
    Chart_StatMembers: 'Tagok',
    Chart_StatGuests: 'Vendégek',
    Chart_StatDepts: 'Osztályok',
    Chart_ReportingLineAria: 'Jelentési vonal',
    Chart_BackToFullOrgTitle: 'Vissza a teljes szervezeti ábrához',
    Chart_FullOrgLabel: 'Teljes szervezet',
    Chart_FocusOnPerson: 'Fókusz erre: {name}',
    Chart_OrgChartAria: 'Szervezeti ábra',
    Chart_ExportNote_DrillLevel: 'Az aktuális lefúrási szint (a közvetlen beosztottak egy szintje)',
    Chart_ExportNote_PartialLevels: 'Csak a betöltött szinteket tartalmazza — a mélyebb szintek beillesztéséhez exportálás előtt használja az „Összes kibontása” lehetőséget',
    Chart_AllowPopupsForPdf: 'A PDF exportálásához engedélyezze a felugró ablakokat.',

    // ── Person card ──
    PersonCard_ProfileAria: 'Profil: {name}',
    PersonCard_CloseTitle: 'Bezárás',
    PersonCard_CloseAria: 'Profil bezárása',
    PersonCard_StatusDisabled: 'Letiltva',
    PersonCard_StatusGuest: 'Vendég',
    PersonCard_DirectReportSingular: '{count} közvetlen beosztott',
    PersonCard_DirectReportPlural: '{count} közvetlen beosztott',
    PersonCard_TotalSuffix: ' · {total} összesen',
    PersonCard_CopyEmailTitle: 'E-mail-cím másolása',
    PersonCard_EmailCopiedAria: 'E-mail-cím másolva',
    PersonCard_ReportsTo: 'Beszámol neki',
    PersonCard_FocusOnPerson: 'Fókusz erre: {name}',
    PersonCard_FocusOrgChartOnPerson: 'Szervezeti ábra fókuszálása erre: {name}',
    PersonCard_DottedLine: 'Szaggatott vonal',
    PersonCard_DottedLineManager: 'Szaggatott vonalú vezető: {name}',
    PersonCard_DottedLineReport: 'Szaggatott vonalú beosztott: {name}',
    PersonCard_ChatButton: 'Csevegés',
    PersonCard_EmailButton: 'E-mail',
    PersonCard_FocusButton: 'Fókusz',
    PersonCard_FocusTitle: 'Szervezeti ábra fókuszálása erre a személyre',

    // ── Org node card ──
    OrgNode_ViewProfile: '{name} profiljának megtekintése',
    OrgNode_FocusOrgChartOn: 'Szervezeti ábra fókuszálása erre: {name}',
    OrgNode_Collapse: 'Összecsukás',
    OrgNode_Expand: 'Kibontás',
    OrgNode_DirectReportsSuffix: '{name} közvetlen beosztottjai',
    OrgNode_StatusDisabled: 'Letiltva',
    OrgNode_StatusGuest: 'Vendég',
    OrgNode_TotalReportsAcrossLevels: '{count} fő az összes szinten {name} alatt',

    // ── Drill view ──
    Drill_ReportingLineAria: 'Jelentési vonal',
    Drill_BackToTopTitle: 'Vissza a tetejére',
    Drill_BackToTopAria: 'Vissza a szervezeti ábra tetejére',
    Drill_GoBackTo: 'Vissza ide: {name}',
    Drill_ViewProfileTitle: 'Profil megtekintése',
    Drill_ViewProfileAria: '{name} profiljának megtekintése',
    Drill_ProfileButton: 'Profil',
    Drill_LoadingLabel: 'Betöltés...',
    Drill_DirectReports: 'Közvetlen beosztottak',
    Drill_DirectReportsOfAria: '{name} közvetlen beosztottjai',
    Drill_DirectReportsAria: 'Közvetlen beosztottak',
    Drill_ViewPersonProfile: '{name} profiljának megtekintése',
    Drill_ShowPersonReports: '{name} közvetlen beosztottjainak megjelenítése',
    Drill_NoDirectReports: 'Nincsenek közvetlen beosztottak',

    // ── Settings panel ──
    Settings_AlphabetFirstName: 'Keresztnév',
    Settings_AlphabetLastName: 'Vezetéknév',
    Settings_CardSizeSmall: 'Kicsi — kompakt, több kártya látható',
    Settings_CardSizeMedium: 'Közepes — kiegyensúlyozott',
    Settings_CardSizeLarge: 'Nagy — tágas, kevesebb kártya',
    Settings_HeaderText: 'Beállítások',
    Settings_SaveButton: 'Mentés',
    Settings_CancelButton: 'Mégse',
    Settings_DiscardButton: 'Módosítások elvetése',
    Settings_SectionDirectory: 'Címtár',
    Settings_AlphabetFilterByLabel: 'Ábécé szerinti szűrés alapja',
    Settings_CardSizeLabel: 'Kártyaméret',
    Settings_FontSizeLabel: 'Betűméret',
    Settings_SectionCardsAndFields: 'Kártyák és mezők',
    Settings_ShowOnCardsLabel: 'Megjelenítés a munkatárskártyákon:',
    Settings_EmailAddressLabel: 'E-mail-cím',
    Settings_PhoneNumberLabel: 'Telefonszám',
    Settings_DepartmentLabel: 'Osztály',
    Settings_OfficeLocationLabel: 'Iroda helye',
    Settings_SectionOrgChart: 'Szervezeti ábra',
    Settings_ManagerLevelsLabel: 'Egy személyre fókuszáláskor megjelenő vezetői szintek: {levels}',
    Settings_CompactCardsLabel: 'Kompakt kártyák',
    Settings_CompactCardsOn: 'Be — kisebb kártyák, egyszerre több látható',
    Settings_CompactCardsOff: 'Ki — normál méret',
    Settings_Hint: 'Ezek a beállítások a böngészőjében kerülnek mentésre, és csak Önre vonatkoznak. Az ábra témáját, az alapértelmezett nézetet és az elrendezést a SharePoint-rendszergazda állítja be.',
    Settings_SectionDemoData: 'Demóadatok',
    Settings_DatasetSizeLabel: 'Adathalmaz mérete',
    Settings_PeopleCountSuffix: '{count} fő',

    // ── Export (CSV / PDF) ──
    Export_ColumnName: 'Név',
    Export_ColumnJobTitle: 'Munkakör',
    Export_ColumnDepartment: 'Osztály',
    Export_ColumnOffice: 'Iroda',
    Export_ColumnEmail: 'E-mail',
    Export_ColumnPhone: 'Telefon',
    Export_ColumnManager: 'Vezető',
    Export_ColumnLevel: 'Szint',
    Export_PdfDocumentTitle: 'Szervezeti ábra',
    Export_PdfHeading: 'Szervezeti ábra',
    Export_PdfRootLabel: 'Gyökér: {name}',
  };
});
