define([], function () {
  return {
    // ── Property pane: pane header / groups ──
    PropertyPane_HeaderDescription: 'Pengaturan Smart Org Chart',
    PropertyPane_Group_General: 'Umum',
    PropertyPane_Group_Branding: 'Branding',
    PropertyPane_Group_VisualStyle: 'Gaya Visual',
    PropertyPane_Group_DataSource: 'Sumber Data',
    PropertyPane_Group_CustomAttributes: 'Atribut Kustom',
    PropertyPane_Group_UserFilters: 'Filter Pengguna',
    PropertyPane_Group_OrgChart: 'Bagan Organisasi',
    PropertyPane_Group_OrgChartFeatures: 'Fitur Bagan Organisasi',
    PropertyPane_Group_Directory: 'Direktori',
    PropertyPane_Group_Demo: 'Demo',

    // ── Property pane: General ──
    PropertyPane_DefaultView_Label: 'Tampilan Default',

    // ── Property pane: Branding ──
    PropertyPane_AppTitle_Label: 'Judul Aplikasi',
    PropertyPane_AppTitle_Placeholder: 'Bagan Organisasi Contoso',
    PropertyPane_AppTitle_Description: 'Ditampilkan di bilah header bersama nama tampilan',
    PropertyPane_LogoUrl_Label: 'URL Logo',
    PropertyPane_LogoUrl_Placeholder: 'https://contoso.sharepoint.com/sites/yoursite/SiteAssets/logo.png',
    PropertyPane_LogoUrl_Description: 'URL lengkap ke gambar PNG/SVG/JPG. Tips: buka file gambar di browser Anda lalu salin URL pada bilah alamat. URL berbagi "Salin tautan" tidak akan berfungsi.',
    PropertyPane_DirectoryLabel_Label: 'Label Tampilan Direktori Karyawan',
    PropertyPane_OrgChartLabel_Label: 'Label Tampilan Bagan Organisasi',
    PropertyPane_ViewLabel_Description: 'Biarkan kosong untuk menggunakan nama default, atau ketik "[blank]" untuk menyembunyikan label sepenuhnya.',

    // ── Property pane: Visual Style ──
    PropertyPane_ChartTheme_Label: 'Tema Bagan',
    PropertyPane_Theme_Modern: 'Modern — warna departemen pada latar putih',
    PropertyPane_Theme_Minimal: 'Minimal — datar & kontras rendah',
    PropertyPane_Theme_Corporate: 'Korporat — biru seragam',
    PropertyPane_Theme_Dark: 'Gelap — latar biru navy gelap',
    PropertyPane_Theme_Custom: 'Kustom — pilih warna Anda sendiri',
    PropertyPane_AccentColor_Label: 'Warna Aksen Kustom',
    PropertyPane_AccentColor_PickerAriaLabel: 'Pemilih warna aksen',
    PropertyPane_AccentColor_HexLabel: 'Hex',
    PropertyPane_AccentColor_HexAriaLabel: 'Nilai hex warna aksen',
    PropertyPane_AccentColor_RgbLabel: 'RGB',
    PropertyPane_AccentColor_ChannelAriaLabel: 'Saluran {name} (0 hingga 255)',
    PropertyPane_AccentColor_ContrastWithWhite: 'Kontras dengan putih: {ratio}:1 ({passes})',
    PropertyPane_AccentColor_PassesAA: 'memenuhi AA',
    PropertyPane_AccentColor_LargeTextOnly: 'hanya teks besar',
    PropertyPane_AccentColor_LowContrast: 'kontras rendah',
    PropertyPane_AccentColor_DarkTextNote: 'Teks pada warna ini akan menggunakan teks gelap agar lebih mudah dibaca.',
    PropertyPane_AccentColor_DarkerShadeNote: 'Judul dan tautan akan menggunakan corak yang lebih gelap ({hex}) agar lebih mudah dibaca.',
    PropertyPane_AccentColor_InvalidHex: '"{typed}" bukan warna hex yang valid. Gunakan nilai seperti #0078d4 atau #07d.',
    PropertyPane_DefaultFontSize_Label: 'Ukuran Font Default',
    PropertyPane_FontSize_75: '75% — Sangat Kecil',
    PropertyPane_FontSize_85: '85% — Kecil',
    PropertyPane_FontSize_100: '100% — Normal',
    PropertyPane_FontSize_115: '115% — Besar',
    PropertyPane_FontSize_130: '130% — Sangat Besar',
    PropertyPane_FontSize_150: '150% — XXL',
    PropertyPane_FontSize_175: '175% — XXXL',
    PropertyPane_DefaultLayout_Label: 'Tata Letak Bagan Organisasi Default',
    PropertyPane_Layout_Drill: 'Per Tingkat',
    PropertyPane_Layout_Vertical: 'Atas ke Bawah',
    PropertyPane_Layout_Horizontal: 'Kiri ke Kanan',

    // ── Property pane: Data Source ──
    PropertyPane_DataSource_Label: 'Sumber untuk memuat data pengguna & organisasi',
    PropertyPane_DataSource_Auto: 'Otomatis — Graph API, dengan cadangan ke SharePoint Search',
    PropertyPane_DataSource_Graph: 'Graph API — data Azure AD langsung (tanpa jeda pengindeksan)',
    PropertyPane_DataSource_Search: 'SharePoint Search — perilaku lama',
    PropertyPane_DataSource_Note: 'Graph API direkomendasikan. Data dibaca langsung dari Azure Active Directory sehingga pengguna baru dan perubahan atasan langsung terlihat. Memerlukan persetujuan izin Microsoft Graph di SharePoint App Catalog.',

    // ── Property pane: Custom Attributes ──
    PropertyPane_CustomAttributes_Note: 'Atribut kustom memerlukan Microsoft Graph (Sumber data: Graph atau Auto). SharePoint Search tidak memiliki cara umum untuk membaca atribut Entra ID.',
    PropertyPane_CustomAttributes_Heading: 'Kelola atribut kustom',
    PropertyPane_CustomAttributes_Empty: 'Belum ada atribut kustom yang dikonfigurasi.',
    PropertyPane_CustomAttributes_AddButton: '+ Tambah atribut',
    PropertyPane_CustomAttributes_MaxTooltip: 'Maksimum {max} atribut kustom',
    PropertyPane_CustomAttributes_FieldNameLabel: 'Nama atribut',
    PropertyPane_CustomAttributes_FieldPlaceholder: 'misalnya companyName',
    PropertyPane_CustomAttributes_FieldError: 'Gunakan employeeId, companyName, city, ... atau extensionAttribute1-15',
    PropertyPane_CustomAttributes_DisplayLabelLabel: 'Label tampilan',
    PropertyPane_CustomAttributes_LabelPlaceholder: 'misalnya Pusat Biaya',
    PropertyPane_CustomAttributes_RemoveTitle: 'Hapus atribut',
    PropertyPane_CustomAttributes_RemoveAriaLabel: 'Hapus atribut {ordinal}',
    PropertyPane_CustomAttributes_ShowInDirectory: 'Tampilkan di Direktori',
    PropertyPane_CustomAttributes_ShowInOrgChart: 'Tampilkan di Bagan Organisasi',

    // ── Property pane: User Filters ──
    PropertyPane_ExcludedAccounts_Label: 'Kecualikan akun',
    PropertyPane_ExcludedAccounts_Placeholder: 'conf-room, noreply, admin@, Service Account',
    PropertyPane_ExcludedAccounts_Description: 'Kata atau pola dipisahkan koma (tidak membedakan huruf besar/kecil). Pengguna mana pun yang nama tampilan, email, atau UPN-nya mengandung salah satu kata ini akan disembunyikan dari semua tampilan.',
    PropertyPane_RestrictTenant_Label: 'Hanya tampilkan pengguna tenant',
    PropertyPane_RestrictTenant_On: 'Aktif — menyembunyikan akun dengan domain email eksternal (misalnya gmail.com, hotmail.com)',
    PropertyPane_RestrictTenant_Off: 'Nonaktif — semua pengguna ditampilkan terlepas dari domain email',
    PropertyPane_HideGuest_Label: 'Sembunyikan akun tamu Azure AD',
    PropertyPane_HideGuest_On: 'Aktif — akun tamu disembunyikan',
    PropertyPane_HideGuest_Off: 'Nonaktif — akun tamu terlihat (ditandai dengan lencana Tamu)',
    PropertyPane_HideDisabled_Label: 'Sembunyikan akun yang dinonaktifkan',
    PropertyPane_HideDisabled_On: 'Aktif — akun dengan masuk yang diblokir disembunyikan',
    PropertyPane_HideDisabled_Off: 'Nonaktif — akun yang dinonaktifkan terlihat (ditandai dengan lencana Dinonaktifkan)',
    PropertyPane_HideDisabled_Note: 'Catatan: deteksi akun tamu dan akun yang dinonaktifkan memerlukan sumber data Graph API. SharePoint Search tidak mengembalikan informasi ini, sehingga kedua filter ini (dan lencana Tamu/Dinonaktifkan) tidak berpengaruh saat data berasal dari Search.',
    PropertyPane_HideNoJobTitle_Label: 'Sembunyikan akun tanpa jabatan',
    PropertyPane_HideNoJobTitle_On: 'Aktif — akun tanpa jabatan disembunyikan',
    PropertyPane_HideNoJobTitle_Off: 'Nonaktif — semua akun ditampilkan terlepas dari jabatan',
    PropertyPane_HideNoDept_Label: 'Sembunyikan akun tanpa departemen',
    PropertyPane_HideNoDept_On: 'Aktif — akun tanpa departemen disembunyikan',
    PropertyPane_HideNoDept_Off: 'Nonaktif — semua akun ditampilkan terlepas dari departemen',

    // ── Property pane: Org Chart ──
    PropertyPane_TopLevelUser_Label: 'Pengguna Tingkat Teratas (UPN atau Email)',
    PropertyPane_TopLevelUser_Placeholder: 'ceo@yourcompany.com',
    PropertyPane_TopLevelUser_Description: 'Orang yang ditampilkan di akar bagan organisasi',
    PropertyPane_LevelsBelow_Label: 'Jumlah tingkat yang dimuat di bawah akar',
    PropertyPane_DottedLine_Label: 'Atribut atasan garis putus-putus',
    PropertyPane_DottedLine_Placeholder: 'extensionAttribute10',
    PropertyPane_DottedLine_Description: 'Opsional. Nama atribut ekstensi Azure AD on-premises (extensionAttribute1-15) yang menyimpan email atau UPN atasan sekunder "garis putus-putus". Hubungan garis putus-putus akan muncul pada kartu profil. Memerlukan sumber data Graph API.',
    PropertyPane_DefaultZoom_Label: 'Zoom Bagan Organisasi Default',
    PropertyPane_Zoom_Auto: 'Default (Sesuaikan otomatis)',
    PropertyPane_Zoom_50: '50%',
    PropertyPane_Zoom_75: '75%',
    PropertyPane_Zoom_100: '100%',
    PropertyPane_Zoom_125: '125%',
    PropertyPane_Zoom_150: '150%',

    // ── Property pane: Org Chart Features ──
    PropertyPane_FeatureToggles_Note: 'Tampilkan atau sembunyikan tombol bilah alat di tampilan bagan organisasi.',
    PropertyPane_FindMe_Label: 'Tombol Temukan Saya',
    PropertyPane_LayoutToggle_Label: 'Alih tata letak (bertingkat / vertikal / horizontal)',
    PropertyPane_Stats_Label: 'Bilah statistik organisasi',
    PropertyPane_DeptFilter_Label: 'Filter departemen',
    PropertyPane_UserFilter_Label: 'Filter jenis pengguna (anggota / tamu)',
    PropertyPane_Visible: 'Terlihat',
    PropertyPane_Hidden: 'Tersembunyi',

    // ── Property pane: Directory ──
    PropertyPane_PageSize_Label: 'Jumlah maksimum karyawan per halaman',
    PropertyPane_PageSize_AriaLabel: 'Jumlah maksimum karyawan per halaman (10 hingga 200)',
    PropertyPane_PageSize_Note: 'Ukuran kartu, kolom yang ditampilkan, dan preferensi tampilan lainnya diatur per pengguna melalui ikon roda gigi Pengaturan di aplikasi.',

    // ── Property pane: Demo ──
    PropertyPane_UseDemoData_Label: 'Gunakan Data Demo',
    PropertyPane_UseDemoData_On: 'Aktif — menampilkan contoh karyawan',
    PropertyPane_UseDemoData_Off: 'Nonaktif — data Microsoft 365 langsung',

    // ── Presence status labels ──
    Presence_Available: 'Tersedia',
    Presence_Busy: 'Sibuk',
    Presence_DoNotDisturb: 'Jangan Ganggu',
    Presence_BeRightBack: 'Segera Kembali',
    Presence_Away: 'Tidak di Tempat',
    Presence_Offline: 'Offline',

    // ── Header / top bar ──
    Header_DirectoryLabel: 'Direktori Karyawan',
    Header_OrgChartLabel: 'Bagan Organisasi',
    Header_SwitchToView: 'Beralih ke {view}',
    Header_CompanyLogoAlt: 'Logo perusahaan',
    Header_RefreshingAria: 'Menyegarkan data',
    Header_RefreshAria: 'Segarkan data',
    Header_RefreshTitle: 'Segarkan data (terakhir diperbarui {when})',
    Header_NotLoadedYet: 'belum dimuat',
    Header_JustNow: 'baru saja',
    Header_MinutesAgo: '{mins} menit lalu',
    Header_HoursAgo: '{hours} jam lalu',
    Header_PreferencesTitle: 'Preferensi',
    Header_PreferencesAria: 'Buka panel preferensi',

    // ── Employee Directory ──
    Directory_LoadingLabel: 'Memuat karyawan...',
    Directory_LoadFailedFallback: 'Pastikan web part memiliki izin User.Read.All.',
    Directory_LoadFailedPrefix: 'Gagal memuat karyawan. {detail}',
    Directory_AllDepartments: 'Semua Departemen',
    Directory_AllOffices: 'Semua Kantor',
    Directory_StatusDisabled: 'Dinonaktifkan',
    Directory_StatusGuest: 'Tamu',
    Directory_PresenceStatus: 'Status: {status}',
    Directory_ChatInTeams: 'Chat di Teams',
    Directory_ChatWithInTeams: 'Chat dengan {name} di Teams',
    Directory_ManagesCount: 'Mengelola {direct}',
    Directory_ManagesCountWithTotal: 'Mengelola {direct} (total {total})',
    Directory_ReportsCountWithTotal: '{direct} (total {total})',
    Directory_ColumnName: 'Nama',
    Directory_ColumnJobTitle: 'Jabatan',
    Directory_ColumnDepartment: 'Departemen',
    Directory_ColumnOffice: 'Kantor',
    Directory_ColumnEmail: 'Email',
    Directory_ColumnPhone: 'Telepon',
    Directory_ColumnReports: 'Bawahan',
    Directory_ColumnChat: 'Chat',
    Directory_PrevPage: 'Sebelumnya',
    Directory_NextPage: 'Berikutnya',
    Directory_PreviousPageAria: 'Halaman sebelumnya',
    Directory_NextPageAria: 'Halaman berikutnya',
    Directory_SearchPlaceholder: 'Cari berdasarkan nama, jabatan, email, atau departemen...',
    Directory_SearchAria: 'Cari orang',
    Directory_FilterByDepartmentAria: 'Filter berdasarkan departemen',
    Directory_FilterByOfficeAria: 'Filter berdasarkan kantor',
    Directory_ClearSearchTitle: 'Hapus pencarian dan semua filter',
    Directory_ClearButton: 'Hapus',
    Directory_ClearFiltersButton: 'Hapus filter',
    Directory_ExportCsvTitle: 'Ekspor semua hasil yang difilter ke file CSV (dibuka di Excel)',
    Directory_ExportCsvButton: 'Ekspor CSV',
    Directory_ViewModeAria: 'Mode tampilan',
    Directory_CardViewTitle: 'Tampilan kartu',
    Directory_ListViewTitle: 'Tampilan daftar',
    Directory_AlphabetFilterAria: 'Filter abjad',
    Directory_ShowAllTitle: 'Tampilkan semua',
    Directory_OtherLettersTitle: 'Filter berdasarkan nama yang dimulai dengan angka atau karakter lain',
    Directory_FilterByLetterTitle: 'Filter berdasarkan {letter}',
    Directory_ResultCountSingular: 'orang',
    Directory_ResultCountPlural: 'orang',
    Directory_PageOf: ' · halaman {page} dari {totalPages}',
    Directory_FilterActiveSingular: '{count} filter aktif',
    Directory_FilterActivePlural: '{count} filter aktif',
    Directory_NoResults: 'Tidak ada orang yang ditemukan',
    Directory_PaginationAria: 'Navigasi halaman',

    // ── Org chart toolbar / shared chart chrome ──
    Chart_Layout_Drill: 'Per Tingkat',
    Chart_Layout_Vertical: 'Atas ke Bawah',
    Chart_Layout_Horizontal: 'Kiri ke Kanan',
    Chart_SearchPlaceholder: 'Cari orang...',
    Chart_SearchAria: 'Cari orang',
    Chart_MatchSingular: 'hasil cocok dalam struktur',
    Chart_MatchPlural: 'hasil cocok dalam struktur',
    Chart_ResultsListAria: 'Orang',
    Chart_ExpandAll: 'Perluas Semua',
    Chart_CollapseAll: 'Ciutkan Semua',
    Chart_Expanding: 'Memperluas…',
    Chart_Loading: 'Memuat…',
    Chart_FindMeTitle: 'Temukan saya di bagan organisasi',
    Chart_ViewLayoutButton: 'Tampilan',
    Chart_ViewLayoutTitle: 'Ganti tata letak tampilan',
    Chart_ViewLayoutPanelTitle: 'Tata letak tampilan',
    Chart_StatsSummaryTitle: 'Ringkasan statistik organisasi',
    Chart_FilterByDepartmentTitle: 'Filter berdasarkan departemen',
    Chart_FilterByDepartmentWithCountAria: 'Filter berdasarkan departemen ({count} dipilih)',
    Chart_FilterByDepartmentPanelTitle: 'Filter berdasarkan departemen',
    Chart_ClearAllFilters: 'Hapus semua filter',
    Chart_FilterUserTypesTitle: 'Filter jenis pengguna',
    Chart_DownloadPdfTitle: 'Unduh sebagai PDF',
    Chart_DownloadCsvTitle: 'Unduh sebagai spreadsheet CSV',
    Chart_ResetRootTitle: 'Atur ulang ke akar default',
    Chart_ViewFromPersonPlaceholder: 'Lihat dari orang…',
    Chart_ViewFromPersonAria: 'Lihat bagan organisasi dari seseorang',
    Chart_ZoomOutTitle: 'Perkecil',
    Chart_ZoomInTitle: 'Perbesar',
    Chart_ZoomResetTitle: 'Atur ulang zoom',
    Chart_ShowInChartAria: 'Tampilkan di bagan',
    Chart_ShowInChartTitle: 'Tampilkan di bagan',
    Chart_FilterMembers: 'Anggota reguler',
    Chart_FilterGuests: 'Pengguna tamu',
    Chart_FilterDisabled: 'Akun yang dinonaktifkan',
    Chart_SetupTitle: 'Siapkan Bagan Organisasi',
    Chart_SetupSubtitle: 'Masukkan email atau UPN orang di tingkat teratas untuk memulai.',
    Chart_SetupPlaceholder: 'ceo@company.com',
    Chart_SetupInputAria: 'Email atau UPN orang di tingkat teratas',
    Chart_SetupLoadButton: 'Muat',
    Chart_SetupHint: 'Anda juga dapat mengatur ini secara permanen di pengaturan web part (admin).',
    Chart_BuildingLabel: 'Membangun bagan organisasi...',
    Chart_RetryButton: 'Coba Lagi',
    Chart_NotFoundFromSetup: 'Pengguna "{identifier}" tidak ditemukan.',
    Chart_NotFoundWithSettings: 'Pengguna "{identifier}" tidak ditemukan. Periksa UPN atau email di Pengaturan.',
    Chart_LoadFailedGeneric: 'Gagal memuat bagan organisasi.{detail}',
    Chart_LoadFailedPermissions: ' Periksa izin.',
    Chart_LoadFailedForPerson: 'Gagal memuat bagan organisasi untuk orang ini.',
    Chart_FindMeNotFound: 'Akun Anda tidak ditemukan dalam organisasi ini.',
    Chart_StatPeople: 'Orang',
    Chart_StatMembers: 'Anggota',
    Chart_StatGuests: 'Tamu',
    Chart_StatDepts: 'Departemen',
    Chart_ReportingLineAria: 'Garis pelaporan',
    Chart_BackToFullOrgTitle: 'Kembali ke bagan organisasi lengkap',
    Chart_FullOrgLabel: 'Organisasi lengkap',
    Chart_FocusOnPerson: 'Fokus pada {name}',
    Chart_OrgChartAria: 'Bagan organisasi',
    Chart_ExportNote_DrillLevel: 'Tingkat saat ini (satu tingkat bawahan langsung)',
    Chart_ExportNote_PartialLevels: 'Hanya mencakup tingkat yang telah dimuat — gunakan Perluas Semua sebelum mengekspor untuk menyertakan tingkat yang lebih dalam',
    Chart_AllowPopupsForPdf: 'Mohon izinkan pop-up untuk mengekspor PDF.',

    // ── Person card ──
    PersonCard_ProfileAria: 'Profil: {name}',
    PersonCard_CloseTitle: 'Tutup',
    PersonCard_CloseAria: 'Tutup profil',
    PersonCard_StatusDisabled: 'Dinonaktifkan',
    PersonCard_StatusGuest: 'Tamu',
    PersonCard_DirectReportSingular: '{count} bawahan langsung',
    PersonCard_DirectReportPlural: '{count} bawahan langsung',
    PersonCard_TotalSuffix: ' · total {total}',
    PersonCard_CopyEmailTitle: 'Salin alamat email',
    PersonCard_EmailCopiedAria: 'Alamat email disalin',
    PersonCard_ReportsTo: 'Melapor kepada',
    PersonCard_FocusOnPerson: 'Fokus pada {name}',
    PersonCard_FocusOrgChartOnPerson: 'Fokuskan bagan organisasi pada {name}',
    PersonCard_DottedLine: 'Garis putus-putus',
    PersonCard_DottedLineManager: 'Atasan garis putus-putus: {name}',
    PersonCard_DottedLineReport: 'Bawahan garis putus-putus: {name}',
    PersonCard_ChatButton: 'Chat',
    PersonCard_EmailButton: 'Email',
    PersonCard_FocusButton: 'Fokus',
    PersonCard_FocusTitle: 'Fokuskan bagan organisasi pada orang ini',

    // ── Org node card ──
    OrgNode_ViewProfile: 'Lihat profil {name}',
    OrgNode_FocusOrgChartOn: 'Fokuskan bagan organisasi pada {name}',
    OrgNode_Collapse: 'Ciutkan',
    OrgNode_Expand: 'Perluas',
    OrgNode_DirectReportsSuffix: 'Bawahan langsung {name}',
    OrgNode_StatusDisabled: 'Dinonaktifkan',
    OrgNode_StatusGuest: 'Tamu',
    OrgNode_TotalReportsAcrossLevels: '{count} orang di semua tingkat di bawah {name}',

    // ── Drill view ──
    Drill_ReportingLineAria: 'Garis pelaporan',
    Drill_BackToTopTitle: 'Kembali ke atas',
    Drill_BackToTopAria: 'Kembali ke bagian atas bagan organisasi',
    Drill_GoBackTo: 'Kembali ke {name}',
    Drill_ViewProfileTitle: 'Lihat profil',
    Drill_ViewProfileAria: 'Lihat profil {name}',
    Drill_ProfileButton: 'Profil',
    Drill_LoadingLabel: 'Memuat...',
    Drill_DirectReports: 'Bawahan Langsung',
    Drill_DirectReportsOfAria: 'Bawahan langsung dari {name}',
    Drill_DirectReportsAria: 'Bawahan langsung',
    Drill_ViewPersonProfile: 'Lihat profil {name}',
    Drill_ShowPersonReports: 'Tampilkan bawahan langsung {name}',
    Drill_NoDirectReports: 'Tidak ada bawahan langsung',

    // ── Settings panel ──
    Settings_AlphabetFirstName: 'Nama Depan',
    Settings_AlphabetLastName: 'Nama Belakang',
    Settings_CardSizeSmall: 'Kecil — ringkas, lebih banyak kartu terlihat',
    Settings_CardSizeMedium: 'Sedang — seimbang',
    Settings_CardSizeLarge: 'Besar — lega, lebih sedikit kartu',
    Settings_HeaderText: 'Preferensi',
    Settings_SaveButton: 'Simpan',
    Settings_CancelButton: 'Batal',
    Settings_DiscardButton: 'Buang Perubahan',
    Settings_SectionDirectory: 'Direktori',
    Settings_AlphabetFilterByLabel: 'Filter Abjad Berdasarkan',
    Settings_CardSizeLabel: 'Ukuran Kartu',
    Settings_FontSizeLabel: 'Ukuran Font',
    Settings_SectionCardsAndFields: 'Kartu & Kolom',
    Settings_ShowOnCardsLabel: 'Tampilkan pada kartu karyawan:',
    Settings_EmailAddressLabel: 'Alamat email',
    Settings_PhoneNumberLabel: 'Nomor telepon',
    Settings_DepartmentLabel: 'Departemen',
    Settings_OfficeLocationLabel: 'Lokasi kantor',
    Settings_SectionOrgChart: 'Bagan Organisasi',
    Settings_ManagerLevelsLabel: 'Tingkat atasan yang ditampilkan saat memfokuskan seseorang: {levels}',
    Settings_CompactCardsLabel: 'Kartu ringkas',
    Settings_CompactCardsOn: 'Aktif — kartu lebih kecil, lebih banyak terlihat sekaligus',
    Settings_CompactCardsOff: 'Nonaktif — ukuran standar',
    Settings_Hint: 'Preferensi ini disimpan di browser Anda dan hanya berlaku untuk Anda. Tema bagan, tampilan default, dan tata letak dikonfigurasi oleh admin SharePoint Anda.',
    Settings_SectionDemoData: 'Data Demo',
    Settings_DatasetSizeLabel: 'Ukuran dataset',
    Settings_PeopleCountSuffix: '{count} orang',

    // ── Export (CSV / PDF) ──
    Export_ColumnName: 'Nama',
    Export_ColumnJobTitle: 'Jabatan',
    Export_ColumnDepartment: 'Departemen',
    Export_ColumnOffice: 'Kantor',
    Export_ColumnEmail: 'Email',
    Export_ColumnPhone: 'Telepon',
    Export_ColumnManager: 'Atasan',
    Export_ColumnLevel: 'Tingkat',
    Export_PdfDocumentTitle: 'Bagan Organisasi',
    Export_PdfHeading: 'Bagan Organisasi',
    Export_PdfRootLabel: 'Akar: {name}',
  };
});
