define([], function () {
  return {
    // ── Property pane: pane header / groups ──
    PropertyPane_HeaderDescription: 'Impostazioni di Smart Org Chart',
    PropertyPane_Group_General: 'Generale',
    PropertyPane_Group_Branding: 'Branding',
    PropertyPane_Group_VisualStyle: 'Stile visivo',
    PropertyPane_Group_DataSource: 'Origine dati',
    PropertyPane_Group_CustomAttributes: 'Attributi personalizzati',
    PropertyPane_Group_UserFilters: 'Filtri utente',
    PropertyPane_Group_OrgChart: 'Organigramma',
    PropertyPane_Group_OrgChartFeatures: "Funzionalità dell'organigramma",
    PropertyPane_Group_Directory: 'Elenco',
    PropertyPane_Group_Demo: 'Demo',

    // ── Property pane: General ──
    PropertyPane_DefaultView_Label: 'Visualizzazione predefinita',

    // ── Property pane: Branding ──
    PropertyPane_AppTitle_Label: "Titolo dell'app",
    PropertyPane_AppTitle_Placeholder: 'Contoso Org Chart',
    PropertyPane_AppTitle_Description: 'Visualizzato nella barra del titolo accanto al nome della visualizzazione',
    PropertyPane_LogoUrl_Label: 'URL del logo',
    PropertyPane_LogoUrl_Placeholder: 'https://contoso.sharepoint.com/sites/yoursite/SiteAssets/logo.png',
    PropertyPane_LogoUrl_Description: "URL completo di un'immagine PNG/SVG/JPG. Suggerimento: apri il file immagine nel browser e copia l'URL dalla barra degli indirizzi. Gli URL di condivisione \"Copia collegamento\" non funzionano.",
    PropertyPane_DirectoryLabel_Label: 'Etichetta per la visualizzazione "Elenco dipendenti"',
    PropertyPane_OrgChartLabel_Label: 'Etichetta per la visualizzazione "Organigramma"',
    PropertyPane_ViewLabel_Description: 'Lascia vuoto per utilizzare il nome predefinito, oppure digita "[blank]" per nascondere completamente l\'etichetta.',

    // ── Property pane: Visual Style ──
    PropertyPane_ChartTheme_Label: 'Tema del grafico',
    PropertyPane_Theme_Modern: 'Moderno — colori dei reparti su sfondo bianco',
    PropertyPane_Theme_Minimal: 'Minimal — piatto e a basso contrasto',
    PropertyPane_Theme_Corporate: 'Corporate — blu uniforme',
    PropertyPane_Theme_Dark: 'Scuro — sfondo blu navy scuro',
    PropertyPane_Theme_Custom: 'Personalizzato — scegli il tuo colore',
    PropertyPane_AccentColor_Label: 'Colore di accento personalizzato',
    PropertyPane_AccentColor_PickerAriaLabel: 'Selettore del colore di accento',
    PropertyPane_AccentColor_HexLabel: 'Hex',
    PropertyPane_AccentColor_HexAriaLabel: 'Valore esadecimale del colore di accento',
    PropertyPane_AccentColor_RgbLabel: 'RGB',
    PropertyPane_AccentColor_ChannelAriaLabel: 'Canale {name} (da 0 a 255)',
    PropertyPane_AccentColor_ContrastWithWhite: 'Contrasto con il bianco: {ratio}:1 ({passes})',
    PropertyPane_AccentColor_PassesAA: 'conforme AA',
    PropertyPane_AccentColor_LargeTextOnly: 'solo testo grande',
    PropertyPane_AccentColor_LowContrast: 'basso contrasto',
    PropertyPane_AccentColor_DarkTextNote: 'Il testo su questo colore verrà visualizzato in scuro per una migliore leggibilità.',
    PropertyPane_AccentColor_DarkerShadeNote: 'Titoli e link utilizzeranno una tonalità più scura ({hex}) per una migliore leggibilità.',
    PropertyPane_AccentColor_InvalidHex: '"{typed}" non è un colore esadecimale valido. Usa un valore come #0078d4 o #07d.',
    PropertyPane_DefaultFontSize_Label: 'Dimensione carattere predefinita',
    PropertyPane_FontSize_75: '75% — Molto piccolo',
    PropertyPane_FontSize_85: '85% — Piccolo',
    PropertyPane_FontSize_100: '100% — Normale',
    PropertyPane_FontSize_115: '115% — Grande',
    PropertyPane_FontSize_130: '130% — Molto grande',
    PropertyPane_FontSize_150: '150% — XXL',
    PropertyPane_FontSize_175: '175% — XXXL',
    PropertyPane_DefaultLayout_Label: "Layout predefinito dell'organigramma",
    PropertyPane_Layout_Drill: 'Drill-down',
    PropertyPane_Layout_Vertical: "Dall'alto verso il basso",
    PropertyPane_Layout_Horizontal: 'Da sinistra a destra',

    // ── Property pane: Data Source ──
    PropertyPane_DataSource_Label: 'Da dove caricare i dati di utenti e organizzazione',
    PropertyPane_DataSource_Auto: 'Automatico — Graph API, con fallback a Ricerca di SharePoint',
    PropertyPane_DataSource_Graph: 'Graph API — dati di Azure AD in tempo reale (nessun ritardo di indicizzazione)',
    PropertyPane_DataSource_Search: 'Ricerca di SharePoint — comportamento precedente',
    PropertyPane_DataSource_Note: "Graph API è consigliata. Legge direttamente da Azure Active Directory, quindi i nuovi utenti e le modifiche ai responsabili vengono visualizzati immediatamente. Richiede l'approvazione delle autorizzazioni di Microsoft Graph nel catalogo app di SharePoint.",

    // ── Property pane: Custom Attributes ──
    PropertyPane_CustomAttributes_Note: 'Gli attributi personalizzati richiedono Microsoft Graph (Origine dati: Graph o Automatico). La Ricerca di SharePoint non offre un metodo generico per leggere gli attributi di Entra ID.',
    PropertyPane_CustomAttributes_Heading: 'Gestisci attributi personalizzati',
    PropertyPane_CustomAttributes_Empty: 'Nessun attributo personalizzato configurato.',
    PropertyPane_CustomAttributes_AddButton: '+ Aggiungi attributo',
    PropertyPane_CustomAttributes_MaxTooltip: 'Massimo {max} attributi personalizzati',
    PropertyPane_CustomAttributes_FieldNameLabel: 'Nome attributo',
    PropertyPane_CustomAttributes_FieldPlaceholder: 'ad es. companyName',
    PropertyPane_CustomAttributes_FieldError: 'Usa employeeId, companyName, city, ... oppure extensionAttribute1-15',
    PropertyPane_CustomAttributes_DisplayLabelLabel: 'Etichetta visualizzata',
    PropertyPane_CustomAttributes_LabelPlaceholder: 'ad es. Centro di costo',
    PropertyPane_CustomAttributes_RemoveTitle: 'Rimuovi attributo',
    PropertyPane_CustomAttributes_RemoveAriaLabel: 'Rimuovi attributo {ordinal}',
    PropertyPane_CustomAttributes_ShowInDirectory: "Mostra nell'elenco",
    PropertyPane_CustomAttributes_ShowInOrgChart: "Mostra nell'organigramma",

    // ── Property pane: User Filters ──
    PropertyPane_ExcludedAccounts_Label: 'Escludi account',
    PropertyPane_ExcludedAccounts_Placeholder: 'conf-room, noreply, admin@, Account di servizio',
    PropertyPane_ExcludedAccounts_Description: 'Parole o pattern separati da virgola (senza distinzione tra maiuscole e minuscole). Qualsiasi utente il cui nome visualizzato, indirizzo e-mail o UPN contenga uno di questi verrà nascosto in tutte le visualizzazioni.',
    PropertyPane_RestrictTenant_Label: 'Mostra solo utenti del tenant',
    PropertyPane_RestrictTenant_On: 'Attivato — nasconde gli account con domini e-mail esterni (ad es. gmail.com, hotmail.com)',
    PropertyPane_RestrictTenant_Off: 'Disattivato — tutti gli utenti vengono mostrati indipendentemente dal dominio e-mail',
    PropertyPane_HideGuest_Label: 'Nascondi gli account guest di Azure AD',
    PropertyPane_HideGuest_On: 'Attivato — gli account guest sono nascosti',
    PropertyPane_HideGuest_Off: "Disattivato — gli account guest sono visibili (contrassegnati con l'etichetta Guest)",
    PropertyPane_HideDisabled_Label: 'Nascondi account disabilitati',
    PropertyPane_HideDisabled_On: 'Attivato — gli account con accesso bloccato sono nascosti',
    PropertyPane_HideDisabled_Off: "Disattivato — gli account disabilitati sono visibili (contrassegnati con l'etichetta Disabled)",
    PropertyPane_HideDisabled_Note: "Nota: il rilevamento degli account guest e disabilitati richiede l'origine dati Graph API. La Ricerca di SharePoint non restituisce queste informazioni, pertanto questi due filtri (e le etichette Guest/Disabled) non hanno alcun effetto quando i dati provengono dalla Ricerca.",
    PropertyPane_HideNoJobTitle_Label: 'Nascondi account senza qualifica',
    PropertyPane_HideNoJobTitle_On: 'Attivato — gli account senza qualifica sono nascosti',
    PropertyPane_HideNoJobTitle_Off: 'Disattivato — tutti gli account vengono mostrati indipendentemente dalla qualifica',
    PropertyPane_HideNoDept_Label: 'Nascondi account senza reparto',
    PropertyPane_HideNoDept_On: 'Attivato — gli account senza reparto sono nascosti',
    PropertyPane_HideNoDept_Off: 'Disattivato — tutti gli account vengono mostrati indipendentemente dal reparto',

    // ── Property pane: Org Chart ──
    PropertyPane_TopLevelUser_Label: 'Utente di primo livello (UPN o e-mail)',
    PropertyPane_TopLevelUser_Placeholder: 'ceo@yourcompany.com',
    PropertyPane_TopLevelUser_Description: "La persona visualizzata alla radice dell'organigramma",
    PropertyPane_LevelsBelow_Label: 'Livelli da caricare sotto la radice',
    PropertyPane_DottedLine_Label: 'Attributo per il responsabile con linea tratteggiata',
    PropertyPane_DottedLine_Placeholder: 'extensionAttribute10',
    PropertyPane_DottedLine_Description: "Facoltativo. Nome dell'attributo di estensione locale di Azure AD (extensionAttribute1-15) che memorizza l'indirizzo e-mail o l'UPN di un responsabile secondario con \"linea tratteggiata\". Le relazioni con linea tratteggiata vengono visualizzate sulle schede profilo. Richiede l'origine dati Graph API.",
    PropertyPane_DefaultZoom_Label: "Zoom predefinito dell'organigramma",
    PropertyPane_Zoom_Auto: 'Predefinito (adattamento automatico)',
    PropertyPane_Zoom_50: '50%',
    PropertyPane_Zoom_75: '75%',
    PropertyPane_Zoom_100: '100%',
    PropertyPane_Zoom_125: '125%',
    PropertyPane_Zoom_150: '150%',

    // ── Property pane: Org Chart Features ──
    PropertyPane_FeatureToggles_Note: 'Mostra o nascondi i pulsanti della barra degli strumenti nella visualizzazione organigramma.',
    PropertyPane_FindMe_Label: 'Pulsante "Trova me"',
    PropertyPane_LayoutToggle_Label: 'Selettore layout (drill-down/verticale/orizzontale)',
    PropertyPane_Stats_Label: "Barra delle statistiche dell'organigramma",
    PropertyPane_DeptFilter_Label: 'Filtro reparto',
    PropertyPane_UserFilter_Label: 'Filtro tipo utente (membri/guest)',
    PropertyPane_Visible: 'Visibile',
    PropertyPane_Hidden: 'Nascosto',

    // ── Property pane: Directory ──
    PropertyPane_PageSize_Label: 'Numero massimo di dipendenti per pagina',
    PropertyPane_PageSize_AriaLabel: 'Numero massimo di dipendenti per pagina (da 10 a 200)',
    PropertyPane_PageSize_Note: "Le dimensioni delle schede, i campi visibili e altre preferenze di visualizzazione vengono impostati per singolo utente tramite l'icona delle impostazioni nell'app.",

    // ── Property pane: Demo ──
    PropertyPane_UseDemoData_Label: 'Usa dati demo',
    PropertyPane_UseDemoData_On: 'Attivato — vengono mostrati dipendenti di esempio',
    PropertyPane_UseDemoData_Off: 'Disattivato — dati in tempo reale di Microsoft 365',

    // ── Presence status labels ──
    Presence_Available: 'Disponibile',
    Presence_Busy: 'Occupato',
    Presence_DoNotDisturb: 'Non disturbare',
    Presence_BeRightBack: 'Torno subito',
    Presence_Away: 'Assente',
    Presence_Offline: 'Offline',

    // ── Header / top bar ──
    Header_DirectoryLabel: 'Elenco dipendenti',
    Header_OrgChartLabel: 'Organigramma',
    Header_SwitchToView: 'Passa a {view}',
    Header_CompanyLogoAlt: 'Logo aziendale',
    Header_RefreshingAria: 'Aggiornamento dati in corso',
    Header_RefreshAria: 'Aggiorna dati',
    Header_RefreshTitle: 'Aggiorna dati (ultimo aggiornamento: {when})',
    Header_NotLoadedYet: 'non ancora caricato',
    Header_JustNow: 'proprio ora',
    Header_MinutesAgo: '{mins} min fa',
    Header_HoursAgo: '{hours} ore fa',
    Header_PreferencesTitle: 'Preferenze',
    Header_PreferencesAria: 'Apri il pannello delle preferenze',

    // ── Employee Directory ──
    Directory_LoadingLabel: 'Caricamento dipendenti in corso...',
    Directory_LoadFailedFallback: "Verifica che il web part disponga dell'autorizzazione User.Read.All.",
    Directory_LoadFailedPrefix: 'Impossibile caricare i dipendenti. {detail}',
    Directory_AllDepartments: 'Tutti i reparti',
    Directory_AllOffices: 'Tutte le sedi',
    Directory_StatusDisabled: 'Disabilitato',
    Directory_StatusGuest: 'Guest',
    Directory_PresenceStatus: 'Stato: {status}',
    Directory_ChatInTeams: 'Chat in Teams',
    Directory_ChatWithInTeams: 'Chatta con {name} in Teams',
    Directory_ManagesCount: 'Gestisce {direct}',
    Directory_ManagesCountWithTotal: 'Gestisce {direct} ({total} in totale)',
    Directory_ReportsCountWithTotal: '{direct} ({total} in totale)',
    Directory_ColumnName: 'Nome',
    Directory_ColumnJobTitle: 'Qualifica',
    Directory_ColumnDepartment: 'Reparto',
    Directory_ColumnOffice: 'Sede',
    Directory_ColumnEmail: 'E-mail',
    Directory_ColumnPhone: 'Telefono',
    Directory_ColumnReports: 'Riporti',
    Directory_ColumnChat: 'Chat',
    Directory_PrevPage: 'Indietro',
    Directory_NextPage: 'Avanti',
    Directory_PreviousPageAria: 'Pagina precedente',
    Directory_NextPageAria: 'Pagina successiva',
    Directory_SearchPlaceholder: 'Cerca per nome, qualifica, e-mail o reparto...',
    Directory_SearchAria: 'Cerca persone',
    Directory_FilterByDepartmentAria: 'Filtra per reparto',
    Directory_FilterByOfficeAria: 'Filtra per sede',
    Directory_ClearSearchTitle: 'Cancella la ricerca e tutti i filtri',
    Directory_ClearButton: 'Cancella',
    Directory_ClearFiltersButton: 'Cancella filtri',
    Directory_ExportCsvTitle: 'Esporta tutti i risultati filtrati in un file CSV (si apre in Excel)',
    Directory_ExportCsvButton: 'Esporta CSV',
    Directory_ViewModeAria: 'Modalità di visualizzazione',
    Directory_CardViewTitle: 'Visualizzazione a schede',
    Directory_ListViewTitle: 'Visualizzazione a elenco',
    Directory_AlphabetFilterAria: 'Filtro alfabetico',
    Directory_ShowAllTitle: 'Mostra tutti',
    Directory_OtherLettersTitle: 'Filtra per nomi che iniziano con un numero o un altro carattere',
    Directory_FilterByLetterTitle: 'Filtra per {letter}',
    Directory_ResultCountSingular: 'persona',
    Directory_ResultCountPlural: 'persone',
    Directory_PageOf: ' · pagina {page} di {totalPages}',
    Directory_FilterActiveSingular: '{count} filtro attivo',
    Directory_FilterActivePlural: '{count} filtri attivi',
    Directory_NoResults: 'Nessuna persona trovata',
    Directory_PaginationAria: 'Paginazione',

    // ── Org chart toolbar / shared chart chrome ──
    Chart_Layout_Drill: 'Drill-down',
    Chart_Layout_Vertical: "Dall'alto verso il basso",
    Chart_Layout_Horizontal: 'Da sinistra a destra',
    Chart_SearchPlaceholder: 'Cerca persone...',
    Chart_SearchAria: 'Cerca persone',
    Chart_MatchSingular: "corrispondenza nell'albero",
    Chart_MatchPlural: "corrispondenze nell'albero",
    Chart_ResultsListAria: 'Persone',
    Chart_ExpandAll: 'Espandi tutto',
    Chart_CollapseAll: 'Comprimi tutto',
    Chart_Expanding: 'Espansione in corso…',
    Chart_Loading: 'Caricamento in corso…',
    Chart_FindMeTitle: "Trovami nell'organigramma",
    Chart_ViewLayoutButton: 'Visualizza',
    Chart_ViewLayoutTitle: 'Cambia layout di visualizzazione',
    Chart_ViewLayoutPanelTitle: 'Layout di visualizzazione',
    Chart_StatsSummaryTitle: 'Riepilogo statistiche organizzazione',
    Chart_FilterByDepartmentTitle: 'Filtra per reparto',
    Chart_FilterByDepartmentWithCountAria: 'Filtra per reparto ({count} selezionati)',
    Chart_FilterByDepartmentPanelTitle: 'Filtra per reparto',
    Chart_ClearAllFilters: 'Cancella tutti i filtri',
    Chart_FilterUserTypesTitle: 'Filtra tipi di utente',
    Chart_DownloadPdfTitle: 'Scarica come PDF',
    Chart_DownloadCsvTitle: 'Scarica come foglio di calcolo CSV',
    Chart_ResetRootTitle: 'Ripristina la radice predefinita',
    Chart_ViewFromPersonPlaceholder: 'Visualizza a partire da…',
    Chart_ViewFromPersonAria: "Visualizza l'organigramma a partire da una persona",
    Chart_ZoomOutTitle: 'Riduci zoom',
    Chart_ZoomInTitle: 'Aumenta zoom',
    Chart_ZoomResetTitle: 'Ripristina zoom',
    Chart_ShowInChartAria: "Mostra nell'organigramma",
    Chart_ShowInChartTitle: "Mostra nell'organigramma",
    Chart_FilterMembers: 'Membri regolari',
    Chart_FilterGuests: 'Utenti guest',
    Chart_FilterDisabled: 'Account disabilitati',
    Chart_SetupTitle: "Configura l'organigramma",
    Chart_SetupSubtitle: 'Inserisci l’indirizzo e-mail o l’UPN della persona di primo livello per iniziare.',
    Chart_SetupPlaceholder: 'ceo@company.com',
    Chart_SetupInputAria: 'Indirizzo e-mail o UPN della persona di primo livello',
    Chart_SetupLoadButton: 'Carica',
    Chart_SetupHint: 'Puoi anche impostarlo in modo permanente nelle impostazioni del web part (amministratore).',
    Chart_BuildingLabel: "Creazione dell'organigramma in corso...",
    Chart_RetryButton: 'Riprova',
    Chart_NotFoundFromSetup: 'Utente "{identifier}" non trovato.',
    Chart_NotFoundWithSettings: 'Utente "{identifier}" non trovato. Verifica l’UPN o l’indirizzo e-mail nelle impostazioni.',
    Chart_LoadFailedGeneric: "Impossibile caricare l'organigramma.{detail}",
    Chart_LoadFailedPermissions: ' Verifica le autorizzazioni.',
    Chart_LoadFailedForPerson: "Impossibile caricare l'organigramma per questa persona.",
    Chart_FindMeNotFound: 'Il tuo account non è stato trovato in questa organizzazione.',
    Chart_StatPeople: 'Persone',
    Chart_StatMembers: 'Membri',
    Chart_StatGuests: 'Guest',
    Chart_StatDepts: 'Reparti',
    Chart_ReportingLineAria: 'Linea gerarchica',
    Chart_BackToFullOrgTitle: "Torna all'organigramma completo",
    Chart_FullOrgLabel: 'Organizzazione completa',
    Chart_FocusOnPerson: 'Centra su {name}',
    Chart_OrgChartAria: 'Organigramma',
    Chart_ExportNote_DrillLevel: 'Livello di drill-down corrente (un livello di riporti diretti)',
    Chart_ExportNote_PartialLevels: 'Include solo i livelli caricati — usa "Espandi tutto" prima di esportare per includere i livelli più profondi',
    Chart_AllowPopupsForPdf: 'Consenti i popup per esportare il PDF.',

    // ── Person card ──
    PersonCard_ProfileAria: 'Profilo: {name}',
    PersonCard_CloseTitle: 'Chiudi',
    PersonCard_CloseAria: 'Chiudi profilo',
    PersonCard_StatusDisabled: 'Disabilitato',
    PersonCard_StatusGuest: 'Guest',
    PersonCard_DirectReportSingular: '{count} riporto diretto',
    PersonCard_DirectReportPlural: '{count} riporti diretti',
    PersonCard_TotalSuffix: ' · {total} in totale',
    PersonCard_CopyEmailTitle: 'Copia indirizzo e-mail',
    PersonCard_EmailCopiedAria: 'Indirizzo e-mail copiato',
    PersonCard_ReportsTo: 'Riporta a',
    PersonCard_FocusOnPerson: 'Centra su {name}',
    PersonCard_FocusOrgChartOnPerson: "Centra l'organigramma su {name}",
    PersonCard_DottedLine: 'Linea tratteggiata',
    PersonCard_DottedLineManager: 'Responsabile con linea tratteggiata: {name}',
    PersonCard_DottedLineReport: 'Riporto con linea tratteggiata: {name}',
    PersonCard_ChatButton: 'Chat',
    PersonCard_EmailButton: 'E-mail',
    PersonCard_FocusButton: 'Centra',
    PersonCard_FocusTitle: "Centra l'organigramma su questa persona",

    // ── Org node card ──
    OrgNode_ViewProfile: 'Visualizza il profilo di {name}',
    OrgNode_FocusOrgChartOn: "Centra l'organigramma su {name}",
    OrgNode_Collapse: 'Comprimi',
    OrgNode_Expand: 'Espandi',
    OrgNode_DirectReportsSuffix: 'Riporti diretti di {name}',
    OrgNode_StatusDisabled: 'Disabilitato',
    OrgNode_StatusGuest: 'Guest',
    OrgNode_TotalReportsAcrossLevels: '{count} persone su tutti i livelli sotto {name}',

    // ── Drill view ──
    Drill_ReportingLineAria: 'Linea gerarchica',
    Drill_BackToTopTitle: 'Torna in cima',
    Drill_BackToTopAria: "Torna all'inizio dell'organigramma",
    Drill_GoBackTo: 'Torna a {name}',
    Drill_ViewProfileTitle: 'Visualizza profilo',
    Drill_ViewProfileAria: 'Visualizza il profilo di {name}',
    Drill_ProfileButton: 'Profilo',
    Drill_LoadingLabel: 'Caricamento...',
    Drill_DirectReports: 'Riporti diretti',
    Drill_DirectReportsOfAria: 'Riporti diretti di {name}',
    Drill_DirectReportsAria: 'Riporti diretti',
    Drill_ViewPersonProfile: 'Visualizza il profilo di {name}',
    Drill_ShowPersonReports: 'Mostra i riporti diretti di {name}',
    Drill_NoDirectReports: 'Nessun riporto diretto',

    // ── Settings panel ──
    Settings_AlphabetFirstName: 'Nome',
    Settings_AlphabetLastName: 'Cognome',
    Settings_CardSizeSmall: 'Piccolo — compatto, più schede visibili',
    Settings_CardSizeMedium: 'Medio — bilanciato',
    Settings_CardSizeLarge: 'Grande — spazioso, meno schede',
    Settings_HeaderText: 'Preferenze',
    Settings_SaveButton: 'Salva',
    Settings_CancelButton: 'Annulla',
    Settings_DiscardButton: 'Ignora modifiche',
    Settings_SectionDirectory: 'Elenco',
    Settings_AlphabetFilterByLabel: 'Filtro alfabetico per',
    Settings_CardSizeLabel: 'Dimensione scheda',
    Settings_FontSizeLabel: 'Dimensione carattere',
    Settings_SectionCardsAndFields: 'Schede e campi',
    Settings_ShowOnCardsLabel: 'Mostra sulle schede dei dipendenti:',
    Settings_EmailAddressLabel: 'Indirizzo e-mail',
    Settings_PhoneNumberLabel: 'Numero di telefono',
    Settings_DepartmentLabel: 'Reparto',
    Settings_OfficeLocationLabel: 'Sede',
    Settings_SectionOrgChart: 'Organigramma',
    Settings_ManagerLevelsLabel: 'Livelli di responsabili mostrati quando si centra su una persona: {levels}',
    Settings_CompactCardsLabel: 'Schede compatte',
    Settings_CompactCardsOn: 'Attivato — schede più piccole, più visibili contemporaneamente',
    Settings_CompactCardsOff: 'Disattivato — dimensione standard',
    Settings_Hint: "Queste preferenze vengono salvate nel browser e si applicano solo a te. Il tema del grafico, la visualizzazione predefinita e il layout sono configurati dall'amministratore di SharePoint.",
    Settings_SectionDemoData: 'Dati demo',
    Settings_DatasetSizeLabel: 'Dimensione del set di dati',
    Settings_PeopleCountSuffix: '{count} persone',

    // ── Export (CSV / PDF) ──
    Export_ColumnName: 'Nome',
    Export_ColumnJobTitle: 'Qualifica',
    Export_ColumnDepartment: 'Reparto',
    Export_ColumnOffice: 'Sede',
    Export_ColumnEmail: 'E-mail',
    Export_ColumnPhone: 'Telefono',
    Export_ColumnManager: 'Responsabile',
    Export_ColumnLevel: 'Livello',
    Export_PdfDocumentTitle: 'Organigramma',
    Export_PdfHeading: 'Organigramma aziendale',
    Export_PdfRootLabel: 'Radice: {name}',
  };
});
