define([], function () {
  return {
    // ── Property pane: pane header / groups ──
    PropertyPane_HeaderDescription: 'スマート組織図の設定',
    PropertyPane_Group_General: '全般',
    PropertyPane_Group_Branding: 'ブランディング',
    PropertyPane_Group_VisualStyle: 'ビジュアル スタイル',
    PropertyPane_Group_DataSource: 'データ ソース',
    PropertyPane_Group_CustomAttributes: 'カスタム属性',
    PropertyPane_Group_UserFilters: 'ユーザー フィルター',
    PropertyPane_Group_OrgChart: '組織図',
    PropertyPane_Group_OrgChartFeatures: '組織図の機能',
    PropertyPane_Group_Directory: 'ディレクトリ',
    PropertyPane_Group_Demo: 'デモ',

    // ── Property pane: General ──
    PropertyPane_DefaultView_Label: '既定のビュー',

    // ── Property pane: Branding ──
    PropertyPane_AppTitle_Label: 'アプリのタイトル',
    PropertyPane_AppTitle_Placeholder: 'Contoso 組織図',
    PropertyPane_AppTitle_Description: 'ビュー名と共にヘッダー バーに表示されます',
    PropertyPane_LogoUrl_Label: 'ロゴの URL',
    PropertyPane_LogoUrl_Placeholder: 'https://contoso.sharepoint.com/sites/yoursite/SiteAssets/logo.png',
    PropertyPane_LogoUrl_Description: 'PNG/SVG/JPG 画像への完全な URL。ヒント: 画像ファイルをブラウザーで開き、アドレス バーの URL をコピーしてください。「リンクのコピー」で生成される共有 URL は使用できません。',
    PropertyPane_DirectoryLabel_Label: '[従業員ディレクトリ] ビューのラベル',
    PropertyPane_OrgChartLabel_Label: '[組織図] ビューのラベル',
    PropertyPane_ViewLabel_Description: '既定の名前を使用する場合は空白のままにしてください。ラベルを完全に非表示にするには「[blank]」と入力します。',

    // ── Property pane: Visual Style ──
    PropertyPane_ChartTheme_Label: '図のテーマ',
    PropertyPane_Theme_Modern: 'モダン - 白背景に部署ごとの配色',
    PropertyPane_Theme_Minimal: 'ミニマル - フラットで低コントラスト',
    PropertyPane_Theme_Corporate: 'コーポレート - 統一されたブルー',
    PropertyPane_Theme_Dark: 'ダーク - ダーク ネイビーの背景',
    PropertyPane_Theme_Custom: 'カスタム - 任意の色を選択',
    PropertyPane_AccentColor_Label: 'カスタム アクセント カラー',
    PropertyPane_AccentColor_PickerAriaLabel: 'アクセント カラー ピッカー',
    PropertyPane_AccentColor_HexLabel: '16 進数',
    PropertyPane_AccentColor_HexAriaLabel: 'アクセント カラーの 16 進数値',
    PropertyPane_AccentColor_RgbLabel: 'RGB',
    PropertyPane_AccentColor_ChannelAriaLabel: '{name} チャネル (0 ～ 255)',
    PropertyPane_AccentColor_ContrastWithWhite: '白とのコントラスト比: {ratio}:1 ({passes})',
    PropertyPane_AccentColor_PassesAA: 'AA 基準に適合',
    PropertyPane_AccentColor_LargeTextOnly: '大きな文字のみ',
    PropertyPane_AccentColor_LowContrast: 'コントラストが低い',
    PropertyPane_AccentColor_DarkTextNote: '読みやすさのため、この色の上のテキストは濃色で表示されます。',
    PropertyPane_AccentColor_DarkerShadeNote: '読みやすさのため、タイトルとリンクにはより濃い色調 ({hex}) が使用されます。',
    PropertyPane_AccentColor_InvalidHex: '"{typed}" は有効な 16 進数カラーではありません。#0078d4 や #07d のような値を使用してください。',
    PropertyPane_DefaultFontSize_Label: '既定のフォント サイズ',
    PropertyPane_FontSize_75: '75% - 極小',
    PropertyPane_FontSize_85: '85% - 小',
    PropertyPane_FontSize_100: '100% - 標準',
    PropertyPane_FontSize_115: '115% - 大',
    PropertyPane_FontSize_130: '130% - 特大',
    PropertyPane_FontSize_150: '150% - XXL',
    PropertyPane_FontSize_175: '175% - XXXL',
    PropertyPane_DefaultLayout_Label: '既定の組織図レイアウト',
    PropertyPane_Layout_Drill: 'ドリルダウン',
    PropertyPane_Layout_Vertical: 'トップダウン',
    PropertyPane_Layout_Horizontal: '左から右',

    // ── Property pane: Data Source ──
    PropertyPane_DataSource_Label: 'ユーザーおよび組織データの読み込み元',
    PropertyPane_DataSource_Auto: '自動 - Graph API を使用し、失敗した場合は SharePoint 検索にフォールバック',
    PropertyPane_DataSource_Graph: 'Graph API - リアルタイムの Azure AD データ (インデックス作成の遅延なし)',
    PropertyPane_DataSource_Search: 'SharePoint 検索 - 従来の動作',
    PropertyPane_DataSource_Note: 'Graph API の使用をお勧めします。Azure Active Directory から直接データを読み取るため、新しいユーザーやマネージャーの変更が即座に反映されます。SharePoint アプリ カタログで Microsoft Graph のアクセス許可を承認する必要があります。',

    // ── Property pane: Custom Attributes ──
    PropertyPane_CustomAttributes_Note: 'カスタム属性を使用するには Microsoft Graph が必要です (データ ソース: Graph または自動)。SharePoint 検索には Microsoft Entra ID 属性を読み取る汎用的な方法がありません。',
    PropertyPane_CustomAttributes_Heading: 'カスタム属性の管理',
    PropertyPane_CustomAttributes_Empty: 'カスタム属性が構成されていません。',
    PropertyPane_CustomAttributes_AddButton: '+ 属性を追加',
    PropertyPane_CustomAttributes_MaxTooltip: 'カスタム属性は最大 {max} 個までです',
    PropertyPane_CustomAttributes_FieldNameLabel: '属性名',
    PropertyPane_CustomAttributes_FieldPlaceholder: '例: companyName',
    PropertyPane_CustomAttributes_FieldError: 'employeeId、companyName、city などか、extensionAttribute1-15 を使用してください',
    PropertyPane_CustomAttributes_DisplayLabelLabel: '表示ラベル',
    PropertyPane_CustomAttributes_LabelPlaceholder: '例: コスト センター',
    PropertyPane_CustomAttributes_RemoveTitle: '属性を削除',
    PropertyPane_CustomAttributes_RemoveAriaLabel: '属性 {ordinal} を削除',
    PropertyPane_CustomAttributes_ShowInDirectory: 'ディレクトリに表示',
    PropertyPane_CustomAttributes_ShowInOrgChart: '組織図に表示',

    // ── Property pane: User Filters ──
    PropertyPane_ExcludedAccounts_Label: '除外するアカウント',
    PropertyPane_ExcludedAccounts_Placeholder: 'conf-room, noreply, admin@, Service Account',
    PropertyPane_ExcludedAccounts_Description: 'コンマ区切りの単語またはパターン (大文字と小文字は区別されません)。表示名、メール アドレス、または UPN にこれらのいずれかを含むユーザーは、すべてのビューで非表示になります。',
    PropertyPane_RestrictTenant_Label: 'テナント ユーザーのみを表示',
    PropertyPane_RestrictTenant_On: 'オン - 外部のメール ドメイン (gmail.com、hotmail.com など) を使用するアカウントを非表示にします',
    PropertyPane_RestrictTenant_Off: 'オフ - メール ドメインに関係なくすべてのユーザーを表示します',
    PropertyPane_HideGuest_Label: 'Azure AD ゲスト アカウントを非表示にする',
    PropertyPane_HideGuest_On: 'オン - ゲスト アカウントを非表示にします',
    PropertyPane_HideGuest_Off: 'オフ - ゲスト アカウントを表示します ([ゲスト] バッジ付き)',
    PropertyPane_HideDisabled_Label: '無効なアカウントを非表示にする',
    PropertyPane_HideDisabled_On: 'オン - サインインがブロックされたアカウントを非表示にします',
    PropertyPane_HideDisabled_Off: 'オフ - 無効なアカウントを表示します ([無効] バッジ付き)',
    PropertyPane_HideDisabled_Note: '注: ゲスト アカウントと無効なアカウントの検出には Graph API データ ソースが必要です。SharePoint 検索ではこの情報が返されないため、データが検索から取得される場合、これら 2 つのフィルター (および [ゲスト]/[無効] バッジ) は機能しません。',
    PropertyPane_HideNoJobTitle_Label: '役職が未設定のアカウントを非表示にする',
    PropertyPane_HideNoJobTitle_On: 'オン - 役職が未設定のアカウントを非表示にします',
    PropertyPane_HideNoJobTitle_Off: 'オフ - 役職の有無にかかわらずすべてのアカウントを表示します',
    PropertyPane_HideNoDept_Label: '部署が未設定のアカウントを非表示にする',
    PropertyPane_HideNoDept_On: 'オン - 部署が未設定のアカウントを非表示にします',
    PropertyPane_HideNoDept_Off: 'オフ - 部署の有無にかかわらずすべてのアカウントを表示します',

    // ── Property pane: Org Chart ──
    PropertyPane_TopLevelUser_Label: '最上位ユーザー (UPN またはメール アドレス)',
    PropertyPane_TopLevelUser_Placeholder: 'ceo@yourcompany.com',
    PropertyPane_TopLevelUser_Description: '組織図のルートに表示される人物',
    PropertyPane_LevelsBelow_Label: 'ルートより下に読み込む階層数',
    PropertyPane_DottedLine_Label: '点線関係の上司属性',
    PropertyPane_DottedLine_Placeholder: 'extensionAttribute10',
    PropertyPane_DottedLine_Description: '省略可能。二次的な「点線」上司のメール アドレスまたは UPN を格納する Azure AD オンプレミス拡張属性名 (extensionAttribute1-15)。点線関係はプロファイル カードに表示されます。Graph API データ ソースが必要です。',
    PropertyPane_DefaultZoom_Label: '組織図の既定のズーム',
    PropertyPane_Zoom_Auto: '既定 (自動調整)',
    PropertyPane_Zoom_50: '50%',
    PropertyPane_Zoom_75: '75%',
    PropertyPane_Zoom_100: '100%',
    PropertyPane_Zoom_125: '125%',
    PropertyPane_Zoom_150: '150%',

    // ── Property pane: Org Chart Features ──
    PropertyPane_FeatureToggles_Note: '組織図ビューのツールバー ボタンを表示または非表示にします。',
    PropertyPane_FindMe_Label: '[自分を検索] ボタン',
    PropertyPane_LayoutToggle_Label: 'レイアウト切り替え (ドリルダウン / 縦 / 横)',
    PropertyPane_Stats_Label: '組織統計バー',
    PropertyPane_DeptFilter_Label: '部署フィルター',
    PropertyPane_UserFilter_Label: 'ユーザーの種類フィルター (メンバー / ゲスト)',
    PropertyPane_Visible: '表示',
    PropertyPane_Hidden: '非表示',

    // ── Property pane: Directory ──
    PropertyPane_PageSize_Label: '1 ページあたりの最大従業員数',
    PropertyPane_PageSize_AriaLabel: '1 ページあたりの最大従業員数 (10 ～ 200)',
    PropertyPane_PageSize_Note: 'カードのサイズ、表示するフィールドなどの表示設定は、アプリ内の設定 (歯車アイコン) からユーザーごとに設定します。',

    // ── Property pane: Demo ──
    PropertyPane_UseDemoData_Label: 'デモ データを使用する',
    PropertyPane_UseDemoData_On: 'オン - サンプルの従業員を表示します',
    PropertyPane_UseDemoData_Off: 'オフ - 実際の Microsoft 365 データを使用します',

    // ── Presence status labels ──
    Presence_Available: '連絡可能',
    Presence_Busy: '取り込み中',
    Presence_DoNotDisturb: '応答不可',
    Presence_BeRightBack: '一時退席中',
    Presence_Away: '退席中',
    Presence_Offline: 'オフライン',

    // ── Header / top bar ──
    Header_DirectoryLabel: '従業員ディレクトリ',
    Header_OrgChartLabel: '組織図',
    Header_SwitchToView: '{view} に切り替え',
    Header_CompanyLogoAlt: '会社のロゴ',
    Header_RefreshingAria: 'データを更新中',
    Header_RefreshAria: 'データを更新',
    Header_RefreshTitle: 'データを更新 (最終更新: {when})',
    Header_NotLoadedYet: '未読み込み',
    Header_JustNow: 'たった今',
    Header_MinutesAgo: '{mins} 分前',
    Header_HoursAgo: '{hours} 時間前',
    Header_PreferencesTitle: '個人設定',
    Header_PreferencesAria: '個人設定パネルを開く',

    // ── Employee Directory ──
    Directory_LoadingLabel: '従業員を読み込んでいます...',
    Directory_LoadFailedFallback: 'Web パーツに User.Read.All のアクセス許可が付与されていることを確認してください。',
    Directory_LoadFailedPrefix: '従業員の読み込みに失敗しました。{detail}',
    Directory_AllDepartments: 'すべての部署',
    Directory_AllOffices: 'すべての勤務地',
    Directory_StatusDisabled: '無効',
    Directory_StatusGuest: 'ゲスト',
    Directory_PresenceStatus: 'ステータス: {status}',
    Directory_ChatInTeams: 'Teams でチャット',
    Directory_ChatWithInTeams: 'Teams で {name} さんとチャット',
    Directory_ManagesCount: '{direct} 人を管理',
    Directory_ManagesCountWithTotal: '{direct} 人を管理 (合計 {total} 人)',
    Directory_ReportsCountWithTotal: '{direct} (合計 {total})',
    Directory_ColumnName: '氏名',
    Directory_ColumnJobTitle: '役職',
    Directory_ColumnDepartment: '部署',
    Directory_ColumnOffice: '勤務地',
    Directory_ColumnEmail: 'メール',
    Directory_ColumnPhone: '電話番号',
    Directory_ColumnReports: '部下',
    Directory_ColumnChat: 'チャット',
    Directory_PrevPage: '前へ',
    Directory_NextPage: '次へ',
    Directory_PreviousPageAria: '前のページ',
    Directory_NextPageAria: '次のページ',
    Directory_SearchPlaceholder: '氏名、役職、メール、部署で検索...',
    Directory_SearchAria: '人物を検索',
    Directory_FilterByDepartmentAria: '部署で絞り込み',
    Directory_FilterByOfficeAria: '勤務地で絞り込み',
    Directory_ClearSearchTitle: '検索とすべてのフィルターをクリア',
    Directory_ClearButton: 'クリア',
    Directory_ClearFiltersButton: 'フィルターをクリア',
    Directory_ExportCsvTitle: 'フィルター処理された結果をすべて CSV ファイルにエクスポートします (Excel で開けます)',
    Directory_ExportCsvButton: 'CSV をエクスポート',
    Directory_ViewModeAria: '表示モード',
    Directory_CardViewTitle: 'カード ビュー',
    Directory_ListViewTitle: 'リスト ビュー',
    Directory_AlphabetFilterAria: 'アルファベット フィルター',
    Directory_ShowAllTitle: 'すべて表示',
    Directory_OtherLettersTitle: '数字またはその他の文字で始まる名前で絞り込み',
    Directory_FilterByLetterTitle: '{letter} で絞り込み',
    Directory_ResultCountSingular: '人',
    Directory_ResultCountPlural: '人',
    Directory_PageOf: ' · {totalPages} ページ中 {page} ページ目',
    Directory_FilterActiveSingular: '{count} 件のフィルターが有効',
    Directory_FilterActivePlural: '{count} 件のフィルターが有効',
    Directory_NoResults: '該当する人物が見つかりません',
    Directory_PaginationAria: 'ページ ナビゲーション',

    // ── Org chart toolbar / shared chart chrome ──
    Chart_Layout_Drill: 'ドリルダウン',
    Chart_Layout_Vertical: 'トップダウン',
    Chart_Layout_Horizontal: '左から右',
    Chart_SearchPlaceholder: '人物を検索...',
    Chart_SearchAria: '人物を検索',
    Chart_MatchSingular: '件 (ツリー内で一致)',
    Chart_MatchPlural: '件 (ツリー内で一致)',
    Chart_ResultsListAria: '人物',
    Chart_ExpandAll: 'すべて展開',
    Chart_CollapseAll: 'すべて折りたたむ',
    Chart_Expanding: '展開中…',
    Chart_Loading: '読み込み中…',
    Chart_FindMeTitle: '組織図内で自分を検索',
    Chart_ViewLayoutButton: '表示',
    Chart_ViewLayoutTitle: '表示レイアウトを切り替え',
    Chart_ViewLayoutPanelTitle: '表示レイアウト',
    Chart_StatsSummaryTitle: '組織統計の概要',
    Chart_FilterByDepartmentTitle: '部署で絞り込み',
    Chart_FilterByDepartmentWithCountAria: '部署で絞り込み ({count} 件選択中)',
    Chart_FilterByDepartmentPanelTitle: '部署で絞り込み',
    Chart_ClearAllFilters: 'すべてのフィルターをクリア',
    Chart_FilterUserTypesTitle: 'ユーザーの種類で絞り込み',
    Chart_DownloadPdfTitle: 'PDF としてダウンロード',
    Chart_DownloadCsvTitle: 'CSV 形式のスプレッドシートとしてダウンロード',
    Chart_ResetRootTitle: '既定のルートにリセット',
    Chart_ViewFromPersonPlaceholder: '起点となる人物を指定…',
    Chart_ViewFromPersonAria: '指定した人物を起点に組織図を表示',
    Chart_ZoomOutTitle: '縮小',
    Chart_ZoomInTitle: '拡大',
    Chart_ZoomResetTitle: 'ズームをリセット',
    Chart_ShowInChartAria: '図に表示',
    Chart_ShowInChartTitle: '図に表示',
    Chart_FilterMembers: '通常のメンバー',
    Chart_FilterGuests: 'ゲスト ユーザー',
    Chart_FilterDisabled: '無効なアカウント',
    Chart_SetupTitle: '組織図をセットアップ',
    Chart_SetupSubtitle: '開始するには、最上位の人物のメール アドレスまたは UPN を入力してください。',
    Chart_SetupPlaceholder: 'ceo@company.com',
    Chart_SetupInputAria: '最上位の人物のメール アドレスまたは UPN',
    Chart_SetupLoadButton: '読み込み',
    Chart_SetupHint: 'Web パーツの設定 (管理者向け) でこれを恒久的に設定することもできます。',
    Chart_BuildingLabel: '組織図を作成しています...',
    Chart_RetryButton: '再試行',
    Chart_NotFoundFromSetup: 'ユーザー "{identifier}" が見つかりません。',
    Chart_NotFoundWithSettings: 'ユーザー "{identifier}" が見つかりません。設定で UPN またはメール アドレスを確認してください。',
    Chart_LoadFailedGeneric: '組織図の読み込みに失敗しました。{detail}',
    Chart_LoadFailedPermissions: ' アクセス許可を確認してください。',
    Chart_LoadFailedForPerson: 'この人物の組織図の読み込みに失敗しました。',
    Chart_FindMeNotFound: 'この組織内でお使いのアカウントが見つかりませんでした。',
    Chart_StatPeople: '人数',
    Chart_StatMembers: 'メンバー',
    Chart_StatGuests: 'ゲスト',
    Chart_StatDepts: '部署',
    Chart_ReportingLineAria: 'レポート ライン',
    Chart_BackToFullOrgTitle: '組織図全体に戻る',
    Chart_FullOrgLabel: '組織全体',
    Chart_FocusOnPerson: '{name} にフォーカス',
    Chart_OrgChartAria: '組織図',
    Chart_ExportNote_DrillLevel: '現在のドリルダウン階層 (直属の部下 1 階層分)',
    Chart_ExportNote_PartialLevels: '読み込み済みの階層のみが含まれます。より深い階層を含めるには、エクスポート前に [すべて展開] を使用してください',
    Chart_AllowPopupsForPdf: 'PDF をエクスポートするには、ポップアップを許可してください。',

    // ── Person card ──
    PersonCard_ProfileAria: 'プロファイル: {name}',
    PersonCard_CloseTitle: '閉じる',
    PersonCard_CloseAria: 'プロファイルを閉じる',
    PersonCard_StatusDisabled: '無効',
    PersonCard_StatusGuest: 'ゲスト',
    PersonCard_DirectReportSingular: '直属の部下 {count} 人',
    PersonCard_DirectReportPlural: '直属の部下 {count} 人',
    PersonCard_TotalSuffix: ' · 合計 {total} 人',
    PersonCard_CopyEmailTitle: 'メール アドレスをコピー',
    PersonCard_EmailCopiedAria: 'メール アドレスをコピーしました',
    PersonCard_ReportsTo: '報告先',
    PersonCard_FocusOnPerson: '{name} にフォーカス',
    PersonCard_FocusOrgChartOnPerson: '組織図を {name} にフォーカス',
    PersonCard_DottedLine: '点線関係',
    PersonCard_DottedLineManager: '点線関係の上司: {name}',
    PersonCard_DottedLineReport: '点線関係の部下: {name}',
    PersonCard_ChatButton: 'チャット',
    PersonCard_EmailButton: 'メール',
    PersonCard_FocusButton: 'フォーカス',
    PersonCard_FocusTitle: 'この人物に組織図をフォーカス',

    // ── Org node card ──
    OrgNode_ViewProfile: '{name} さんのプロファイルを表示',
    OrgNode_FocusOrgChartOn: '組織図を {name} にフォーカス',
    OrgNode_Collapse: '折りたたむ',
    OrgNode_Expand: '展開',
    OrgNode_DirectReportsSuffix: '{name} さんの直属の部下',
    OrgNode_StatusDisabled: '無効',
    OrgNode_StatusGuest: 'ゲスト',
    OrgNode_TotalReportsAcrossLevels: '{name} さんの配下全階層で合計 {count} 人',

    // ── Drill view ──
    Drill_ReportingLineAria: 'レポート ライン',
    Drill_BackToTopTitle: '先頭に戻る',
    Drill_BackToTopAria: '組織図の先頭に戻る',
    Drill_GoBackTo: '{name} さんに戻る',
    Drill_ViewProfileTitle: 'プロファイルを表示',
    Drill_ViewProfileAria: '{name} さんのプロファイルを表示',
    Drill_ProfileButton: 'プロファイル',
    Drill_LoadingLabel: '読み込み中...',
    Drill_DirectReports: '直属の部下',
    Drill_DirectReportsOfAria: '{name} さんの直属の部下',
    Drill_DirectReportsAria: '直属の部下',
    Drill_ViewPersonProfile: '{name} さんのプロファイルを表示',
    Drill_ShowPersonReports: '{name} さんの直属の部下を表示',
    Drill_NoDirectReports: '直属の部下はいません',

    // ── Settings panel ──
    Settings_AlphabetFirstName: '名',
    Settings_AlphabetLastName: '姓',
    Settings_CardSizeSmall: '小 - コンパクトで、より多くのカードを表示',
    Settings_CardSizeMedium: '中 - バランス重視',
    Settings_CardSizeLarge: '大 - ゆったり表示、カード数は少なめ',
    Settings_HeaderText: '個人設定',
    Settings_SaveButton: '保存',
    Settings_CancelButton: 'キャンセル',
    Settings_DiscardButton: '変更を破棄',
    Settings_SectionDirectory: 'ディレクトリ',
    Settings_AlphabetFilterByLabel: 'アルファベット フィルターの基準',
    Settings_CardSizeLabel: 'カード サイズ',
    Settings_FontSizeLabel: 'フォント サイズ',
    Settings_SectionCardsAndFields: 'カードとフィールド',
    Settings_ShowOnCardsLabel: '従業員カードに表示する項目:',
    Settings_EmailAddressLabel: 'メール アドレス',
    Settings_PhoneNumberLabel: '電話番号',
    Settings_DepartmentLabel: '部署',
    Settings_OfficeLocationLabel: '勤務地',
    Settings_SectionOrgChart: '組織図',
    Settings_ManagerLevelsLabel: '人物にフォーカスしたときに表示する上司の階層数: {levels}',
    Settings_CompactCardsLabel: 'コンパクト カード',
    Settings_CompactCardsOn: 'オン - カードが小さくなり、一度に多く表示されます',
    Settings_CompactCardsOff: 'オフ - 標準サイズ',
    Settings_Hint: 'これらの個人設定はお使いのブラウザーに保存され、ご自身にのみ適用されます。図のテーマ、既定のビュー、レイアウトは SharePoint 管理者が構成します。',
    Settings_SectionDemoData: 'デモ データ',
    Settings_DatasetSizeLabel: 'データセットのサイズ',
    Settings_PeopleCountSuffix: '{count} 人',

    // ── Export (CSV / PDF) ──
    Export_ColumnName: '氏名',
    Export_ColumnJobTitle: '役職',
    Export_ColumnDepartment: '部署',
    Export_ColumnOffice: '勤務地',
    Export_ColumnEmail: 'メール',
    Export_ColumnPhone: '電話番号',
    Export_ColumnManager: '上司',
    Export_ColumnLevel: '階層',
    Export_PdfDocumentTitle: '組織図',
    Export_PdfHeading: '組織図',
    Export_PdfRootLabel: 'ルート: {name}',
  };
});
