define([], function () {
  return {
    // ── 속성 창: 창 머리글 / 그룹 ──
    PropertyPane_HeaderDescription: 'Smart Org Chart 설정',
    PropertyPane_Group_General: '일반',
    PropertyPane_Group_Branding: '브랜딩',
    PropertyPane_Group_VisualStyle: '시각적 스타일',
    PropertyPane_Group_DataSource: '데이터 원본',
    PropertyPane_Group_CustomAttributes: '사용자 지정 속성',
    PropertyPane_Group_UserFilters: '사용자 필터',
    PropertyPane_Group_OrgChart: '조직도',
    PropertyPane_Group_OrgChartFeatures: '조직도 기능',
    PropertyPane_Group_Directory: '주소록',
    PropertyPane_Group_Demo: '데모',

    // ── 속성 창: 일반 ──
    PropertyPane_DefaultView_Label: '기본 보기',

    // ── 속성 창: 브랜딩 ──
    PropertyPane_AppTitle_Label: '앱 제목',
    PropertyPane_AppTitle_Placeholder: 'Contoso 조직도',
    PropertyPane_AppTitle_Description: '보기 이름과 함께 헤더 표시줄에 표시됩니다',
    PropertyPane_LogoUrl_Label: '로고 URL',
    PropertyPane_LogoUrl_Placeholder: 'https://contoso.sharepoint.com/sites/yoursite/SiteAssets/logo.png',
    PropertyPane_LogoUrl_Description: 'PNG/SVG/JPG 이미지의 전체 URL입니다. 팁: 브라우저에서 이미지 파일을 열고 주소 표시줄의 URL을 복사하세요. "링크 복사" 공유 URL은 작동하지 않습니다.',
    PropertyPane_DirectoryLabel_Label: '직원 주소록 보기 레이블',
    PropertyPane_OrgChartLabel_Label: '조직도 보기 레이블',
    PropertyPane_ViewLabel_Description: '기본 이름을 사용하려면 비워 두세요. 레이블을 완전히 숨기려면 "[blank]"를 입력하세요.',

    // ── 속성 창: 시각적 스타일 ──
    PropertyPane_ChartTheme_Label: '차트 테마',
    PropertyPane_Theme_Modern: '모던 — 흰색 배경에 부서별 색상',
    PropertyPane_Theme_Minimal: '미니멀 — 플랫 디자인 및 낮은 대비',
    PropertyPane_Theme_Corporate: '기업형 — 단일 파란색 테마',
    PropertyPane_Theme_Dark: '다크 — 짙은 남색 배경',
    PropertyPane_Theme_Custom: '사용자 지정 — 원하는 색상 선택',
    PropertyPane_AccentColor_Label: '사용자 지정 강조 색',
    PropertyPane_AccentColor_PickerAriaLabel: '강조 색 선택 도구',
    PropertyPane_AccentColor_HexLabel: '16진수',
    PropertyPane_AccentColor_HexAriaLabel: '강조 색의 16진수 값',
    PropertyPane_AccentColor_RgbLabel: 'RGB',
    PropertyPane_AccentColor_ChannelAriaLabel: '{name} 채널 (0~255)',
    PropertyPane_AccentColor_ContrastWithWhite: '흰색과의 대비: {ratio}:1 ({passes})',
    PropertyPane_AccentColor_PassesAA: 'AA 기준 충족',
    PropertyPane_AccentColor_LargeTextOnly: '큰 텍스트에만 해당',
    PropertyPane_AccentColor_LowContrast: '낮은 대비',
    PropertyPane_AccentColor_DarkTextNote: '가독성을 위해 이 색상 위의 텍스트는 어두운 색으로 표시됩니다.',
    PropertyPane_AccentColor_DarkerShadeNote: '가독성을 위해 제목과 링크는 더 어두운 색조({hex})로 표시됩니다.',
    PropertyPane_AccentColor_InvalidHex: '"{typed}"은(는) 올바른 16진수 색상 값이 아닙니다. #0078d4 또는 #07d와 같은 값을 사용하세요.',
    PropertyPane_DefaultFontSize_Label: '기본 글꼴 크기',
    PropertyPane_FontSize_75: '75% — 매우 작게',
    PropertyPane_FontSize_85: '85% — 작게',
    PropertyPane_FontSize_100: '100% — 보통',
    PropertyPane_FontSize_115: '115% — 크게',
    PropertyPane_FontSize_130: '130% — 매우 크게',
    PropertyPane_FontSize_150: '150% — XXL',
    PropertyPane_FontSize_175: '175% — XXXL',
    PropertyPane_DefaultLayout_Label: '기본 조직도 레이아웃',
    PropertyPane_Layout_Drill: '드릴다운',
    PropertyPane_Layout_Vertical: '위에서 아래로',
    PropertyPane_Layout_Horizontal: '왼쪽에서 오른쪽으로',

    // ── 속성 창: 데이터 원본 ──
    PropertyPane_DataSource_Label: '사용자 및 조직 데이터를 가져올 위치',
    PropertyPane_DataSource_Auto: '자동 — Graph API 사용, 실패 시 SharePoint 검색으로 대체',
    PropertyPane_DataSource_Graph: 'Graph API — 실시간 Azure AD 데이터(인덱싱 지연 없음)',
    PropertyPane_DataSource_Search: 'SharePoint 검색 — 이전 방식',
    PropertyPane_DataSource_Note: 'Graph API 사용을 권장합니다. Azure Active Directory에서 직접 데이터를 읽어오므로 신규 사용자 및 관리자 변경 사항이 즉시 반영됩니다. SharePoint 앱 카탈로그에서 Microsoft Graph 권한이 승인되어야 합니다.',

    // ── 속성 창: 사용자 지정 속성 ──
    PropertyPane_CustomAttributes_Note: '사용자 지정 속성을 사용하려면 Microsoft Graph가 필요합니다(데이터 원본: Graph 또는 자동). SharePoint 검색으로는 Microsoft Entra ID 속성을 읽을 수 있는 범용적인 방법이 없습니다.',
    PropertyPane_CustomAttributes_Heading: '사용자 지정 속성 관리',
    PropertyPane_CustomAttributes_Empty: '구성된 사용자 지정 속성이 없습니다.',
    PropertyPane_CustomAttributes_AddButton: '+ 속성 추가',
    PropertyPane_CustomAttributes_MaxTooltip: '사용자 지정 속성은 최대 {max}개까지 가능합니다',
    PropertyPane_CustomAttributes_FieldNameLabel: '속성 이름',
    PropertyPane_CustomAttributes_FieldPlaceholder: '예: companyName',
    PropertyPane_CustomAttributes_FieldError: 'employeeId, companyName, city 등 또는 extensionAttribute1-15를 사용하세요',
    PropertyPane_CustomAttributes_DisplayLabelLabel: '표시 레이블',
    PropertyPane_CustomAttributes_LabelPlaceholder: '예: 코스트 센터',
    PropertyPane_CustomAttributes_RemoveTitle: '속성 제거',
    PropertyPane_CustomAttributes_RemoveAriaLabel: '속성 {ordinal} 제거',
    PropertyPane_CustomAttributes_ShowInDirectory: '주소록에 표시',
    PropertyPane_CustomAttributes_ShowInOrgChart: '조직도에 표시',

    // ── 속성 창: 사용자 필터 ──
    PropertyPane_ExcludedAccounts_Label: '제외할 계정',
    PropertyPane_ExcludedAccounts_Placeholder: 'conf-room, noreply, admin@, Service Account',
    PropertyPane_ExcludedAccounts_Description: '쉼표로 구분된 단어 또는 패턴입니다(대/소문자 구분 안 함). 표시 이름, 이메일 또는 UPN에 이 값 중 하나라도 포함된 사용자는 모든 보기에서 숨겨집니다.',
    PropertyPane_RestrictTenant_Label: '테넌트 사용자만 표시',
    PropertyPane_RestrictTenant_On: '켜짐 — 외부 이메일 도메인을 사용하는 계정 숨김(예: gmail.com, hotmail.com)',
    PropertyPane_RestrictTenant_Off: '꺼짐 — 이메일 도메인과 관계없이 모든 사용자 표시',
    PropertyPane_HideGuest_Label: 'Azure AD 게스트 계정 숨기기',
    PropertyPane_HideGuest_On: '켜짐 — 게스트 계정 숨김',
    PropertyPane_HideGuest_Off: '꺼짐 — 게스트 계정 표시(게스트 배지와 함께 표시)',
    PropertyPane_HideDisabled_Label: '사용 중지된 계정 숨기기',
    PropertyPane_HideDisabled_On: '켜짐 — 로그인이 차단된 계정 숨김',
    PropertyPane_HideDisabled_Off: '꺼짐 — 사용 중지된 계정 표시(사용 중지됨 배지와 함께 표시)',
    PropertyPane_HideDisabled_Note: '참고: 게스트 및 사용 중지된 계정 감지에는 Graph API 데이터 원본이 필요합니다. SharePoint 검색은 이 정보를 반환하지 않으므로 데이터가 검색에서 제공되는 경우 이 두 필터(및 게스트/사용 중지됨 배지)는 적용되지 않습니다.',
    PropertyPane_HideNoJobTitle_Label: '직함이 없는 계정 숨기기',
    PropertyPane_HideNoJobTitle_On: '켜짐 — 직함이 없는 계정 숨김',
    PropertyPane_HideNoJobTitle_Off: '꺼짐 — 직함과 관계없이 모든 계정 표시',
    PropertyPane_HideNoDept_Label: '부서가 없는 계정 숨기기',
    PropertyPane_HideNoDept_On: '켜짐 — 부서가 없는 계정 숨김',
    PropertyPane_HideNoDept_Off: '꺼짐 — 부서와 관계없이 모든 계정 표시',

    // ── 속성 창: 조직도 ──
    PropertyPane_TopLevelUser_Label: '최상위 사용자(UPN 또는 이메일)',
    PropertyPane_TopLevelUser_Placeholder: 'ceo@yourcompany.com',
    PropertyPane_TopLevelUser_Description: '조직도의 최상위에 표시될 사용자입니다',
    PropertyPane_LevelsBelow_Label: '루트 아래에 로드할 단계 수',
    PropertyPane_DottedLine_Label: '점선 관리자 속성',
    PropertyPane_DottedLine_Placeholder: 'extensionAttribute10',
    PropertyPane_DottedLine_Description: '선택 사항입니다. 보조 "점선" 관리자의 이메일 또는 UPN을 저장하는 Azure AD 온프레미스 확장 속성(extensionAttribute1-15)의 이름입니다. 점선 관계는 프로필 카드에 표시됩니다. Graph API 데이터 원본이 필요합니다.',
    PropertyPane_DefaultZoom_Label: '기본 조직도 확대/축소 배율',
    PropertyPane_Zoom_Auto: '기본값(자동 맞춤)',
    PropertyPane_Zoom_50: '50%',
    PropertyPane_Zoom_75: '75%',
    PropertyPane_Zoom_100: '100%',
    PropertyPane_Zoom_125: '125%',
    PropertyPane_Zoom_150: '150%',

    // ── 속성 창: 조직도 기능 ──
    PropertyPane_FeatureToggles_Note: '조직도 보기에서 도구 모음 버튼을 표시하거나 숨깁니다.',
    PropertyPane_FindMe_Label: '나 찾기 버튼',
    PropertyPane_LayoutToggle_Label: '레이아웃 전환(드릴다운/세로/가로)',
    PropertyPane_Stats_Label: '조직 통계 표시줄',
    PropertyPane_DeptFilter_Label: '부서 필터',
    PropertyPane_UserFilter_Label: '사용자 유형 필터(구성원/게스트)',
    PropertyPane_Visible: '표시',
    PropertyPane_Hidden: '숨김',

    // ── 속성 창: 주소록 ──
    PropertyPane_PageSize_Label: '페이지당 최대 직원 수',
    PropertyPane_PageSize_AriaLabel: '페이지당 최대 직원 수(10~200)',
    PropertyPane_PageSize_Note: '카드 크기, 표시 필드 및 기타 표시 설정은 앱의 설정 톱니바퀴 아이콘을 통해 사용자별로 지정됩니다.',

    // ── 속성 창: 데모 ──
    PropertyPane_UseDemoData_Label: '데모 데이터 사용',
    PropertyPane_UseDemoData_On: '켜짐 — 샘플 직원 데이터 표시',
    PropertyPane_UseDemoData_Off: '꺼짐 — 실제 Microsoft 365 데이터',

    // ── 상태 표시 레이블 ──
    Presence_Available: '통화 가능',
    Presence_Busy: '다른 용무 중',
    Presence_DoNotDisturb: '방해 금지',
    Presence_BeRightBack: '곧 돌아오겠습니다',
    Presence_Away: '자리 비움',
    Presence_Offline: '오프라인',

    // ── 헤더 / 상단 표시줄 ──
    Header_DirectoryLabel: '직원 주소록',
    Header_OrgChartLabel: '조직도',
    Header_SwitchToView: '{view}(으)로 전환',
    Header_CompanyLogoAlt: '회사 로고',
    Header_RefreshingAria: '데이터 새로 고침 중',
    Header_RefreshAria: '데이터 새로 고침',
    Header_RefreshTitle: '데이터 새로 고침(마지막 업데이트: {when})',
    Header_NotLoadedYet: '아직 로드되지 않음',
    Header_JustNow: '방금 전',
    Header_MinutesAgo: '{mins}분 전',
    Header_HoursAgo: '{hours}시간 전',
    Header_PreferencesTitle: '기본 설정',
    Header_PreferencesAria: '기본 설정 패널 열기',

    // ── 직원 주소록 ──
    Directory_LoadingLabel: '직원 정보를 불러오는 중...',
    Directory_LoadFailedFallback: '웹 파트에 User.Read.All 권한이 있는지 확인하세요.',
    Directory_LoadFailedPrefix: '직원 정보를 불러오지 못했습니다. {detail}',
    Directory_AllDepartments: '모든 부서',
    Directory_AllOffices: '모든 사무실',
    Directory_StatusDisabled: '사용 중지됨',
    Directory_StatusGuest: '게스트',
    Directory_PresenceStatus: '상태: {status}',
    Directory_ChatInTeams: 'Teams에서 채팅',
    Directory_ChatWithInTeams: 'Teams에서 {name}님과 채팅',
    Directory_ManagesCount: '관리 인원 {direct}명',
    Directory_ManagesCountWithTotal: '관리 인원 {direct}명(전체 {total}명)',
    Directory_ReportsCountWithTotal: '{direct}명(전체 {total}명)',
    Directory_ColumnName: '이름',
    Directory_ColumnJobTitle: '직함',
    Directory_ColumnDepartment: '부서',
    Directory_ColumnOffice: '사무실',
    Directory_ColumnEmail: '이메일',
    Directory_ColumnPhone: '전화번호',
    Directory_ColumnReports: '보고 대상',
    Directory_ColumnChat: '채팅',
    Directory_PrevPage: '이전',
    Directory_NextPage: '다음',
    Directory_PreviousPageAria: '이전 페이지',
    Directory_NextPageAria: '다음 페이지',
    Directory_SearchPlaceholder: '이름, 직함, 이메일 또는 부서로 검색...',
    Directory_SearchAria: '직원 검색',
    Directory_FilterByDepartmentAria: '부서별 필터',
    Directory_FilterByOfficeAria: '사무실별 필터',
    Directory_ClearSearchTitle: '검색 및 모든 필터 지우기',
    Directory_ClearButton: '지우기',
    Directory_ClearFiltersButton: '필터 지우기',
    Directory_ExportCsvTitle: '필터링된 모든 결과를 CSV 파일로 내보내기(Excel에서 열림)',
    Directory_ExportCsvButton: 'CSV로 내보내기',
    Directory_ViewModeAria: '보기 모드',
    Directory_CardViewTitle: '카드 보기',
    Directory_ListViewTitle: '목록 보기',
    Directory_AlphabetFilterAria: '알파벳순 필터',
    Directory_ShowAllTitle: '모두 표시',
    Directory_OtherLettersTitle: '숫자나 기타 문자로 시작하는 이름 필터링',
    Directory_FilterByLetterTitle: '{letter}(으)로 필터링',
    Directory_ResultCountSingular: '명',
    Directory_ResultCountPlural: '명',
    Directory_PageOf: ' · {totalPages}페이지 중 {page}페이지',
    Directory_FilterActiveSingular: '필터 {count}개 적용됨',
    Directory_FilterActivePlural: '필터 {count}개 적용됨',
    Directory_NoResults: '검색 결과가 없습니다',
    Directory_PaginationAria: '페이지 번호 매기기',

    // ── 조직도 도구 모음 / 공통 차트 UI ──
    Chart_Layout_Drill: '드릴다운',
    Chart_Layout_Vertical: '위에서 아래로',
    Chart_Layout_Horizontal: '왼쪽에서 오른쪽으로',
    Chart_SearchPlaceholder: '직원 검색...',
    Chart_SearchAria: '직원 검색',
    Chart_MatchSingular: '트리 내 일치 항목',
    Chart_MatchPlural: '트리 내 일치 항목',
    Chart_ResultsListAria: '직원 목록',
    Chart_ExpandAll: '모두 확장',
    Chart_CollapseAll: '모두 축소',
    Chart_Expanding: '확장하는 중…',
    Chart_Loading: '로드하는 중…',
    Chart_FindMeTitle: '조직도에서 나 찾기',
    Chart_ViewLayoutButton: '보기',
    Chart_ViewLayoutTitle: '보기 레이아웃 전환',
    Chart_ViewLayoutPanelTitle: '보기 레이아웃',
    Chart_StatsSummaryTitle: '조직 통계 요약',
    Chart_FilterByDepartmentTitle: '부서별 필터',
    Chart_FilterByDepartmentWithCountAria: '부서별 필터({count}개 선택됨)',
    Chart_FilterByDepartmentPanelTitle: '부서별 필터',
    Chart_ClearAllFilters: '모든 필터 지우기',
    Chart_FilterUserTypesTitle: '사용자 유형 필터',
    Chart_DownloadPdfTitle: 'PDF로 다운로드',
    Chart_DownloadCsvTitle: 'CSV 스프레드시트로 다운로드',
    Chart_ResetRootTitle: '기본 루트로 재설정',
    Chart_ViewFromPersonPlaceholder: '특정 직원 기준으로 보기…',
    Chart_ViewFromPersonAria: '특정 직원을 기준으로 조직도 보기',
    Chart_ZoomOutTitle: '축소',
    Chart_ZoomInTitle: '확대',
    Chart_ZoomResetTitle: '확대/축소 재설정',
    Chart_ShowInChartAria: '차트에 표시',
    Chart_ShowInChartTitle: '차트에 표시',
    Chart_FilterMembers: '일반 구성원',
    Chart_FilterGuests: '게스트 사용자',
    Chart_FilterDisabled: '사용 중지된 계정',
    Chart_SetupTitle: '조직도 설정',
    Chart_SetupSubtitle: '시작하려면 최상위 직원의 이메일 또는 UPN을 입력하세요.',
    Chart_SetupPlaceholder: 'ceo@company.com',
    Chart_SetupInputAria: '최상위 직원의 이메일 또는 UPN',
    Chart_SetupLoadButton: '로드',
    Chart_SetupHint: '웹 파트 설정(관리자)에서 이 값을 영구적으로 설정할 수도 있습니다.',
    Chart_BuildingLabel: '조직도를 생성하는 중...',
    Chart_RetryButton: '다시 시도',
    Chart_NotFoundFromSetup: '"{identifier}" 사용자를 찾을 수 없습니다.',
    Chart_NotFoundWithSettings: '"{identifier}" 사용자를 찾을 수 없습니다. 설정에서 UPN 또는 이메일을 확인하세요.',
    Chart_LoadFailedGeneric: '조직도를 불러오지 못했습니다.{detail}',
    Chart_LoadFailedPermissions: ' 권한을 확인하세요.',
    Chart_LoadFailedForPerson: '이 직원의 조직도를 불러오지 못했습니다.',
    Chart_FindMeNotFound: '이 조직에서 사용자의 계정을 찾을 수 없습니다.',
    Chart_StatPeople: '전체 인원',
    Chart_StatMembers: '구성원',
    Chart_StatGuests: '게스트',
    Chart_StatDepts: '부서',
    Chart_ReportingLineAria: '보고 체계',
    Chart_BackToFullOrgTitle: '전체 조직도로 돌아가기',
    Chart_FullOrgLabel: '전체 조직',
    Chart_FocusOnPerson: '{name}에 초점 맞추기',
    Chart_OrgChartAria: '조직도',
    Chart_ExportNote_DrillLevel: '현재 드릴다운 단계(직속 부하 직원 한 단계)',
    Chart_ExportNote_PartialLevels: '로드된 단계만 포함됩니다 — 하위 단계까지 포함하려면 내보내기 전에 모두 확장을 사용하세요',
    Chart_AllowPopupsForPdf: 'PDF를 내보내려면 팝업을 허용하세요.',

    // ── 프로필 카드 ──
    PersonCard_ProfileAria: '프로필: {name}',
    PersonCard_CloseTitle: '닫기',
    PersonCard_CloseAria: '프로필 닫기',
    PersonCard_StatusDisabled: '사용 중지됨',
    PersonCard_StatusGuest: '게스트',
    PersonCard_DirectReportSingular: '직속 부하 직원 {count}명',
    PersonCard_DirectReportPlural: '직속 부하 직원 {count}명',
    PersonCard_TotalSuffix: ' · 전체 {total}명',
    PersonCard_CopyEmailTitle: '이메일 주소 복사',
    PersonCard_EmailCopiedAria: '이메일 주소가 복사됨',
    PersonCard_ReportsTo: '보고 대상',
    PersonCard_FocusOnPerson: '{name}에 초점 맞추기',
    PersonCard_FocusOrgChartOnPerson: '조직도의 초점을 {name}(으)로 이동',
    PersonCard_DottedLine: '점선 관계',
    PersonCard_DottedLineManager: '점선 관리자: {name}',
    PersonCard_DottedLineReport: '점선 부하 직원: {name}',
    PersonCard_ChatButton: '채팅',
    PersonCard_EmailButton: '이메일',
    PersonCard_FocusButton: '초점',
    PersonCard_FocusTitle: '이 직원에게 조직도 초점 맞추기',

    // ── 조직도 노드 카드 ──
    OrgNode_ViewProfile: '{name}님의 프로필 보기',
    OrgNode_FocusOrgChartOn: '조직도의 초점을 {name}(으)로 이동',
    OrgNode_Collapse: '축소',
    OrgNode_Expand: '확장',
    OrgNode_DirectReportsSuffix: '{name}님의 직속 부하 직원',
    OrgNode_StatusDisabled: '사용 중지됨',
    OrgNode_StatusGuest: '게스트',
    OrgNode_TotalReportsAcrossLevels: '{name}님 아래의 모든 단계에 걸쳐 {count}명',

    // ── 드릴다운 보기 ──
    Drill_ReportingLineAria: '보고 체계',
    Drill_BackToTopTitle: '맨 위로 돌아가기',
    Drill_BackToTopAria: '조직도 맨 위로 돌아가기',
    Drill_GoBackTo: '{name}(으)로 돌아가기',
    Drill_ViewProfileTitle: '프로필 보기',
    Drill_ViewProfileAria: '{name}님의 프로필 보기',
    Drill_ProfileButton: '프로필',
    Drill_LoadingLabel: '로드하는 중...',
    Drill_DirectReports: '직속 부하 직원',
    Drill_DirectReportsOfAria: '{name}님의 직속 부하 직원',
    Drill_DirectReportsAria: '직속 부하 직원',
    Drill_ViewPersonProfile: '{name}님의 프로필 보기',
    Drill_ShowPersonReports: '{name}님의 직속 부하 직원 표시',
    Drill_NoDirectReports: '직속 부하 직원 없음',

    // ── 설정 패널 ──
    Settings_AlphabetFirstName: '이름',
    Settings_AlphabetLastName: '성',
    Settings_CardSizeSmall: '작게 — 간결하며 더 많은 카드 표시',
    Settings_CardSizeMedium: '보통 — 균형 잡힌 크기',
    Settings_CardSizeLarge: '크게 — 여유로운 배치, 적은 카드 표시',
    Settings_HeaderText: '기본 설정',
    Settings_SaveButton: '저장',
    Settings_CancelButton: '취소',
    Settings_DiscardButton: '변경 내용 취소',
    Settings_SectionDirectory: '주소록',
    Settings_AlphabetFilterByLabel: '알파벳 필터 기준',
    Settings_CardSizeLabel: '카드 크기',
    Settings_FontSizeLabel: '글꼴 크기',
    Settings_SectionCardsAndFields: '카드 및 필드',
    Settings_ShowOnCardsLabel: '직원 카드에 표시할 항목:',
    Settings_EmailAddressLabel: '이메일 주소',
    Settings_PhoneNumberLabel: '전화번호',
    Settings_DepartmentLabel: '부서',
    Settings_OfficeLocationLabel: '사무실 위치',
    Settings_SectionOrgChart: '조직도',
    Settings_ManagerLevelsLabel: '직원 초점 시 표시할 관리자 단계 수: {levels}',
    Settings_CompactCardsLabel: '간결한 카드',
    Settings_CompactCardsOn: '켜짐 — 카드 크기 축소, 한 번에 더 많이 표시',
    Settings_CompactCardsOff: '꺼짐 — 표준 크기',
    Settings_Hint: '이 기본 설정은 브라우저에 저장되며 사용자 본인에게만 적용됩니다. 차트 테마, 기본 보기 및 레이아웃은 SharePoint 관리자가 구성합니다.',
    Settings_SectionDemoData: '데모 데이터',
    Settings_DatasetSizeLabel: '데이터 세트 크기',
    Settings_PeopleCountSuffix: '{count}명',

    // ── 내보내기 (CSV / PDF) ──
    Export_ColumnName: '이름',
    Export_ColumnJobTitle: '직함',
    Export_ColumnDepartment: '부서',
    Export_ColumnOffice: '사무실',
    Export_ColumnEmail: '이메일',
    Export_ColumnPhone: '전화번호',
    Export_ColumnManager: '관리자',
    Export_ColumnLevel: '단계',
    Export_PdfDocumentTitle: '조직도',
    Export_PdfHeading: '조직도',
    Export_PdfRootLabel: '루트: {name}',
  };
});
