define([], function () {
  return {
    // ── Property pane: pane header / groups ──
    PropertyPane_HeaderDescription: 'Innstillinger for Smart Org Chart',
    PropertyPane_Group_General: 'Generelt',
    PropertyPane_Group_Branding: 'Branding',
    PropertyPane_Group_VisualStyle: 'Visuell stil',
    PropertyPane_Group_DataSource: 'Datakilde',
    PropertyPane_Group_CustomAttributes: 'Egendefinerte attributter',
    PropertyPane_Group_UserFilters: 'Brukerfiltre',
    PropertyPane_Group_OrgChart: 'Organisasjonskart',
    PropertyPane_Group_OrgChartFeatures: 'Funksjoner i organisasjonskart',
    PropertyPane_Group_Directory: 'Katalog',
    PropertyPane_Group_Demo: 'Demo',

    // ── Property pane: General ──
    PropertyPane_DefaultView_Label: 'Standardvisning',

    // ── Property pane: Branding ──
    PropertyPane_AppTitle_Label: 'Apptittel',
    PropertyPane_AppTitle_Placeholder: 'Contoso Organisasjonskart',
    PropertyPane_AppTitle_Description: 'Vises i topplinjen sammen med visningsnavnet',
    PropertyPane_LogoUrl_Label: 'Logo-URL',
    PropertyPane_LogoUrl_Placeholder: 'https://contoso.sharepoint.com/sites/yoursite/SiteAssets/logo.png',
    PropertyPane_LogoUrl_Description: 'Fullstendig URL til et PNG/SVG/JPG-bilde. Tips: Åpne bildefilen i nettleseren din, og kopier URL-en fra adresselinjen. Delings-URL-er fra "Kopier kobling" fungerer ikke.',
    PropertyPane_DirectoryLabel_Label: 'Visningsnavn for ansattkatalog',
    PropertyPane_OrgChartLabel_Label: 'Visningsnavn for organisasjonskart',
    PropertyPane_ViewLabel_Description: 'La stå tomt for å bruke standardnavnet, eller skriv "[blank]" for å skjule etiketten helt.',

    // ── Property pane: Visual Style ──
    PropertyPane_ChartTheme_Label: 'Diagramtema',
    PropertyPane_Theme_Modern: 'Moderne – avdelingsfarger på hvit bakgrunn',
    PropertyPane_Theme_Minimal: 'Minimalistisk – flat design med lav kontrast',
    PropertyPane_Theme_Corporate: 'Bedrift – ensartet blå',
    PropertyPane_Theme_Dark: 'Mørk – mørk marineblå bakgrunn',
    PropertyPane_Theme_Custom: 'Egendefinert – velg din egen farge',
    PropertyPane_AccentColor_Label: 'Egendefinert aksentfarge',
    PropertyPane_AccentColor_PickerAriaLabel: 'Velger for aksentfarge',
    PropertyPane_AccentColor_HexLabel: 'Hex',
    PropertyPane_AccentColor_HexAriaLabel: 'Hex-verdi for aksentfarge',
    PropertyPane_AccentColor_RgbLabel: 'RGB',
    PropertyPane_AccentColor_ChannelAriaLabel: '{name}-kanal (0 til 255)',
    PropertyPane_AccentColor_ContrastWithWhite: 'Kontrast mot hvitt: {ratio}:1 ({passes})',
    PropertyPane_AccentColor_PassesAA: 'oppfyller AA',
    PropertyPane_AccentColor_LargeTextOnly: 'kun stor tekst',
    PropertyPane_AccentColor_LowContrast: 'lav kontrast',
    PropertyPane_AccentColor_DarkTextNote: 'Tekst på denne fargen vil bruke mørk skrift for bedre lesbarhet.',
    PropertyPane_AccentColor_DarkerShadeNote: 'Titler og koblinger vil bruke en mørkere nyanse ({hex}) for bedre lesbarhet.',
    PropertyPane_AccentColor_InvalidHex: '"{typed}" er ikke en gyldig hex-farge. Bruk en verdi som #0078d4 eller #07d.',
    PropertyPane_DefaultFontSize_Label: 'Standard skriftstørrelse',
    PropertyPane_FontSize_75: '75 % – Ekstra liten',
    PropertyPane_FontSize_85: '85 % – Liten',
    PropertyPane_FontSize_100: '100 % – Normal',
    PropertyPane_FontSize_115: '115 % – Stor',
    PropertyPane_FontSize_130: '130 % – Ekstra stor',
    PropertyPane_FontSize_150: '150 % – XXL',
    PropertyPane_FontSize_175: '175 % – XXXL',
    PropertyPane_DefaultLayout_Label: 'Standardlayout for organisasjonskart',
    PropertyPane_Layout_Drill: 'Drilldown',
    PropertyPane_Layout_Vertical: 'Ovenfra og ned',
    PropertyPane_Layout_Horizontal: 'Fra venstre til høyre',

    // ── Property pane: Data Source ──
    PropertyPane_DataSource_Label: 'Hvor bruker- og organisasjonsdata skal lastes fra',
    PropertyPane_DataSource_Auto: 'Automatisk – Graph API, med SharePoint-søk som reserveløsning',
    PropertyPane_DataSource_Graph: 'Graph API – sanntidsdata fra Azure AD (ingen indekseringsforsinkelse)',
    PropertyPane_DataSource_Search: 'SharePoint-søk – eldre virkemåte',
    PropertyPane_DataSource_Note: 'Graph API anbefales. Det leser direkte fra Azure Active Directory, slik at nye brukere og lederendringer vises umiddelbart. Krever at Microsoft Graph-tillatelser er godkjent i SharePoint-appkatalogen.',

    // ── Property pane: Custom Attributes ──
    PropertyPane_CustomAttributes_Note: 'Egendefinerte attributter krever Microsoft Graph (datakilde: Graph eller Automatisk). SharePoint-søk har ingen generisk måte å lese Entra ID-attributter på.',
    PropertyPane_CustomAttributes_Heading: 'Administrer egendefinerte attributter',
    PropertyPane_CustomAttributes_Empty: 'Ingen egendefinerte attributter er konfigurert.',
    PropertyPane_CustomAttributes_AddButton: '+ Legg til attributt',
    PropertyPane_CustomAttributes_MaxTooltip: 'Maks {max} egendefinerte attributter',
    PropertyPane_CustomAttributes_FieldNameLabel: 'Attributtnavn',
    PropertyPane_CustomAttributes_FieldPlaceholder: 'f.eks. companyName',
    PropertyPane_CustomAttributes_FieldError: 'Bruk employeeId, companyName, city, ... eller extensionAttribute1-15',
    PropertyPane_CustomAttributes_DisplayLabelLabel: 'Visningsnavn',
    PropertyPane_CustomAttributes_LabelPlaceholder: 'f.eks. Kostnadssted',
    PropertyPane_CustomAttributes_RemoveTitle: 'Fjern attributt',
    PropertyPane_CustomAttributes_RemoveAriaLabel: 'Fjern attributt {ordinal}',
    PropertyPane_CustomAttributes_ShowInDirectory: 'Vis i katalog',
    PropertyPane_CustomAttributes_ShowInOrgChart: 'Vis i organisasjonskart',

    // ── Property pane: User Filters ──
    PropertyPane_ExcludedAccounts_Label: 'Ekskluder kontoer',
    PropertyPane_ExcludedAccounts_Placeholder: 'conf-room, noreply, admin@, Tjenestekonto',
    PropertyPane_ExcludedAccounts_Description: 'Kommaseparerte ord eller mønstre (det skilles ikke mellom store og små bokstaver). Enhver bruker hvis visningsnavn, e-post eller UPN inneholder et av disse, skjules i alle visninger.',
    PropertyPane_RestrictTenant_Label: 'Vis kun brukere i denne organisasjonen',
    PropertyPane_RestrictTenant_On: 'På – skjuler kontoer med eksterne e-postdomener (f.eks. gmail.com, hotmail.com)',
    PropertyPane_RestrictTenant_Off: 'Av – alle brukere vises uansett e-postdomene',
    PropertyPane_HideGuest_Label: 'Skjul Azure AD-gjestekontoer',
    PropertyPane_HideGuest_On: 'På – gjestekontoer skjules',
    PropertyPane_HideGuest_Off: 'Av – gjestekontoer vises (med merket Gjest)',
    PropertyPane_HideDisabled_Label: 'Skjul deaktiverte kontoer',
    PropertyPane_HideDisabled_On: 'På – kontoer med blokkert pålogging skjules',
    PropertyPane_HideDisabled_Off: 'Av – deaktiverte kontoer vises (med merket Deaktivert)',
    PropertyPane_HideDisabled_Note: 'Merk: Gjenkjenning av gjeste- og deaktiverte kontoer krever datakilden Graph API. SharePoint-søk returnerer ikke denne informasjonen, så disse to filtrene (og merkene Gjest/Deaktivert) har ingen effekt når data kommer fra søk.',
    PropertyPane_HideNoJobTitle_Label: 'Skjul kontoer uten stillingstittel',
    PropertyPane_HideNoJobTitle_On: 'På – kontoer uten stillingstittel skjules',
    PropertyPane_HideNoJobTitle_Off: 'Av – alle kontoer vises uansett stillingstittel',
    PropertyPane_HideNoDept_Label: 'Skjul kontoer uten avdeling',
    PropertyPane_HideNoDept_On: 'På – kontoer uten avdeling skjules',
    PropertyPane_HideNoDept_Off: 'Av – alle kontoer vises uansett avdeling',

    // ── Property pane: Org Chart ──
    PropertyPane_TopLevelUser_Label: 'Toppnivåbruker (UPN eller e-post)',
    PropertyPane_TopLevelUser_Placeholder: 'ceo@yourcompany.com',
    PropertyPane_TopLevelUser_Description: 'Personen som vises øverst i organisasjonskartet',
    PropertyPane_LevelsBelow_Label: 'Antall nivåer som skal lastes under roten',
    PropertyPane_DottedLine_Label: 'Attributt for stiplet linje-leder',
    PropertyPane_DottedLine_Placeholder: 'extensionAttribute10',
    PropertyPane_DottedLine_Description: "Valgfritt. Navnet på den lokale Azure AD-utvidelsesattributten (extensionAttribute1-15) som lagrer e-post eller UPN for en sekundær leder via \"stiplet linje\". Stiplet linje-relasjoner vises på profilkort. Krever datakilden Graph API.",
    PropertyPane_DefaultZoom_Label: 'Standard zoom for organisasjonskart',
    PropertyPane_Zoom_Auto: 'Standard (Automatisk tilpasning)',
    PropertyPane_Zoom_50: '50 %',
    PropertyPane_Zoom_75: '75 %',
    PropertyPane_Zoom_100: '100 %',
    PropertyPane_Zoom_125: '125 %',
    PropertyPane_Zoom_150: '150 %',

    // ── Property pane: Org Chart Features ──
    PropertyPane_FeatureToggles_Note: 'Vis eller skjul verktøylinjeknapper i organisasjonskartvisningen.',
    PropertyPane_FindMe_Label: 'Knappen Finn meg',
    PropertyPane_LayoutToggle_Label: 'Bytte av layout (drilldown/loddrett/vannrett)',
    PropertyPane_Stats_Label: 'Statistikklinje for organisasjon',
    PropertyPane_DeptFilter_Label: 'Avdelingsfilter',
    PropertyPane_UserFilter_Label: 'Filter for brukertype (medlemmer/gjester)',
    PropertyPane_Visible: 'Synlig',
    PropertyPane_Hidden: 'Skjult',

    // ── Property pane: Directory ──
    PropertyPane_PageSize_Label: 'Maks. antall ansatte per side',
    PropertyPane_PageSize_AriaLabel: 'Maks. antall ansatte per side (10 til 200)',
    PropertyPane_PageSize_Note: 'Kortstørrelse, synlige felt og andre visningsinnstillinger angis per bruker via innstillingstannhjulet i appen.',

    // ── Property pane: Demo ──
    PropertyPane_UseDemoData_Label: 'Bruk demodata',
    PropertyPane_UseDemoData_On: 'På – viser eksempelansatte',
    PropertyPane_UseDemoData_Off: 'Av – direkte Microsoft 365-data',

    // ── Presence status labels ──
    Presence_Available: 'Tilgjengelig',
    Presence_Busy: 'Opptatt',
    Presence_DoNotDisturb: 'Ikke forstyrr',
    Presence_BeRightBack: 'Straks tilbake',
    Presence_Away: 'Borte',
    Presence_Offline: 'Frakoblet',

    // ── Header / top bar ──
    Header_DirectoryLabel: 'Ansattkatalog',
    Header_OrgChartLabel: 'Organisasjonskart',
    Header_SwitchToView: 'Bytt til {view}',
    Header_CompanyLogoAlt: 'Firmalogo',
    Header_RefreshingAria: 'Oppdaterer data',
    Header_RefreshAria: 'Oppdater data',
    Header_RefreshTitle: 'Oppdater data (sist oppdatert {when})',
    Header_NotLoadedYet: 'ikke lastet ennå',
    Header_JustNow: 'akkurat nå',
    Header_MinutesAgo: '{mins} min siden',
    Header_HoursAgo: '{hours} t siden',
    Header_PreferencesTitle: 'Innstillinger',
    Header_PreferencesAria: 'Åpne innstillingspanelet',

    // ── Employee Directory ──
    Directory_LoadingLabel: 'Laster ansatte...',
    Directory_LoadFailedFallback: 'Kontroller at webdelen har tillatelsen User.Read.All.',
    Directory_LoadFailedPrefix: 'Kunne ikke laste ansatte. {detail}',
    Directory_AllDepartments: 'Alle avdelinger',
    Directory_AllOffices: 'Alle kontorer',
    Directory_StatusDisabled: 'Deaktivert',
    Directory_StatusGuest: 'Gjest',
    Directory_PresenceStatus: 'Status: {status}',
    Directory_ChatInTeams: 'Chat i Teams',
    Directory_ChatWithInTeams: 'Chat med {name} i Teams',
    Directory_ManagesCount: 'Er leder for {direct}',
    Directory_ManagesCountWithTotal: 'Er leder for {direct} ({total} totalt)',
    Directory_ReportsCountWithTotal: '{direct} ({total} totalt)',
    Directory_ColumnName: 'Navn',
    Directory_ColumnJobTitle: 'Stillingstittel',
    Directory_ColumnDepartment: 'Avdeling',
    Directory_ColumnOffice: 'Kontor',
    Directory_ColumnEmail: 'E-post',
    Directory_ColumnPhone: 'Telefon',
    Directory_ColumnReports: 'Underordnede',
    Directory_ColumnChat: 'Chat',
    Directory_PrevPage: 'Forrige',
    Directory_NextPage: 'Neste',
    Directory_PreviousPageAria: 'Forrige side',
    Directory_NextPageAria: 'Neste side',
    Directory_SearchPlaceholder: 'Søk etter navn, tittel, e-post eller avdeling...',
    Directory_SearchAria: 'Søk etter personer',
    Directory_FilterByDepartmentAria: 'Filtrer etter avdeling',
    Directory_FilterByOfficeAria: 'Filtrer etter kontor',
    Directory_ClearSearchTitle: 'Fjern søk og alle filtre',
    Directory_ClearButton: 'Fjern',
    Directory_ClearFiltersButton: 'Fjern filtre',
    Directory_ExportCsvTitle: 'Eksporter alle filtrerte resultater til en CSV-fil (åpnes i Excel)',
    Directory_ExportCsvButton: 'Eksporter CSV',
    Directory_ViewModeAria: 'Visningsmodus',
    Directory_CardViewTitle: 'Kortvisning',
    Directory_ListViewTitle: 'Listevisning',
    Directory_AlphabetFilterAria: 'Alfabetfilter',
    Directory_ShowAllTitle: 'Vis alle',
    Directory_OtherLettersTitle: 'Filtrer etter navn som starter med et tall eller annet tegn',
    Directory_FilterByLetterTitle: 'Filtrer etter {letter}',
    Directory_ResultCountSingular: 'person',
    Directory_ResultCountPlural: 'personer',
    Directory_PageOf: ' · side {page} av {totalPages}',
    Directory_FilterActiveSingular: '{count} filter aktivt',
    Directory_FilterActivePlural: '{count} filtre aktive',
    Directory_NoResults: 'Ingen personer funnet',
    Directory_PaginationAria: 'Sideinndeling',

    // ── Org chart toolbar / shared chart chrome ──
    Chart_Layout_Drill: 'Drilldown',
    Chart_Layout_Vertical: 'Ovenfra og ned',
    Chart_Layout_Horizontal: 'Fra venstre til høyre',
    Chart_SearchPlaceholder: 'Søk etter personer...',
    Chart_SearchAria: 'Søk etter personer',
    Chart_MatchSingular: 'resultat i treet',
    Chart_MatchPlural: 'resultater i treet',
    Chart_ResultsListAria: 'Personer',
    Chart_ExpandAll: 'Utvid alle',
    Chart_CollapseAll: 'Skjul alle',
    Chart_Expanding: 'Utvider…',
    Chart_Loading: 'Laster…',
    Chart_FindMeTitle: 'Finn meg i organisasjonskartet',
    Chart_ViewLayoutButton: 'Vis',
    Chart_ViewLayoutTitle: 'Bytt visningslayout',
    Chart_ViewLayoutPanelTitle: 'Visningslayout',
    Chart_StatsSummaryTitle: 'Sammendrag av organisasjonsstatistikk',
    Chart_FilterByDepartmentTitle: 'Filtrer etter avdeling',
    Chart_FilterByDepartmentWithCountAria: 'Filtrer etter avdeling ({count} valgt)',
    Chart_FilterByDepartmentPanelTitle: 'Filtrer etter avdeling',
    Chart_ClearAllFilters: 'Fjern alle filtre',
    Chart_FilterUserTypesTitle: 'Filtrer brukertyper',
    Chart_DownloadPdfTitle: 'Last ned som PDF',
    Chart_DownloadCsvTitle: 'Last ned som CSV-regneark',
    Chart_ResetRootTitle: 'Tilbakestill til standardrot',
    Chart_ViewFromPersonPlaceholder: 'Vis fra person…',
    Chart_ViewFromPersonAria: 'Vis organisasjonskartet fra en person',
    Chart_ZoomOutTitle: 'Zoom ut',
    Chart_ZoomInTitle: 'Zoom inn',
    Chart_ZoomResetTitle: 'Tilbakestill zoom',
    Chart_ShowInChartAria: 'Vis i diagram',
    Chart_ShowInChartTitle: 'Vis i diagram',
    Chart_FilterMembers: 'Vanlige medlemmer',
    Chart_FilterGuests: 'Gjestebrukere',
    Chart_FilterDisabled: 'Deaktiverte kontoer',
    Chart_SetupTitle: 'Konfigurer organisasjonskartet',
    Chart_SetupSubtitle: 'Angi e-post eller UPN for toppnivåpersonen for å komme i gang.',
    Chart_SetupPlaceholder: 'ceo@company.com',
    Chart_SetupInputAria: 'Toppnivåpersonens e-post eller UPN',
    Chart_SetupLoadButton: 'Last inn',
    Chart_SetupHint: 'Du kan også angi dette permanent i webdelinnstillingene (administrator).',
    Chart_BuildingLabel: 'Bygger organisasjonskart...',
    Chart_RetryButton: 'Prøv igjen',
    Chart_NotFoundFromSetup: 'Brukeren "{identifier}" ble ikke funnet.',
    Chart_NotFoundWithSettings: 'Brukeren "{identifier}" ble ikke funnet. Kontroller UPN eller e-post i innstillingene.',
    Chart_LoadFailedGeneric: 'Kunne ikke laste organisasjonskartet.{detail}',
    Chart_LoadFailedPermissions: ' Kontroller tillatelser.',
    Chart_LoadFailedForPerson: 'Kunne ikke laste organisasjonskartet for denne personen.',
    Chart_FindMeNotFound: 'Kontoen din ble ikke funnet i denne organisasjonen.',
    Chart_StatPeople: 'Personer',
    Chart_StatMembers: 'Medlemmer',
    Chart_StatGuests: 'Gjester',
    Chart_StatDepts: 'Avd.',
    Chart_ReportingLineAria: 'Rapporteringslinje',
    Chart_BackToFullOrgTitle: 'Tilbake til fullt organisasjonskart',
    Chart_FullOrgLabel: 'Full organisasjon',
    Chart_FocusOnPerson: 'Fokuser på {name}',
    Chart_OrgChartAria: 'Organisasjonskart',
    Chart_ExportNote_DrillLevel: 'Gjeldende drilldown-nivå (ett nivå med direkte underordnede)',
    Chart_ExportNote_PartialLevels: 'Inkluderer kun lastede nivåer – bruk Utvid alle før eksport for å inkludere dypere nivåer',
    Chart_AllowPopupsForPdf: 'Tillat sprettoppvinduer for å eksportere PDF.',

    // ── Person card ──
    PersonCard_ProfileAria: 'Profil: {name}',
    PersonCard_CloseTitle: 'Lukk',
    PersonCard_CloseAria: 'Lukk profil',
    PersonCard_StatusDisabled: 'Deaktivert',
    PersonCard_StatusGuest: 'Gjest',
    PersonCard_DirectReportSingular: '{count} direkte underordnet',
    PersonCard_DirectReportPlural: '{count} direkte underordnede',
    PersonCard_TotalSuffix: ' · {total} totalt',
    PersonCard_CopyEmailTitle: 'Kopier e-postadresse',
    PersonCard_EmailCopiedAria: 'E-postadresse kopiert',
    PersonCard_ReportsTo: 'Rapporterer til',
    PersonCard_FocusOnPerson: 'Fokuser på {name}',
    PersonCard_FocusOrgChartOnPerson: 'Fokuser organisasjonskartet på {name}',
    PersonCard_DottedLine: 'Stiplet linje',
    PersonCard_DottedLineManager: 'Stiplet linje-leder: {name}',
    PersonCard_DottedLineReport: 'Stiplet linje-underordnet: {name}',
    PersonCard_ChatButton: 'Chat',
    PersonCard_EmailButton: 'E-post',
    PersonCard_FocusButton: 'Fokuser',
    PersonCard_FocusTitle: 'Fokuser organisasjonskartet på denne personen',

    // ── Org node card ──
    OrgNode_ViewProfile: 'Vis {name}s profil',
    OrgNode_FocusOrgChartOn: 'Fokuser organisasjonskartet på {name}',
    OrgNode_Collapse: 'Skjul',
    OrgNode_Expand: 'Utvid',
    OrgNode_DirectReportsSuffix: '{name}s direkte underordnede',
    OrgNode_StatusDisabled: 'Deaktivert',
    OrgNode_StatusGuest: 'Gjest',
    OrgNode_TotalReportsAcrossLevels: '{count} personer på tvers av alle nivåer under {name}',

    // ── Drill view ──
    Drill_ReportingLineAria: 'Rapporteringslinje',
    Drill_BackToTopTitle: 'Tilbake til toppen',
    Drill_BackToTopAria: 'Tilbake til toppen av organisasjonskartet',
    Drill_GoBackTo: 'Gå tilbake til {name}',
    Drill_ViewProfileTitle: 'Vis profil',
    Drill_ViewProfileAria: 'Vis {name}s profil',
    Drill_ProfileButton: 'Profil',
    Drill_LoadingLabel: 'Laster...',
    Drill_DirectReports: 'Direkte underordnede',
    Drill_DirectReportsOfAria: 'Direkte underordnede av {name}',
    Drill_DirectReportsAria: 'Direkte underordnede',
    Drill_ViewPersonProfile: 'Vis {name}s profil',
    Drill_ShowPersonReports: 'Vis {name}s direkte underordnede',
    Drill_NoDirectReports: 'Ingen direkte underordnede',

    // ── Settings panel ──
    Settings_AlphabetFirstName: 'Fornavn',
    Settings_AlphabetLastName: 'Etternavn',
    Settings_CardSizeSmall: 'Liten – kompakt, flere kort synlige',
    Settings_CardSizeMedium: 'Middels – balansert',
    Settings_CardSizeLarge: 'Stor – romslig, færre kort',
    Settings_HeaderText: 'Innstillinger',
    Settings_SaveButton: 'Lagre',
    Settings_CancelButton: 'Avbryt',
    Settings_DiscardButton: 'Forkast endringer',
    Settings_SectionDirectory: 'Katalog',
    Settings_AlphabetFilterByLabel: 'Alfabetfilter etter',
    Settings_CardSizeLabel: 'Kortstørrelse',
    Settings_FontSizeLabel: 'Skriftstørrelse',
    Settings_SectionCardsAndFields: 'Kort og felt',
    Settings_ShowOnCardsLabel: 'Vis på ansattkort:',
    Settings_EmailAddressLabel: 'E-postadresse',
    Settings_PhoneNumberLabel: 'Telefonnummer',
    Settings_DepartmentLabel: 'Avdeling',
    Settings_OfficeLocationLabel: 'Kontorsted',
    Settings_SectionOrgChart: 'Organisasjonskart',
    Settings_ManagerLevelsLabel: 'Ledernivåer vist ved fokus på en person: {levels}',
    Settings_CompactCardsLabel: 'Kompakte kort',
    Settings_CompactCardsOn: 'På – mindre kort, flere synlige samtidig',
    Settings_CompactCardsOff: 'Av – standardstørrelse',
    Settings_Hint: 'Disse innstillingene lagres i nettleseren din og gjelder kun for deg. Diagramtema, standardvisning og layout konfigureres av SharePoint-administratoren din.',
    Settings_SectionDemoData: 'Demodata',
    Settings_DatasetSizeLabel: 'Datasettstørrelse',
    Settings_PeopleCountSuffix: '{count} personer',

    // ── Export (CSV / PDF) ──
    Export_ColumnName: 'Navn',
    Export_ColumnJobTitle: 'Stillingstittel',
    Export_ColumnDepartment: 'Avdeling',
    Export_ColumnOffice: 'Kontor',
    Export_ColumnEmail: 'E-post',
    Export_ColumnPhone: 'Telefon',
    Export_ColumnManager: 'Leder',
    Export_ColumnLevel: 'Nivå',
    Export_PdfDocumentTitle: 'Organisasjonskart',
    Export_PdfHeading: 'Organisasjonskart',
    Export_PdfRootLabel: 'Rot: {name}',
  };
});
