define([], function () {
  return {
    // ── Property pane: pane header / groups ──
    PropertyPane_HeaderDescription: 'Instellingen voor Smart Org Chart',
    PropertyPane_Group_General: 'Algemeen',
    PropertyPane_Group_Branding: 'Huisstijl',
    PropertyPane_Group_VisualStyle: 'Visuele stijl',
    PropertyPane_Group_DataSource: 'Gegevensbron',
    PropertyPane_Group_CustomAttributes: 'Aangepaste kenmerken',
    PropertyPane_Group_UserFilters: 'Gebruikersfilters',
    PropertyPane_Group_OrgChart: 'Organigram',
    PropertyPane_Group_OrgChartFeatures: 'Organigramfuncties',
    PropertyPane_Group_Directory: 'Personeelsgids',
    PropertyPane_Group_Demo: 'Demo',

    // ── Property pane: General ──
    PropertyPane_DefaultView_Label: 'Standaardweergave',

    // ── Property pane: Branding ──
    PropertyPane_AppTitle_Label: 'Apptitel',
    PropertyPane_AppTitle_Placeholder: 'Contoso Organigram',
    PropertyPane_AppTitle_Description: 'Wordt weergegeven in de kopbalk naast de naam van de weergave',
    PropertyPane_LogoUrl_Label: 'Logo-URL',
    PropertyPane_LogoUrl_Placeholder: 'https://contoso.sharepoint.com/sites/uwsite/SiteAssets/logo.png',
    PropertyPane_LogoUrl_Description: "Volledige URL naar een PNG-, SVG- of JPG-afbeelding. Tip: open het afbeeldingsbestand in uw browser en kopieer de URL uit de adresbalk. URL's van 'Koppeling kopiëren' werken niet.",
    PropertyPane_DirectoryLabel_Label: 'Label voor de weergave Personeelsgids',
    PropertyPane_OrgChartLabel_Label: 'Label voor de weergave Organigram',
    PropertyPane_ViewLabel_Description: 'Laat leeg om de standaardnaam te gebruiken, of typ "[blank]" om het label volledig te verbergen.',

    // ── Property pane: Visual Style ──
    PropertyPane_ChartTheme_Label: 'Thema van het organigram',
    PropertyPane_Theme_Modern: 'Modern — afdelingskleuren op wit',
    PropertyPane_Theme_Minimal: 'Minimalistisch — vlak en weinig contrast',
    PropertyPane_Theme_Corporate: 'Zakelijk — uniform blauw',
    PropertyPane_Theme_Dark: 'Donker — donkere marineblauwe achtergrond',
    PropertyPane_Theme_Custom: 'Aangepast — kies uw eigen kleur',
    PropertyPane_AccentColor_Label: 'Aangepaste accentkleur',
    PropertyPane_AccentColor_PickerAriaLabel: 'Kleurkiezer voor accentkleur',
    PropertyPane_AccentColor_HexLabel: 'Hex',
    PropertyPane_AccentColor_HexAriaLabel: 'Hexadecimale waarde van de accentkleur',
    PropertyPane_AccentColor_RgbLabel: 'RGB',
    PropertyPane_AccentColor_ChannelAriaLabel: 'Kanaal {name} (0 tot 255)',
    PropertyPane_AccentColor_ContrastWithWhite: 'Contrast met wit: {ratio}:1 ({passes})',
    PropertyPane_AccentColor_PassesAA: 'voldoet aan AA',
    PropertyPane_AccentColor_LargeTextOnly: 'alleen grote tekst',
    PropertyPane_AccentColor_LowContrast: 'laag contrast',
    PropertyPane_AccentColor_DarkTextNote: 'Tekst op deze kleur gebruikt donkere tekst voor een betere leesbaarheid.',
    PropertyPane_AccentColor_DarkerShadeNote: 'Titels en koppelingen gebruiken een donkerdere tint ({hex}) voor een betere leesbaarheid.',
    PropertyPane_AccentColor_InvalidHex: '"{typed}" is geen geldige hexadecimale kleur. Gebruik een waarde zoals #0078d4 of #07d.',
    PropertyPane_DefaultFontSize_Label: 'Standaard lettergrootte',
    PropertyPane_FontSize_75: '75% — Extra klein',
    PropertyPane_FontSize_85: '85% — Klein',
    PropertyPane_FontSize_100: '100% — Normaal',
    PropertyPane_FontSize_115: '115% — Groot',
    PropertyPane_FontSize_130: '130% — Extra groot',
    PropertyPane_FontSize_150: '150% — XXL',
    PropertyPane_FontSize_175: '175% — XXXL',
    PropertyPane_DefaultLayout_Label: 'Standaardindeling van het organigram',
    PropertyPane_Layout_Drill: 'Detailweergave',
    PropertyPane_Layout_Vertical: 'Van boven naar beneden',
    PropertyPane_Layout_Horizontal: 'Van links naar rechts',

    // ── Property pane: Data Source ──
    PropertyPane_DataSource_Label: 'Bron voor het laden van gebruikers- en organisatiegegevens',
    PropertyPane_DataSource_Auto: 'Automatisch — Graph API, met SharePoint Search als terugval',
    PropertyPane_DataSource_Graph: 'Graph API — actuele Azure AD-gegevens (geen indexeringsvertraging)',
    PropertyPane_DataSource_Search: 'SharePoint Search — verouderd gedrag',
    PropertyPane_DataSource_Note: 'Graph API wordt aanbevolen. Deze leest rechtstreeks uit Azure Active Directory, zodat nieuwe gebruikers en wijzigingen van manager onmiddellijk zichtbaar zijn. Hiervoor moeten Microsoft Graph-machtigingen zijn goedgekeurd in de SharePoint-appcatalogus.',

    // ── Property pane: Custom Attributes ──
    PropertyPane_CustomAttributes_Note: 'Aangepaste kenmerken vereisen Microsoft Graph (gegevensbron: Graph of Automatisch). SharePoint Search heeft geen generieke manier om Entra ID-kenmerken te lezen.',
    PropertyPane_CustomAttributes_Heading: 'Aangepaste kenmerken beheren',
    PropertyPane_CustomAttributes_Empty: 'Er zijn geen aangepaste kenmerken geconfigureerd.',
    PropertyPane_CustomAttributes_AddButton: '+ Kenmerk toevoegen',
    PropertyPane_CustomAttributes_MaxTooltip: 'Maximaal {max} aangepaste kenmerken',
    PropertyPane_CustomAttributes_FieldNameLabel: 'Kenmerknaam',
    PropertyPane_CustomAttributes_FieldPlaceholder: 'bijv. companyName',
    PropertyPane_CustomAttributes_FieldError: 'Gebruik employeeId, companyName, city, ... of extensionAttribute1-15',
    PropertyPane_CustomAttributes_DisplayLabelLabel: 'Weergavelabel',
    PropertyPane_CustomAttributes_LabelPlaceholder: 'bijv. Kostenplaats',
    PropertyPane_CustomAttributes_RemoveTitle: 'Kenmerk verwijderen',
    PropertyPane_CustomAttributes_RemoveAriaLabel: 'Kenmerk {ordinal} verwijderen',
    PropertyPane_CustomAttributes_ShowInDirectory: 'Weergeven in Personeelsgids',
    PropertyPane_CustomAttributes_ShowInOrgChart: 'Weergeven in Organigram',

    // ── Property pane: User Filters ──
    PropertyPane_ExcludedAccounts_Label: 'Accounts uitsluiten',
    PropertyPane_ExcludedAccounts_Placeholder: 'vergaderzaal, noreply, admin@, Serviceaccount',
    PropertyPane_ExcludedAccounts_Description: "Door komma's gescheiden woorden of patronen (hoofdlettergevoeligheid speelt geen rol). Elke gebruiker van wie de weergavenaam, het e-mailadres of de UPN een van deze termen bevat, wordt in alle weergaven verborgen.",
    PropertyPane_RestrictTenant_Label: 'Alleen tenantgebruikers weergeven',
    PropertyPane_RestrictTenant_On: 'Aan — verbergt accounts met externe e-maildomeinen (bijv. gmail.com, hotmail.com)',
    PropertyPane_RestrictTenant_Off: 'Uit — alle gebruikers worden weergegeven, ongeacht het e-maildomein',
    PropertyPane_HideGuest_Label: 'Azure AD-gastaccounts verbergen',
    PropertyPane_HideGuest_On: 'Aan — gastaccounts verborgen',
    PropertyPane_HideGuest_Off: 'Uit — gastaccounts zichtbaar (weergegeven met het label Gast)',
    PropertyPane_HideDisabled_Label: 'Uitgeschakelde accounts verbergen',
    PropertyPane_HideDisabled_On: 'Aan — accounts met geblokkeerde aanmelding verborgen',
    PropertyPane_HideDisabled_Off: 'Uit — uitgeschakelde accounts zichtbaar (weergegeven met het label Uitgeschakeld)',
    PropertyPane_HideDisabled_Note: 'Opmerking: detectie van gast- en uitgeschakelde accounts vereist de Graph API-gegevensbron. SharePoint Search geeft deze informatie niet terug, dus deze twee filters (en de labels Gast/Uitgeschakeld) hebben geen effect wanneer de gegevens afkomstig zijn uit Search.',
    PropertyPane_HideNoJobTitle_Label: 'Accounts zonder functietitel verbergen',
    PropertyPane_HideNoJobTitle_On: 'Aan — accounts zonder functietitel verborgen',
    PropertyPane_HideNoJobTitle_Off: 'Uit — alle accounts worden weergegeven, ongeacht de functietitel',
    PropertyPane_HideNoDept_Label: 'Accounts zonder afdeling verbergen',
    PropertyPane_HideNoDept_On: 'Aan — accounts zonder afdeling verborgen',
    PropertyPane_HideNoDept_Off: 'Uit — alle accounts worden weergegeven, ongeacht de afdeling',

    // ── Property pane: Org Chart ──
    PropertyPane_TopLevelUser_Label: 'Gebruiker op het hoogste niveau (UPN of e-mailadres)',
    PropertyPane_TopLevelUser_Placeholder: 'ceo@uwbedrijf.com',
    PropertyPane_TopLevelUser_Description: 'De persoon die wordt weergegeven bij de basis van het organigram',
    PropertyPane_LevelsBelow_Label: 'Aantal te laden niveaus onder de basis',
    PropertyPane_DottedLine_Label: 'Kenmerk voor stippellijnmanager',
    PropertyPane_DottedLine_Placeholder: 'extensionAttribute10',
    PropertyPane_DottedLine_Description: 'Optioneel. Naam van het on-premises uitbreidingskenmerk van Azure AD (extensionAttribute1-15) waarin het e-mailadres of de UPN van een secundaire "stippellijn"-manager wordt opgeslagen. Stippellijnrelaties worden weergegeven op profielkaarten. Vereist de Graph API-gegevensbron.',
    PropertyPane_DefaultZoom_Label: 'Standaardzoomniveau van het organigram',
    PropertyPane_Zoom_Auto: 'Standaard (automatisch aanpassen)',
    PropertyPane_Zoom_50: '50%',
    PropertyPane_Zoom_75: '75%',
    PropertyPane_Zoom_100: '100%',
    PropertyPane_Zoom_125: '125%',
    PropertyPane_Zoom_150: '150%',

    // ── Property pane: Org Chart Features ──
    PropertyPane_FeatureToggles_Note: 'Werkbalkknoppen in de weergave van het organigram weergeven of verbergen.',
    PropertyPane_FindMe_Label: 'Knop Zoek mij',
    PropertyPane_LayoutToggle_Label: 'Indelingsschakelaar (detail / verticaal / horizontaal)',
    PropertyPane_Stats_Label: 'Statistiekenbalk van de organisatie',
    PropertyPane_DeptFilter_Label: 'Afdelingsfilter',
    PropertyPane_UserFilter_Label: 'Filter voor gebruikerstype (leden / gasten)',
    PropertyPane_Visible: 'Zichtbaar',
    PropertyPane_Hidden: 'Verborgen',

    // ── Property pane: Directory ──
    PropertyPane_PageSize_Label: 'Maximum aantal medewerkers per pagina',
    PropertyPane_PageSize_AriaLabel: 'Maximum aantal medewerkers per pagina (10 tot 200)',
    PropertyPane_PageSize_Note: 'Kaartgrootte, zichtbare velden en andere weergavevoorkeuren worden per gebruiker ingesteld via het tandwielpictogram Instellingen in de app.',

    // ── Property pane: Demo ──
    PropertyPane_UseDemoData_Label: 'Demogegevens gebruiken',
    PropertyPane_UseDemoData_On: 'Aan — voorbeeldmedewerkers worden weergegeven',
    PropertyPane_UseDemoData_Off: 'Uit — actuele Microsoft 365-gegevens',

    // ── Presence status labels ──
    Presence_Available: 'Beschikbaar',
    Presence_Busy: 'Bezet',
    Presence_DoNotDisturb: 'Niet storen',
    Presence_BeRightBack: 'Zo terug',
    Presence_Away: 'Afwezig',
    Presence_Offline: 'Offline',

    // ── Header / top bar ──
    Header_DirectoryLabel: 'Personeelsgids',
    Header_OrgChartLabel: 'Organigram',
    Header_SwitchToView: 'Overschakelen naar {view}',
    Header_CompanyLogoAlt: 'Bedrijfslogo',
    Header_RefreshingAria: 'Gegevens worden vernieuwd',
    Header_RefreshAria: 'Gegevens vernieuwen',
    Header_RefreshTitle: 'Gegevens vernieuwen (laatst bijgewerkt {when})',
    Header_NotLoadedYet: 'nog niet geladen',
    Header_JustNow: 'zojuist',
    Header_MinutesAgo: '{mins} min geleden',
    Header_HoursAgo: '{hours} uur geleden',
    Header_PreferencesTitle: 'Voorkeuren',
    Header_PreferencesAria: 'Voorkeurenpaneel openen',

    // ── Employee Directory ──
    Directory_LoadingLabel: 'Medewerkers worden geladen...',
    Directory_LoadFailedFallback: 'Controleer of het webonderdeel over de machtiging User.Read.All beschikt.',
    Directory_LoadFailedPrefix: 'Medewerkers laden is mislukt. {detail}',
    Directory_AllDepartments: 'Alle afdelingen',
    Directory_AllOffices: 'Alle kantoren',
    Directory_StatusDisabled: 'Uitgeschakeld',
    Directory_StatusGuest: 'Gast',
    Directory_PresenceStatus: 'Status: {status}',
    Directory_ChatInTeams: 'Chatten in Teams',
    Directory_ChatWithInTeams: 'Chatten met {name} in Teams',
    Directory_ManagesCount: 'Geeft leiding aan {direct}',
    Directory_ManagesCountWithTotal: 'Geeft leiding aan {direct} ({total} totaal)',
    Directory_ReportsCountWithTotal: '{direct} ({total} totaal)',
    Directory_ColumnName: 'Naam',
    Directory_ColumnJobTitle: 'Functietitel',
    Directory_ColumnDepartment: 'Afdeling',
    Directory_ColumnOffice: 'Kantoor',
    Directory_ColumnEmail: 'E-mail',
    Directory_ColumnPhone: 'Telefoon',
    Directory_ColumnReports: 'Rapportages',
    Directory_ColumnChat: 'Chat',
    Directory_PrevPage: 'Vorige',
    Directory_NextPage: 'Volgende',
    Directory_PreviousPageAria: 'Vorige pagina',
    Directory_NextPageAria: 'Volgende pagina',
    Directory_SearchPlaceholder: 'Zoeken op naam, functie, e-mail of afdeling...',
    Directory_SearchAria: 'Personen zoeken',
    Directory_FilterByDepartmentAria: 'Filteren op afdeling',
    Directory_FilterByOfficeAria: 'Filteren op kantoor',
    Directory_ClearSearchTitle: 'Zoekopdracht en alle filters wissen',
    Directory_ClearButton: 'Wissen',
    Directory_ClearFiltersButton: 'Filters wissen',
    Directory_ExportCsvTitle: 'Alle gefilterde resultaten exporteren naar een CSV-bestand (wordt geopend in Excel)',
    Directory_ExportCsvButton: 'CSV exporteren',
    Directory_ViewModeAria: 'Weergavemodus',
    Directory_CardViewTitle: 'Kaartweergave',
    Directory_ListViewTitle: 'Lijstweergave',
    Directory_AlphabetFilterAria: 'Alfabetfilter',
    Directory_ShowAllTitle: 'Alles weergeven',
    Directory_OtherLettersTitle: 'Filteren op namen die beginnen met een cijfer of ander teken',
    Directory_FilterByLetterTitle: 'Filteren op {letter}',
    Directory_ResultCountSingular: 'persoon',
    Directory_ResultCountPlural: 'personen',
    Directory_PageOf: ' · pagina {page} van {totalPages}',
    Directory_FilterActiveSingular: '{count} filter actief',
    Directory_FilterActivePlural: '{count} filters actief',
    Directory_NoResults: 'Geen personen gevonden',
    Directory_PaginationAria: 'Paginering',

    // ── Org chart toolbar / shared chart chrome ──
    Chart_Layout_Drill: 'Detailweergave',
    Chart_Layout_Vertical: 'Van boven naar beneden',
    Chart_Layout_Horizontal: 'Van links naar rechts',
    Chart_SearchPlaceholder: 'Personen zoeken...',
    Chart_SearchAria: 'Personen zoeken',
    Chart_MatchSingular: 'overeenkomst in de structuur',
    Chart_MatchPlural: 'overeenkomsten in de structuur',
    Chart_ResultsListAria: 'Personen',
    Chart_ExpandAll: 'Alles uitvouwen',
    Chart_CollapseAll: 'Alles samenvouwen',
    Chart_Expanding: 'Bezig met uitvouwen…',
    Chart_Loading: 'Bezig met laden…',
    Chart_FindMeTitle: 'Zoek mij in het organigram',
    Chart_ViewLayoutButton: 'Weergave',
    Chart_ViewLayoutTitle: 'Weergave-indeling wijzigen',
    Chart_ViewLayoutPanelTitle: 'Weergave-indeling',
    Chart_StatsSummaryTitle: 'Samenvatting van organisatiestatistieken',
    Chart_FilterByDepartmentTitle: 'Filteren op afdeling',
    Chart_FilterByDepartmentWithCountAria: 'Filteren op afdeling ({count} geselecteerd)',
    Chart_FilterByDepartmentPanelTitle: 'Filteren op afdeling',
    Chart_ClearAllFilters: 'Alle filters wissen',
    Chart_FilterUserTypesTitle: 'Gebruikerstypen filteren',
    Chart_DownloadPdfTitle: 'Downloaden als PDF',
    Chart_DownloadCsvTitle: 'Downloaden als CSV-spreadsheet',
    Chart_ResetRootTitle: 'Terugzetten naar standaardbasis',
    Chart_ViewFromPersonPlaceholder: 'Weergeven vanaf persoon…',
    Chart_ViewFromPersonAria: 'Het organigram vanaf een persoon weergeven',
    Chart_ZoomOutTitle: 'Uitzoomen',
    Chart_ZoomInTitle: 'Inzoomen',
    Chart_ZoomResetTitle: 'Zoomniveau opnieuw instellen',
    Chart_ShowInChartAria: 'Weergeven in organigram',
    Chart_ShowInChartTitle: 'Weergeven in organigram',
    Chart_FilterMembers: 'Gewone leden',
    Chart_FilterGuests: 'Gastgebruikers',
    Chart_FilterDisabled: 'Uitgeschakelde accounts',
    Chart_SetupTitle: 'Het organigram instellen',
    Chart_SetupSubtitle: 'Voer het e-mailadres of de UPN van de persoon op het hoogste niveau in om te beginnen.',
    Chart_SetupPlaceholder: 'ceo@bedrijf.com',
    Chart_SetupInputAria: 'E-mailadres of UPN van de persoon op het hoogste niveau',
    Chart_SetupLoadButton: 'Laden',
    Chart_SetupHint: 'U kunt dit ook permanent instellen in de instellingen van het webonderdeel (beheerder).',
    Chart_BuildingLabel: 'Organigram wordt opgebouwd...',
    Chart_RetryButton: 'Opnieuw proberen',
    Chart_NotFoundFromSetup: 'Gebruiker "{identifier}" niet gevonden.',
    Chart_NotFoundWithSettings: 'Gebruiker "{identifier}" niet gevonden. Controleer de UPN of het e-mailadres bij Instellingen.',
    Chart_LoadFailedGeneric: 'Het laden van het organigram is mislukt.{detail}',
    Chart_LoadFailedPermissions: ' Controleer de machtigingen.',
    Chart_LoadFailedForPerson: 'Het laden van het organigram voor deze persoon is mislukt.',
    Chart_FindMeNotFound: 'Uw account is niet gevonden in deze organisatie.',
    Chart_StatPeople: 'Personen',
    Chart_StatMembers: 'Leden',
    Chart_StatGuests: 'Gasten',
    Chart_StatDepts: 'Afd.',
    Chart_ReportingLineAria: 'Rapportagelijn',
    Chart_BackToFullOrgTitle: 'Terug naar het volledige organigram',
    Chart_FullOrgLabel: 'Volledige organisatie',
    Chart_FocusOnPerson: 'Focussen op {name}',
    Chart_OrgChartAria: 'Organigram',
    Chart_ExportNote_DrillLevel: 'Huidig detailniveau (één niveau van directe rapportages)',
    Chart_ExportNote_PartialLevels: 'Bevat alleen geladen niveaus — gebruik Alles uitvouwen vóór het exporteren om diepere niveaus op te nemen',
    Chart_AllowPopupsForPdf: 'Sta pop-ups toe om de PDF te exporteren.',

    // ── Person card ──
    PersonCard_ProfileAria: 'Profiel: {name}',
    PersonCard_CloseTitle: 'Sluiten',
    PersonCard_CloseAria: 'Profiel sluiten',
    PersonCard_StatusDisabled: 'Uitgeschakeld',
    PersonCard_StatusGuest: 'Gast',
    PersonCard_DirectReportSingular: '{count} directe rapportage',
    PersonCard_DirectReportPlural: '{count} directe rapportages',
    PersonCard_TotalSuffix: ' · {total} totaal',
    PersonCard_CopyEmailTitle: 'E-mailadres kopiëren',
    PersonCard_EmailCopiedAria: 'E-mailadres gekopieerd',
    PersonCard_ReportsTo: 'Rapporteert aan',
    PersonCard_FocusOnPerson: 'Focussen op {name}',
    PersonCard_FocusOrgChartOnPerson: 'Organigram focussen op {name}',
    PersonCard_DottedLine: 'Stippellijn',
    PersonCard_DottedLineManager: 'Stippellijnmanager: {name}',
    PersonCard_DottedLineReport: 'Stippellijnrapportage: {name}',
    PersonCard_ChatButton: 'Chat',
    PersonCard_EmailButton: 'E-mail',
    PersonCard_FocusButton: 'Focussen',
    PersonCard_FocusTitle: 'Organigram op deze persoon focussen',

    // ── Org node card ──
    OrgNode_ViewProfile: 'Profiel van {name} weergeven',
    OrgNode_FocusOrgChartOn: 'Organigram focussen op {name}',
    OrgNode_Collapse: 'Samenvouwen',
    OrgNode_Expand: 'Uitvouwen',
    OrgNode_DirectReportsSuffix: 'Directe rapportages van {name}',
    OrgNode_StatusDisabled: 'Uitgeschakeld',
    OrgNode_StatusGuest: 'Gast',
    OrgNode_TotalReportsAcrossLevels: '{count} personen op alle niveaus onder {name}',

    // ── Drill view ──
    Drill_ReportingLineAria: 'Rapportagelijn',
    Drill_BackToTopTitle: 'Terug naar boven',
    Drill_BackToTopAria: 'Terug naar de bovenkant van het organigram',
    Drill_GoBackTo: 'Terug naar {name}',
    Drill_ViewProfileTitle: 'Profiel weergeven',
    Drill_ViewProfileAria: 'Profiel van {name} weergeven',
    Drill_ProfileButton: 'Profiel',
    Drill_LoadingLabel: 'Bezig met laden...',
    Drill_DirectReports: 'Directe rapportages',
    Drill_DirectReportsOfAria: 'Directe rapportages van {name}',
    Drill_DirectReportsAria: 'Directe rapportages',
    Drill_ViewPersonProfile: 'Profiel van {name} weergeven',
    Drill_ShowPersonReports: 'Directe rapportages van {name} weergeven',
    Drill_NoDirectReports: 'Geen directe rapportages',

    // ── Settings panel ──
    Settings_AlphabetFirstName: 'Voornaam',
    Settings_AlphabetLastName: 'Achternaam',
    Settings_CardSizeSmall: 'Klein — compact, meer kaarten zichtbaar',
    Settings_CardSizeMedium: 'Middel — evenwichtig',
    Settings_CardSizeLarge: 'Groot — ruim, minder kaarten',
    Settings_HeaderText: 'Voorkeuren',
    Settings_SaveButton: 'Opslaan',
    Settings_CancelButton: 'Annuleren',
    Settings_DiscardButton: 'Wijzigingen verwerpen',
    Settings_SectionDirectory: 'Personeelsgids',
    Settings_AlphabetFilterByLabel: 'Alfabetfilter op',
    Settings_CardSizeLabel: 'Kaartgrootte',
    Settings_FontSizeLabel: 'Lettergrootte',
    Settings_SectionCardsAndFields: 'Kaarten en velden',
    Settings_ShowOnCardsLabel: 'Weergeven op medewerkerskaarten:',
    Settings_EmailAddressLabel: 'E-mailadres',
    Settings_PhoneNumberLabel: 'Telefoonnummer',
    Settings_DepartmentLabel: 'Afdeling',
    Settings_OfficeLocationLabel: 'Kantoorlocatie',
    Settings_SectionOrgChart: 'Organigram',
    Settings_ManagerLevelsLabel: 'Managerniveaus weergegeven bij het focussen op een persoon: {levels}',
    Settings_CompactCardsLabel: 'Compacte kaarten',
    Settings_CompactCardsOn: 'Aan — kleinere kaarten, meer tegelijk zichtbaar',
    Settings_CompactCardsOff: 'Uit — standaardgrootte',
    Settings_Hint: 'Deze voorkeuren worden opgeslagen in uw browser en gelden alleen voor u. Het thema van het organigram, de standaardweergave en de indeling worden geconfigureerd door uw SharePoint-beheerder.',
    Settings_SectionDemoData: 'Demogegevens',
    Settings_DatasetSizeLabel: 'Omvang van de gegevensset',
    Settings_PeopleCountSuffix: '{count} personen',

    // ── Export (CSV / PDF) ──
    Export_ColumnName: 'Naam',
    Export_ColumnJobTitle: 'Functietitel',
    Export_ColumnDepartment: 'Afdeling',
    Export_ColumnOffice: 'Kantoor',
    Export_ColumnEmail: 'E-mail',
    Export_ColumnPhone: 'Telefoon',
    Export_ColumnManager: 'Manager',
    Export_ColumnLevel: 'Niveau',
    Export_PdfDocumentTitle: 'Organigram',
    Export_PdfHeading: 'Organigram',
    Export_PdfRootLabel: 'Basis: {name}',
  };
});
