define([], function () {
  return {
    // ── Property pane: pane header / groups ──
    PropertyPane_HeaderDescription: 'Ustawienia Smart Org Chart',
    PropertyPane_Group_General: 'Ogólne',
    PropertyPane_Group_Branding: 'Branding',
    PropertyPane_Group_VisualStyle: 'Styl wizualny',
    PropertyPane_Group_DataSource: 'Źródło danych',
    PropertyPane_Group_CustomAttributes: 'Atrybuty niestandardowe',
    PropertyPane_Group_UserFilters: 'Filtry użytkowników',
    PropertyPane_Group_OrgChart: 'Schemat organizacyjny',
    PropertyPane_Group_OrgChartFeatures: 'Funkcje schematu organizacyjnego',
    PropertyPane_Group_Directory: 'Katalog pracowników',
    PropertyPane_Group_Demo: 'Dane demonstracyjne',

    // ── Property pane: General ──
    PropertyPane_DefaultView_Label: 'Widok domyślny',

    // ── Property pane: Branding ──
    PropertyPane_AppTitle_Label: 'Tytuł aplikacji',
    PropertyPane_AppTitle_Placeholder: 'Contoso Org Chart',
    PropertyPane_AppTitle_Description: 'Wyświetlany na pasku nagłówka obok nazwy widoku',
    PropertyPane_LogoUrl_Label: 'Adres URL logo',
    PropertyPane_LogoUrl_Placeholder: 'https://contoso.sharepoint.com/sites/yoursite/SiteAssets/logo.png',
    PropertyPane_LogoUrl_Description: 'Pełny adres URL obrazu w formacie PNG, SVG lub JPG. Wskazówka: otwórz plik obrazu w przeglądarce i skopiuj adres z paska adresu. Linki udostępniane opcją „Kopiuj link” nie będą działać.',
    PropertyPane_DirectoryLabel_Label: 'Etykieta widoku „Katalog pracowników”',
    PropertyPane_OrgChartLabel_Label: 'Etykieta widoku „Schemat organizacyjny”',
    PropertyPane_ViewLabel_Description: 'Pozostaw puste, aby użyć nazwy domyślnej, lub wpisz "[blank]", aby całkowicie ukryć etykietę.',

    // ── Property pane: Visual Style ──
    PropertyPane_ChartTheme_Label: 'Motyw schematu',
    PropertyPane_Theme_Modern: 'Nowoczesny — kolory działów na białym tle',
    PropertyPane_Theme_Minimal: 'Minimalny — płaski, niski kontrast',
    PropertyPane_Theme_Corporate: 'Korporacyjny — jednolity niebieski',
    PropertyPane_Theme_Dark: 'Ciemny — ciemnogranatowe tło',
    PropertyPane_Theme_Custom: 'Niestandardowy — wybierz własny kolor',
    PropertyPane_AccentColor_Label: 'Niestandardowy kolor akcentu',
    PropertyPane_AccentColor_PickerAriaLabel: 'Wybór koloru akcentu',
    PropertyPane_AccentColor_HexLabel: 'HEX',
    PropertyPane_AccentColor_HexAriaLabel: 'Wartość szesnastkowa koloru akcentu',
    PropertyPane_AccentColor_RgbLabel: 'RGB',
    PropertyPane_AccentColor_ChannelAriaLabel: 'Kanał {name} (od 0 do 255)',
    PropertyPane_AccentColor_ContrastWithWhite: 'Kontrast z bielą: {ratio}:1 ({passes})',
    PropertyPane_AccentColor_PassesAA: 'spełnia AA',
    PropertyPane_AccentColor_LargeTextOnly: 'tylko duży tekst',
    PropertyPane_AccentColor_LowContrast: 'niski kontrast',
    PropertyPane_AccentColor_DarkTextNote: 'Dla lepszej czytelności tekst na tym kolorze będzie ciemny.',
    PropertyPane_AccentColor_DarkerShadeNote: 'Dla lepszej czytelności tytuły i linki będą używać ciemniejszego odcienia ({hex}).',
    PropertyPane_AccentColor_InvalidHex: '„{typed}” nie jest prawidłowym kolorem HEX. Użyj wartości takiej jak #0078d4 lub #07d.',
    PropertyPane_DefaultFontSize_Label: 'Domyślny rozmiar czcionki',
    PropertyPane_FontSize_75: '75% — bardzo mała',
    PropertyPane_FontSize_85: '85% — mała',
    PropertyPane_FontSize_100: '100% — normalna',
    PropertyPane_FontSize_115: '115% — duża',
    PropertyPane_FontSize_130: '130% — bardzo duża',
    PropertyPane_FontSize_150: '150% — XXL',
    PropertyPane_FontSize_175: '175% — XXXL',
    PropertyPane_DefaultLayout_Label: 'Domyślny układ schematu organizacyjnego',
    PropertyPane_Layout_Drill: 'Drążenie w dół',
    PropertyPane_Layout_Vertical: 'Od góry do dołu',
    PropertyPane_Layout_Horizontal: 'Od lewej do prawej',

    // ── Property pane: Data Source ──
    PropertyPane_DataSource_Label: 'Skąd pobierać dane użytkowników i organizacji',
    PropertyPane_DataSource_Auto: 'Automatycznie — Graph API, w razie potrzeby wyszukiwanie SharePoint',
    PropertyPane_DataSource_Graph: 'Graph API — aktualne dane Azure AD (bez opóźnienia indeksowania)',
    PropertyPane_DataSource_Search: 'Wyszukiwanie SharePoint — starsze zachowanie',
    PropertyPane_DataSource_Note: 'Zalecane jest korzystanie z Graph API. Dane są odczytywane bezpośrednio z Azure Active Directory, dzięki czemu nowi użytkownicy i zmiany przełożonych są widoczne natychmiast. Wymaga zatwierdzenia uprawnień Microsoft Graph w katalogu aplikacji SharePoint.',

    // ── Property pane: Custom Attributes ──
    PropertyPane_CustomAttributes_Note: 'Atrybuty niestandardowe wymagają Microsoft Graph (źródło danych: Graph lub Automatycznie). Wyszukiwanie SharePoint nie ma uniwersalnego sposobu odczytu atrybutów Entra ID.',
    PropertyPane_CustomAttributes_Heading: 'Zarządzanie atrybutami niestandardowymi',
    PropertyPane_CustomAttributes_Empty: 'Nie skonfigurowano żadnych atrybutów niestandardowych.',
    PropertyPane_CustomAttributes_AddButton: '+ Dodaj atrybut',
    PropertyPane_CustomAttributes_MaxTooltip: 'Maksymalnie {max} atrybutów niestandardowych',
    PropertyPane_CustomAttributes_FieldNameLabel: 'Nazwa atrybutu',
    PropertyPane_CustomAttributes_FieldPlaceholder: 'np. companyName',
    PropertyPane_CustomAttributes_FieldError: 'Użyj employeeId, companyName, city, ... lub extensionAttribute1-15',
    PropertyPane_CustomAttributes_DisplayLabelLabel: 'Etykieta wyświetlana',
    PropertyPane_CustomAttributes_LabelPlaceholder: 'np. Centrum kosztów',
    PropertyPane_CustomAttributes_RemoveTitle: 'Usuń atrybut',
    PropertyPane_CustomAttributes_RemoveAriaLabel: 'Usuń atrybut {ordinal}',
    PropertyPane_CustomAttributes_ShowInDirectory: 'Pokaż w katalogu',
    PropertyPane_CustomAttributes_ShowInOrgChart: 'Pokaż w schemacie organizacyjnym',

    // ── Property pane: User Filters ──
    PropertyPane_ExcludedAccounts_Label: 'Wyklucz konta',
    PropertyPane_ExcludedAccounts_Placeholder: 'conf-room, noreply, admin@, Service Account',
    PropertyPane_ExcludedAccounts_Description: 'Słowa lub wzorce rozdzielone przecinkami (bez uwzględniania wielkości liter). Każdy użytkownik, którego nazwa wyświetlana, adres e-mail lub UPN zawiera jedno z nich, zostanie ukryty we wszystkich widokach.',
    PropertyPane_RestrictTenant_Label: 'Pokazuj tylko użytkowników dzierżawy',
    PropertyPane_RestrictTenant_On: 'Włączone — ukrywa konta z zewnętrznymi domenami e-mail (np. gmail.com, hotmail.com)',
    PropertyPane_RestrictTenant_Off: 'Wyłączone — pokazywani są wszyscy użytkownicy niezależnie od domeny e-mail',
    PropertyPane_HideGuest_Label: 'Ukryj konta gości Azure AD',
    PropertyPane_HideGuest_On: 'Włączone — konta gości są ukryte',
    PropertyPane_HideGuest_Off: 'Wyłączone — konta gości są widoczne (oznaczone plakietką „Gość”)',
    PropertyPane_HideDisabled_Label: 'Ukryj konta wyłączone',
    PropertyPane_HideDisabled_On: 'Włączone — konta z zablokowanym logowaniem są ukryte',
    PropertyPane_HideDisabled_Off: 'Wyłączone — konta wyłączone są widoczne (oznaczone plakietką „Wyłączone”)',
    PropertyPane_HideDisabled_Note: 'Uwaga: wykrywanie kont gości i kont wyłączonych wymaga źródła danych Graph API. Wyszukiwanie SharePoint nie zwraca tych informacji, więc te dwa filtry (oraz plakietki „Gość”/„Wyłączone”) nie działają, gdy dane pochodzą z wyszukiwania.',
    PropertyPane_HideNoJobTitle_Label: 'Ukryj konta bez stanowiska',
    PropertyPane_HideNoJobTitle_On: 'Włączone — konta bez stanowiska są ukryte',
    PropertyPane_HideNoJobTitle_Off: 'Wyłączone — pokazywane są wszystkie konta niezależnie od stanowiska',
    PropertyPane_HideNoDept_Label: 'Ukryj konta bez działu',
    PropertyPane_HideNoDept_On: 'Włączone — konta bez działu są ukryte',
    PropertyPane_HideNoDept_Off: 'Wyłączone — pokazywane są wszystkie konta niezależnie od działu',

    // ── Property pane: Org Chart ──
    PropertyPane_TopLevelUser_Label: 'Użytkownik najwyższego poziomu (UPN lub e-mail)',
    PropertyPane_TopLevelUser_Placeholder: 'ceo@yourcompany.com',
    PropertyPane_TopLevelUser_Description: 'Osoba wyświetlana u podstawy schematu organizacyjnego',
    PropertyPane_LevelsBelow_Label: 'Liczba poziomów do wczytania poniżej korzenia',
    PropertyPane_DottedLine_Label: 'Atrybut dodatkowego przełożonego (linia przerywana)',
    PropertyPane_DottedLine_Placeholder: 'extensionAttribute10',
    PropertyPane_DottedLine_Description: 'Opcjonalnie. Nazwa lokalnego atrybutu rozszerzonego Azure AD (extensionAttribute1-15), w którym przechowywany jest adres e-mail lub UPN dodatkowego przełożonego („linia przerywana”). Relacje typu linia przerywana są widoczne na kartach profilu. Wymaga źródła danych Graph API.',
    PropertyPane_DefaultZoom_Label: 'Domyślne powiększenie schematu organizacyjnego',
    PropertyPane_Zoom_Auto: 'Domyślne (automatyczne dopasowanie)',
    PropertyPane_Zoom_50: '50%',
    PropertyPane_Zoom_75: '75%',
    PropertyPane_Zoom_100: '100%',
    PropertyPane_Zoom_125: '125%',
    PropertyPane_Zoom_150: '150%',

    // ── Property pane: Org Chart Features ──
    PropertyPane_FeatureToggles_Note: 'Pokaż lub ukryj przyciski paska narzędzi w widoku schematu organizacyjnego.',
    PropertyPane_FindMe_Label: 'Przycisk „Znajdź mnie”',
    PropertyPane_LayoutToggle_Label: 'Przełącznik układu (drążenie / pionowy / poziomy)',
    PropertyPane_Stats_Label: 'Pasek statystyk organizacji',
    PropertyPane_DeptFilter_Label: 'Filtr działów',
    PropertyPane_UserFilter_Label: 'Filtr typu użytkownika (członkowie / goście)',
    PropertyPane_Visible: 'Widoczny',
    PropertyPane_Hidden: 'Ukryty',

    // ── Property pane: Directory ──
    PropertyPane_PageSize_Label: 'Maksymalna liczba pracowników na stronę',
    PropertyPane_PageSize_AriaLabel: 'Maksymalna liczba pracowników na stronę (od 10 do 200)',
    PropertyPane_PageSize_Note: 'Rozmiar kart, widoczne pola i inne preferencje wyświetlania są ustawiane indywidualnie dla każdego użytkownika za pomocą ikony ustawień w aplikacji.',

    // ── Property pane: Demo ──
    PropertyPane_UseDemoData_Label: 'Użyj danych demonstracyjnych',
    PropertyPane_UseDemoData_On: 'Włączone — wyświetlani są przykładowi pracownicy',
    PropertyPane_UseDemoData_Off: 'Wyłączone — rzeczywiste dane Microsoft 365',

    // ── Presence status labels ──
    Presence_Available: 'Dostępny',
    Presence_Busy: 'Zajęty',
    Presence_DoNotDisturb: 'Nie przeszkadzać',
    Presence_BeRightBack: 'Zaraz wracam',
    Presence_Away: 'Bezczynny',
    Presence_Offline: 'Offline',

    // ── Header / top bar ──
    Header_DirectoryLabel: 'Katalog pracowników',
    Header_OrgChartLabel: 'Schemat organizacyjny',
    Header_SwitchToView: 'Przełącz na {view}',
    Header_CompanyLogoAlt: 'Logo firmy',
    Header_RefreshingAria: 'Odświeżanie danych',
    Header_RefreshAria: 'Odśwież dane',
    Header_RefreshTitle: 'Odśwież dane (ostatnia aktualizacja: {when})',
    Header_NotLoadedYet: 'jeszcze nie wczytano',
    Header_JustNow: 'przed chwilą',
    Header_MinutesAgo: '{mins} min temu',
    Header_HoursAgo: '{hours} godz. temu',
    Header_PreferencesTitle: 'Preferencje',
    Header_PreferencesAria: 'Otwórz panel preferencji',

    // ── Employee Directory ──
    Directory_LoadingLabel: 'Wczytywanie pracowników…',
    Directory_LoadFailedFallback: 'Upewnij się, że składnik Web Part ma uprawnienie User.Read.All.',
    Directory_LoadFailedPrefix: 'Nie udało się wczytać pracowników. {detail}',
    Directory_AllDepartments: 'Wszystkie działy',
    Directory_AllOffices: 'Wszystkie biura',
    Directory_StatusDisabled: 'Wyłączone',
    Directory_StatusGuest: 'Gość',
    Directory_PresenceStatus: 'Status: {status}',
    Directory_ChatInTeams: 'Czat w Teams',
    Directory_ChatWithInTeams: 'Czat z {name} w Teams',
    Directory_ManagesCount: 'Podwładni: {direct}',
    Directory_ManagesCountWithTotal: 'Podwładni: {direct} (łącznie {total})',
    Directory_ReportsCountWithTotal: '{direct} (łącznie {total})',
    Directory_ColumnName: 'Imię i nazwisko',
    Directory_ColumnJobTitle: 'Stanowisko',
    Directory_ColumnDepartment: 'Dział',
    Directory_ColumnOffice: 'Biuro',
    Directory_ColumnEmail: 'E-mail',
    Directory_ColumnPhone: 'Telefon',
    Directory_ColumnReports: 'Podwładni',
    Directory_ColumnChat: 'Czat',
    Directory_PrevPage: 'Wstecz',
    Directory_NextPage: 'Dalej',
    Directory_PreviousPageAria: 'Poprzednia strona',
    Directory_NextPageAria: 'Następna strona',
    Directory_SearchPlaceholder: 'Szukaj według imienia, stanowiska, e-maila lub działu…',
    Directory_SearchAria: 'Wyszukaj osoby',
    Directory_FilterByDepartmentAria: 'Filtruj według działu',
    Directory_FilterByOfficeAria: 'Filtruj według biura',
    Directory_ClearSearchTitle: 'Wyczyść wyszukiwanie i wszystkie filtry',
    Directory_ClearButton: 'Wyczyść',
    Directory_ClearFiltersButton: 'Wyczyść filtry',
    Directory_ExportCsvTitle: 'Eksportuj wszystkie przefiltrowane wyniki do pliku CSV (otwiera się w programie Excel)',
    Directory_ExportCsvButton: 'Eksportuj CSV',
    Directory_ViewModeAria: 'Tryb widoku',
    Directory_CardViewTitle: 'Widok kart',
    Directory_ListViewTitle: 'Widok listy',
    Directory_AlphabetFilterAria: 'Filtr alfabetyczny',
    Directory_ShowAllTitle: 'Pokaż wszystkie',
    Directory_OtherLettersTitle: 'Filtruj według nazwisk zaczynających się od cyfry lub innego znaku',
    Directory_FilterByLetterTitle: 'Filtruj według litery {letter}',
    Directory_ResultCountSingular: 'osoba',
    Directory_ResultCountPlural: 'osób',
    Directory_PageOf: ' · strona {page} z {totalPages}',
    Directory_FilterActiveSingular: 'Aktywny {count} filtr',
    Directory_FilterActivePlural: 'Aktywne filtry: {count}',
    Directory_NoResults: 'Nie znaleziono osób',
    Directory_PaginationAria: 'Paginacja',

    // ── Org chart toolbar / shared chart chrome ──
    Chart_Layout_Drill: 'Drążenie w dół',
    Chart_Layout_Vertical: 'Od góry do dołu',
    Chart_Layout_Horizontal: 'Od lewej do prawej',
    Chart_SearchPlaceholder: 'Szukaj osób…',
    Chart_SearchAria: 'Wyszukaj osoby',
    Chart_MatchSingular: 'dopasowanie w drzewie',
    Chart_MatchPlural: 'dopasowania w drzewie',
    Chart_ResultsListAria: 'Osoby',
    Chart_ExpandAll: 'Rozwiń wszystko',
    Chart_CollapseAll: 'Zwiń wszystko',
    Chart_Expanding: 'Rozwijanie…',
    Chart_Loading: 'Wczytywanie…',
    Chart_FindMeTitle: 'Znajdź mnie w schemacie organizacyjnym',
    Chart_ViewLayoutButton: 'Widok',
    Chart_ViewLayoutTitle: 'Przełącz układ widoku',
    Chart_ViewLayoutPanelTitle: 'Układ widoku',
    Chart_StatsSummaryTitle: 'Podsumowanie statystyk organizacji',
    Chart_FilterByDepartmentTitle: 'Filtruj według działu',
    Chart_FilterByDepartmentWithCountAria: 'Filtruj według działu (wybrano: {count})',
    Chart_FilterByDepartmentPanelTitle: 'Filtruj według działu',
    Chart_ClearAllFilters: 'Wyczyść wszystkie filtry',
    Chart_FilterUserTypesTitle: 'Filtruj typy użytkowników',
    Chart_DownloadPdfTitle: 'Pobierz jako PDF',
    Chart_DownloadCsvTitle: 'Pobierz jako arkusz CSV',
    Chart_ResetRootTitle: 'Przywróć domyślny korzeń',
    Chart_ViewFromPersonPlaceholder: 'Widok od osoby…',
    Chart_ViewFromPersonAria: 'Wyświetl schemat organizacyjny od wybranej osoby',
    Chart_ZoomOutTitle: 'Pomniejsz',
    Chart_ZoomInTitle: 'Powiększ',
    Chart_ZoomResetTitle: 'Zresetuj powiększenie',
    Chart_ShowInChartAria: 'Pokaż w schemacie',
    Chart_ShowInChartTitle: 'Pokaż w schemacie',
    Chart_FilterMembers: 'Zwykli członkowie',
    Chart_FilterGuests: 'Użytkownicy-goście',
    Chart_FilterDisabled: 'Konta wyłączone',
    Chart_SetupTitle: 'Skonfiguruj schemat organizacyjny',
    Chart_SetupSubtitle: 'Aby rozpocząć, wprowadź adres e-mail lub UPN osoby najwyższego poziomu.',
    Chart_SetupPlaceholder: 'ceo@company.com',
    Chart_SetupInputAria: 'Adres e-mail lub UPN osoby najwyższego poziomu',
    Chart_SetupLoadButton: 'Wczytaj',
    Chart_SetupHint: 'Można to również ustawić na stałe w ustawieniach składnika Web Part (dla administratorów).',
    Chart_BuildingLabel: 'Budowanie schematu organizacyjnego…',
    Chart_RetryButton: 'Ponów',
    Chart_NotFoundFromSetup: 'Nie znaleziono użytkownika „{identifier}”.',
    Chart_NotFoundWithSettings: 'Nie znaleziono użytkownika „{identifier}”. Sprawdź UPN lub adres e-mail w ustawieniach.',
    Chart_LoadFailedGeneric: 'Nie udało się wczytać schematu organizacyjnego.{detail}',
    Chart_LoadFailedPermissions: ' Sprawdź uprawnienia.',
    Chart_LoadFailedForPerson: 'Nie udało się wczytać schematu organizacyjnego dla tej osoby.',
    Chart_FindMeNotFound: 'Nie znaleziono Twojego konta w tej organizacji.',
    Chart_StatPeople: 'Osoby',
    Chart_StatMembers: 'Członkowie',
    Chart_StatGuests: 'Goście',
    Chart_StatDepts: 'Działy',
    Chart_ReportingLineAria: 'Linia podległości',
    Chart_BackToFullOrgTitle: 'Wróć do pełnego schematu organizacyjnego',
    Chart_FullOrgLabel: 'Cała organizacja',
    Chart_FocusOnPerson: 'Skup się na {name}',
    Chart_OrgChartAria: 'Schemat organizacyjny',
    Chart_ExportNote_DrillLevel: 'Bieżący poziom drążenia (jeden poziom bezpośrednich podwładnych)',
    Chart_ExportNote_PartialLevels: 'Zawiera tylko wczytane poziomy — aby uwzględnić głębsze poziomy, przed eksportem użyj opcji „Rozwiń wszystko”',
    Chart_AllowPopupsForPdf: 'Zezwól na wyskakujące okienka, aby wyeksportować PDF.',

    // ── Person card ──
    PersonCard_ProfileAria: 'Profil: {name}',
    PersonCard_CloseTitle: 'Zamknij',
    PersonCard_CloseAria: 'Zamknij profil',
    PersonCard_StatusDisabled: 'Wyłączone',
    PersonCard_StatusGuest: 'Gość',
    PersonCard_DirectReportSingular: '{count} bezpośredni podwładny',
    PersonCard_DirectReportPlural: '{count} bezpośrednich podwładnych',
    PersonCard_TotalSuffix: ' · łącznie {total}',
    PersonCard_CopyEmailTitle: 'Kopiuj adres e-mail',
    PersonCard_EmailCopiedAria: 'Adres e-mail skopiowany',
    PersonCard_ReportsTo: 'Podlega',
    PersonCard_FocusOnPerson: 'Skup się na {name}',
    PersonCard_FocusOrgChartOnPerson: 'Skup schemat organizacyjny na {name}',
    PersonCard_DottedLine: 'Linia przerywana',
    PersonCard_DottedLineManager: 'Dodatkowy przełożony: {name}',
    PersonCard_DottedLineReport: 'Dodatkowy podwładny: {name}',
    PersonCard_ChatButton: 'Czat',
    PersonCard_EmailButton: 'E-mail',
    PersonCard_FocusButton: 'Skup',
    PersonCard_FocusTitle: 'Skup schemat organizacyjny na tej osobie',

    // ── Org node card ──
    OrgNode_ViewProfile: 'Wyświetl profil osoby {name}',
    OrgNode_FocusOrgChartOn: 'Skup schemat organizacyjny na {name}',
    OrgNode_Collapse: 'Zwiń',
    OrgNode_Expand: 'Rozwiń',
    OrgNode_DirectReportsSuffix: 'Bezpośredni podwładni osoby {name}',
    OrgNode_StatusDisabled: 'Wyłączone',
    OrgNode_StatusGuest: 'Gość',
    OrgNode_TotalReportsAcrossLevels: '{count} osób na wszystkich poziomach poniżej {name}',

    // ── Drill view ──
    Drill_ReportingLineAria: 'Linia podległości',
    Drill_BackToTopTitle: 'Wróć na górę',
    Drill_BackToTopAria: 'Wróć na górę schematu organizacyjnego',
    Drill_GoBackTo: 'Wróć do {name}',
    Drill_ViewProfileTitle: 'Wyświetl profil',
    Drill_ViewProfileAria: 'Wyświetl profil osoby {name}',
    Drill_ProfileButton: 'Profil',
    Drill_LoadingLabel: 'Wczytywanie…',
    Drill_DirectReports: 'Bezpośredni podwładni',
    Drill_DirectReportsOfAria: 'Bezpośredni podwładni osoby {name}',
    Drill_DirectReportsAria: 'Bezpośredni podwładni',
    Drill_ViewPersonProfile: 'Wyświetl profil osoby {name}',
    Drill_ShowPersonReports: 'Pokaż bezpośrednich podwładnych osoby {name}',
    Drill_NoDirectReports: 'Brak bezpośrednich podwładnych',

    // ── Settings panel ──
    Settings_AlphabetFirstName: 'Imię',
    Settings_AlphabetLastName: 'Nazwisko',
    Settings_CardSizeSmall: 'Mały — kompaktowy, więcej kart na ekranie',
    Settings_CardSizeMedium: 'Średni — zrównoważony',
    Settings_CardSizeLarge: 'Duży — przestronny, mniej kart na ekranie',
    Settings_HeaderText: 'Preferencje',
    Settings_SaveButton: 'Zapisz',
    Settings_CancelButton: 'Anuluj',
    Settings_DiscardButton: 'Odrzuć zmiany',
    Settings_SectionDirectory: 'Katalog pracowników',
    Settings_AlphabetFilterByLabel: 'Filtr alfabetyczny według',
    Settings_CardSizeLabel: 'Rozmiar kart',
    Settings_FontSizeLabel: 'Rozmiar czcionki',
    Settings_SectionCardsAndFields: 'Karty i pola',
    Settings_ShowOnCardsLabel: 'Pokaż na kartach pracowników:',
    Settings_EmailAddressLabel: 'Adres e-mail',
    Settings_PhoneNumberLabel: 'Numer telefonu',
    Settings_DepartmentLabel: 'Dział',
    Settings_OfficeLocationLabel: 'Lokalizacja biura',
    Settings_SectionOrgChart: 'Schemat organizacyjny',
    Settings_ManagerLevelsLabel: 'Liczba poziomów przełożonych pokazywana po skupieniu się na osobie: {levels}',
    Settings_CompactCardsLabel: 'Kompaktowe karty',
    Settings_CompactCardsOn: 'Włączone — mniejsze karty, więcej widocznych naraz',
    Settings_CompactCardsOff: 'Wyłączone — standardowy rozmiar',
    Settings_Hint: 'Te preferencje są zapisywane w Twojej przeglądarce i dotyczą tylko Ciebie. Motyw schematu, widok domyślny i układ są konfigurowane przez administratora SharePoint.',
    Settings_SectionDemoData: 'Dane demonstracyjne',
    Settings_DatasetSizeLabel: 'Rozmiar zbioru danych',
    Settings_PeopleCountSuffix: '{count} osób',

    // ── Export (CSV / PDF) ──
    Export_ColumnName: 'Imię i nazwisko',
    Export_ColumnJobTitle: 'Stanowisko',
    Export_ColumnDepartment: 'Dział',
    Export_ColumnOffice: 'Biuro',
    Export_ColumnEmail: 'E-mail',
    Export_ColumnPhone: 'Telefon',
    Export_ColumnManager: 'Przełożony',
    Export_ColumnLevel: 'Poziom',
    Export_PdfDocumentTitle: 'Schemat organizacyjny',
    Export_PdfHeading: 'Struktura organizacyjna',
    Export_PdfRootLabel: 'Korzeń: {name}',
  };
});
