define([], function () {
  return {
    // ── Property pane: pane header / groups ──
    PropertyPane_HeaderDescription: 'Configurações do Smart Org Chart',
    PropertyPane_Group_General: 'Geral',
    PropertyPane_Group_Branding: 'Identidade Visual',
    PropertyPane_Group_VisualStyle: 'Estilo Visual',
    PropertyPane_Group_DataSource: 'Fonte de Dados',
    PropertyPane_Group_CustomAttributes: 'Atributos Personalizados',
    PropertyPane_Group_UserFilters: 'Filtros de Usuário',
    PropertyPane_Group_OrgChart: 'Organograma',
    PropertyPane_Group_OrgChartFeatures: 'Recursos do Organograma',
    PropertyPane_Group_Directory: 'Diretório',
    PropertyPane_Group_Demo: 'Demonstração',

    // ── Property pane: General ──
    PropertyPane_DefaultView_Label: 'Exibição Padrão',

    // ── Property pane: Branding ──
    PropertyPane_AppTitle_Label: 'Título do Aplicativo',
    PropertyPane_AppTitle_Placeholder: 'Organograma Contoso',
    PropertyPane_AppTitle_Description: 'Exibido na barra de cabeçalho ao lado do nome da exibição',
    PropertyPane_LogoUrl_Label: 'URL do Logotipo',
    PropertyPane_LogoUrl_Placeholder: 'https://contoso.sharepoint.com/sites/seusite/SiteAssets/logo.png',
    PropertyPane_LogoUrl_Description: 'URL completa de uma imagem PNG/SVG/JPG. Dica: abra o arquivo de imagem no navegador e copie a URL da barra de endereços. URLs de compartilhamento do tipo "Copiar link" não funcionarão.',
    PropertyPane_DirectoryLabel_Label: 'Rótulo da Exibição do Diretório de Funcionários',
    PropertyPane_OrgChartLabel_Label: 'Rótulo da Exibição do Organograma',
    PropertyPane_ViewLabel_Description: 'Deixe em branco para usar o nome padrão, ou digite "[blank]" para ocultar o rótulo completamente.',

    // ── Property pane: Visual Style ──
    PropertyPane_ChartTheme_Label: 'Tema do Organograma',
    PropertyPane_Theme_Modern: 'Moderno — cores de departamento em branco',
    PropertyPane_Theme_Minimal: 'Minimalista — plano e baixo contraste',
    PropertyPane_Theme_Corporate: 'Corporativo — azul unificado',
    PropertyPane_Theme_Dark: 'Escuro — fundo azul-marinho escuro',
    PropertyPane_Theme_Custom: 'Personalizado — escolha sua própria cor',
    PropertyPane_AccentColor_Label: 'Cor de Destaque Personalizada',
    PropertyPane_AccentColor_PickerAriaLabel: 'Seletor de cor de destaque',
    PropertyPane_AccentColor_HexLabel: 'Hex',
    PropertyPane_AccentColor_HexAriaLabel: 'Valor hexadecimal da cor de destaque',
    PropertyPane_AccentColor_RgbLabel: 'RGB',
    PropertyPane_AccentColor_ChannelAriaLabel: 'Canal {name} (0 a 255)',
    PropertyPane_AccentColor_ContrastWithWhite: 'Contraste com branco: {ratio}:1 ({passes})',
    PropertyPane_AccentColor_PassesAA: 'atende ao nível AA',
    PropertyPane_AccentColor_LargeTextOnly: 'apenas texto grande',
    PropertyPane_AccentColor_LowContrast: 'contraste baixo',
    PropertyPane_AccentColor_DarkTextNote: 'O texto sobre essa cor usará texto escuro para melhor legibilidade.',
    PropertyPane_AccentColor_DarkerShadeNote: 'Títulos e links usarão um tom mais escuro ({hex}) para melhor legibilidade.',
    PropertyPane_AccentColor_InvalidHex: '"{typed}" não é uma cor hexadecimal válida. Use um valor como #0078d4 ou #07d.',
    PropertyPane_DefaultFontSize_Label: 'Tamanho de Fonte Padrão',
    PropertyPane_FontSize_75: '75% — Extra Pequeno',
    PropertyPane_FontSize_85: '85% — Pequeno',
    PropertyPane_FontSize_100: '100% — Normal',
    PropertyPane_FontSize_115: '115% — Grande',
    PropertyPane_FontSize_130: '130% — Extra Grande',
    PropertyPane_FontSize_150: '150% — XXL',
    PropertyPane_FontSize_175: '175% — XXXL',
    PropertyPane_DefaultLayout_Label: 'Layout Padrão do Organograma',
    PropertyPane_Layout_Drill: 'Detalhamento',
    PropertyPane_Layout_Vertical: 'De Cima para Baixo',
    PropertyPane_Layout_Horizontal: 'Da Esquerda para a Direita',

    // ── Property pane: Data Source ──
    PropertyPane_DataSource_Label: 'De onde carregar os dados de usuários e da organização',
    PropertyPane_DataSource_Auto: 'Automático — API do Graph, com substituição pela Pesquisa do SharePoint',
    PropertyPane_DataSource_Graph: 'API do Graph — dados do Azure AD em tempo real (sem atraso de indexação)',
    PropertyPane_DataSource_Search: 'Pesquisa do SharePoint — comportamento legado',
    PropertyPane_DataSource_Note: 'A API do Graph é recomendada. Ela lê diretamente do Azure Active Directory, portanto novos usuários e alterações de gerente aparecem imediatamente. Requer que as permissões do Microsoft Graph sejam aprovadas no Catálogo de Aplicativos do SharePoint.',

    // ── Property pane: Custom Attributes ──
    PropertyPane_CustomAttributes_Note: 'Os atributos personalizados exigem o Microsoft Graph (Fonte de dados: Graph ou Automático). A Pesquisa do SharePoint não possui uma forma genérica de ler atributos do Entra ID.',
    PropertyPane_CustomAttributes_Heading: 'Gerenciar atributos personalizados',
    PropertyPane_CustomAttributes_Empty: 'Nenhum atributo personalizado configurado.',
    PropertyPane_CustomAttributes_AddButton: '+ Adicionar atributo',
    PropertyPane_CustomAttributes_MaxTooltip: 'Máximo de {max} atributos personalizados',
    PropertyPane_CustomAttributes_FieldNameLabel: 'Nome do atributo',
    PropertyPane_CustomAttributes_FieldPlaceholder: 'ex.: companyName',
    PropertyPane_CustomAttributes_FieldError: 'Use employeeId, companyName, city, ... ou extensionAttribute1-15',
    PropertyPane_CustomAttributes_DisplayLabelLabel: 'Rótulo de exibição',
    PropertyPane_CustomAttributes_LabelPlaceholder: 'ex.: Centro de Custo',
    PropertyPane_CustomAttributes_RemoveTitle: 'Remover atributo',
    PropertyPane_CustomAttributes_RemoveAriaLabel: 'Remover atributo {ordinal}',
    PropertyPane_CustomAttributes_ShowInDirectory: 'Mostrar no Diretório',
    PropertyPane_CustomAttributes_ShowInOrgChart: 'Mostrar no Organograma',

    // ── Property pane: User Filters ──
    PropertyPane_ExcludedAccounts_Label: 'Excluir contas',
    PropertyPane_ExcludedAccounts_Placeholder: 'sala-reuniao, noreply, admin@, Conta de Serviço',
    PropertyPane_ExcludedAccounts_Description: 'Palavras ou padrões separados por vírgula (não diferencia maiúsculas de minúsculas). Qualquer usuário cujo nome de exibição, e-mail ou UPN contenha um destes termos será ocultado em todas as exibições.',
    PropertyPane_RestrictTenant_Label: 'Mostrar apenas usuários do locatário',
    PropertyPane_RestrictTenant_On: 'Ativado — oculta contas com domínios de e-mail externos (ex.: gmail.com, hotmail.com)',
    PropertyPane_RestrictTenant_Off: 'Desativado — todos os usuários são exibidos, independentemente do domínio de e-mail',
    PropertyPane_HideGuest_Label: 'Ocultar contas de convidado do Azure AD',
    PropertyPane_HideGuest_On: 'Ativado — contas de convidado ocultas',
    PropertyPane_HideGuest_Off: 'Desativado — contas de convidado visíveis (exibidas com o selo Convidado)',
    PropertyPane_HideDisabled_Label: 'Ocultar contas desativadas',
    PropertyPane_HideDisabled_On: 'Ativado — contas com entrada bloqueada ocultas',
    PropertyPane_HideDisabled_Off: 'Desativado — contas desativadas visíveis (exibidas com o selo Desativada)',
    PropertyPane_HideDisabled_Note: 'Observação: a detecção de contas de convidado e desativadas requer a fonte de dados da API do Graph. A Pesquisa do SharePoint não retorna essas informações, portanto esses dois filtros (e os selos Convidado/Desativada) não têm efeito quando os dados vêm da Pesquisa.',
    PropertyPane_HideNoJobTitle_Label: 'Ocultar contas sem cargo',
    PropertyPane_HideNoJobTitle_On: 'Ativado — contas sem cargo ocultas',
    PropertyPane_HideNoJobTitle_Off: 'Desativado — todas as contas são exibidas, independentemente do cargo',
    PropertyPane_HideNoDept_Label: 'Ocultar contas sem departamento',
    PropertyPane_HideNoDept_On: 'Ativado — contas sem departamento ocultas',
    PropertyPane_HideNoDept_Off: 'Desativado — todas as contas são exibidas, independentemente do departamento',

    // ── Property pane: Org Chart ──
    PropertyPane_TopLevelUser_Label: 'Usuário de Nível Superior (UPN ou E-mail)',
    PropertyPane_TopLevelUser_Placeholder: 'ceo@suaempresa.com',
    PropertyPane_TopLevelUser_Description: 'A pessoa exibida na raiz do organograma',
    PropertyPane_LevelsBelow_Label: 'Níveis a carregar abaixo da raiz',
    PropertyPane_DottedLine_Label: 'Atributo de gerente de linha pontilhada',
    PropertyPane_DottedLine_Placeholder: 'extensionAttribute10',
    PropertyPane_DottedLine_Description: 'Opcional. Nome do atributo de extensão local do Azure AD (extensionAttribute1-15) que armazena o e-mail ou UPN de um gerente secundário de "linha pontilhada". Os relacionamentos de linha pontilhada aparecem nos cartões de perfil. Requer a fonte de dados da API do Graph.',
    PropertyPane_DefaultZoom_Label: 'Zoom Padrão do Organograma',
    PropertyPane_Zoom_Auto: 'Padrão (Ajuste automático)',
    PropertyPane_Zoom_50: '50%',
    PropertyPane_Zoom_75: '75%',
    PropertyPane_Zoom_100: '100%',
    PropertyPane_Zoom_125: '125%',
    PropertyPane_Zoom_150: '150%',

    // ── Property pane: Org Chart Features ──
    PropertyPane_FeatureToggles_Note: 'Mostre ou oculte botões da barra de ferramentas na exibição do organograma.',
    PropertyPane_FindMe_Label: 'Botão Localizar-me',
    PropertyPane_LayoutToggle_Label: 'Alternância de layout (detalhamento / vertical / horizontal)',
    PropertyPane_Stats_Label: 'Barra de estatísticas da organização',
    PropertyPane_DeptFilter_Label: 'Filtro de departamento',
    PropertyPane_UserFilter_Label: 'Filtro de tipo de usuário (membros / convidados)',
    PropertyPane_Visible: 'Visível',
    PropertyPane_Hidden: 'Oculto',

    // ── Property pane: Directory ──
    PropertyPane_PageSize_Label: 'Máximo de funcionários por página',
    PropertyPane_PageSize_AriaLabel: 'Máximo de funcionários por página (10 a 200)',
    PropertyPane_PageSize_Note: 'O tamanho do cartão, os campos visíveis e outras preferências de exibição são definidos por usuário por meio do ícone de engrenagem de Configurações no aplicativo.',

    // ── Property pane: Demo ──
    PropertyPane_UseDemoData_Label: 'Usar Dados de Demonstração',
    PropertyPane_UseDemoData_On: 'Ativado — exibindo funcionários de exemplo',
    PropertyPane_UseDemoData_Off: 'Desativado — dados reais do Microsoft 365',

    // ── Presence status labels ──
    Presence_Available: 'Disponível',
    Presence_Busy: 'Ocupado',
    Presence_DoNotDisturb: 'Não Perturbe',
    Presence_BeRightBack: 'Volto Já',
    Presence_Away: 'Ausente',
    Presence_Offline: 'Offline',

    // ── Header / top bar ──
    Header_DirectoryLabel: 'Diretório de Funcionários',
    Header_OrgChartLabel: 'Organograma',
    Header_SwitchToView: 'Mudar para {view}',
    Header_CompanyLogoAlt: 'Logotipo da empresa',
    Header_RefreshingAria: 'Atualizando dados',
    Header_RefreshAria: 'Atualizar dados',
    Header_RefreshTitle: 'Atualizar dados (última atualização {when})',
    Header_NotLoadedYet: 'ainda não carregado',
    Header_JustNow: 'agora mesmo',
    Header_MinutesAgo: 'há {mins} min',
    Header_HoursAgo: 'há {hours} h',
    Header_PreferencesTitle: 'Preferências',
    Header_PreferencesAria: 'Abrir painel de preferências',

    // ── Employee Directory ──
    Directory_LoadingLabel: 'Carregando funcionários...',
    Directory_LoadFailedFallback: 'Verifique se o web part tem a permissão User.Read.All.',
    Directory_LoadFailedPrefix: 'Falha ao carregar funcionários. {detail}',
    Directory_AllDepartments: 'Todos os Departamentos',
    Directory_AllOffices: 'Todos os Escritórios',
    Directory_StatusDisabled: 'Desativada',
    Directory_StatusGuest: 'Convidado',
    Directory_PresenceStatus: 'Status: {status}',
    Directory_ChatInTeams: 'Conversar no Teams',
    Directory_ChatWithInTeams: 'Conversar com {name} no Teams',
    Directory_ManagesCount: 'Gerencia {direct}',
    Directory_ManagesCountWithTotal: 'Gerencia {direct} ({total} no total)',
    Directory_ReportsCountWithTotal: '{direct} ({total} no total)',
    Directory_ColumnName: 'Nome',
    Directory_ColumnJobTitle: 'Cargo',
    Directory_ColumnDepartment: 'Departamento',
    Directory_ColumnOffice: 'Escritório',
    Directory_ColumnEmail: 'E-mail',
    Directory_ColumnPhone: 'Telefone',
    Directory_ColumnReports: 'Subordinados',
    Directory_ColumnChat: 'Chat',
    Directory_PrevPage: 'Anterior',
    Directory_NextPage: 'Próxima',
    Directory_PreviousPageAria: 'Página anterior',
    Directory_NextPageAria: 'Próxima página',
    Directory_SearchPlaceholder: 'Pesquisar por nome, cargo, e-mail ou departamento...',
    Directory_SearchAria: 'Pesquisar pessoas',
    Directory_FilterByDepartmentAria: 'Filtrar por departamento',
    Directory_FilterByOfficeAria: 'Filtrar por escritório',
    Directory_ClearSearchTitle: 'Limpar pesquisa e todos os filtros',
    Directory_ClearButton: 'Limpar',
    Directory_ClearFiltersButton: 'Limpar filtros',
    Directory_ExportCsvTitle: 'Exportar todos os resultados filtrados para um arquivo CSV (abre no Excel)',
    Directory_ExportCsvButton: 'Exportar CSV',
    Directory_ViewModeAria: 'Modo de exibição',
    Directory_CardViewTitle: 'Exibição em cartões',
    Directory_ListViewTitle: 'Exibição em lista',
    Directory_AlphabetFilterAria: 'Filtro alfabético',
    Directory_ShowAllTitle: 'Mostrar todos',
    Directory_OtherLettersTitle: 'Filtrar por nomes que começam com número ou outro caractere',
    Directory_FilterByLetterTitle: 'Filtrar por {letter}',
    Directory_ResultCountSingular: 'pessoa',
    Directory_ResultCountPlural: 'pessoas',
    Directory_PageOf: ' · página {page} de {totalPages}',
    Directory_FilterActiveSingular: '{count} filtro ativo',
    Directory_FilterActivePlural: '{count} filtros ativos',
    Directory_NoResults: 'Nenhuma pessoa encontrada',
    Directory_PaginationAria: 'Paginação',

    // ── Org chart toolbar / shared chart chrome ──
    Chart_Layout_Drill: 'Detalhamento',
    Chart_Layout_Vertical: 'De Cima para Baixo',
    Chart_Layout_Horizontal: 'Da Esquerda para a Direita',
    Chart_SearchPlaceholder: 'Pesquisar pessoas...',
    Chart_SearchAria: 'Pesquisar pessoas',
    Chart_MatchSingular: 'correspondência na árvore',
    Chart_MatchPlural: 'correspondências na árvore',
    Chart_ResultsListAria: 'Pessoas',
    Chart_ExpandAll: 'Expandir Tudo',
    Chart_CollapseAll: 'Recolher Tudo',
    Chart_Expanding: 'Expandindo…',
    Chart_Loading: 'Carregando…',
    Chart_FindMeTitle: 'Localizar-me no organograma',
    Chart_ViewLayoutButton: 'Exibir',
    Chart_ViewLayoutTitle: 'Alternar layout de exibição',
    Chart_ViewLayoutPanelTitle: 'Layout de exibição',
    Chart_StatsSummaryTitle: 'Resumo de estatísticas da organização',
    Chart_FilterByDepartmentTitle: 'Filtrar por departamento',
    Chart_FilterByDepartmentWithCountAria: 'Filtrar por departamento ({count} selecionado(s))',
    Chart_FilterByDepartmentPanelTitle: 'Filtrar por departamento',
    Chart_ClearAllFilters: 'Limpar todos os filtros',
    Chart_FilterUserTypesTitle: 'Filtrar tipos de usuário',
    Chart_DownloadPdfTitle: 'Baixar como PDF',
    Chart_DownloadCsvTitle: 'Baixar como planilha CSV',
    Chart_ResetRootTitle: 'Restaurar raiz padrão',
    Chart_ViewFromPersonPlaceholder: 'Ver a partir de uma pessoa…',
    Chart_ViewFromPersonAria: 'Exibir o organograma a partir de uma pessoa',
    Chart_ZoomOutTitle: 'Diminuir zoom',
    Chart_ZoomInTitle: 'Aumentar zoom',
    Chart_ZoomResetTitle: 'Redefinir zoom',
    Chart_ShowInChartAria: 'Mostrar no organograma',
    Chart_ShowInChartTitle: 'Mostrar no organograma',
    Chart_FilterMembers: 'Membros regulares',
    Chart_FilterGuests: 'Usuários convidados',
    Chart_FilterDisabled: 'Contas desativadas',
    Chart_SetupTitle: 'Configurar o Organograma',
    Chart_SetupSubtitle: 'Insira o e-mail ou UPN da pessoa de nível superior para começar.',
    Chart_SetupPlaceholder: 'ceo@empresa.com',
    Chart_SetupInputAria: 'E-mail ou UPN da pessoa de nível superior',
    Chart_SetupLoadButton: 'Carregar',
    Chart_SetupHint: 'Você também pode definir isso permanentemente nas configurações do web part (administrador).',
    Chart_BuildingLabel: 'Construindo organograma...',
    Chart_RetryButton: 'Tentar novamente',
    Chart_NotFoundFromSetup: 'Usuário "{identifier}" não encontrado.',
    Chart_NotFoundWithSettings: 'Usuário "{identifier}" não encontrado. Verifique o UPN ou e-mail nas Configurações.',
    Chart_LoadFailedGeneric: 'Falha ao carregar o organograma.{detail}',
    Chart_LoadFailedPermissions: ' Verifique as permissões.',
    Chart_LoadFailedForPerson: 'Falha ao carregar o organograma desta pessoa.',
    Chart_FindMeNotFound: 'Sua conta não foi encontrada nesta organização.',
    Chart_StatPeople: 'Pessoas',
    Chart_StatMembers: 'Membros',
    Chart_StatGuests: 'Convidados',
    Chart_StatDepts: 'Deptos.',
    Chart_ReportingLineAria: 'Linha hierárquica',
    Chart_BackToFullOrgTitle: 'Voltar ao organograma completo',
    Chart_FullOrgLabel: 'Organização completa',
    Chart_FocusOnPerson: 'Focar em {name}',
    Chart_OrgChartAria: 'Organograma',
    Chart_ExportNote_DrillLevel: 'Nível de detalhamento atual (um nível de subordinados diretos)',
    Chart_ExportNote_PartialLevels: 'Inclui apenas os níveis carregados — use Expandir Tudo antes de exportar para incluir níveis mais profundos',
    Chart_AllowPopupsForPdf: 'Permita pop-ups para exportar o PDF.',

    // ── Person card ──
    PersonCard_ProfileAria: 'Perfil: {name}',
    PersonCard_CloseTitle: 'Fechar',
    PersonCard_CloseAria: 'Fechar perfil',
    PersonCard_StatusDisabled: 'Desativada',
    PersonCard_StatusGuest: 'Convidado',
    PersonCard_DirectReportSingular: '{count} subordinado direto',
    PersonCard_DirectReportPlural: '{count} subordinados diretos',
    PersonCard_TotalSuffix: ' · {total} no total',
    PersonCard_CopyEmailTitle: 'Copiar endereço de e-mail',
    PersonCard_EmailCopiedAria: 'Endereço de e-mail copiado',
    PersonCard_ReportsTo: 'Reporta-se a',
    PersonCard_FocusOnPerson: 'Focar em {name}',
    PersonCard_FocusOrgChartOnPerson: 'Focar o organograma em {name}',
    PersonCard_DottedLine: 'Linha pontilhada',
    PersonCard_DottedLineManager: 'Gerente de linha pontilhada: {name}',
    PersonCard_DottedLineReport: 'Subordinado de linha pontilhada: {name}',
    PersonCard_ChatButton: 'Chat',
    PersonCard_EmailButton: 'E-mail',
    PersonCard_FocusButton: 'Focar',
    PersonCard_FocusTitle: 'Focar o organograma nesta pessoa',

    // ── Org node card ──
    OrgNode_ViewProfile: 'Ver o perfil de {name}',
    OrgNode_FocusOrgChartOn: 'Focar o organograma em {name}',
    OrgNode_Collapse: 'Recolher',
    OrgNode_Expand: 'Expandir',
    OrgNode_DirectReportsSuffix: 'Subordinados diretos de {name}',
    OrgNode_StatusDisabled: 'Desativada',
    OrgNode_StatusGuest: 'Convidado',
    OrgNode_TotalReportsAcrossLevels: '{count} pessoas em todos os níveis abaixo de {name}',

    // ── Drill view ──
    Drill_ReportingLineAria: 'Linha hierárquica',
    Drill_BackToTopTitle: 'Voltar ao topo',
    Drill_BackToTopAria: 'Voltar ao topo do organograma',
    Drill_GoBackTo: 'Voltar para {name}',
    Drill_ViewProfileTitle: 'Ver perfil',
    Drill_ViewProfileAria: 'Ver o perfil de {name}',
    Drill_ProfileButton: 'Perfil',
    Drill_LoadingLabel: 'Carregando...',
    Drill_DirectReports: 'Subordinados Diretos',
    Drill_DirectReportsOfAria: 'Subordinados diretos de {name}',
    Drill_DirectReportsAria: 'Subordinados diretos',
    Drill_ViewPersonProfile: 'Ver o perfil de {name}',
    Drill_ShowPersonReports: 'Mostrar os subordinados diretos de {name}',
    Drill_NoDirectReports: 'Nenhum subordinado direto',

    // ── Settings panel ──
    Settings_AlphabetFirstName: 'Primeiro Nome',
    Settings_AlphabetLastName: 'Sobrenome',
    Settings_CardSizeSmall: 'Pequeno — compacto, mais cartões visíveis',
    Settings_CardSizeMedium: 'Médio — equilibrado',
    Settings_CardSizeLarge: 'Grande — espaçoso, menos cartões',
    Settings_HeaderText: 'Preferências',
    Settings_SaveButton: 'Salvar',
    Settings_CancelButton: 'Cancelar',
    Settings_DiscardButton: 'Descartar Alterações',
    Settings_SectionDirectory: 'Diretório',
    Settings_AlphabetFilterByLabel: 'Filtro Alfabético Por',
    Settings_CardSizeLabel: 'Tamanho do Cartão',
    Settings_FontSizeLabel: 'Tamanho da Fonte',
    Settings_SectionCardsAndFields: 'Cartões e Campos',
    Settings_ShowOnCardsLabel: 'Mostrar nos cartões de funcionário:',
    Settings_EmailAddressLabel: 'Endereço de e-mail',
    Settings_PhoneNumberLabel: 'Número de telefone',
    Settings_DepartmentLabel: 'Departamento',
    Settings_OfficeLocationLabel: 'Local do escritório',
    Settings_SectionOrgChart: 'Organograma',
    Settings_ManagerLevelsLabel: 'Níveis de gerência exibidos ao focar em uma pessoa: {levels}',
    Settings_CompactCardsLabel: 'Cartões compactos',
    Settings_CompactCardsOn: 'Ativado — cartões menores, mais visíveis ao mesmo tempo',
    Settings_CompactCardsOff: 'Desativado — tamanho padrão',
    Settings_Hint: 'Essas preferências são salvas no seu navegador e se aplicam somente a você. O tema do organograma, a exibição padrão e o layout são configurados pelo administrador do SharePoint.',
    Settings_SectionDemoData: 'Dados de Demonstração',
    Settings_DatasetSizeLabel: 'Tamanho do conjunto de dados',
    Settings_PeopleCountSuffix: '{count} pessoas',

    // ── Export (CSV / PDF) ──
    Export_ColumnName: 'Nome',
    Export_ColumnJobTitle: 'Cargo',
    Export_ColumnDepartment: 'Departamento',
    Export_ColumnOffice: 'Escritório',
    Export_ColumnEmail: 'E-mail',
    Export_ColumnPhone: 'Telefone',
    Export_ColumnManager: 'Gerente',
    Export_ColumnLevel: 'Nível',
    Export_PdfDocumentTitle: 'Organograma',
    Export_PdfHeading: 'Organograma da Empresa',
    Export_PdfRootLabel: 'Raiz: {name}',
  };
});
