define([], function () {
  return {
    // ── Property pane: pane header / groups ──
    PropertyPane_HeaderDescription: 'Definições do Smart Org Chart',
    PropertyPane_Group_General: 'Geral',
    PropertyPane_Group_Branding: 'Identidade Visual',
    PropertyPane_Group_VisualStyle: 'Estilo Visual',
    PropertyPane_Group_DataSource: 'Fonte de Dados',
    PropertyPane_Group_CustomAttributes: 'Atributos Personalizados',
    PropertyPane_Group_UserFilters: 'Filtros de Utilizador',
    PropertyPane_Group_OrgChart: 'Organograma',
    PropertyPane_Group_OrgChartFeatures: 'Funcionalidades do Organograma',
    PropertyPane_Group_Directory: 'Diretório',
    PropertyPane_Group_Demo: 'Demonstração',

    // ── Property pane: General ──
    PropertyPane_DefaultView_Label: 'Vista Predefinida',

    // ── Property pane: Branding ──
    PropertyPane_AppTitle_Label: 'Título da Aplicação',
    PropertyPane_AppTitle_Placeholder: 'Organograma Contoso',
    PropertyPane_AppTitle_Description: 'Apresentado na barra de cabeçalho junto ao nome da vista',
    PropertyPane_LogoUrl_Label: 'URL do Logótipo',
    PropertyPane_LogoUrl_Placeholder: 'https://contoso.sharepoint.com/sites/oseusite/SiteAssets/logo.png',
    PropertyPane_LogoUrl_Description: 'URL completo de uma imagem PNG/SVG/JPG. Sugestão: abra o ficheiro de imagem no navegador e copie o URL da barra de endereço. Os URLs de partilha do tipo "Copiar ligação" não funcionarão.',
    PropertyPane_DirectoryLabel_Label: 'Etiqueta da Vista do Diretório de Colaboradores',
    PropertyPane_OrgChartLabel_Label: 'Etiqueta da Vista do Organograma',
    PropertyPane_ViewLabel_Description: 'Deixe em branco para utilizar o nome predefinido, ou escreva "[blank]" para ocultar completamente o rótulo.',

    // ── Property pane: Visual Style ──
    PropertyPane_ChartTheme_Label: 'Tema do Organograma',
    PropertyPane_Theme_Modern: 'Moderno — cores de departamento sobre branco',
    PropertyPane_Theme_Minimal: 'Minimalista — plano e de baixo contraste',
    PropertyPane_Theme_Corporate: 'Empresarial — azul unificado',
    PropertyPane_Theme_Dark: 'Escuro — fundo azul-marinho escuro',
    PropertyPane_Theme_Custom: 'Personalizado — escolha a sua própria cor',
    PropertyPane_AccentColor_Label: 'Cor de Destaque Personalizada',
    PropertyPane_AccentColor_PickerAriaLabel: 'Seletor de cor de destaque',
    PropertyPane_AccentColor_HexLabel: 'Hex',
    PropertyPane_AccentColor_HexAriaLabel: 'Valor hexadecimal da cor de destaque',
    PropertyPane_AccentColor_RgbLabel: 'RGB',
    PropertyPane_AccentColor_ChannelAriaLabel: 'Canal {name} (0 a 255)',
    PropertyPane_AccentColor_ContrastWithWhite: 'Contraste com o branco: {ratio}:1 ({passes})',
    PropertyPane_AccentColor_PassesAA: 'cumpre o nível AA',
    PropertyPane_AccentColor_LargeTextOnly: 'apenas texto grande',
    PropertyPane_AccentColor_LowContrast: 'contraste baixo',
    PropertyPane_AccentColor_DarkTextNote: 'O texto sobre esta cor utilizará texto escuro para melhor legibilidade.',
    PropertyPane_AccentColor_DarkerShadeNote: 'Os títulos e as ligações utilizarão um tom mais escuro ({hex}) para melhor legibilidade.',
    PropertyPane_AccentColor_InvalidHex: '"{typed}" não é uma cor hexadecimal válida. Utilize um valor como #0078d4 ou #07d.',
    PropertyPane_DefaultFontSize_Label: 'Tamanho de Letra Predefinido',
    PropertyPane_FontSize_75: '75% — Muito Pequeno',
    PropertyPane_FontSize_85: '85% — Pequeno',
    PropertyPane_FontSize_100: '100% — Normal',
    PropertyPane_FontSize_115: '115% — Grande',
    PropertyPane_FontSize_130: '130% — Muito Grande',
    PropertyPane_FontSize_150: '150% — XXL',
    PropertyPane_FontSize_175: '175% — XXXL',
    PropertyPane_DefaultLayout_Label: 'Esquema Predefinido do Organograma',
    PropertyPane_Layout_Drill: 'Aprofundar',
    PropertyPane_Layout_Vertical: 'De Cima para Baixo',
    PropertyPane_Layout_Horizontal: 'Da Esquerda para a Direita',

    // ── Property pane: Data Source ──
    PropertyPane_DataSource_Label: 'De onde carregar os dados de utilizadores e da organização',
    PropertyPane_DataSource_Auto: 'Automático — API do Graph, com recurso à Pesquisa do SharePoint',
    PropertyPane_DataSource_Graph: 'API do Graph — dados do Azure AD em tempo real (sem atraso de indexação)',
    PropertyPane_DataSource_Search: 'Pesquisa do SharePoint — comportamento legado',
    PropertyPane_DataSource_Note: 'Recomenda-se a API do Graph. Esta lê diretamente do Azure Active Directory, pelo que novos utilizadores e alterações de gestor são refletidos de imediato. Requer que as permissões do Microsoft Graph sejam aprovadas no Catálogo de Aplicações do SharePoint.',

    // ── Property pane: Custom Attributes ──
    PropertyPane_CustomAttributes_Note: 'Os atributos personalizados requerem o Microsoft Graph (Fonte de dados: Graph ou Automático). A Pesquisa do SharePoint não tem uma forma genérica de ler atributos do Entra ID.',
    PropertyPane_CustomAttributes_Heading: 'Gerir atributos personalizados',
    PropertyPane_CustomAttributes_Empty: 'Sem atributos personalizados configurados.',
    PropertyPane_CustomAttributes_AddButton: '+ Adicionar atributo',
    PropertyPane_CustomAttributes_MaxTooltip: 'Máximo de {max} atributos personalizados',
    PropertyPane_CustomAttributes_FieldNameLabel: 'Nome do atributo',
    PropertyPane_CustomAttributes_FieldPlaceholder: 'p. ex. companyName',
    PropertyPane_CustomAttributes_FieldError: 'Utilize employeeId, companyName, city, ... ou extensionAttribute1-15',
    PropertyPane_CustomAttributes_DisplayLabelLabel: 'Etiqueta de apresentação',
    PropertyPane_CustomAttributes_LabelPlaceholder: 'p. ex. Centro de Custo',
    PropertyPane_CustomAttributes_RemoveTitle: 'Remover atributo',
    PropertyPane_CustomAttributes_RemoveAriaLabel: 'Remover atributo {ordinal}',
    PropertyPane_CustomAttributes_ShowInDirectory: 'Mostrar no Diretório',
    PropertyPane_CustomAttributes_ShowInOrgChart: 'Mostrar no Organograma',

    // ── Property pane: User Filters ──
    PropertyPane_ExcludedAccounts_Label: 'Excluir contas',
    PropertyPane_ExcludedAccounts_Placeholder: 'sala-reunioes, noreply, admin@, Conta de Serviço',
    PropertyPane_ExcludedAccounts_Description: 'Palavras ou padrões separados por vírgula (não sensível a maiúsculas/minúsculas). Qualquer utilizador cujo nome a apresentar, e-mail ou UPN contenha um destes será ocultado em todas as vistas.',
    PropertyPane_RestrictTenant_Label: 'Mostrar apenas utilizadores do inquilino',
    PropertyPane_RestrictTenant_On: 'Ativado — oculta contas com domínios de e-mail externos (por ex., gmail.com, hotmail.com)',
    PropertyPane_RestrictTenant_Off: 'Desativado — são mostrados todos os utilizadores, seja qual for o domínio de e-mail',
    PropertyPane_HideGuest_Label: 'Ocultar contas de convidado do Azure AD',
    PropertyPane_HideGuest_On: 'Ativado — contas de convidado ocultas',
    PropertyPane_HideGuest_Off: 'Desativado — contas de convidado visíveis (apresentadas com o emblema Convidado)',
    PropertyPane_HideDisabled_Label: 'Ocultar contas desativadas',
    PropertyPane_HideDisabled_On: 'Ativado — contas com início de sessão bloqueado ocultas',
    PropertyPane_HideDisabled_Off: 'Desativado — contas desativadas visíveis (apresentadas com o emblema Desativada)',
    PropertyPane_HideDisabled_Note: 'Nota: a deteção de contas de convidado e desativadas requer a fonte de dados da API do Graph. A Pesquisa do SharePoint não devolve esta informação, pelo que estes dois filtros (e os emblemas Convidado/Desativada) não têm qualquer efeito quando os dados provêm da Pesquisa.',
    PropertyPane_HideNoJobTitle_Label: 'Ocultar contas sem função',
    PropertyPane_HideNoJobTitle_On: 'Ativado — contas sem função ocultas',
    PropertyPane_HideNoJobTitle_Off: 'Desativado — são mostradas todas as contas, independentemente da função',
    PropertyPane_HideNoDept_Label: 'Ocultar contas sem departamento',
    PropertyPane_HideNoDept_On: 'Ativado — contas sem departamento ocultas',
    PropertyPane_HideNoDept_Off: 'Desativado — são mostradas todas as contas, independentemente do departamento',

    // ── Property pane: Org Chart ──
    PropertyPane_TopLevelUser_Label: 'Utilizador de Topo (UPN ou E-mail)',
    PropertyPane_TopLevelUser_Placeholder: 'ceo@asuaempresa.com',
    PropertyPane_TopLevelUser_Description: 'A pessoa apresentada na raiz do organograma',
    PropertyPane_LevelsBelow_Label: 'Níveis a carregar abaixo da raiz',
    PropertyPane_DottedLine_Label: 'Atributo do gestor de linha tracejada',
    PropertyPane_DottedLine_Placeholder: 'extensionAttribute10',
    PropertyPane_DottedLine_Description: 'Opcional. Nome do atributo de extensão on-premises do Azure AD (extensionAttribute1-15) que armazena o e-mail ou UPN de um gestor secundário de "linha tracejada". As relações de linha tracejada são apresentadas nos cartões de perfil. Requer a fonte de dados da API do Graph.',
    PropertyPane_DefaultZoom_Label: 'Zoom Predefinido do Organograma',
    PropertyPane_Zoom_Auto: 'Predefinido (ajuste automático)',
    PropertyPane_Zoom_50: '50%',
    PropertyPane_Zoom_75: '75%',
    PropertyPane_Zoom_100: '100%',
    PropertyPane_Zoom_125: '125%',
    PropertyPane_Zoom_150: '150%',

    // ── Property pane: Org Chart Features ──
    PropertyPane_FeatureToggles_Note: 'Mostre ou oculte botões da barra de ferramentas na vista do organograma.',
    PropertyPane_FindMe_Label: 'Botão Encontrar-me',
    PropertyPane_LayoutToggle_Label: 'Alternar esquema (aprofundar / vertical / horizontal)',
    PropertyPane_Stats_Label: 'Barra de estatísticas da organização',
    PropertyPane_DeptFilter_Label: 'Filtro de departamento',
    PropertyPane_UserFilter_Label: 'Filtro de tipo de utilizador (membros / convidados)',
    PropertyPane_Visible: 'Visível',
    PropertyPane_Hidden: 'Oculto',

    // ── Property pane: Directory ──
    PropertyPane_PageSize_Label: 'Máximo de colaboradores por página',
    PropertyPane_PageSize_AriaLabel: 'Máximo de colaboradores por página (10 a 200)',
    PropertyPane_PageSize_Note: 'O tamanho dos cartões, os campos visíveis e outras preferências de apresentação são definidos por utilizador através do ícone de Definições na aplicação.',

    // ── Property pane: Demo ──
    PropertyPane_UseDemoData_Label: 'Utilizar Dados de Demonstração',
    PropertyPane_UseDemoData_On: 'Ativado — a mostrar colaboradores de exemplo',
    PropertyPane_UseDemoData_Off: 'Desativado — dados reais do Microsoft 365',

    // ── Presence status labels ──
    Presence_Available: 'Disponível',
    Presence_Busy: 'Ocupado',
    Presence_DoNotDisturb: 'Não Incomodar',
    Presence_BeRightBack: 'Volto Já',
    Presence_Away: 'Ausente',
    Presence_Offline: 'Offline',

    // ── Header / top bar ──
    Header_DirectoryLabel: 'Diretório de Colaboradores',
    Header_OrgChartLabel: 'Organograma',
    Header_SwitchToView: 'Mudar para {view}',
    Header_CompanyLogoAlt: 'Logótipo da empresa',
    Header_RefreshingAria: 'A atualizar dados',
    Header_RefreshAria: 'Atualizar dados',
    Header_RefreshTitle: 'Atualizar dados (última atualização: {when})',
    Header_NotLoadedYet: 'ainda não carregado',
    Header_JustNow: 'agora mesmo',
    Header_MinutesAgo: 'há {mins} min',
    Header_HoursAgo: 'há {hours} h',
    Header_PreferencesTitle: 'Preferências',
    Header_PreferencesAria: 'Abrir painel de preferências',

    // ── Employee Directory ──
    Directory_LoadingLabel: 'A carregar colaboradores...',
    Directory_LoadFailedFallback: 'Certifique-se de que o web part tem a permissão User.Read.All.',
    Directory_LoadFailedPrefix: 'Falha ao carregar colaboradores. {detail}',
    Directory_AllDepartments: 'Todos os Departamentos',
    Directory_AllOffices: 'Todos os Escritórios',
    Directory_StatusDisabled: 'Desativada',
    Directory_StatusGuest: 'Convidado',
    Directory_PresenceStatus: 'Estado: {status}',
    Directory_ChatInTeams: 'Conversar no Teams',
    Directory_ChatWithInTeams: 'Conversar com {name} no Teams',
    Directory_ManagesCount: 'Gere {direct}',
    Directory_ManagesCountWithTotal: 'Gere {direct} ({total} no total)',
    Directory_ReportsCountWithTotal: '{direct} ({total} no total)',
    Directory_ColumnName: 'Nome',
    Directory_ColumnJobTitle: 'Função',
    Directory_ColumnDepartment: 'Departamento',
    Directory_ColumnOffice: 'Escritório',
    Directory_ColumnEmail: 'E-mail',
    Directory_ColumnPhone: 'Telefone',
    Directory_ColumnReports: 'Subordinados',
    Directory_ColumnChat: 'Chat',
    Directory_PrevPage: 'Anterior',
    Directory_NextPage: 'Seguinte',
    Directory_PreviousPageAria: 'Página anterior',
    Directory_NextPageAria: 'Página seguinte',
    Directory_SearchPlaceholder: 'Pesquisar por nome, função, e-mail ou departamento...',
    Directory_SearchAria: 'Pesquisar pessoas',
    Directory_FilterByDepartmentAria: 'Filtrar por departamento',
    Directory_FilterByOfficeAria: 'Filtrar por escritório',
    Directory_ClearSearchTitle: 'Limpar a pesquisa e todos os filtros',
    Directory_ClearButton: 'Limpar',
    Directory_ClearFiltersButton: 'Limpar filtros',
    Directory_ExportCsvTitle: 'Exportar todos os resultados filtrados para um ficheiro CSV (abre no Excel)',
    Directory_ExportCsvButton: 'Exportar CSV',
    Directory_ViewModeAria: 'Modo de vista',
    Directory_CardViewTitle: 'Vista em cartões',
    Directory_ListViewTitle: 'Vista em lista',
    Directory_AlphabetFilterAria: 'Filtro alfabético',
    Directory_ShowAllTitle: 'Mostrar tudo',
    Directory_OtherLettersTitle: 'Filtrar por nomes que comecem por um número ou outro caráter',
    Directory_FilterByLetterTitle: 'Filtrar por {letter}',
    Directory_ResultCountSingular: 'pessoa',
    Directory_ResultCountPlural: 'pessoas',
    Directory_PageOf: ' · página {page} de {totalPages}',
    Directory_FilterActiveSingular: '{count} filtro ativo',
    Directory_FilterActivePlural: '{count} filtros ativos',
    Directory_NoResults: 'Não foi encontrada nenhuma pessoa',
    Directory_PaginationAria: 'Paginação',

    // ── Org chart toolbar / shared chart chrome ──
    Chart_Layout_Drill: 'Aprofundar',
    Chart_Layout_Vertical: 'De Cima para Baixo',
    Chart_Layout_Horizontal: 'Da Esquerda para a Direita',
    Chart_SearchPlaceholder: 'Pesquisar pessoas...',
    Chart_SearchAria: 'Pesquisar pessoas',
    Chart_MatchSingular: 'correspondência na árvore',
    Chart_MatchPlural: 'correspondências na árvore',
    Chart_ResultsListAria: 'Pessoas',
    Chart_ExpandAll: 'Expandir Tudo',
    Chart_CollapseAll: 'Recolher Tudo',
    Chart_Expanding: 'A expandir…',
    Chart_Loading: 'A carregar…',
    Chart_FindMeTitle: 'Encontrar-me no organograma',
    Chart_ViewLayoutButton: 'Vista',
    Chart_ViewLayoutTitle: 'Alternar esquema de vista',
    Chart_ViewLayoutPanelTitle: 'Esquema de vista',
    Chart_StatsSummaryTitle: 'Resumo de estatísticas da organização',
    Chart_FilterByDepartmentTitle: 'Filtrar por departamento',
    Chart_FilterByDepartmentWithCountAria: 'Filtrar por departamento ({count} selecionado(s))',
    Chart_FilterByDepartmentPanelTitle: 'Filtrar por departamento',
    Chart_ClearAllFilters: 'Limpar todos os filtros',
    Chart_FilterUserTypesTitle: 'Filtrar tipos de utilizador',
    Chart_DownloadPdfTitle: 'Transferir como PDF',
    Chart_DownloadCsvTitle: 'Transferir como folha de cálculo CSV',
    Chart_ResetRootTitle: 'Repor raiz predefinida',
    Chart_ViewFromPersonPlaceholder: 'Ver a partir de uma pessoa…',
    Chart_ViewFromPersonAria: 'Ver o organograma a partir de uma pessoa',
    Chart_ZoomOutTitle: 'Reduzir zoom',
    Chart_ZoomInTitle: 'Aumentar zoom',
    Chart_ZoomResetTitle: 'Repor zoom',
    Chart_ShowInChartAria: 'Mostrar no organograma',
    Chart_ShowInChartTitle: 'Mostrar no organograma',
    Chart_FilterMembers: 'Membros regulares',
    Chart_FilterGuests: 'Utilizadores convidados',
    Chart_FilterDisabled: 'Contas desativadas',
    Chart_SetupTitle: 'Configurar o Organograma',
    Chart_SetupSubtitle: 'Introduza o e-mail ou UPN da pessoa de topo para começar.',
    Chart_SetupPlaceholder: 'ceo@empresa.com',
    Chart_SetupInputAria: 'E-mail ou UPN da pessoa de topo',
    Chart_SetupLoadButton: 'Carregar',
    Chart_SetupHint: 'Também pode definir isto de forma permanente nas definições do web part (administrador).',
    Chart_BuildingLabel: 'A criar o organograma...',
    Chart_RetryButton: 'Tentar novamente',
    Chart_NotFoundFromSetup: 'Utilizador "{identifier}" não encontrado.',
    Chart_NotFoundWithSettings: 'Utilizador "{identifier}" não encontrado. Verifique o UPN ou o e-mail nas Definições.',
    Chart_LoadFailedGeneric: 'Falha ao carregar o organograma.{detail}',
    Chart_LoadFailedPermissions: ' Verifique as permissões.',
    Chart_LoadFailedForPerson: 'Falha ao carregar o organograma desta pessoa.',
    Chart_FindMeNotFound: 'A sua conta não foi encontrada nesta organização.',
    Chart_StatPeople: 'Pessoas',
    Chart_StatMembers: 'Membros',
    Chart_StatGuests: 'Convidados',
    Chart_StatDepts: 'Deptos.',
    Chart_ReportingLineAria: 'Linha hierárquica',
    Chart_BackToFullOrgTitle: 'Voltar ao organograma completo',
    Chart_FullOrgLabel: 'Organização completa',
    Chart_FocusOnPerson: 'Focar em {name}',
    Chart_OrgChartAria: 'Organograma',
    Chart_ExportNote_DrillLevel: 'Nível de aprofundamento atual (um nível de subordinados diretos)',
    Chart_ExportNote_PartialLevels: 'Inclui apenas os níveis carregados — utilize Expandir Tudo antes de exportar para incluir níveis mais profundos',
    Chart_AllowPopupsForPdf: 'Permita janelas pop-up para exportar o PDF.',

    // ── Person card ──
    PersonCard_ProfileAria: 'Perfil: {name}',
    PersonCard_CloseTitle: 'Fechar',
    PersonCard_CloseAria: 'Fechar perfil',
    PersonCard_StatusDisabled: 'Desativada',
    PersonCard_StatusGuest: 'Convidado',
    PersonCard_DirectReportSingular: '{count} subordinado direto',
    PersonCard_DirectReportPlural: '{count} subordinados diretos',
    PersonCard_TotalSuffix: ' · {total} no total',
    PersonCard_CopyEmailTitle: 'Copiar endereço de e-mail',
    PersonCard_EmailCopiedAria: 'Endereço de e-mail copiado',
    PersonCard_ReportsTo: 'Reporta a',
    PersonCard_FocusOnPerson: 'Focar em {name}',
    PersonCard_FocusOrgChartOnPerson: 'Focar o organograma em {name}',
    PersonCard_DottedLine: 'Linha tracejada',
    PersonCard_DottedLineManager: 'Gestor de linha tracejada: {name}',
    PersonCard_DottedLineReport: 'Subordinado de linha tracejada: {name}',
    PersonCard_ChatButton: 'Chat',
    PersonCard_EmailButton: 'E-mail',
    PersonCard_FocusButton: 'Focar',
    PersonCard_FocusTitle: 'Focar o organograma nesta pessoa',

    // ── Org node card ──
    OrgNode_ViewProfile: 'Ver o perfil de {name}',
    OrgNode_FocusOrgChartOn: 'Focar o organograma em {name}',
    OrgNode_Collapse: 'Recolher',
    OrgNode_Expand: 'Expandir',
    OrgNode_DirectReportsSuffix: 'Subordinados diretos de {name}',
    OrgNode_StatusDisabled: 'Desativada',
    OrgNode_StatusGuest: 'Convidado',
    OrgNode_TotalReportsAcrossLevels: '{count} pessoas em todos os níveis abaixo de {name}',

    // ── Drill view ──
    Drill_ReportingLineAria: 'Linha hierárquica',
    Drill_BackToTopTitle: 'Voltar ao topo',
    Drill_BackToTopAria: 'Voltar ao topo do organograma',
    Drill_GoBackTo: 'Voltar a {name}',
    Drill_ViewProfileTitle: 'Ver perfil',
    Drill_ViewProfileAria: 'Ver o perfil de {name}',
    Drill_ProfileButton: 'Perfil',
    Drill_LoadingLabel: 'A carregar...',
    Drill_DirectReports: 'Subordinados Diretos',
    Drill_DirectReportsOfAria: 'Subordinados diretos de {name}',
    Drill_DirectReportsAria: 'Subordinados diretos',
    Drill_ViewPersonProfile: 'Ver o perfil de {name}',
    Drill_ShowPersonReports: 'Mostrar os subordinados diretos de {name}',
    Drill_NoDirectReports: 'Sem subordinados diretos',

    // ── Settings panel ──
    Settings_AlphabetFirstName: 'Primeiro Nome',
    Settings_AlphabetLastName: 'Apelido',
    Settings_CardSizeSmall: 'Pequeno — compacto, mais cartões visíveis',
    Settings_CardSizeMedium: 'Médio — equilibrado',
    Settings_CardSizeLarge: 'Grande — espaçoso, menos cartões',
    Settings_HeaderText: 'Preferências',
    Settings_SaveButton: 'Guardar',
    Settings_CancelButton: 'Cancelar',
    Settings_DiscardButton: 'Descartar Alterações',
    Settings_SectionDirectory: 'Diretório',
    Settings_AlphabetFilterByLabel: 'Filtro Alfabético Por',
    Settings_CardSizeLabel: 'Tamanho do Cartão',
    Settings_FontSizeLabel: 'Tamanho de Letra',
    Settings_SectionCardsAndFields: 'Cartões e Campos',
    Settings_ShowOnCardsLabel: 'Mostrar nos cartões de colaborador:',
    Settings_EmailAddressLabel: 'Endereço de e-mail',
    Settings_PhoneNumberLabel: 'Número de telefone',
    Settings_DepartmentLabel: 'Departamento',
    Settings_OfficeLocationLabel: 'Localização do escritório',
    Settings_SectionOrgChart: 'Organograma',
    Settings_ManagerLevelsLabel: 'Níveis de gestão apresentados ao focar uma pessoa: {levels}',
    Settings_CompactCardsLabel: 'Cartões compactos',
    Settings_CompactCardsOn: 'Ativado — cartões mais pequenos, mais visíveis em simultâneo',
    Settings_CompactCardsOff: 'Desativado — tamanho normal',
    Settings_Hint: 'Estas preferências são guardadas no seu navegador e aplicam-se apenas a si. O tema do organograma, a vista predefinida e o esquema são configurados pelo administrador do SharePoint.',
    Settings_SectionDemoData: 'Dados de Demonstração',
    Settings_DatasetSizeLabel: 'Tamanho do conjunto de dados',
    Settings_PeopleCountSuffix: '{count} pessoas',

    // ── Export (CSV / PDF) ──
    Export_ColumnName: 'Nome',
    Export_ColumnJobTitle: 'Função',
    Export_ColumnDepartment: 'Departamento',
    Export_ColumnOffice: 'Escritório',
    Export_ColumnEmail: 'E-mail',
    Export_ColumnPhone: 'Telefone',
    Export_ColumnManager: 'Gestor',
    Export_ColumnLevel: 'Nível',
    Export_PdfDocumentTitle: 'Organograma',
    Export_PdfHeading: 'Organograma da Empresa',
    Export_PdfRootLabel: 'Raiz: {name}',
  };
});
