define([], function () {
  return {
    // ── Property pane: pane header / groups ──
    PropertyPane_HeaderDescription: 'Setări Smart Org Chart',
    PropertyPane_Group_General: 'General',
    PropertyPane_Group_Branding: 'Branding',
    PropertyPane_Group_VisualStyle: 'Stil vizual',
    PropertyPane_Group_DataSource: 'Sursă de date',
    PropertyPane_Group_CustomAttributes: 'Atribute personalizate',
    PropertyPane_Group_UserFilters: 'Filtre utilizatori',
    PropertyPane_Group_OrgChart: 'Organigramă',
    PropertyPane_Group_OrgChartFeatures: 'Funcții organigramă',
    PropertyPane_Group_Directory: 'Director',
    PropertyPane_Group_Demo: 'Demo',

    // ── Property pane: General ──
    PropertyPane_DefaultView_Label: 'Vizualizare implicită',

    // ── Property pane: Branding ──
    PropertyPane_AppTitle_Label: 'Titlul aplicației',
    PropertyPane_AppTitle_Placeholder: 'Organigrama Contoso',
    PropertyPane_AppTitle_Description: 'Afișat în bara de antet, alături de numele vizualizării',
    PropertyPane_LogoUrl_Label: 'Adresă URL a siglei',
    PropertyPane_LogoUrl_Placeholder: 'https://contoso.sharepoint.com/sites/yoursite/SiteAssets/logo.png',
    PropertyPane_LogoUrl_Description: 'Adresă URL completă către o imagine PNG/SVG/JPG. Sfat: deschideți fișierul imagine în browser și copiați adresa URL din bara de adrese. Adresele URL de tip „Copiere link" nu vor funcționa.',
    PropertyPane_DirectoryLabel_Label: 'Eticheta vizualizării Director angajați',
    PropertyPane_OrgChartLabel_Label: 'Eticheta vizualizării Organigramă',
    PropertyPane_ViewLabel_Description: 'Lăsați necompletat pentru a utiliza numele implicit, sau introduceți "[blank]" pentru a ascunde complet eticheta.',

    // ── Property pane: Visual Style ──
    PropertyPane_ChartTheme_Label: 'Temă organigramă',
    PropertyPane_Theme_Modern: 'Modern — culori de departament pe fundal alb',
    PropertyPane_Theme_Minimal: 'Minimalist — plat și contrast redus',
    PropertyPane_Theme_Corporate: 'Corporate — albastru unificat',
    PropertyPane_Theme_Dark: 'Întunecat — fundal bleumarin închis',
    PropertyPane_Theme_Custom: 'Personalizat — alegeți propria culoare',
    PropertyPane_AccentColor_Label: 'Culoare de accent personalizată',
    PropertyPane_AccentColor_PickerAriaLabel: 'Selector culoare de accent',
    PropertyPane_AccentColor_HexLabel: 'Hex',
    PropertyPane_AccentColor_HexAriaLabel: 'Valoare Hex a culorii de accent',
    PropertyPane_AccentColor_RgbLabel: 'RGB',
    PropertyPane_AccentColor_ChannelAriaLabel: 'Canal {name} (0 până la 255)',
    PropertyPane_AccentColor_ContrastWithWhite: 'Contrast cu alb: {ratio}:1 ({passes})',
    PropertyPane_AccentColor_PassesAA: 'îndeplinește standardul AA',
    PropertyPane_AccentColor_LargeTextOnly: 'doar text mare',
    PropertyPane_AccentColor_LowContrast: 'contrast redus',
    PropertyPane_AccentColor_DarkTextNote: 'Textul pe această culoare va folosi text închis la culoare pentru lizibilitate.',
    PropertyPane_AccentColor_DarkerShadeNote: 'Titlurile și linkurile vor folosi o nuanță mai închisă ({hex}) pentru lizibilitate.',
    PropertyPane_AccentColor_InvalidHex: '„{typed}" nu este o culoare Hex validă. Utilizați o valoare precum #0078d4 sau #07d.',
    PropertyPane_DefaultFontSize_Label: 'Dimensiune font implicită',
    PropertyPane_FontSize_75: '75% — Foarte mic',
    PropertyPane_FontSize_85: '85% — Mic',
    PropertyPane_FontSize_100: '100% — Normal',
    PropertyPane_FontSize_115: '115% — Mare',
    PropertyPane_FontSize_130: '130% — Foarte mare',
    PropertyPane_FontSize_150: '150% — XXL',
    PropertyPane_FontSize_175: '175% — XXXL',
    PropertyPane_DefaultLayout_Label: 'Aspect implicit al organigramei',
    PropertyPane_Layout_Drill: 'Explorare ierarhică',
    PropertyPane_Layout_Vertical: 'De sus în jos',
    PropertyPane_Layout_Horizontal: 'De la stânga la dreapta',

    // ── Property pane: Data Source ──
    PropertyPane_DataSource_Label: 'De unde se încarcă datele despre utilizatori și organizație',
    PropertyPane_DataSource_Auto: 'Automat — Graph API, cu revenire la căutarea SharePoint',
    PropertyPane_DataSource_Graph: 'Graph API — date live din Azure AD (fără întârziere de indexare)',
    PropertyPane_DataSource_Search: 'Căutare SharePoint — comportament vechi',
    PropertyPane_DataSource_Note: 'Se recomandă Microsoft Graph API. Acesta citește direct din Azure Active Directory, astfel încât utilizatorii noi și schimbările de manager apar imediat. Necesită aprobarea permisiunilor Microsoft Graph în catalogul de aplicații SharePoint.',

    // ── Property pane: Custom Attributes ──
    PropertyPane_CustomAttributes_Note: 'Atributele personalizate necesită Microsoft Graph (Sursă de date: Graph sau Automat). Căutarea SharePoint nu are o modalitate generică de a citi atribute Entra ID.',
    PropertyPane_CustomAttributes_Heading: 'Gestionare atribute personalizate',
    PropertyPane_CustomAttributes_Empty: 'Nu este configurat niciun atribut personalizat.',
    PropertyPane_CustomAttributes_AddButton: '+ Adăugare atribut',
    PropertyPane_CustomAttributes_MaxTooltip: 'Maximum {max} atribute personalizate',
    PropertyPane_CustomAttributes_FieldNameLabel: 'Nume atribut',
    PropertyPane_CustomAttributes_FieldPlaceholder: 'de ex. companyName',
    PropertyPane_CustomAttributes_FieldError: 'Utilizați employeeId, companyName, city, ... sau extensionAttribute1-15',
    PropertyPane_CustomAttributes_DisplayLabelLabel: 'Etichetă afișată',
    PropertyPane_CustomAttributes_LabelPlaceholder: 'de ex. Centru de cost',
    PropertyPane_CustomAttributes_RemoveTitle: 'Eliminare atribut',
    PropertyPane_CustomAttributes_RemoveAriaLabel: 'Eliminare atribut {ordinal}',
    PropertyPane_CustomAttributes_ShowInDirectory: 'Afișare în Director',
    PropertyPane_CustomAttributes_ShowInOrgChart: 'Afișare în Organigramă',

    // ── Property pane: User Filters ──
    PropertyPane_ExcludedAccounts_Label: 'Excludere conturi',
    PropertyPane_ExcludedAccounts_Placeholder: 'conf-room, noreply, admin@, Service Account',
    PropertyPane_ExcludedAccounts_Description: 'Cuvinte sau tipare separate prin virgulă (fără sensibilitate la majuscule). Orice utilizator al cărui nume afișat, e-mail sau UPN conține unul dintre acestea va fi ascuns din toate vizualizările.',
    PropertyPane_RestrictTenant_Label: 'Afișare doar utilizatori din tenant',
    PropertyPane_RestrictTenant_On: 'Activat — ascunde conturile cu domenii de e-mail externe (de ex. gmail.com, hotmail.com)',
    PropertyPane_RestrictTenant_Off: 'Dezactivat — toți utilizatorii sunt afișați indiferent de domeniul de e-mail',
    PropertyPane_HideGuest_Label: 'Ascundere conturi invitat Azure AD',
    PropertyPane_HideGuest_On: 'Activat — conturile invitat sunt ascunse',
    PropertyPane_HideGuest_Off: 'Dezactivat — conturile invitat sunt vizibile (afișate cu insigna Invitat)',
    PropertyPane_HideDisabled_Label: 'Ascundere conturi dezactivate',
    PropertyPane_HideDisabled_On: 'Activat — conturile cu autentificare blocată sunt ascunse',
    PropertyPane_HideDisabled_Off: 'Dezactivat — conturile dezactivate sunt vizibile (afișate cu insigna Dezactivat)',
    PropertyPane_HideDisabled_Note: 'Notă: detectarea conturilor invitat și dezactivate necesită sursa de date Graph API. Căutarea SharePoint nu returnează aceste informații, așa că aceste două filtre (și insignele Invitat/Dezactivat) nu au niciun efect atunci când datele provin din Căutare.',
    PropertyPane_HideNoJobTitle_Label: 'Ascundere conturi fără titlu de post',
    PropertyPane_HideNoJobTitle_On: 'Activat — conturile fără titlu de post sunt ascunse',
    PropertyPane_HideNoJobTitle_Off: 'Dezactivat — toate conturile sunt afișate indiferent de titlul de post',
    PropertyPane_HideNoDept_Label: 'Ascundere conturi fără departament',
    PropertyPane_HideNoDept_On: 'Activat — conturile fără departament sunt ascunse',
    PropertyPane_HideNoDept_Off: 'Dezactivat — toate conturile sunt afișate indiferent de departament',

    // ── Property pane: Org Chart ──
    PropertyPane_TopLevelUser_Label: 'Utilizator de nivel superior (UPN sau e-mail)',
    PropertyPane_TopLevelUser_Placeholder: 'ceo@yourcompany.com',
    PropertyPane_TopLevelUser_Description: 'Persoana afișată la rădăcina organigramei',
    PropertyPane_LevelsBelow_Label: 'Niveluri de încărcat sub rădăcină',
    PropertyPane_DottedLine_Label: 'Atribut manager cu linie punctată',
    PropertyPane_DottedLine_Placeholder: 'extensionAttribute10',
    PropertyPane_DottedLine_Description: 'Opțional. Numele atributului de extensie Azure AD local (extensionAttribute1-15) care stochează e-mailul sau UPN-ul unui manager secundar „cu linie punctată". Relațiile cu linie punctată apar pe fișele de profil. Necesită sursa de date Graph API.',
    PropertyPane_DefaultZoom_Label: 'Zoom implicit al organigramei',
    PropertyPane_Zoom_Auto: 'Implicit (potrivire automată)',
    PropertyPane_Zoom_50: '50%',
    PropertyPane_Zoom_75: '75%',
    PropertyPane_Zoom_100: '100%',
    PropertyPane_Zoom_125: '125%',
    PropertyPane_Zoom_150: '150%',

    // ── Property pane: Org Chart Features ──
    PropertyPane_FeatureToggles_Note: 'Afișați sau ascundeți butoanele din bara de instrumente în vizualizarea organigramei.',
    PropertyPane_FindMe_Label: 'Buton „Găsește-mă"',
    PropertyPane_LayoutToggle_Label: 'Comutare aspect (ierarhic / vertical / orizontal)',
    PropertyPane_Stats_Label: 'Bară statistici organizație',
    PropertyPane_DeptFilter_Label: 'Filtru departament',
    PropertyPane_UserFilter_Label: 'Filtru tip utilizator (membri / invitați)',
    PropertyPane_Visible: 'Vizibil',
    PropertyPane_Hidden: 'Ascuns',

    // ── Property pane: Directory ──
    PropertyPane_PageSize_Label: 'Număr maxim de angajați per pagină',
    PropertyPane_PageSize_AriaLabel: 'Număr maxim de angajați per pagină (10 până la 200)',
    PropertyPane_PageSize_Note: 'Dimensiunea cardurilor, câmpurile vizibile și alte preferințe de afișare sunt setate per utilizator prin pictograma Setări din aplicație.',

    // ── Property pane: Demo ──
    PropertyPane_UseDemoData_Label: 'Utilizare date demonstrative',
    PropertyPane_UseDemoData_On: 'Activat — se afișează angajați exemplu',
    PropertyPane_UseDemoData_Off: 'Dezactivat — date live Microsoft 365',

    // ── Presence status labels ──
    Presence_Available: 'Disponibil',
    Presence_Busy: 'Ocupat',
    Presence_DoNotDisturb: 'Nu deranjați',
    Presence_BeRightBack: 'Revin imediat',
    Presence_Away: 'Absent',
    Presence_Offline: 'Deconectat',

    // ── Header / top bar ──
    Header_DirectoryLabel: 'Director angajați',
    Header_OrgChartLabel: 'Organigramă',
    Header_SwitchToView: 'Comutare la {view}',
    Header_CompanyLogoAlt: 'Siglă companie',
    Header_RefreshingAria: 'Se reîmprospătează datele',
    Header_RefreshAria: 'Reîmprospătare date',
    Header_RefreshTitle: 'Reîmprospătare date (ultima actualizare {when})',
    Header_NotLoadedYet: 'neîncărcat încă',
    Header_JustNow: 'chiar acum',
    Header_MinutesAgo: 'acum {mins} min',
    Header_HoursAgo: 'acum {hours} h',
    Header_PreferencesTitle: 'Preferințe',
    Header_PreferencesAria: 'Deschidere panou de preferințe',

    // ── Employee Directory ──
    Directory_LoadingLabel: 'Se încarcă angajații...',
    Directory_LoadFailedFallback: 'Asigurați-vă că elementul web are permisiunea User.Read.All.',
    Directory_LoadFailedPrefix: 'Încărcarea angajaților a eșuat. {detail}',
    Directory_AllDepartments: 'Toate departamentele',
    Directory_AllOffices: 'Toate birourile',
    Directory_StatusDisabled: 'Dezactivat',
    Directory_StatusGuest: 'Invitat',
    Directory_PresenceStatus: 'Stare: {status}',
    Directory_ChatInTeams: 'Chat în Teams',
    Directory_ChatWithInTeams: 'Chat cu {name} în Teams',
    Directory_ManagesCount: 'Coordonează {direct}',
    Directory_ManagesCountWithTotal: 'Coordonează {direct} (total {total})',
    Directory_ReportsCountWithTotal: '{direct} (total {total})',
    Directory_ColumnName: 'Nume',
    Directory_ColumnJobTitle: 'Titlu post',
    Directory_ColumnDepartment: 'Departament',
    Directory_ColumnOffice: 'Birou',
    Directory_ColumnEmail: 'E-mail',
    Directory_ColumnPhone: 'Telefon',
    Directory_ColumnReports: 'Subordonați',
    Directory_ColumnChat: 'Chat',
    Directory_PrevPage: 'Anterior',
    Directory_NextPage: 'Următor',
    Directory_PreviousPageAria: 'Pagina anterioară',
    Directory_NextPageAria: 'Pagina următoare',
    Directory_SearchPlaceholder: 'Căutați după nume, titlu, e-mail sau departament...',
    Directory_SearchAria: 'Căutare persoane',
    Directory_FilterByDepartmentAria: 'Filtrare după departament',
    Directory_FilterByOfficeAria: 'Filtrare după birou',
    Directory_ClearSearchTitle: 'Ștergere căutare și toate filtrele',
    Directory_ClearButton: 'Ștergere',
    Directory_ClearFiltersButton: 'Ștergere filtre',
    Directory_ExportCsvTitle: 'Exportați toate rezultatele filtrate într-un fișier CSV (se deschide în Excel)',
    Directory_ExportCsvButton: 'Export CSV',
    Directory_ViewModeAria: 'Mod de vizualizare',
    Directory_CardViewTitle: 'Vizualizare carduri',
    Directory_ListViewTitle: 'Vizualizare listă',
    Directory_AlphabetFilterAria: 'Filtru alfabetic',
    Directory_ShowAllTitle: 'Afișare toate',
    Directory_OtherLettersTitle: 'Filtrare după nume ce încep cu o cifră sau alt caracter',
    Directory_FilterByLetterTitle: 'Filtrare după {letter}',
    Directory_ResultCountSingular: 'persoană',
    Directory_ResultCountPlural: 'persoane',
    Directory_PageOf: ' · pagina {page} din {totalPages}',
    Directory_FilterActiveSingular: '{count} filtru activ',
    Directory_FilterActivePlural: '{count} filtre active',
    Directory_NoResults: 'Nu s-au găsit persoane',
    Directory_PaginationAria: 'Paginare',

    // ── Org chart toolbar / shared chart chrome ──
    Chart_Layout_Drill: 'Explorare ierarhică',
    Chart_Layout_Vertical: 'De sus în jos',
    Chart_Layout_Horizontal: 'De la stânga la dreapta',
    Chart_SearchPlaceholder: 'Căutare persoane...',
    Chart_SearchAria: 'Căutare persoane',
    Chart_MatchSingular: 'potrivire în arbore',
    Chart_MatchPlural: 'potriviri în arbore',
    Chart_ResultsListAria: 'Persoane',
    Chart_ExpandAll: 'Extindere totală',
    Chart_CollapseAll: 'Restrângere totală',
    Chart_Expanding: 'Se extinde…',
    Chart_Loading: 'Se încarcă…',
    Chart_FindMeTitle: 'Găsește-mă în organigramă',
    Chart_ViewLayoutButton: 'Vizualizare',
    Chart_ViewLayoutTitle: 'Comutare aspect de vizualizare',
    Chart_ViewLayoutPanelTitle: 'Aspect de vizualizare',
    Chart_StatsSummaryTitle: 'Rezumat statistici organizație',
    Chart_FilterByDepartmentTitle: 'Filtrare după departament',
    Chart_FilterByDepartmentWithCountAria: 'Filtrare după departament ({count} selectate)',
    Chart_FilterByDepartmentPanelTitle: 'Filtrare după departament',
    Chart_ClearAllFilters: 'Ștergere toate filtrele',
    Chart_FilterUserTypesTitle: 'Filtrare tipuri de utilizatori',
    Chart_DownloadPdfTitle: 'Descărcare ca PDF',
    Chart_DownloadCsvTitle: 'Descărcare ca foaie de calcul CSV',
    Chart_ResetRootTitle: 'Resetare la rădăcina implicită',
    Chart_ViewFromPersonPlaceholder: 'Vizualizare din perspectiva unei persoane…',
    Chart_ViewFromPersonAria: 'Vizualizați organigrama din perspectiva unei persoane',
    Chart_ZoomOutTitle: 'Micșorare',
    Chart_ZoomInTitle: 'Mărire',
    Chart_ZoomResetTitle: 'Resetare zoom',
    Chart_ShowInChartAria: 'Afișare în organigramă',
    Chart_ShowInChartTitle: 'Afișare în organigramă',
    Chart_FilterMembers: 'Membri obișnuiți',
    Chart_FilterGuests: 'Utilizatori invitați',
    Chart_FilterDisabled: 'Conturi dezactivate',
    Chart_SetupTitle: 'Configurați organigrama',
    Chart_SetupSubtitle: 'Introduceți e-mailul sau UPN-ul persoanei de nivel superior pentru a începe.',
    Chart_SetupPlaceholder: 'ceo@company.com',
    Chart_SetupInputAria: 'E-mailul sau UPN-ul persoanei de nivel superior',
    Chart_SetupLoadButton: 'Încărcare',
    Chart_SetupHint: 'Puteți seta acest lucru și permanent în setările elementului web (administrator).',
    Chart_BuildingLabel: 'Se construiește organigrama...',
    Chart_RetryButton: 'Reîncercare',
    Chart_NotFoundFromSetup: 'Utilizatorul „{identifier}" nu a fost găsit.',
    Chart_NotFoundWithSettings: 'Utilizatorul „{identifier}" nu a fost găsit. Verificați UPN-ul sau e-mailul în Setări.',
    Chart_LoadFailedGeneric: 'Încărcarea organigramei a eșuat.{detail}',
    Chart_LoadFailedPermissions: ' Verificați permisiunile.',
    Chart_LoadFailedForPerson: 'Încărcarea organigramei pentru această persoană a eșuat.',
    Chart_FindMeNotFound: 'Contul dvs. nu a fost găsit în această organizație.',
    Chart_StatPeople: 'Persoane',
    Chart_StatMembers: 'Membri',
    Chart_StatGuests: 'Invitați',
    Chart_StatDepts: 'Dept.',
    Chart_ReportingLineAria: 'Linie ierarhică',
    Chart_BackToFullOrgTitle: 'Înapoi la organigrama completă',
    Chart_FullOrgLabel: 'Organizație completă',
    Chart_FocusOnPerson: 'Focalizare pe {name}',
    Chart_OrgChartAria: 'Organigramă',
    Chart_ExportNote_DrillLevel: 'Nivelul curent de explorare (un nivel de subordonați direcți)',
    Chart_ExportNote_PartialLevels: 'Include doar nivelurile încărcate — utilizați Extindere totală înainte de export pentru a include niveluri mai profunde',
    Chart_AllowPopupsForPdf: 'Permiteți ferestrele pop-up pentru a exporta în PDF.',

    // ── Person card ──
    PersonCard_ProfileAria: 'Profil: {name}',
    PersonCard_CloseTitle: 'Închidere',
    PersonCard_CloseAria: 'Închidere profil',
    PersonCard_StatusDisabled: 'Dezactivat',
    PersonCard_StatusGuest: 'Invitat',
    PersonCard_DirectReportSingular: '{count} subordonat direct',
    PersonCard_DirectReportPlural: '{count} subordonați direcți',
    PersonCard_TotalSuffix: ' · total {total}',
    PersonCard_CopyEmailTitle: 'Copiere adresă de e-mail',
    PersonCard_EmailCopiedAria: 'Adresa de e-mail a fost copiată',
    PersonCard_ReportsTo: 'Subordonat față de',
    PersonCard_FocusOnPerson: 'Focalizare pe {name}',
    PersonCard_FocusOrgChartOnPerson: 'Focalizare organigramă pe {name}',
    PersonCard_DottedLine: 'Linie punctată',
    PersonCard_DottedLineManager: 'Manager cu linie punctată: {name}',
    PersonCard_DottedLineReport: 'Subordonat cu linie punctată: {name}',
    PersonCard_ChatButton: 'Chat',
    PersonCard_EmailButton: 'E-mail',
    PersonCard_FocusButton: 'Focalizare',
    PersonCard_FocusTitle: 'Focalizare organigramă pe această persoană',

    // ── Org node card ──
    OrgNode_ViewProfile: 'Vizualizare profilul lui {name}',
    OrgNode_FocusOrgChartOn: 'Focalizare organigramă pe {name}',
    OrgNode_Collapse: 'Restrângere',
    OrgNode_Expand: 'Extindere',
    OrgNode_DirectReportsSuffix: 'Subordonații direcți ai lui {name}',
    OrgNode_StatusDisabled: 'Dezactivat',
    OrgNode_StatusGuest: 'Invitat',
    OrgNode_TotalReportsAcrossLevels: '{count} persoane pe toate nivelurile sub {name}',

    // ── Drill view ──
    Drill_ReportingLineAria: 'Linie ierarhică',
    Drill_BackToTopTitle: 'Înapoi sus',
    Drill_BackToTopAria: 'Înapoi la vârful organigramei',
    Drill_GoBackTo: 'Înapoi la {name}',
    Drill_ViewProfileTitle: 'Vizualizare profil',
    Drill_ViewProfileAria: 'Vizualizare profilul lui {name}',
    Drill_ProfileButton: 'Profil',
    Drill_LoadingLabel: 'Se încarcă...',
    Drill_DirectReports: 'Subordonați direcți',
    Drill_DirectReportsOfAria: 'Subordonații direcți ai lui {name}',
    Drill_DirectReportsAria: 'Subordonați direcți',
    Drill_ViewPersonProfile: 'Vizualizare profilul lui {name}',
    Drill_ShowPersonReports: 'Afișare subordonații direcți ai lui {name}',
    Drill_NoDirectReports: 'Niciun subordonat direct',

    // ── Settings panel ──
    Settings_AlphabetFirstName: 'Prenume',
    Settings_AlphabetLastName: 'Nume de familie',
    Settings_CardSizeSmall: 'Mic — compact, mai multe carduri vizibile',
    Settings_CardSizeMedium: 'Mediu — echilibrat',
    Settings_CardSizeLarge: 'Mare — spațios, mai puține carduri',
    Settings_HeaderText: 'Preferințe',
    Settings_SaveButton: 'Salvare',
    Settings_CancelButton: 'Anulare',
    Settings_DiscardButton: 'Anulare modificări',
    Settings_SectionDirectory: 'Director',
    Settings_AlphabetFilterByLabel: 'Filtrare alfabetică după',
    Settings_CardSizeLabel: 'Dimensiune card',
    Settings_FontSizeLabel: 'Dimensiune font',
    Settings_SectionCardsAndFields: 'Carduri și câmpuri',
    Settings_ShowOnCardsLabel: 'Afișare pe cardurile angajaților:',
    Settings_EmailAddressLabel: 'Adresă de e-mail',
    Settings_PhoneNumberLabel: 'Număr de telefon',
    Settings_DepartmentLabel: 'Departament',
    Settings_OfficeLocationLabel: 'Locație birou',
    Settings_SectionOrgChart: 'Organigramă',
    Settings_ManagerLevelsLabel: 'Niveluri de manageri afișate la focalizarea pe o persoană: {levels}',
    Settings_CompactCardsLabel: 'Carduri compacte',
    Settings_CompactCardsOn: 'Activat — carduri mai mici, mai multe vizibile simultan',
    Settings_CompactCardsOff: 'Dezactivat — dimensiune standard',
    Settings_Hint: 'Aceste preferințe sunt salvate în browserul dvs. și se aplică doar dvs. Tema organigramei, vizualizarea implicită și aspectul sunt configurate de administratorul dvs. SharePoint.',
    Settings_SectionDemoData: 'Date demonstrative',
    Settings_DatasetSizeLabel: 'Dimensiune set de date',
    Settings_PeopleCountSuffix: '{count} persoane',

    // ── Export (CSV / PDF) ──
    Export_ColumnName: 'Nume',
    Export_ColumnJobTitle: 'Titlu post',
    Export_ColumnDepartment: 'Departament',
    Export_ColumnOffice: 'Birou',
    Export_ColumnEmail: 'E-mail',
    Export_ColumnPhone: 'Telefon',
    Export_ColumnManager: 'Manager',
    Export_ColumnLevel: 'Nivel',
    Export_PdfDocumentTitle: 'Organigramă',
    Export_PdfHeading: 'Organigrama companiei',
    Export_PdfRootLabel: 'Rădăcină: {name}',
  };
});
