define([], function () {
  return {
    // ── Property pane: pane header / groups ──
    PropertyPane_HeaderDescription: 'Параметры Smart Org Chart',
    PropertyPane_Group_General: 'Общие',
    PropertyPane_Group_Branding: 'Брендинг',
    PropertyPane_Group_VisualStyle: 'Оформление',
    PropertyPane_Group_DataSource: 'Источник данных',
    PropertyPane_Group_CustomAttributes: 'Настраиваемые атрибуты',
    PropertyPane_Group_UserFilters: 'Фильтры пользователей',
    PropertyPane_Group_OrgChart: 'Оргструктура',
    PropertyPane_Group_OrgChartFeatures: 'Функции оргструктуры',
    PropertyPane_Group_Directory: 'Каталог сотрудников',
    PropertyPane_Group_Demo: 'Демоданные',

    // ── Property pane: General ──
    PropertyPane_DefaultView_Label: 'Представление по умолчанию',

    // ── Property pane: Branding ──
    PropertyPane_AppTitle_Label: 'Название приложения',
    PropertyPane_AppTitle_Placeholder: 'Contoso Org Chart',
    PropertyPane_AppTitle_Description: 'Отображается на панели заголовка рядом с названием представления',
    PropertyPane_LogoUrl_Label: 'URL-адрес логотипа',
    PropertyPane_LogoUrl_Placeholder: 'https://contoso.sharepoint.com/sites/yoursite/SiteAssets/logo.png',
    PropertyPane_LogoUrl_Description: 'Полный URL-адрес изображения в формате PNG, SVG или JPG. Совет: откройте файл изображения в браузере и скопируйте адрес из адресной строки. Ссылки, полученные через «Копировать ссылку», работать не будут.',
    PropertyPane_DirectoryLabel_Label: 'Название представления «Каталог сотрудников»',
    PropertyPane_OrgChartLabel_Label: 'Название представления «Оргструктура»',
    PropertyPane_ViewLabel_Description: 'Оставьте пустым, чтобы использовать имя по умолчанию, или введите "[blank]", чтобы полностью скрыть метку.',

    // ── Property pane: Visual Style ──
    PropertyPane_ChartTheme_Label: 'Тема оргструктуры',
    PropertyPane_Theme_Modern: 'Современная — цвета отделов на белом фоне',
    PropertyPane_Theme_Minimal: 'Минимальная — плоский стиль, низкая контрастность',
    PropertyPane_Theme_Corporate: 'Корпоративная — единый синий цвет',
    PropertyPane_Theme_Dark: 'Тёмная — тёмно-синий фон',
    PropertyPane_Theme_Custom: 'Пользовательская — выберите свой цвет',
    PropertyPane_AccentColor_Label: 'Пользовательский акцентный цвет',
    PropertyPane_AccentColor_PickerAriaLabel: 'Выбор акцентного цвета',
    PropertyPane_AccentColor_HexLabel: 'HEX',
    PropertyPane_AccentColor_HexAriaLabel: 'Шестнадцатеричное значение акцентного цвета',
    PropertyPane_AccentColor_RgbLabel: 'RGB',
    PropertyPane_AccentColor_ChannelAriaLabel: 'Канал {name} (от 0 до 255)',
    PropertyPane_AccentColor_ContrastWithWhite: 'Контраст с белым: {ratio}:1 ({passes})',
    PropertyPane_AccentColor_PassesAA: 'соответствует AA',
    PropertyPane_AccentColor_LargeTextOnly: 'только для крупного текста',
    PropertyPane_AccentColor_LowContrast: 'низкий контраст',
    PropertyPane_AccentColor_DarkTextNote: 'Для удобства чтения текст на этом цвете будет тёмным.',
    PropertyPane_AccentColor_DarkerShadeNote: 'Для удобства чтения заголовки и ссылки будут использовать более тёмный оттенок ({hex}).',
    PropertyPane_AccentColor_InvalidHex: '«{typed}» не является допустимым HEX-цветом. Используйте значение вида #0078d4 или #07d.',
    PropertyPane_DefaultFontSize_Label: 'Размер шрифта по умолчанию',
    PropertyPane_FontSize_75: '75 % — очень мелкий',
    PropertyPane_FontSize_85: '85 % — мелкий',
    PropertyPane_FontSize_100: '100 % — обычный',
    PropertyPane_FontSize_115: '115 % — крупный',
    PropertyPane_FontSize_130: '130 % — очень крупный',
    PropertyPane_FontSize_150: '150 % — XXL',
    PropertyPane_FontSize_175: '175 % — XXXL',
    PropertyPane_DefaultLayout_Label: 'Макет оргструктуры по умолчанию',
    PropertyPane_Layout_Drill: 'Детализация',
    PropertyPane_Layout_Vertical: 'Сверху вниз',
    PropertyPane_Layout_Horizontal: 'Слева направо',

    // ── Property pane: Data Source ──
    PropertyPane_DataSource_Label: 'Источник данных о пользователях и организации',
    PropertyPane_DataSource_Auto: 'Авто — Graph API с переходом на поиск SharePoint при недоступности',
    PropertyPane_DataSource_Graph: 'Graph API — актуальные данные Azure AD (без задержки индексации)',
    PropertyPane_DataSource_Search: 'Поиск SharePoint — прежнее поведение',
    PropertyPane_DataSource_Note: 'Рекомендуется использовать Graph API. Данные считываются напрямую из Azure Active Directory, поэтому новые пользователи и изменения руководителей отображаются сразу же. Для этого необходимо утвердить разрешения Microsoft Graph в каталоге приложений SharePoint.',

    // ── Property pane: Custom Attributes ──
    PropertyPane_CustomAttributes_Note: 'Для настраиваемых атрибутов требуется Microsoft Graph (источник данных: Graph или Авто). Поиск SharePoint не имеет универсального способа чтения атрибутов Entra ID.',
    PropertyPane_CustomAttributes_Heading: 'Управление настраиваемыми атрибутами',
    PropertyPane_CustomAttributes_Empty: 'Настраиваемые атрибуты не настроены.',
    PropertyPane_CustomAttributes_AddButton: '+ Добавить атрибут',
    PropertyPane_CustomAttributes_MaxTooltip: 'Максимум {max} настраиваемых атрибутов',
    PropertyPane_CustomAttributes_FieldNameLabel: 'Имя атрибута',
    PropertyPane_CustomAttributes_FieldPlaceholder: 'например, companyName',
    PropertyPane_CustomAttributes_FieldError: 'Используйте employeeId, companyName, city, ... или extensionAttribute1-15',
    PropertyPane_CustomAttributes_DisplayLabelLabel: 'Отображаемое название',
    PropertyPane_CustomAttributes_LabelPlaceholder: 'например, Центр затрат',
    PropertyPane_CustomAttributes_RemoveTitle: 'Удалить атрибут',
    PropertyPane_CustomAttributes_RemoveAriaLabel: 'Удалить атрибут {ordinal}',
    PropertyPane_CustomAttributes_ShowInDirectory: 'Показывать в каталоге',
    PropertyPane_CustomAttributes_ShowInOrgChart: 'Показывать в оргструктуре',

    // ── Property pane: User Filters ──
    PropertyPane_ExcludedAccounts_Label: 'Исключить учётные записи',
    PropertyPane_ExcludedAccounts_Placeholder: 'conf-room, noreply, admin@, Service Account',
    PropertyPane_ExcludedAccounts_Description: 'Слова или шаблоны через запятую (без учёта регистра). Любой пользователь, чьё отображаемое имя, адрес электронной почты или UPN содержит одно из них, будет скрыт во всех представлениях.',
    PropertyPane_RestrictTenant_Label: 'Показывать только пользователей организации',
    PropertyPane_RestrictTenant_On: 'Включено — скрывает учётные записи с внешними доменами электронной почты (например, gmail.com, hotmail.com)',
    PropertyPane_RestrictTenant_Off: 'Отключено — отображаются все пользователи независимо от домена электронной почты',
    PropertyPane_HideGuest_Label: 'Скрывать гостевые учётные записи Azure AD',
    PropertyPane_HideGuest_On: 'Включено — гостевые учётные записи скрыты',
    PropertyPane_HideGuest_Off: 'Отключено — гостевые учётные записи видны (отмечены значком «Гость»)',
    PropertyPane_HideDisabled_Label: 'Скрывать отключённые учётные записи',
    PropertyPane_HideDisabled_On: 'Включено — учётные записи с заблокированным входом скрыты',
    PropertyPane_HideDisabled_Off: 'Отключено — отключённые учётные записи видны (отмечены значком «Отключена»)',
    PropertyPane_HideDisabled_Note: 'Примечание. Для определения гостевых и отключённых учётных записей требуется источник данных Graph API. Поиск SharePoint не возвращает эту информацию, поэтому эти два фильтра (а также значки «Гость»/«Отключена») не действуют, если данные получены через поиск.',
    PropertyPane_HideNoJobTitle_Label: 'Скрывать учётные записи без должности',
    PropertyPane_HideNoJobTitle_On: 'Включено — учётные записи без должности скрыты',
    PropertyPane_HideNoJobTitle_Off: 'Отключено — отображаются все учётные записи независимо от должности',
    PropertyPane_HideNoDept_Label: 'Скрывать учётные записи без отдела',
    PropertyPane_HideNoDept_On: 'Включено — учётные записи без отдела скрыты',
    PropertyPane_HideNoDept_Off: 'Отключено — отображаются все учётные записи независимо от отдела',

    // ── Property pane: Org Chart ──
    PropertyPane_TopLevelUser_Label: 'Пользователь верхнего уровня (UPN или адрес электронной почты)',
    PropertyPane_TopLevelUser_Placeholder: 'ceo@yourcompany.com',
    PropertyPane_TopLevelUser_Description: 'Сотрудник, отображаемый в корне оргструктуры',
    PropertyPane_LevelsBelow_Label: 'Число уровней для загрузки ниже корня',
    PropertyPane_DottedLine_Label: 'Атрибут дополнительного руководителя (пунктирная линия)',
    PropertyPane_DottedLine_Placeholder: 'extensionAttribute10',
    PropertyPane_DottedLine_Description: 'Необязательно. Имя локального расширенного атрибута Azure AD (extensionAttribute1-15), в котором хранится адрес электронной почты или UPN дополнительного руководителя («пунктирная линия»). Связи по пунктирной линии отображаются на карточках профиля. Требуется источник данных Graph API.',
    PropertyPane_DefaultZoom_Label: 'Масштаб оргструктуры по умолчанию',
    PropertyPane_Zoom_Auto: 'По умолчанию (автоподбор)',
    PropertyPane_Zoom_50: '50%',
    PropertyPane_Zoom_75: '75%',
    PropertyPane_Zoom_100: '100%',
    PropertyPane_Zoom_125: '125%',
    PropertyPane_Zoom_150: '150%',

    // ── Property pane: Org Chart Features ──
    PropertyPane_FeatureToggles_Note: 'Показать или скрыть кнопки панели инструментов в представлении оргструктуры.',
    PropertyPane_FindMe_Label: 'Кнопка «Найти меня»',
    PropertyPane_LayoutToggle_Label: 'Переключатель макета (детализация / по вертикали / по горизонтали)',
    PropertyPane_Stats_Label: 'Панель статистики организации',
    PropertyPane_DeptFilter_Label: 'Фильтр по отделу',
    PropertyPane_UserFilter_Label: 'Фильтр типа пользователей (участники / гости)',
    PropertyPane_Visible: 'Показано',
    PropertyPane_Hidden: 'Скрыто',

    // ── Property pane: Directory ──
    PropertyPane_PageSize_Label: 'Максимум сотрудников на странице',
    PropertyPane_PageSize_AriaLabel: 'Максимум сотрудников на странице (от 10 до 200)',
    PropertyPane_PageSize_Note: 'Размер карточек, отображаемые поля и другие параметры отображения настраиваются индивидуально для каждого пользователя через значок настроек в приложении.',

    // ── Property pane: Demo ──
    PropertyPane_UseDemoData_Label: 'Использовать демоданные',
    PropertyPane_UseDemoData_On: 'Включено — отображаются примерные сотрудники',
    PropertyPane_UseDemoData_Off: 'Отключено — реальные данные Microsoft 365',

    // ── Presence status labels ──
    Presence_Available: 'В сети',
    Presence_Busy: 'Занят',
    Presence_DoNotDisturb: 'Не беспокоить',
    Presence_BeRightBack: 'Скоро вернусь',
    Presence_Away: 'Отошёл',
    Presence_Offline: 'Не в сети',

    // ── Header / top bar ──
    Header_DirectoryLabel: 'Каталог сотрудников',
    Header_OrgChartLabel: 'Оргструктура',
    Header_SwitchToView: 'Переключиться на {view}',
    Header_CompanyLogoAlt: 'Логотип компании',
    Header_RefreshingAria: 'Обновление данных',
    Header_RefreshAria: 'Обновить данные',
    Header_RefreshTitle: 'Обновить данные (последнее обновление: {when})',
    Header_NotLoadedYet: 'ещё не загружено',
    Header_JustNow: 'только что',
    Header_MinutesAgo: '{mins} мин. назад',
    Header_HoursAgo: '{hours} ч. назад',
    Header_PreferencesTitle: 'Параметры',
    Header_PreferencesAria: 'Открыть панель параметров',

    // ── Employee Directory ──
    Directory_LoadingLabel: 'Загрузка сотрудников…',
    Directory_LoadFailedFallback: 'Убедитесь, что веб-части предоставлено разрешение User.Read.All.',
    Directory_LoadFailedPrefix: 'Не удалось загрузить сотрудников. {detail}',
    Directory_AllDepartments: 'Все отделы',
    Directory_AllOffices: 'Все офисы',
    Directory_StatusDisabled: 'Отключена',
    Directory_StatusGuest: 'Гость',
    Directory_PresenceStatus: 'Статус: {status}',
    Directory_ChatInTeams: 'Чат в Teams',
    Directory_ChatWithInTeams: 'Написать {name} в Teams',
    Directory_ManagesCount: 'В подчинении: {direct}',
    Directory_ManagesCountWithTotal: 'В подчинении: {direct} (всего {total})',
    Directory_ReportsCountWithTotal: '{direct} (всего {total})',
    Directory_ColumnName: 'Имя',
    Directory_ColumnJobTitle: 'Должность',
    Directory_ColumnDepartment: 'Отдел',
    Directory_ColumnOffice: 'Офис',
    Directory_ColumnEmail: 'Эл. почта',
    Directory_ColumnPhone: 'Телефон',
    Directory_ColumnReports: 'Подчинённые',
    Directory_ColumnChat: 'Чат',
    Directory_PrevPage: 'Назад',
    Directory_NextPage: 'Далее',
    Directory_PreviousPageAria: 'Предыдущая страница',
    Directory_NextPageAria: 'Следующая страница',
    Directory_SearchPlaceholder: 'Поиск по имени, должности, эл. почте или отделу…',
    Directory_SearchAria: 'Поиск сотрудников',
    Directory_FilterByDepartmentAria: 'Фильтр по отделу',
    Directory_FilterByOfficeAria: 'Фильтр по офису',
    Directory_ClearSearchTitle: 'Очистить поиск и все фильтры',
    Directory_ClearButton: 'Очистить',
    Directory_ClearFiltersButton: 'Очистить фильтры',
    Directory_ExportCsvTitle: 'Экспортировать все отфильтрованные результаты в файл CSV (открывается в Excel)',
    Directory_ExportCsvButton: 'Экспорт в CSV',
    Directory_ViewModeAria: 'Режим отображения',
    Directory_CardViewTitle: 'Отображение карточками',
    Directory_ListViewTitle: 'Отображение списком',
    Directory_AlphabetFilterAria: 'Фильтр по алфавиту',
    Directory_ShowAllTitle: 'Показать все',
    Directory_OtherLettersTitle: 'Фильтр по именам, начинающимся с цифры или другого символа',
    Directory_FilterByLetterTitle: 'Фильтр по букве {letter}',
    Directory_ResultCountSingular: 'человек',
    Directory_ResultCountPlural: 'человек',
    Directory_PageOf: ' · страница {page} из {totalPages}',
    Directory_FilterActiveSingular: 'Активен {count} фильтр',
    Directory_FilterActivePlural: 'Активно фильтров: {count}',
    Directory_NoResults: 'Сотрудники не найдены',
    Directory_PaginationAria: 'Постраничная навигация',

    // ── Org chart toolbar / shared chart chrome ──
    Chart_Layout_Drill: 'Детализация',
    Chart_Layout_Vertical: 'Сверху вниз',
    Chart_Layout_Horizontal: 'Слева направо',
    Chart_SearchPlaceholder: 'Поиск сотрудников…',
    Chart_SearchAria: 'Поиск сотрудников',
    Chart_MatchSingular: 'совпадение в дереве',
    Chart_MatchPlural: 'совпадений в дереве',
    Chart_ResultsListAria: 'Сотрудники',
    Chart_ExpandAll: 'Развернуть все',
    Chart_CollapseAll: 'Свернуть все',
    Chart_Expanding: 'Разворачивание…',
    Chart_Loading: 'Загрузка…',
    Chart_FindMeTitle: 'Найти меня в оргструктуре',
    Chart_ViewLayoutButton: 'Вид',
    Chart_ViewLayoutTitle: 'Переключить макет отображения',
    Chart_ViewLayoutPanelTitle: 'Макет отображения',
    Chart_StatsSummaryTitle: 'Сводная статистика организации',
    Chart_FilterByDepartmentTitle: 'Фильтр по отделу',
    Chart_FilterByDepartmentWithCountAria: 'Фильтр по отделу (выбрано: {count})',
    Chart_FilterByDepartmentPanelTitle: 'Фильтр по отделу',
    Chart_ClearAllFilters: 'Очистить все фильтры',
    Chart_FilterUserTypesTitle: 'Фильтр типов пользователей',
    Chart_DownloadPdfTitle: 'Скачать в формате PDF',
    Chart_DownloadCsvTitle: 'Скачать таблицу в формате CSV',
    Chart_ResetRootTitle: 'Сбросить к корню по умолчанию',
    Chart_ViewFromPersonPlaceholder: 'Просмотр от сотрудника…',
    Chart_ViewFromPersonAria: 'Просмотр оргструктуры от указанного сотрудника',
    Chart_ZoomOutTitle: 'Уменьшить масштаб',
    Chart_ZoomInTitle: 'Увеличить масштаб',
    Chart_ZoomResetTitle: 'Сбросить масштаб',
    Chart_ShowInChartAria: 'Показать в оргструктуре',
    Chart_ShowInChartTitle: 'Показать в оргструктуре',
    Chart_FilterMembers: 'Обычные участники',
    Chart_FilterGuests: 'Гостевые пользователи',
    Chart_FilterDisabled: 'Отключённые учётные записи',
    Chart_SetupTitle: 'Настройка оргструктуры',
    Chart_SetupSubtitle: 'Чтобы начать, введите адрес электронной почты или UPN сотрудника верхнего уровня.',
    Chart_SetupPlaceholder: 'ceo@company.com',
    Chart_SetupInputAria: 'Адрес электронной почты или UPN сотрудника верхнего уровня',
    Chart_SetupLoadButton: 'Загрузить',
    Chart_SetupHint: 'Это также можно настроить на постоянной основе в параметрах веб-части (для администраторов).',
    Chart_BuildingLabel: 'Построение оргструктуры…',
    Chart_RetryButton: 'Повторить',
    Chart_NotFoundFromSetup: 'Пользователь «{identifier}» не найден.',
    Chart_NotFoundWithSettings: 'Пользователь «{identifier}» не найден. Проверьте UPN или адрес электронной почты в параметрах.',
    Chart_LoadFailedGeneric: 'Не удалось загрузить оргструктуру.{detail}',
    Chart_LoadFailedPermissions: ' Проверьте разрешения.',
    Chart_LoadFailedForPerson: 'Не удалось загрузить оргструктуру для этого сотрудника.',
    Chart_FindMeNotFound: 'Ваша учётная запись не найдена в этой организации.',
    Chart_StatPeople: 'Сотрудники',
    Chart_StatMembers: 'Участники',
    Chart_StatGuests: 'Гости',
    Chart_StatDepts: 'Отделы',
    Chart_ReportingLineAria: 'Линия подчинения',
    Chart_BackToFullOrgTitle: 'Вернуться к полной оргструктуре',
    Chart_FullOrgLabel: 'Вся организация',
    Chart_FocusOnPerson: 'Фокус на {name}',
    Chart_OrgChartAria: 'Оргструктура',
    Chart_ExportNote_DrillLevel: 'Текущий уровень детализации (один уровень прямых подчинённых)',
    Chart_ExportNote_PartialLevels: 'Включает только загруженные уровни — чтобы включить более глубокие уровни, перед экспортом используйте «Развернуть все»',
    Chart_AllowPopupsForPdf: 'Разрешите всплывающие окна, чтобы экспортировать PDF.',

    // ── Person card ──
    PersonCard_ProfileAria: 'Профиль: {name}',
    PersonCard_CloseTitle: 'Закрыть',
    PersonCard_CloseAria: 'Закрыть профиль',
    PersonCard_StatusDisabled: 'Отключена',
    PersonCard_StatusGuest: 'Гость',
    PersonCard_DirectReportSingular: '{count} прямой подчинённый',
    PersonCard_DirectReportPlural: '{count} прямых подчинённых',
    PersonCard_TotalSuffix: ' · всего {total}',
    PersonCard_CopyEmailTitle: 'Скопировать адрес электронной почты',
    PersonCard_EmailCopiedAria: 'Адрес электронной почты скопирован',
    PersonCard_ReportsTo: 'Подчиняется',
    PersonCard_FocusOnPerson: 'Фокус на {name}',
    PersonCard_FocusOrgChartOnPerson: 'Сфокусировать оргструктуру на {name}',
    PersonCard_DottedLine: 'Пунктирная линия',
    PersonCard_DottedLineManager: 'Дополнительный руководитель: {name}',
    PersonCard_DottedLineReport: 'Дополнительный подчинённый: {name}',
    PersonCard_ChatButton: 'Чат',
    PersonCard_EmailButton: 'Эл. почта',
    PersonCard_FocusButton: 'Фокус',
    PersonCard_FocusTitle: 'Сфокусировать оргструктуру на этом сотруднике',

    // ── Org node card ──
    OrgNode_ViewProfile: 'Просмотреть профиль сотрудника {name}',
    OrgNode_FocusOrgChartOn: 'Сфокусировать оргструктуру на {name}',
    OrgNode_Collapse: 'Свернуть',
    OrgNode_Expand: 'Развернуть',
    OrgNode_DirectReportsSuffix: 'Прямые подчинённые сотрудника {name}',
    OrgNode_StatusDisabled: 'Отключена',
    OrgNode_StatusGuest: 'Гость',
    OrgNode_TotalReportsAcrossLevels: '{count} сотрудников на всех уровнях ниже {name}',

    // ── Drill view ──
    Drill_ReportingLineAria: 'Линия подчинения',
    Drill_BackToTopTitle: 'Вернуться к началу',
    Drill_BackToTopAria: 'Вернуться к началу оргструктуры',
    Drill_GoBackTo: 'Вернуться к {name}',
    Drill_ViewProfileTitle: 'Просмотреть профиль',
    Drill_ViewProfileAria: 'Просмотреть профиль сотрудника {name}',
    Drill_ProfileButton: 'Профиль',
    Drill_LoadingLabel: 'Загрузка…',
    Drill_DirectReports: 'Прямые подчинённые',
    Drill_DirectReportsOfAria: 'Прямые подчинённые сотрудника {name}',
    Drill_DirectReportsAria: 'Прямые подчинённые',
    Drill_ViewPersonProfile: 'Просмотреть профиль сотрудника {name}',
    Drill_ShowPersonReports: 'Показать прямых подчинённых сотрудника {name}',
    Drill_NoDirectReports: 'Нет прямых подчинённых',

    // ── Settings panel ──
    Settings_AlphabetFirstName: 'Имя',
    Settings_AlphabetLastName: 'Фамилия',
    Settings_CardSizeSmall: 'Маленький — компактно, больше карточек на экране',
    Settings_CardSizeMedium: 'Средний — сбалансированный',
    Settings_CardSizeLarge: 'Большой — просторно, меньше карточек на экране',
    Settings_HeaderText: 'Параметры',
    Settings_SaveButton: 'Сохранить',
    Settings_CancelButton: 'Отмена',
    Settings_DiscardButton: 'Отменить изменения',
    Settings_SectionDirectory: 'Каталог сотрудников',
    Settings_AlphabetFilterByLabel: 'Алфавитный фильтр по',
    Settings_CardSizeLabel: 'Размер карточек',
    Settings_FontSizeLabel: 'Размер шрифта',
    Settings_SectionCardsAndFields: 'Карточки и поля',
    Settings_ShowOnCardsLabel: 'Показывать на карточках сотрудников:',
    Settings_EmailAddressLabel: 'Адрес электронной почты',
    Settings_PhoneNumberLabel: 'Номер телефона',
    Settings_DepartmentLabel: 'Отдел',
    Settings_OfficeLocationLabel: 'Расположение офиса',
    Settings_SectionOrgChart: 'Оргструктура',
    Settings_ManagerLevelsLabel: 'Число уровней руководителей при фокусировке на сотруднике: {levels}',
    Settings_CompactCardsLabel: 'Компактные карточки',
    Settings_CompactCardsOn: 'Включено — карточки меньше, больше видно одновременно',
    Settings_CompactCardsOff: 'Отключено — стандартный размер',
    Settings_Hint: 'Эти параметры сохраняются в вашем браузере и применяются только к вам. Тема оргструктуры, представление по умолчанию и макет настраиваются администратором SharePoint.',
    Settings_SectionDemoData: 'Демоданные',
    Settings_DatasetSizeLabel: 'Размер набора данных',
    Settings_PeopleCountSuffix: '{count} человек',

    // ── Export (CSV / PDF) ──
    Export_ColumnName: 'Имя',
    Export_ColumnJobTitle: 'Должность',
    Export_ColumnDepartment: 'Отдел',
    Export_ColumnOffice: 'Офис',
    Export_ColumnEmail: 'Эл. почта',
    Export_ColumnPhone: 'Телефон',
    Export_ColumnManager: 'Руководитель',
    Export_ColumnLevel: 'Уровень',
    Export_PdfDocumentTitle: 'Оргструктура',
    Export_PdfHeading: 'Организационная структура',
    Export_PdfRootLabel: 'Корень: {name}',
  };
});
