define([], function () {
  return {
    // ── Property pane: pane header / groups ──
    PropertyPane_HeaderDescription: 'Inställningar för Smart Org Chart',
    PropertyPane_Group_General: 'Allmänt',
    PropertyPane_Group_Branding: 'Varumärke',
    PropertyPane_Group_VisualStyle: 'Visuell stil',
    PropertyPane_Group_DataSource: 'Datakälla',
    PropertyPane_Group_CustomAttributes: 'Anpassade attribut',
    PropertyPane_Group_UserFilters: 'Användarfilter',
    PropertyPane_Group_OrgChart: 'Organisationsschema',
    PropertyPane_Group_OrgChartFeatures: 'Funktioner för organisationsschema',
    PropertyPane_Group_Directory: 'Katalog',
    PropertyPane_Group_Demo: 'Demo',

    // ── Property pane: General ──
    PropertyPane_DefaultView_Label: 'Standardvy',

    // ── Property pane: Branding ──
    PropertyPane_AppTitle_Label: 'Apptitel',
    PropertyPane_AppTitle_Placeholder: 'Contoso Org Chart',
    PropertyPane_AppTitle_Description: 'Visas i sidhuvudet tillsammans med vynamnet',
    PropertyPane_LogoUrl_Label: 'Logotyp-URL',
    PropertyPane_LogoUrl_Placeholder: 'https://contoso.sharepoint.com/sites/yoursite/SiteAssets/logo.png',
    PropertyPane_LogoUrl_Description: 'Fullständig URL till en PNG-, SVG- eller JPG-bild. Tips: öppna bildfilen i webbläsaren och kopiera adressen i adressfältet. Delningslänkar av typen "Kopiera länk" fungerar inte.',
    PropertyPane_DirectoryLabel_Label: 'Visningsnamn för personalkatalogen',
    PropertyPane_OrgChartLabel_Label: 'Visningsnamn för organisationsschemat',
    PropertyPane_ViewLabel_Description: 'Lämna tomt för att använda standardnamnet, eller skriv "[blank]" för att dölja etiketten helt.',

    // ── Property pane: Visual Style ──
    PropertyPane_ChartTheme_Label: 'Schematema',
    PropertyPane_Theme_Modern: 'Modern – avdelningsfärger på vitt',
    PropertyPane_Theme_Minimal: 'Minimalistisk – platt och låg kontrast',
    PropertyPane_Theme_Corporate: 'Företag – enhetlig blå',
    PropertyPane_Theme_Dark: 'Mörk – mörkblå bakgrund',
    PropertyPane_Theme_Custom: 'Anpassad – välj egen färg',
    PropertyPane_AccentColor_Label: 'Anpassad accentfärg',
    PropertyPane_AccentColor_PickerAriaLabel: 'Färgväljare för accentfärg',
    PropertyPane_AccentColor_HexLabel: 'Hex',
    PropertyPane_AccentColor_HexAriaLabel: 'Hexadecimalt värde för accentfärg',
    PropertyPane_AccentColor_RgbLabel: 'RGB',
    PropertyPane_AccentColor_ChannelAriaLabel: '{name}-kanal (0 till 255)',
    PropertyPane_AccentColor_ContrastWithWhite: 'Kontrast mot vitt: {ratio}:1 ({passes})',
    PropertyPane_AccentColor_PassesAA: 'uppfyller AA',
    PropertyPane_AccentColor_LargeTextOnly: 'endast stor text',
    PropertyPane_AccentColor_LowContrast: 'låg kontrast',
    PropertyPane_AccentColor_DarkTextNote: 'Text på den här färgen använder mörk text för bättre läsbarhet.',
    PropertyPane_AccentColor_DarkerShadeNote: 'Rubriker och länkar använder en mörkare nyans ({hex}) för bättre läsbarhet.',
    PropertyPane_AccentColor_InvalidHex: '"{typed}" är inte en giltig hexfärg. Ange ett värde som #0078d4 eller #07d.',
    PropertyPane_DefaultFontSize_Label: 'Standard teckenstorlek',
    PropertyPane_FontSize_75: '75 % – extra liten',
    PropertyPane_FontSize_85: '85 % – liten',
    PropertyPane_FontSize_100: '100 % – normal',
    PropertyPane_FontSize_115: '115 % – stor',
    PropertyPane_FontSize_130: '130 % – extra stor',
    PropertyPane_FontSize_150: '150 % – XXL',
    PropertyPane_FontSize_175: '175 % – XXXL',
    PropertyPane_DefaultLayout_Label: 'Standardlayout för organisationsschema',
    PropertyPane_Layout_Drill: 'Nedborrning',
    PropertyPane_Layout_Vertical: 'Uppifrån och ned',
    PropertyPane_Layout_Horizontal: 'Vänster till höger',

    // ── Property pane: Data Source ──
    PropertyPane_DataSource_Label: 'Varifrån användar- och organisationsdata ska läsas in',
    PropertyPane_DataSource_Auto: 'Automatiskt – Microsoft Graph, med SharePoint-sökning som reserv',
    PropertyPane_DataSource_Graph: 'Microsoft Graph – aktuella Azure AD-data (ingen indexeringsfördröjning)',
    PropertyPane_DataSource_Search: 'SharePoint-sökning – tidigare beteende',
    PropertyPane_DataSource_Note: 'Microsoft Graph rekommenderas. Det läser direkt från Azure Active Directory så att nya användare och chefsbyten visas omedelbart. Kräver att behörigheter för Microsoft Graph har godkänts i SharePoints appkatalog.',

    // ── Property pane: Custom Attributes ──
    PropertyPane_CustomAttributes_Note: 'Anpassade attribut kräver Microsoft Graph (Datakälla: Graph eller Automatiskt). SharePoint-sökning har inget generellt sätt att läsa Entra ID-attribut.',
    PropertyPane_CustomAttributes_Heading: 'Hantera anpassade attribut',
    PropertyPane_CustomAttributes_Empty: 'Inga anpassade attribut har konfigurerats.',
    PropertyPane_CustomAttributes_AddButton: '+ Lägg till attribut',
    PropertyPane_CustomAttributes_MaxTooltip: 'Högst {max} anpassade attribut',
    PropertyPane_CustomAttributes_FieldNameLabel: 'Attributnamn',
    PropertyPane_CustomAttributes_FieldPlaceholder: 't.ex. companyName',
    PropertyPane_CustomAttributes_FieldError: 'Använd employeeId, companyName, city, ... eller extensionAttribute1-15',
    PropertyPane_CustomAttributes_DisplayLabelLabel: 'Visningsetikett',
    PropertyPane_CustomAttributes_LabelPlaceholder: 't.ex. Kostnadsställe',
    PropertyPane_CustomAttributes_RemoveTitle: 'Ta bort attribut',
    PropertyPane_CustomAttributes_RemoveAriaLabel: 'Ta bort attribut {ordinal}',
    PropertyPane_CustomAttributes_ShowInDirectory: 'Visa i katalogen',
    PropertyPane_CustomAttributes_ShowInOrgChart: 'Visa i organisationsschemat',

    // ── Property pane: User Filters ──
    PropertyPane_ExcludedAccounts_Label: 'Undanta konton',
    PropertyPane_ExcludedAccounts_Placeholder: 'conf-room, noreply, admin@, Service Account',
    PropertyPane_ExcludedAccounts_Description: 'Kommaavgränsade ord eller mönster (skiftlägesokänsligt). Alla användare vars visningsnamn, e-post eller UPN innehåller något av dessa döljs i alla vyer.',
    PropertyPane_RestrictTenant_Label: 'Visa endast användare i klientorganisationen',
    PropertyPane_RestrictTenant_On: 'På – döljer konton med externa e-postdomäner (t.ex. gmail.com, hotmail.com)',
    PropertyPane_RestrictTenant_Off: 'Av – alla användare visas oavsett e-postdomän',
    PropertyPane_HideGuest_Label: 'Dölj gästkonton i Azure AD',
    PropertyPane_HideGuest_On: 'På – gästkonton döljs',
    PropertyPane_HideGuest_Off: 'Av – gästkonton visas (med märkningen Gäst)',
    PropertyPane_HideDisabled_Label: 'Dölj inaktiverade konton',
    PropertyPane_HideDisabled_On: 'På – konton med blockerad inloggning döljs',
    PropertyPane_HideDisabled_Off: 'Av – inaktiverade konton visas (med märkningen Inaktiverad)',
    PropertyPane_HideDisabled_Note: 'Obs! Identifiering av gäst- och inaktiverade konton kräver datakällan Microsoft Graph. SharePoint-sökning returnerar inte den här informationen, så dessa två filter (och märkningarna Gäst/Inaktiverad) har ingen effekt när data kommer från Sökning.',
    PropertyPane_HideNoJobTitle_Label: 'Dölj konton utan befattning',
    PropertyPane_HideNoJobTitle_On: 'På – konton utan befattning döljs',
    PropertyPane_HideNoJobTitle_Off: 'Av – alla konton visas oavsett befattning',
    PropertyPane_HideNoDept_Label: 'Dölj konton utan avdelning',
    PropertyPane_HideNoDept_On: 'På – konton utan avdelning döljs',
    PropertyPane_HideNoDept_Off: 'Av – alla konton visas oavsett avdelning',

    // ── Property pane: Org Chart ──
    PropertyPane_TopLevelUser_Label: 'Toppnivåanvändare (UPN eller e-post)',
    PropertyPane_TopLevelUser_Placeholder: 'ceo@yourcompany.com',
    PropertyPane_TopLevelUser_Description: 'Personen som visas i organisationsschemats rot',
    PropertyPane_LevelsBelow_Label: 'Nivåer att läsa in under roten',
    PropertyPane_DottedLine_Label: 'Attribut för streckad chefslinje',
    PropertyPane_DottedLine_Placeholder: 'extensionAttribute10',
    PropertyPane_DottedLine_Description: 'Valfritt. Namnet på det lokala Azure AD-tilläggsattributet (extensionAttribute1-15) som lagrar e-post eller UPN för en sekundär chef med "streckad linje". Streckade relationer visas på profilkort. Kräver datakällan Microsoft Graph.',
    PropertyPane_DefaultZoom_Label: 'Standardzoom för organisationsschema',
    PropertyPane_Zoom_Auto: 'Standard (anpassa automatiskt)',
    PropertyPane_Zoom_50: '50 %',
    PropertyPane_Zoom_75: '75 %',
    PropertyPane_Zoom_100: '100 %',
    PropertyPane_Zoom_125: '125 %',
    PropertyPane_Zoom_150: '150 %',

    // ── Property pane: Org Chart Features ──
    PropertyPane_FeatureToggles_Note: 'Visa eller dölj verktygsfältsknappar i organisationsschemavyn.',
    PropertyPane_FindMe_Label: 'Knappen Hitta mig',
    PropertyPane_LayoutToggle_Label: 'Layoutväxling (nedborrning/vertikal/horisontell)',
    PropertyPane_Stats_Label: 'Statistikfält för organisationen',
    PropertyPane_DeptFilter_Label: 'Avdelningsfilter',
    PropertyPane_UserFilter_Label: 'Filter för användartyp (medlemmar/gäster)',
    PropertyPane_Visible: 'Synlig',
    PropertyPane_Hidden: 'Dold',

    // ── Property pane: Directory ──
    PropertyPane_PageSize_Label: 'Högsta antal anställda per sida',
    PropertyPane_PageSize_AriaLabel: 'Högsta antal anställda per sida (10 till 200)',
    PropertyPane_PageSize_Note: 'Kortstorlek, synliga fält och andra visningsinställningar anges per användare via kugghjulet Inställningar i appen.',

    // ── Property pane: Demo ──
    PropertyPane_UseDemoData_Label: 'Använd demodata',
    PropertyPane_UseDemoData_On: 'På – visar exempelanställda',
    PropertyPane_UseDemoData_Off: 'Av – aktuella Microsoft 365-data',

    // ── Presence status labels ──
    Presence_Available: 'Tillgänglig',
    Presence_Busy: 'Upptagen',
    Presence_DoNotDisturb: 'Stör ej',
    Presence_BeRightBack: 'Strax tillbaka',
    Presence_Away: 'Borta',
    Presence_Offline: 'Frånkopplad',

    // ── Header / top bar ──
    Header_DirectoryLabel: 'Personalkatalog',
    Header_OrgChartLabel: 'Organisationsschema',
    Header_SwitchToView: 'Växla till {view}',
    Header_CompanyLogoAlt: 'Företagslogotyp',
    Header_RefreshingAria: 'Uppdaterar data',
    Header_RefreshAria: 'Uppdatera data',
    Header_RefreshTitle: 'Uppdatera data (senast uppdaterad {when})',
    Header_NotLoadedYet: 'inte inläst ännu',
    Header_JustNow: 'just nu',
    Header_MinutesAgo: 'för {mins} min sedan',
    Header_HoursAgo: 'för {hours} tim sedan',
    Header_PreferencesTitle: 'Inställningar',
    Header_PreferencesAria: 'Öppna inställningspanelen',

    // ── Employee Directory ──
    Directory_LoadingLabel: 'Läser in anställda...',
    Directory_LoadFailedFallback: 'Kontrollera att webbdelen har behörigheten User.Read.All.',
    Directory_LoadFailedPrefix: 'Det gick inte att läsa in anställda. {detail}',
    Directory_AllDepartments: 'Alla avdelningar',
    Directory_AllOffices: 'Alla kontor',
    Directory_StatusDisabled: 'Inaktiverad',
    Directory_StatusGuest: 'Gäst',
    Directory_PresenceStatus: 'Status: {status}',
    Directory_ChatInTeams: 'Chatta i Teams',
    Directory_ChatWithInTeams: 'Chatta med {name} i Teams',
    Directory_ManagesCount: 'Chef för {direct}',
    Directory_ManagesCountWithTotal: 'Chef för {direct} (totalt {total})',
    Directory_ReportsCountWithTotal: '{direct} (totalt {total})',
    Directory_ColumnName: 'Namn',
    Directory_ColumnJobTitle: 'Befattning',
    Directory_ColumnDepartment: 'Avdelning',
    Directory_ColumnOffice: 'Kontor',
    Directory_ColumnEmail: 'E-post',
    Directory_ColumnPhone: 'Telefon',
    Directory_ColumnReports: 'Rapporterande',
    Directory_ColumnChat: 'Chatt',
    Directory_PrevPage: 'Föreg.',
    Directory_NextPage: 'Nästa',
    Directory_PreviousPageAria: 'Föregående sida',
    Directory_NextPageAria: 'Nästa sida',
    Directory_SearchPlaceholder: 'Sök efter namn, titel, e-post eller avdelning...',
    Directory_SearchAria: 'Sök personer',
    Directory_FilterByDepartmentAria: 'Filtrera efter avdelning',
    Directory_FilterByOfficeAria: 'Filtrera efter kontor',
    Directory_ClearSearchTitle: 'Rensa sökning och alla filter',
    Directory_ClearButton: 'Rensa',
    Directory_ClearFiltersButton: 'Rensa filter',
    Directory_ExportCsvTitle: 'Exportera alla filtrerade resultat till en CSV-fil (öppnas i Excel)',
    Directory_ExportCsvButton: 'Exportera CSV',
    Directory_ViewModeAria: 'Visningsläge',
    Directory_CardViewTitle: 'Kortvy',
    Directory_ListViewTitle: 'Listvy',
    Directory_AlphabetFilterAria: 'Alfabetiskt filter',
    Directory_ShowAllTitle: 'Visa alla',
    Directory_OtherLettersTitle: 'Filtrera efter namn som börjar med en siffra eller ett annat tecken',
    Directory_FilterByLetterTitle: 'Filtrera efter {letter}',
    Directory_ResultCountSingular: 'person',
    Directory_ResultCountPlural: 'personer',
    Directory_PageOf: ' · sida {page} av {totalPages}',
    Directory_FilterActiveSingular: '{count} filter aktivt',
    Directory_FilterActivePlural: '{count} filter aktiva',
    Directory_NoResults: 'Inga personer hittades',
    Directory_PaginationAria: 'Sidnumrering',

    // ── Org chart toolbar / shared chart chrome ──
    Chart_Layout_Drill: 'Nedborrning',
    Chart_Layout_Vertical: 'Uppifrån och ned',
    Chart_Layout_Horizontal: 'Vänster till höger',
    Chart_SearchPlaceholder: 'Sök personer...',
    Chart_SearchAria: 'Sök personer',
    Chart_MatchSingular: 'träff i trädet',
    Chart_MatchPlural: 'träffar i trädet',
    Chart_ResultsListAria: 'Personer',
    Chart_ExpandAll: 'Expandera alla',
    Chart_CollapseAll: 'Komprimera alla',
    Chart_Expanding: 'Expanderar…',
    Chart_Loading: 'Läser in…',
    Chart_FindMeTitle: 'Hitta mig i organisationsschemat',
    Chart_ViewLayoutButton: 'Visa',
    Chart_ViewLayoutTitle: 'Växla visningslayout',
    Chart_ViewLayoutPanelTitle: 'Visningslayout',
    Chart_StatsSummaryTitle: 'Sammanfattning av organisationsstatistik',
    Chart_FilterByDepartmentTitle: 'Filtrera efter avdelning',
    Chart_FilterByDepartmentWithCountAria: 'Filtrera efter avdelning ({count} valda)',
    Chart_FilterByDepartmentPanelTitle: 'Filtrera efter avdelning',
    Chart_ClearAllFilters: 'Rensa alla filter',
    Chart_FilterUserTypesTitle: 'Filtrera användartyper',
    Chart_DownloadPdfTitle: 'Ladda ned som PDF',
    Chart_DownloadCsvTitle: 'Ladda ned som CSV-kalkylblad',
    Chart_ResetRootTitle: 'Återställ till standardrot',
    Chart_ViewFromPersonPlaceholder: 'Visa från person…',
    Chart_ViewFromPersonAria: 'Visa organisationsschemat från en person',
    Chart_ZoomOutTitle: 'Zooma ut',
    Chart_ZoomInTitle: 'Zooma in',
    Chart_ZoomResetTitle: 'Återställ zoom',
    Chart_ShowInChartAria: 'Visa i schemat',
    Chart_ShowInChartTitle: 'Visa i schemat',
    Chart_FilterMembers: 'Vanliga medlemmar',
    Chart_FilterGuests: 'Gästanvändare',
    Chart_FilterDisabled: 'Inaktiverade konton',
    Chart_SetupTitle: 'Konfigurera organisationsschemat',
    Chart_SetupSubtitle: 'Ange toppersonens e-post eller UPN för att komma igång.',
    Chart_SetupPlaceholder: 'ceo@company.com',
    Chart_SetupInputAria: 'Toppersonens e-post eller UPN',
    Chart_SetupLoadButton: 'Läs in',
    Chart_SetupHint: 'Du kan även ange detta permanent i webbdelens inställningar (administratör).',
    Chart_BuildingLabel: 'Bygger organisationsschema...',
    Chart_RetryButton: 'Försök igen',
    Chart_NotFoundFromSetup: 'Användaren "{identifier}" hittades inte.',
    Chart_NotFoundWithSettings: 'Användaren "{identifier}" hittades inte. Kontrollera UPN eller e-post i Inställningar.',
    Chart_LoadFailedGeneric: 'Det gick inte att läsa in organisationsschemat.{detail}',
    Chart_LoadFailedPermissions: ' Kontrollera behörigheter.',
    Chart_LoadFailedForPerson: 'Det gick inte att läsa in organisationsschemat för den här personen.',
    Chart_FindMeNotFound: 'Ditt konto hittades inte i den här organisationen.',
    Chart_StatPeople: 'Personer',
    Chart_StatMembers: 'Medlemmar',
    Chart_StatGuests: 'Gäster',
    Chart_StatDepts: 'Avd.',
    Chart_ReportingLineAria: 'Rapporteringslinje',
    Chart_BackToFullOrgTitle: 'Tillbaka till hela organisationsschemat',
    Chart_FullOrgLabel: 'Hela organisationen',
    Chart_FocusOnPerson: 'Fokusera på {name}',
    Chart_OrgChartAria: 'Organisationsschema',
    Chart_ExportNote_DrillLevel: 'Aktuell nedborrningsnivå (en nivå av direktrapporterande)',
    Chart_ExportNote_PartialLevels: 'Innehåller endast inlästa nivåer – använd Expandera alla före export för att inkludera djupare nivåer',
    Chart_AllowPopupsForPdf: 'Tillåt popup-fönster för att exportera PDF.',

    // ── Person card ──
    PersonCard_ProfileAria: 'Profil: {name}',
    PersonCard_CloseTitle: 'Stäng',
    PersonCard_CloseAria: 'Stäng profil',
    PersonCard_StatusDisabled: 'Inaktiverad',
    PersonCard_StatusGuest: 'Gäst',
    PersonCard_DirectReportSingular: '{count} direktrapporterande',
    PersonCard_DirectReportPlural: '{count} direktrapporterande',
    PersonCard_TotalSuffix: ' · totalt {total}',
    PersonCard_CopyEmailTitle: 'Kopiera e-postadress',
    PersonCard_EmailCopiedAria: 'E-postadressen har kopierats',
    PersonCard_ReportsTo: 'Rapporterar till',
    PersonCard_FocusOnPerson: 'Fokusera på {name}',
    PersonCard_FocusOrgChartOnPerson: 'Fokusera organisationsschemat på {name}',
    PersonCard_DottedLine: 'Streckad linje',
    PersonCard_DottedLineManager: 'Chef med streckad linje: {name}',
    PersonCard_DottedLineReport: 'Rapporterande med streckad linje: {name}',
    PersonCard_ChatButton: 'Chatt',
    PersonCard_EmailButton: 'E-post',
    PersonCard_FocusButton: 'Fokusera',
    PersonCard_FocusTitle: 'Fokusera organisationsschemat på den här personen',

    // ── Org node card ──
    OrgNode_ViewProfile: 'Visa {name}s profil',
    OrgNode_FocusOrgChartOn: 'Fokusera organisationsschemat på {name}',
    OrgNode_Collapse: 'Komprimera',
    OrgNode_Expand: 'Expandera',
    OrgNode_DirectReportsSuffix: '{name}s direktrapporterande',
    OrgNode_StatusDisabled: 'Inaktiverad',
    OrgNode_StatusGuest: 'Gäst',
    OrgNode_TotalReportsAcrossLevels: '{count} personer på alla nivåer under {name}',

    // ── Drill view ──
    Drill_ReportingLineAria: 'Rapporteringslinje',
    Drill_BackToTopTitle: 'Tillbaka till toppen',
    Drill_BackToTopAria: 'Tillbaka till toppen av organisationsschemat',
    Drill_GoBackTo: 'Gå tillbaka till {name}',
    Drill_ViewProfileTitle: 'Visa profil',
    Drill_ViewProfileAria: 'Visa {name}s profil',
    Drill_ProfileButton: 'Profil',
    Drill_LoadingLabel: 'Läser in...',
    Drill_DirectReports: 'Direktrapporterande',
    Drill_DirectReportsOfAria: 'Direktrapporterande till {name}',
    Drill_DirectReportsAria: 'Direktrapporterande',
    Drill_ViewPersonProfile: 'Visa {name}s profil',
    Drill_ShowPersonReports: 'Visa {name}s direktrapporterande',
    Drill_NoDirectReports: 'Inga direktrapporterande',

    // ── Settings panel ──
    Settings_AlphabetFirstName: 'Förnamn',
    Settings_AlphabetLastName: 'Efternamn',
    Settings_CardSizeSmall: 'Liten – kompakt, fler kort synliga',
    Settings_CardSizeMedium: 'Medel – balanserad',
    Settings_CardSizeLarge: 'Stor – rymlig, färre kort',
    Settings_HeaderText: 'Inställningar',
    Settings_SaveButton: 'Spara',
    Settings_CancelButton: 'Avbryt',
    Settings_DiscardButton: 'Ignorera ändringar',
    Settings_SectionDirectory: 'Katalog',
    Settings_AlphabetFilterByLabel: 'Alfabetiskt filter efter',
    Settings_CardSizeLabel: 'Kortstorlek',
    Settings_FontSizeLabel: 'Teckenstorlek',
    Settings_SectionCardsAndFields: 'Kort och fält',
    Settings_ShowOnCardsLabel: 'Visa på medarbetarkort:',
    Settings_EmailAddressLabel: 'E-postadress',
    Settings_PhoneNumberLabel: 'Telefonnummer',
    Settings_DepartmentLabel: 'Avdelning',
    Settings_OfficeLocationLabel: 'Kontorsplats',
    Settings_SectionOrgChart: 'Organisationsschema',
    Settings_ManagerLevelsLabel: 'Antal chefsnivåer som visas vid fokusering på en person: {levels}',
    Settings_CompactCardsLabel: 'Kompakta kort',
    Settings_CompactCardsOn: 'På – mindre kort, fler synliga samtidigt',
    Settings_CompactCardsOff: 'Av – standardstorlek',
    Settings_Hint: 'De här inställningarna sparas i webbläsaren och gäller bara för dig. Schematema, standardvy och layout konfigureras av din SharePoint-administratör.',
    Settings_SectionDemoData: 'Demodata',
    Settings_DatasetSizeLabel: 'Datamängdens storlek',
    Settings_PeopleCountSuffix: '{count} personer',

    // ── Export (CSV / PDF) ──
    Export_ColumnName: 'Namn',
    Export_ColumnJobTitle: 'Befattning',
    Export_ColumnDepartment: 'Avdelning',
    Export_ColumnOffice: 'Kontor',
    Export_ColumnEmail: 'E-post',
    Export_ColumnPhone: 'Telefon',
    Export_ColumnManager: 'Chef',
    Export_ColumnLevel: 'Nivå',
    Export_PdfDocumentTitle: 'Organisationsschema',
    Export_PdfHeading: 'Organisationsschema',
    Export_PdfRootLabel: 'Rot: {name}',
  };
});
