define([], function () {
  return {
    // ── Property pane: pane header / groups ──
    PropertyPane_HeaderDescription: 'การตั้งค่า Smart Org Chart',
    PropertyPane_Group_General: 'ทั่วไป',
    PropertyPane_Group_Branding: 'การสร้างแบรนด์',
    PropertyPane_Group_VisualStyle: 'รูปแบบภาพ',
    PropertyPane_Group_DataSource: 'แหล่งข้อมูล',
    PropertyPane_Group_CustomAttributes: 'แอตทริบิวต์ที่กำหนดเอง',
    PropertyPane_Group_UserFilters: 'ตัวกรองผู้ใช้',
    PropertyPane_Group_OrgChart: 'แผนผังองค์กร',
    PropertyPane_Group_OrgChartFeatures: 'คุณลักษณะของแผนผังองค์กร',
    PropertyPane_Group_Directory: 'ไดเรกทอรี',
    PropertyPane_Group_Demo: 'ข้อมูลสาธิต',

    // ── Property pane: General ──
    PropertyPane_DefaultView_Label: 'มุมมองเริ่มต้น',

    // ── Property pane: Branding ──
    PropertyPane_AppTitle_Label: 'ชื่อแอป',
    PropertyPane_AppTitle_Placeholder: 'แผนผังองค์กร Contoso',
    PropertyPane_AppTitle_Description: 'แสดงบนแถบส่วนหัวควบคู่กับชื่อมุมมอง',
    PropertyPane_LogoUrl_Label: 'URL โลโก้',
    PropertyPane_LogoUrl_Placeholder: 'https://contoso.sharepoint.com/sites/yoursite/SiteAssets/logo.png',
    PropertyPane_LogoUrl_Description: 'URL แบบเต็มของรูปภาพ PNG/SVG/JPG เคล็ดลับ: เปิดไฟล์รูปภาพในเบราว์เซอร์แล้วคัดลอก URL จากแถบที่อยู่ URL ประเภท "คัดลอกลิงก์" จะใช้ไม่ได้',
    PropertyPane_DirectoryLabel_Label: 'ป้ายชื่อมุมมองไดเรกทอรีพนักงาน',
    PropertyPane_OrgChartLabel_Label: 'ป้ายชื่อมุมมองแผนผังองค์กร',
    PropertyPane_ViewLabel_Description: 'เว้นว่างไว้เพื่อใช้ชื่อเริ่มต้น หรือพิมพ์ "[blank]" เพื่อซ่อนป้ายกำกับทั้งหมด',

    // ── Property pane: Visual Style ──
    PropertyPane_ChartTheme_Label: 'ธีมแผนผัง',
    PropertyPane_Theme_Modern: 'โมเดิร์น — สีแผนกบนพื้นขาว',
    PropertyPane_Theme_Minimal: 'มินิมอล — แบนราบและความคมชัดต่ำ',
    PropertyPane_Theme_Corporate: 'องค์กร — สีน้ำเงินเดียวกันทั้งหมด',
    PropertyPane_Theme_Dark: 'มืด — พื้นหลังกรมท่าเข้ม',
    PropertyPane_Theme_Custom: 'กำหนดเอง — เลือกสีของคุณเอง',
    PropertyPane_AccentColor_Label: 'สีเน้นที่กำหนดเอง',
    PropertyPane_AccentColor_PickerAriaLabel: 'ตัวเลือกสีเน้น',
    PropertyPane_AccentColor_HexLabel: 'Hex',
    PropertyPane_AccentColor_HexAriaLabel: 'ค่า Hex ของสีเน้น',
    PropertyPane_AccentColor_RgbLabel: 'RGB',
    PropertyPane_AccentColor_ChannelAriaLabel: 'ช่อง {name} (0 ถึง 255)',
    PropertyPane_AccentColor_ContrastWithWhite: 'ความคมชัดเทียบกับสีขาว: {ratio}:1 ({passes})',
    PropertyPane_AccentColor_PassesAA: 'ผ่านเกณฑ์ AA',
    PropertyPane_AccentColor_LargeTextOnly: 'เฉพาะข้อความขนาดใหญ่',
    PropertyPane_AccentColor_LowContrast: 'ความคมชัดต่ำ',
    PropertyPane_AccentColor_DarkTextNote: 'ข้อความบนสีนี้จะใช้สีเข้มเพื่อให้อ่านง่ายขึ้น',
    PropertyPane_AccentColor_DarkerShadeNote: 'ชื่อเรื่องและลิงก์จะใช้เฉดสีที่เข้มกว่า ({hex}) เพื่อให้อ่านง่ายขึ้น',
    PropertyPane_AccentColor_InvalidHex: '"{typed}" ไม่ใช่รหัสสี Hex ที่ถูกต้อง โปรดใช้ค่าในรูปแบบ #0078d4 หรือ #07d',
    PropertyPane_DefaultFontSize_Label: 'ขนาดแบบอักษรเริ่มต้น',
    PropertyPane_FontSize_75: '75% — เล็กพิเศษ',
    PropertyPane_FontSize_85: '85% — เล็ก',
    PropertyPane_FontSize_100: '100% — ปกติ',
    PropertyPane_FontSize_115: '115% — ใหญ่',
    PropertyPane_FontSize_130: '130% — ใหญ่พิเศษ',
    PropertyPane_FontSize_150: '150% — ใหญ่มาก (XXL)',
    PropertyPane_FontSize_175: '175% — ใหญ่มากที่สุด (XXXL)',
    PropertyPane_DefaultLayout_Label: 'เค้าโครงแผนผังองค์กรเริ่มต้น',
    PropertyPane_Layout_Drill: 'เจาะลึกทีละระดับ',
    PropertyPane_Layout_Vertical: 'บนลงล่าง',
    PropertyPane_Layout_Horizontal: 'ซ้ายไปขวา',

    // ── Property pane: Data Source ──
    PropertyPane_DataSource_Label: 'แหล่งที่ใช้โหลดข้อมูลผู้ใช้และองค์กร',
    PropertyPane_DataSource_Auto: 'อัตโนมัติ — ใช้ Graph API และสำรองด้วยการค้นหาของ SharePoint',
    PropertyPane_DataSource_Graph: 'Graph API — ข้อมูล Azure AD แบบเรียลไทม์ (ไม่มีความล่าช้าจากการจัดทำดัชนี)',
    PropertyPane_DataSource_Search: 'การค้นหาของ SharePoint — พฤติกรรมแบบเดิม',
    PropertyPane_DataSource_Note: 'ขอแนะนำให้ใช้ Graph API เนื่องจากอ่านข้อมูลโดยตรงจาก Azure Active Directory ทำให้ผู้ใช้ใหม่และการเปลี่ยนแปลงผู้จัดการปรากฏขึ้นทันที ต้องได้รับการอนุมัติสิทธิ์ Microsoft Graph ใน App Catalog ของ SharePoint',

    // ── Property pane: Custom Attributes ──
    PropertyPane_CustomAttributes_Note: 'แอตทริบิวต์ที่กำหนดเองต้องใช้ Microsoft Graph (แหล่งข้อมูล: Graph หรืออัตโนมัติ) การค้นหาของ SharePoint ไม่มีวิธีทั่วไปในการอ่านแอตทริบิวต์ของ Entra ID',
    PropertyPane_CustomAttributes_Heading: 'จัดการแอตทริบิวต์ที่กำหนดเอง',
    PropertyPane_CustomAttributes_Empty: 'ยังไม่ได้กำหนดค่าแอตทริบิวต์ที่กำหนดเอง',
    PropertyPane_CustomAttributes_AddButton: '+ เพิ่มแอตทริบิวต์',
    PropertyPane_CustomAttributes_MaxTooltip: 'เพิ่มแอตทริบิวต์ที่กำหนดเองได้สูงสุด {max} รายการ',
    PropertyPane_CustomAttributes_FieldNameLabel: 'ชื่อแอตทริบิวต์',
    PropertyPane_CustomAttributes_FieldPlaceholder: 'เช่น companyName',
    PropertyPane_CustomAttributes_FieldError: 'ใช้ employeeId, companyName, city ... หรือ extensionAttribute1-15',
    PropertyPane_CustomAttributes_DisplayLabelLabel: 'ป้ายชื่อที่แสดง',
    PropertyPane_CustomAttributes_LabelPlaceholder: 'เช่น ศูนย์ต้นทุน',
    PropertyPane_CustomAttributes_RemoveTitle: 'ลบแอตทริบิวต์',
    PropertyPane_CustomAttributes_RemoveAriaLabel: 'ลบแอตทริบิวต์ {ordinal}',
    PropertyPane_CustomAttributes_ShowInDirectory: 'แสดงในไดเรกทอรี',
    PropertyPane_CustomAttributes_ShowInOrgChart: 'แสดงในแผนผังองค์กร',

    // ── Property pane: User Filters ──
    PropertyPane_ExcludedAccounts_Label: 'ยกเว้นบัญชี',
    PropertyPane_ExcludedAccounts_Placeholder: 'conf-room, noreply, admin@, Service Account',
    PropertyPane_ExcludedAccounts_Description: 'คำหรือรูปแบบที่คั่นด้วยจุลภาค (ไม่คำนึงถึงตัวพิมพ์ใหญ่-เล็ก) ผู้ใช้ที่มีชื่อที่แสดง อีเมล หรือ UPN ที่มีคำเหล่านี้จะถูกซ่อนจากมุมมองทั้งหมด',
    PropertyPane_RestrictTenant_Label: 'แสดงเฉพาะผู้ใช้ในองค์กรนี้',
    PropertyPane_RestrictTenant_On: 'เปิด — ซ่อนบัญชีที่มีโดเมนอีเมลภายนอก (เช่น gmail.com, hotmail.com)',
    PropertyPane_RestrictTenant_Off: 'ปิด — แสดงผู้ใช้ทั้งหมดโดยไม่คำนึงถึงโดเมนอีเมล',
    PropertyPane_HideGuest_Label: 'ซ่อนบัญชีผู้ใช้ภายนอกของ Azure AD',
    PropertyPane_HideGuest_On: 'เปิด — ซ่อนบัญชีผู้ใช้ภายนอก',
    PropertyPane_HideGuest_Off: 'ปิด — แสดงบัญชีผู้ใช้ภายนอก (มีป้าย "ผู้ใช้ภายนอก" กำกับ)',
    PropertyPane_HideDisabled_Label: 'ซ่อนบัญชีที่ถูกปิดใช้งาน',
    PropertyPane_HideDisabled_On: 'เปิด — ซ่อนบัญชีที่ถูกบล็อกการลงชื่อเข้าใช้',
    PropertyPane_HideDisabled_Off: 'ปิด — แสดงบัญชีที่ถูกปิดใช้งาน (มีป้าย "ปิดใช้งาน" กำกับ)',
    PropertyPane_HideDisabled_Note: 'หมายเหตุ: การตรวจหาบัญชีผู้ใช้ภายนอกและบัญชีที่ถูกปิดใช้งานต้องใช้แหล่งข้อมูล Graph API การค้นหาของ SharePoint ไม่ส่งคืนข้อมูลนี้ ดังนั้นตัวกรองทั้งสองนี้ (รวมถึงป้าย "ผู้ใช้ภายนอก"/"ปิดใช้งาน") จะไม่มีผลเมื่อข้อมูลมาจากการค้นหา',
    PropertyPane_HideNoJobTitle_Label: 'ซ่อนบัญชีที่ไม่มีตำแหน่งงาน',
    PropertyPane_HideNoJobTitle_On: 'เปิด — ซ่อนบัญชีที่ไม่มีตำแหน่งงาน',
    PropertyPane_HideNoJobTitle_Off: 'ปิด — แสดงบัญชีทั้งหมดโดยไม่คำนึงถึงตำแหน่งงาน',
    PropertyPane_HideNoDept_Label: 'ซ่อนบัญชีที่ไม่มีแผนก',
    PropertyPane_HideNoDept_On: 'เปิด — ซ่อนบัญชีที่ไม่มีแผนก',
    PropertyPane_HideNoDept_Off: 'ปิด — แสดงบัญชีทั้งหมดโดยไม่คำนึงถึงแผนก',

    // ── Property pane: Org Chart ──
    PropertyPane_TopLevelUser_Label: 'ผู้ใช้ระดับบนสุด (UPN หรืออีเมล)',
    PropertyPane_TopLevelUser_Placeholder: 'ceo@yourcompany.com',
    PropertyPane_TopLevelUser_Description: 'บุคคลที่แสดงที่รากของแผนผังองค์กร',
    PropertyPane_LevelsBelow_Label: 'จำนวนระดับที่จะโหลดใต้ราก',
    PropertyPane_DottedLine_Label: 'แอตทริบิวต์ผู้จัดการแบบเส้นประ',
    PropertyPane_DottedLine_Placeholder: 'extensionAttribute10',
    PropertyPane_DottedLine_Description: 'ไม่บังคับ ชื่อแอตทริบิวต์ส่วนขยายภายในองค์กรของ Azure AD (extensionAttribute1-15) ที่เก็บอีเมลหรือ UPN ของผู้จัดการสำรองแบบ "เส้นประ" ความสัมพันธ์แบบเส้นประจะแสดงบนการ์ดโปรไฟล์ ต้องใช้แหล่งข้อมูล Graph API',
    PropertyPane_DefaultZoom_Label: 'ระดับการซูมแผนผังองค์กรเริ่มต้น',
    PropertyPane_Zoom_Auto: 'ค่าเริ่มต้น (ปรับพอดีอัตโนมัติ)',
    PropertyPane_Zoom_50: '50%',
    PropertyPane_Zoom_75: '75%',
    PropertyPane_Zoom_100: '100%',
    PropertyPane_Zoom_125: '125%',
    PropertyPane_Zoom_150: '150%',

    // ── Property pane: Org Chart Features ──
    PropertyPane_FeatureToggles_Note: 'แสดงหรือซ่อนปุ่มแถบเครื่องมือในมุมมองแผนผังองค์กร',
    PropertyPane_FindMe_Label: 'ปุ่ม "ค้นหาฉัน"',
    PropertyPane_LayoutToggle_Label: 'ตัวสลับเค้าโครง (เจาะลึก / แนวตั้ง / แนวนอน)',
    PropertyPane_Stats_Label: 'แถบสถิติองค์กร',
    PropertyPane_DeptFilter_Label: 'ตัวกรองแผนก',
    PropertyPane_UserFilter_Label: 'ตัวกรองประเภทผู้ใช้ (สมาชิก / ผู้ใช้ภายนอก)',
    PropertyPane_Visible: 'แสดง',
    PropertyPane_Hidden: 'ซ่อน',

    // ── Property pane: Directory ──
    PropertyPane_PageSize_Label: 'จำนวนพนักงานสูงสุดต่อหน้า',
    PropertyPane_PageSize_AriaLabel: 'จำนวนพนักงานสูงสุดต่อหน้า (10 ถึง 200)',
    PropertyPane_PageSize_Note: 'ขนาดการ์ด ฟิลด์ที่แสดง และการตั้งค่าการแสดงผลอื่น ๆ จะถูกตั้งค่าแยกตามผู้ใช้แต่ละคนผ่านไอคอนการตั้งค่าในแอป',

    // ── Property pane: Demo ──
    PropertyPane_UseDemoData_Label: 'ใช้ข้อมูลสาธิต',
    PropertyPane_UseDemoData_On: 'เปิด — แสดงพนักงานตัวอย่าง',
    PropertyPane_UseDemoData_Off: 'ปิด — ข้อมูล Microsoft 365 จริง',

    // ── Presence status labels ──
    Presence_Available: 'ว่าง',
    Presence_Busy: 'ไม่ว่าง',
    Presence_DoNotDisturb: 'ห้ามรบกวน',
    Presence_BeRightBack: 'เดี๋ยวกลับ',
    Presence_Away: 'ไม่อยู่',
    Presence_Offline: 'ออฟไลน์',

    // ── Header / top bar ──
    Header_DirectoryLabel: 'ไดเรกทอรีพนักงาน',
    Header_OrgChartLabel: 'แผนผังองค์กร',
    Header_SwitchToView: 'สลับไปที่ {view}',
    Header_CompanyLogoAlt: 'โลโก้บริษัท',
    Header_RefreshingAria: 'กำลังรีเฟรชข้อมูล',
    Header_RefreshAria: 'รีเฟรชข้อมูล',
    Header_RefreshTitle: 'รีเฟรชข้อมูล (อัปเดตล่าสุด {when})',
    Header_NotLoadedYet: 'ยังไม่ได้โหลด',
    Header_JustNow: 'เมื่อสักครู่',
    Header_MinutesAgo: '{mins} นาทีที่แล้ว',
    Header_HoursAgo: '{hours} ชั่วโมงที่แล้ว',
    Header_PreferencesTitle: 'การตั้งค่าส่วนตัว',
    Header_PreferencesAria: 'เปิดแผงการตั้งค่าส่วนตัว',

    // ── Employee Directory ──
    Directory_LoadingLabel: 'กำลังโหลดพนักงาน...',
    Directory_LoadFailedFallback: 'ตรวจสอบว่าเว็บพาร์ตมีสิทธิ์ User.Read.All',
    Directory_LoadFailedPrefix: 'โหลดพนักงานไม่สำเร็จ {detail}',
    Directory_AllDepartments: 'ทุกแผนก',
    Directory_AllOffices: 'ทุกสำนักงาน',
    Directory_StatusDisabled: 'ปิดใช้งาน',
    Directory_StatusGuest: 'ผู้ใช้ภายนอก',
    Directory_PresenceStatus: 'สถานะ: {status}',
    Directory_ChatInTeams: 'แชทใน Teams',
    Directory_ChatWithInTeams: 'แชทกับ {name} ใน Teams',
    Directory_ManagesCount: 'ดูแล {direct} คน',
    Directory_ManagesCountWithTotal: 'ดูแล {direct} คน (รวม {total} คน)',
    Directory_ReportsCountWithTotal: '{direct} (รวม {total} คน)',
    Directory_ColumnName: 'ชื่อ',
    Directory_ColumnJobTitle: 'ตำแหน่งงาน',
    Directory_ColumnDepartment: 'แผนก',
    Directory_ColumnOffice: 'สำนักงาน',
    Directory_ColumnEmail: 'อีเมล',
    Directory_ColumnPhone: 'โทรศัพท์',
    Directory_ColumnReports: 'ผู้ใต้บังคับบัญชา',
    Directory_ColumnChat: 'แชท',
    Directory_PrevPage: 'ก่อนหน้า',
    Directory_NextPage: 'ถัดไป',
    Directory_PreviousPageAria: 'หน้าก่อนหน้า',
    Directory_NextPageAria: 'หน้าถัดไป',
    Directory_SearchPlaceholder: 'ค้นหาตามชื่อ ตำแหน่ง อีเมล หรือแผนก...',
    Directory_SearchAria: 'ค้นหาบุคคล',
    Directory_FilterByDepartmentAria: 'กรองตามแผนก',
    Directory_FilterByOfficeAria: 'กรองตามสำนักงาน',
    Directory_ClearSearchTitle: 'ล้างการค้นหาและตัวกรองทั้งหมด',
    Directory_ClearButton: 'ล้าง',
    Directory_ClearFiltersButton: 'ล้างตัวกรอง',
    Directory_ExportCsvTitle: 'ส่งออกผลลัพธ์ที่กรองทั้งหมดเป็นไฟล์ CSV (เปิดใน Excel)',
    Directory_ExportCsvButton: 'ส่งออก CSV',
    Directory_ViewModeAria: 'โหมดการแสดงผล',
    Directory_CardViewTitle: 'มุมมองการ์ด',
    Directory_ListViewTitle: 'มุมมองรายการ',
    Directory_AlphabetFilterAria: 'ตัวกรองตามตัวอักษร',
    Directory_ShowAllTitle: 'แสดงทั้งหมด',
    Directory_OtherLettersTitle: 'กรองชื่อที่ขึ้นต้นด้วยตัวเลขหรืออักขระอื่น',
    Directory_FilterByLetterTitle: 'กรองตามตัวอักษร {letter}',
    Directory_ResultCountSingular: 'คน',
    Directory_ResultCountPlural: 'คน',
    Directory_PageOf: ' · หน้า {page} จาก {totalPages}',
    Directory_FilterActiveSingular: 'ใช้ตัวกรองอยู่ {count} รายการ',
    Directory_FilterActivePlural: 'ใช้ตัวกรองอยู่ {count} รายการ',
    Directory_NoResults: 'ไม่พบบุคคล',
    Directory_PaginationAria: 'การแบ่งหน้า',

    // ── Org chart toolbar / shared chart chrome ──
    Chart_Layout_Drill: 'เจาะลึกทีละระดับ',
    Chart_Layout_Vertical: 'บนลงล่าง',
    Chart_Layout_Horizontal: 'ซ้ายไปขวา',
    Chart_SearchPlaceholder: 'ค้นหาบุคคล...',
    Chart_SearchAria: 'ค้นหาบุคคล',
    Chart_MatchSingular: 'รายการที่ตรงกันในโครงสร้าง',
    Chart_MatchPlural: 'รายการที่ตรงกันในโครงสร้าง',
    Chart_ResultsListAria: 'บุคคล',
    Chart_ExpandAll: 'ขยายทั้งหมด',
    Chart_CollapseAll: 'ยุบทั้งหมด',
    Chart_Expanding: 'กำลังขยาย…',
    Chart_Loading: 'กำลังโหลด…',
    Chart_FindMeTitle: 'ค้นหาฉันในแผนผังองค์กร',
    Chart_ViewLayoutButton: 'มุมมอง',
    Chart_ViewLayoutTitle: 'สลับเค้าโครงมุมมอง',
    Chart_ViewLayoutPanelTitle: 'เค้าโครงมุมมอง',
    Chart_StatsSummaryTitle: 'สรุปสถิติองค์กร',
    Chart_FilterByDepartmentTitle: 'กรองตามแผนก',
    Chart_FilterByDepartmentWithCountAria: 'กรองตามแผนก (เลือกแล้ว {count} รายการ)',
    Chart_FilterByDepartmentPanelTitle: 'กรองตามแผนก',
    Chart_ClearAllFilters: 'ล้างตัวกรองทั้งหมด',
    Chart_FilterUserTypesTitle: 'กรองประเภทผู้ใช้',
    Chart_DownloadPdfTitle: 'ดาวน์โหลดเป็น PDF',
    Chart_DownloadCsvTitle: 'ดาวน์โหลดเป็นสเปรดชีต CSV',
    Chart_ResetRootTitle: 'รีเซ็ตกลับไปยังรากเริ่มต้น',
    Chart_ViewFromPersonPlaceholder: 'ดูจากบุคคล…',
    Chart_ViewFromPersonAria: 'ดูแผนผังองค์กรจากบุคคลที่ระบุ',
    Chart_ZoomOutTitle: 'ซูมออก',
    Chart_ZoomInTitle: 'ซูมเข้า',
    Chart_ZoomResetTitle: 'รีเซ็ตการซูม',
    Chart_ShowInChartAria: 'แสดงในแผนผัง',
    Chart_ShowInChartTitle: 'แสดงในแผนผัง',
    Chart_FilterMembers: 'สมาชิกทั่วไป',
    Chart_FilterGuests: 'ผู้ใช้ภายนอก',
    Chart_FilterDisabled: 'บัญชีที่ปิดใช้งาน',
    Chart_SetupTitle: 'ตั้งค่าแผนผังองค์กร',
    Chart_SetupSubtitle: 'ป้อนอีเมลหรือ UPN ของบุคคลระดับบนสุดเพื่อเริ่มต้น',
    Chart_SetupPlaceholder: 'ceo@company.com',
    Chart_SetupInputAria: 'อีเมลหรือ UPN ของบุคคลระดับบนสุด',
    Chart_SetupLoadButton: 'โหลด',
    Chart_SetupHint: 'คุณยังสามารถตั้งค่านี้แบบถาวรได้ในการตั้งค่าเว็บพาร์ต (สำหรับผู้ดูแลระบบ)',
    Chart_BuildingLabel: 'กำลังสร้างแผนผังองค์กร...',
    Chart_RetryButton: 'ลองอีกครั้ง',
    Chart_NotFoundFromSetup: 'ไม่พบผู้ใช้ "{identifier}"',
    Chart_NotFoundWithSettings: 'ไม่พบผู้ใช้ "{identifier}" โปรดตรวจสอบ UPN หรืออีเมลในการตั้งค่า',
    Chart_LoadFailedGeneric: 'โหลดแผนผังองค์กรไม่สำเร็จ{detail}',
    Chart_LoadFailedPermissions: ' โปรดตรวจสอบสิทธิ์การเข้าถึง',
    Chart_LoadFailedForPerson: 'โหลดแผนผังองค์กรของบุคคลนี้ไม่สำเร็จ',
    Chart_FindMeNotFound: 'ไม่พบบัญชีของคุณในองค์กรนี้',
    Chart_StatPeople: 'บุคคล',
    Chart_StatMembers: 'สมาชิก',
    Chart_StatGuests: 'ผู้ใช้ภายนอก',
    Chart_StatDepts: 'แผนก',
    Chart_ReportingLineAria: 'สายการบังคับบัญชา',
    Chart_BackToFullOrgTitle: 'กลับไปยังแผนผังองค์กรทั้งหมด',
    Chart_FullOrgLabel: 'องค์กรทั้งหมด',
    Chart_FocusOnPerson: 'โฟกัสที่ {name}',
    Chart_OrgChartAria: 'แผนผังองค์กร',
    Chart_ExportNote_DrillLevel: 'ระดับการเจาะลึกปัจจุบัน (ผู้ใต้บังคับบัญชาโดยตรงหนึ่งระดับ)',
    Chart_ExportNote_PartialLevels: 'รวมเฉพาะระดับที่โหลดแล้ว — ใช้ "ขยายทั้งหมด" ก่อนส่งออกเพื่อรวมระดับที่ลึกกว่านี้',
    Chart_AllowPopupsForPdf: 'โปรดอนุญาตป๊อปอัปเพื่อส่งออก PDF',

    // ── Person card ──
    PersonCard_ProfileAria: 'โปรไฟล์: {name}',
    PersonCard_CloseTitle: 'ปิด',
    PersonCard_CloseAria: 'ปิดโปรไฟล์',
    PersonCard_StatusDisabled: 'ปิดใช้งาน',
    PersonCard_StatusGuest: 'ผู้ใช้ภายนอก',
    PersonCard_DirectReportSingular: 'ผู้ใต้บังคับบัญชาโดยตรง {count} คน',
    PersonCard_DirectReportPlural: 'ผู้ใต้บังคับบัญชาโดยตรง {count} คน',
    PersonCard_TotalSuffix: ' · รวม {total} คน',
    PersonCard_CopyEmailTitle: 'คัดลอกที่อยู่อีเมล',
    PersonCard_EmailCopiedAria: 'คัดลอกที่อยู่อีเมลแล้ว',
    PersonCard_ReportsTo: 'รายงานต่อ',
    PersonCard_FocusOnPerson: 'โฟกัสที่ {name}',
    PersonCard_FocusOrgChartOnPerson: 'โฟกัสแผนผังองค์กรที่ {name}',
    PersonCard_DottedLine: 'เส้นประ',
    PersonCard_DottedLineManager: 'ผู้จัดการแบบเส้นประ: {name}',
    PersonCard_DottedLineReport: 'ผู้ใต้บังคับบัญชาแบบเส้นประ: {name}',
    PersonCard_ChatButton: 'แชท',
    PersonCard_EmailButton: 'อีเมล',
    PersonCard_FocusButton: 'โฟกัส',
    PersonCard_FocusTitle: 'โฟกัสแผนผังองค์กรที่บุคคลนี้',

    // ── Org node card ──
    OrgNode_ViewProfile: 'ดูโปรไฟล์ของ {name}',
    OrgNode_FocusOrgChartOn: 'โฟกัสแผนผังองค์กรที่ {name}',
    OrgNode_Collapse: 'ยุบ',
    OrgNode_Expand: 'ขยาย',
    OrgNode_DirectReportsSuffix: 'ผู้ใต้บังคับบัญชาโดยตรงของ {name}',
    OrgNode_StatusDisabled: 'ปิดใช้งาน',
    OrgNode_StatusGuest: 'ผู้ใช้ภายนอก',
    OrgNode_TotalReportsAcrossLevels: '{count} คนในทุกระดับใต้ {name}',

    // ── Drill view ──
    Drill_ReportingLineAria: 'สายการบังคับบัญชา',
    Drill_BackToTopTitle: 'กลับไปด้านบนสุด',
    Drill_BackToTopAria: 'กลับไปด้านบนสุดของแผนผังองค์กร',
    Drill_GoBackTo: 'กลับไปที่ {name}',
    Drill_ViewProfileTitle: 'ดูโปรไฟล์',
    Drill_ViewProfileAria: 'ดูโปรไฟล์ของ {name}',
    Drill_ProfileButton: 'โปรไฟล์',
    Drill_LoadingLabel: 'กำลังโหลด...',
    Drill_DirectReports: 'ผู้ใต้บังคับบัญชาโดยตรง',
    Drill_DirectReportsOfAria: 'ผู้ใต้บังคับบัญชาโดยตรงของ {name}',
    Drill_DirectReportsAria: 'ผู้ใต้บังคับบัญชาโดยตรง',
    Drill_ViewPersonProfile: 'ดูโปรไฟล์ของ {name}',
    Drill_ShowPersonReports: 'แสดงผู้ใต้บังคับบัญชาโดยตรงของ {name}',
    Drill_NoDirectReports: 'ไม่มีผู้ใต้บังคับบัญชาโดยตรง',

    // ── Settings panel ──
    Settings_AlphabetFirstName: 'ชื่อจริง',
    Settings_AlphabetLastName: 'นามสกุล',
    Settings_CardSizeSmall: 'เล็ก — กะทัดรัด แสดงการ์ดได้มากขึ้น',
    Settings_CardSizeMedium: 'กลาง — สมดุล',
    Settings_CardSizeLarge: 'ใหญ่ — กว้างขวาง แสดงการ์ดได้น้อยลง',
    Settings_HeaderText: 'การตั้งค่าส่วนตัว',
    Settings_SaveButton: 'บันทึก',
    Settings_CancelButton: 'ยกเลิก',
    Settings_DiscardButton: 'ละทิ้งการเปลี่ยนแปลง',
    Settings_SectionDirectory: 'ไดเรกทอรี',
    Settings_AlphabetFilterByLabel: 'กรองตามตัวอักษรโดยใช้',
    Settings_CardSizeLabel: 'ขนาดการ์ด',
    Settings_FontSizeLabel: 'ขนาดแบบอักษร',
    Settings_SectionCardsAndFields: 'การ์ดและฟิลด์',
    Settings_ShowOnCardsLabel: 'แสดงบนการ์ดพนักงาน:',
    Settings_EmailAddressLabel: 'ที่อยู่อีเมล',
    Settings_PhoneNumberLabel: 'หมายเลขโทรศัพท์',
    Settings_DepartmentLabel: 'แผนก',
    Settings_OfficeLocationLabel: 'ที่ตั้งสำนักงาน',
    Settings_SectionOrgChart: 'แผนผังองค์กร',
    Settings_ManagerLevelsLabel: 'จำนวนระดับผู้จัดการที่แสดงเมื่อโฟกัสที่บุคคล: {levels}',
    Settings_CompactCardsLabel: 'การ์ดแบบกะทัดรัด',
    Settings_CompactCardsOn: 'เปิด — การ์ดขนาดเล็กลง แสดงได้มากขึ้นในคราวเดียว',
    Settings_CompactCardsOff: 'ปิด — ขนาดมาตรฐาน',
    Settings_Hint: 'การตั้งค่าเหล่านี้จะถูกบันทึกไว้ในเบราว์เซอร์ของคุณและมีผลกับคุณเท่านั้น ธีมแผนผัง มุมมองเริ่มต้น และเค้าโครงจะถูกกำหนดโดยผู้ดูแลระบบ SharePoint ของคุณ',
    Settings_SectionDemoData: 'ข้อมูลสาธิต',
    Settings_DatasetSizeLabel: 'ขนาดชุดข้อมูล',
    Settings_PeopleCountSuffix: '{count} คน',

    // ── Export (CSV / PDF) ──
    Export_ColumnName: 'ชื่อ',
    Export_ColumnJobTitle: 'ตำแหน่งงาน',
    Export_ColumnDepartment: 'แผนก',
    Export_ColumnOffice: 'สำนักงาน',
    Export_ColumnEmail: 'อีเมล',
    Export_ColumnPhone: 'โทรศัพท์',
    Export_ColumnManager: 'ผู้จัดการ',
    Export_ColumnLevel: 'ระดับ',
    Export_PdfDocumentTitle: 'แผนผังองค์กร',
    Export_PdfHeading: 'แผนผังองค์กร',
    Export_PdfRootLabel: 'ราก: {name}',
  };
});
