define([], function () {
  return {
    // ── Özellik bölmesi: bölme başlığı / gruplar ──
    PropertyPane_HeaderDescription: 'Smart Org Chart Ayarları',
    PropertyPane_Group_General: 'Genel',
    PropertyPane_Group_Branding: 'Marka Kimliği',
    PropertyPane_Group_VisualStyle: 'Görsel Stil',
    PropertyPane_Group_DataSource: 'Veri Kaynağı',
    PropertyPane_Group_CustomAttributes: 'Özel Öznitelikler',
    PropertyPane_Group_UserFilters: 'Kullanıcı Filtreleri',
    PropertyPane_Group_OrgChart: 'Organizasyon Şeması',
    PropertyPane_Group_OrgChartFeatures: 'Organizasyon Şeması Özellikleri',
    PropertyPane_Group_Directory: 'Dizin',
    PropertyPane_Group_Demo: 'Demo',

    // ── Özellik bölmesi: Genel ──
    PropertyPane_DefaultView_Label: 'Varsayılan Görünüm',

    // ── Özellik bölmesi: Marka Kimliği ──
    PropertyPane_AppTitle_Label: 'Uygulama Başlığı',
    PropertyPane_AppTitle_Placeholder: 'Contoso Organizasyon Şeması',
    PropertyPane_AppTitle_Description: 'Görünüm adının yanında üst bilgi çubuğunda görüntülenir',
    PropertyPane_LogoUrl_Label: 'Logo URL\'si',
    PropertyPane_LogoUrl_Placeholder: 'https://contoso.sharepoint.com/sites/yoursite/SiteAssets/logo.png',
    PropertyPane_LogoUrl_Description: 'PNG/SVG/JPG görüntüsünün tam URL\'si. İpucu: görüntü dosyasını tarayıcınızda açın ve adres çubuğundaki URL\'yi kopyalayın. "Bağlantıyı kopyala" ile paylaşılan URL\'ler çalışmaz.',
    PropertyPane_DirectoryLabel_Label: 'Çalışan Dizini Görünüm Etiketi',
    PropertyPane_OrgChartLabel_Label: 'Organizasyon Şeması Görünüm Etiketi',
    PropertyPane_ViewLabel_Description: 'Varsayılan adı kullanmak için boş bırakın veya etiketi tamamen gizlemek için "[blank]" yazın.',

    // ── Özellik bölmesi: Görsel Stil ──
    PropertyPane_ChartTheme_Label: 'Şema Teması',
    PropertyPane_Theme_Modern: 'Modern — beyaz zeminde departman renkleri',
    PropertyPane_Theme_Minimal: 'Minimal — sade ve düşük kontrast',
    PropertyPane_Theme_Corporate: 'Kurumsal — tek tip mavi',
    PropertyPane_Theme_Dark: 'Koyu — koyu lacivert arka plan',
    PropertyPane_Theme_Custom: 'Özel — kendi renginizi seçin',
    PropertyPane_AccentColor_Label: 'Özel Vurgu Rengi',
    PropertyPane_AccentColor_PickerAriaLabel: 'Vurgu rengi seçici',
    PropertyPane_AccentColor_HexLabel: 'Onaltılık',
    PropertyPane_AccentColor_HexAriaLabel: 'Vurgu rengi onaltılık değeri',
    PropertyPane_AccentColor_RgbLabel: 'RGB',
    PropertyPane_AccentColor_ChannelAriaLabel: '{name} kanalı (0 - 255)',
    PropertyPane_AccentColor_ContrastWithWhite: 'Beyaz ile kontrast: {ratio}:1 ({passes})',
    PropertyPane_AccentColor_PassesAA: 'AA standardını karşılıyor',
    PropertyPane_AccentColor_LargeTextOnly: 'yalnızca büyük metin',
    PropertyPane_AccentColor_LowContrast: 'düşük kontrast',
    PropertyPane_AccentColor_DarkTextNote: 'Okunabilirlik için bu renk üzerindeki metinlerde koyu renk kullanılır.',
    PropertyPane_AccentColor_DarkerShadeNote: 'Okunabilirlik için başlıklarda ve bağlantılarda daha koyu bir ton ({hex}) kullanılır.',
    PropertyPane_AccentColor_InvalidHex: '"{typed}" geçerli bir onaltılık renk değil. #0078d4 veya #07d gibi bir değer kullanın.',
    PropertyPane_DefaultFontSize_Label: 'Varsayılan Yazı Tipi Boyutu',
    PropertyPane_FontSize_75: '%75 — Çok Küçük',
    PropertyPane_FontSize_85: '%85 — Küçük',
    PropertyPane_FontSize_100: '%100 — Normal',
    PropertyPane_FontSize_115: '%115 — Büyük',
    PropertyPane_FontSize_130: '%130 — Çok Büyük',
    PropertyPane_FontSize_150: '%150 — XXL',
    PropertyPane_FontSize_175: '%175 — XXXL',
    PropertyPane_DefaultLayout_Label: 'Varsayılan Organizasyon Şeması Düzeni',
    PropertyPane_Layout_Drill: 'Detaya İnme',
    PropertyPane_Layout_Vertical: 'Yukarıdan Aşağıya',
    PropertyPane_Layout_Horizontal: 'Soldan Sağa',

    // ── Özellik bölmesi: Veri Kaynağı ──
    PropertyPane_DataSource_Label: 'Kullanıcı ve organizasyon verilerinin yükleneceği kaynak',
    PropertyPane_DataSource_Auto: 'Otomatik — Graph API, gerekirse SharePoint Arama\'ya geri döner',
    PropertyPane_DataSource_Graph: 'Graph API — canlı Azure AD verileri (dizinleme gecikmesi yok)',
    PropertyPane_DataSource_Search: 'SharePoint Arama — eski davranış',
    PropertyPane_DataSource_Note: 'Graph API kullanılması önerilir. Veriler doğrudan Azure Active Directory\'den okunduğundan yeni kullanıcılar ve yönetici değişiklikleri hemen görünür. SharePoint Uygulama Kataloğunda Microsoft Graph izinlerinin onaylanmış olması gerekir.',

    // ── Özellik bölmesi: Özel Öznitelikler ──
    PropertyPane_CustomAttributes_Note: 'Özel öznitelikler için Microsoft Graph gerekir (Veri kaynağı: Graph veya Otomatik). SharePoint Arama, Microsoft Entra ID özniteliklerini okumak için genel bir yönteme sahip değildir.',
    PropertyPane_CustomAttributes_Heading: 'Özel öznitelikleri yönet',
    PropertyPane_CustomAttributes_Empty: 'Yapılandırılmış özel öznitelik yok.',
    PropertyPane_CustomAttributes_AddButton: '+ Öznitelik ekle',
    PropertyPane_CustomAttributes_MaxTooltip: 'En fazla {max} özel öznitelik',
    PropertyPane_CustomAttributes_FieldNameLabel: 'Öznitelik adı',
    PropertyPane_CustomAttributes_FieldPlaceholder: 'örn. companyName',
    PropertyPane_CustomAttributes_FieldError: 'employeeId, companyName, city vb. veya extensionAttribute1-15 kullanın',
    PropertyPane_CustomAttributes_DisplayLabelLabel: 'Görünen ad',
    PropertyPane_CustomAttributes_LabelPlaceholder: 'örn. Masraf Merkezi',
    PropertyPane_CustomAttributes_RemoveTitle: 'Özniteliği kaldır',
    PropertyPane_CustomAttributes_RemoveAriaLabel: '{ordinal}. özniteliği kaldır',
    PropertyPane_CustomAttributes_ShowInDirectory: 'Dizinde göster',
    PropertyPane_CustomAttributes_ShowInOrgChart: 'Organizasyon şemasında göster',

    // ── Özellik bölmesi: Kullanıcı Filtreleri ──
    PropertyPane_ExcludedAccounts_Label: 'Hariç tutulacak hesaplar',
    PropertyPane_ExcludedAccounts_Placeholder: 'conf-room, noreply, admin@, Service Account',
    PropertyPane_ExcludedAccounts_Description: 'Virgülle ayrılmış sözcükler veya kalıplar (büyük/küçük harfe duyarlı değildir). Görünen adında, e-postasında veya UPN\'sinde bunlardan birini içeren kullanıcılar tüm görünümlerden gizlenir.',
    PropertyPane_RestrictTenant_Label: 'Yalnızca kiracı kullanıcılarını göster',
    PropertyPane_RestrictTenant_On: 'Açık — harici e-posta etki alanlarına sahip hesapları gizler (örn. gmail.com, hotmail.com)',
    PropertyPane_RestrictTenant_Off: 'Kapalı — e-posta etki alanından bağımsız olarak tüm kullanıcılar gösterilir',
    PropertyPane_HideGuest_Label: 'Azure AD konuk hesaplarını gizle',
    PropertyPane_HideGuest_On: 'Açık — konuk hesapları gizli',
    PropertyPane_HideGuest_Off: 'Kapalı — konuk hesapları görünür (Konuk rozetiyle gösterilir)',
    PropertyPane_HideDisabled_Label: 'Devre dışı hesapları gizle',
    PropertyPane_HideDisabled_On: 'Açık — oturum açması engellenmiş hesaplar gizli',
    PropertyPane_HideDisabled_Off: 'Kapalı — devre dışı hesaplar görünür (Devre Dışı rozetiyle gösterilir)',
    PropertyPane_HideDisabled_Note: 'Not: konuk ve devre dışı hesap tespiti için Graph API veri kaynağı gerekir. SharePoint Arama bu bilgiyi döndürmez; bu nedenle veriler Arama\'dan geldiğinde bu iki filtrenin (ve Konuk/Devre Dışı rozetlerinin) hiçbir etkisi olmaz.',
    PropertyPane_HideNoJobTitle_Label: 'Unvanı olmayan hesapları gizle',
    PropertyPane_HideNoJobTitle_On: 'Açık — unvanı olmayan hesaplar gizli',
    PropertyPane_HideNoJobTitle_Off: 'Kapalı — unvandan bağımsız olarak tüm hesaplar gösterilir',
    PropertyPane_HideNoDept_Label: 'Departmanı olmayan hesapları gizle',
    PropertyPane_HideNoDept_On: 'Açık — departmanı olmayan hesaplar gizli',
    PropertyPane_HideNoDept_Off: 'Kapalı — departmandan bağımsız olarak tüm hesaplar gösterilir',

    // ── Özellik bölmesi: Organizasyon Şeması ──
    PropertyPane_TopLevelUser_Label: 'Üst Düzey Kullanıcı (UPN veya E-posta)',
    PropertyPane_TopLevelUser_Placeholder: 'ceo@yourcompany.com',
    PropertyPane_TopLevelUser_Description: 'Organizasyon şemasının kökünde gösterilecek kişi',
    PropertyPane_LevelsBelow_Label: 'Kökün altında yüklenecek düzey sayısı',
    PropertyPane_DottedLine_Label: 'Kesikli çizgi yönetici özniteliği',
    PropertyPane_DottedLine_Placeholder: 'extensionAttribute10',
    PropertyPane_DottedLine_Description: 'İsteğe bağlı. İkincil "kesikli çizgi" yöneticinin e-posta adresini veya UPN\'sini depolayan Azure AD şirket içi uzantı özniteliğinin (extensionAttribute1-15) adı. Kesikli çizgi ilişkileri profil kartlarında görünür. Graph API veri kaynağı gerektirir.',
    PropertyPane_DefaultZoom_Label: 'Varsayılan Organizasyon Şeması Yakınlaştırması',
    PropertyPane_Zoom_Auto: 'Varsayılan (Otomatik Sığdır)',
    PropertyPane_Zoom_50: '%50',
    PropertyPane_Zoom_75: '%75',
    PropertyPane_Zoom_100: '%100',
    PropertyPane_Zoom_125: '%125',
    PropertyPane_Zoom_150: '%150',

    // ── Özellik bölmesi: Organizasyon Şeması Özellikleri ──
    PropertyPane_FeatureToggles_Note: 'Organizasyon şeması görünümündeki araç çubuğu düğmelerini gösterin veya gizleyin.',
    PropertyPane_FindMe_Label: 'Beni Bul düğmesi',
    PropertyPane_LayoutToggle_Label: 'Düzen değiştirici (detaya inme / dikey / yatay)',
    PropertyPane_Stats_Label: 'Organizasyon istatistikleri çubuğu',
    PropertyPane_DeptFilter_Label: 'Departman filtresi',
    PropertyPane_UserFilter_Label: 'Kullanıcı türü filtresi (üyeler / konuklar)',
    PropertyPane_Visible: 'Görünür',
    PropertyPane_Hidden: 'Gizli',

    // ── Özellik bölmesi: Dizin ──
    PropertyPane_PageSize_Label: 'Sayfa başına en fazla çalışan sayısı',
    PropertyPane_PageSize_AriaLabel: 'Sayfa başına en fazla çalışan sayısı (10 - 200)',
    PropertyPane_PageSize_Note: 'Kart boyutu, görünen alanlar ve diğer görüntüleme tercihleri, uygulamadaki Ayarlar dişlisi aracılığıyla kullanıcı bazında ayarlanır.',

    // ── Özellik bölmesi: Demo ──
    PropertyPane_UseDemoData_Label: 'Demo Verisi Kullan',
    PropertyPane_UseDemoData_On: 'Açık — örnek çalışanlar gösteriliyor',
    PropertyPane_UseDemoData_Off: 'Kapalı — canlı Microsoft 365 verileri',

    // ── Durum etiketleri ──
    Presence_Available: 'Uygun',
    Presence_Busy: 'Meşgul',
    Presence_DoNotDisturb: 'Rahatsız Etmeyin',
    Presence_BeRightBack: 'Hemen Döneceğim',
    Presence_Away: 'Uzakta',
    Presence_Offline: 'Çevrimdışı',

    // ── Üst bilgi / üst çubuk ──
    Header_DirectoryLabel: 'Çalışan Dizini',
    Header_OrgChartLabel: 'Organizasyon Şeması',
    Header_SwitchToView: '{view} görünümüne geç',
    Header_CompanyLogoAlt: 'Şirket logosu',
    Header_RefreshingAria: 'Veriler yenileniyor',
    Header_RefreshAria: 'Verileri yenile',
    Header_RefreshTitle: 'Verileri yenile (son güncelleme: {when})',
    Header_NotLoadedYet: 'henüz yüklenmedi',
    Header_JustNow: 'az önce',
    Header_MinutesAgo: '{mins} dakika önce',
    Header_HoursAgo: '{hours} saat önce',
    Header_PreferencesTitle: 'Tercihler',
    Header_PreferencesAria: 'Tercihler panelini aç',

    // ── Çalışan Dizini ──
    Directory_LoadingLabel: 'Çalışanlar yükleniyor...',
    Directory_LoadFailedFallback: 'Web parçasının User.Read.All iznine sahip olduğundan emin olun.',
    Directory_LoadFailedPrefix: 'Çalışanlar yüklenemedi. {detail}',
    Directory_AllDepartments: 'Tüm Departmanlar',
    Directory_AllOffices: 'Tüm Ofisler',
    Directory_StatusDisabled: 'Devre Dışı',
    Directory_StatusGuest: 'Konuk',
    Directory_PresenceStatus: 'Durum: {status}',
    Directory_ChatInTeams: 'Teams\'de sohbet et',
    Directory_ChatWithInTeams: 'Teams\'de {name} ile sohbet et',
    Directory_ManagesCount: '{direct} kişiyi yönetiyor',
    Directory_ManagesCountWithTotal: '{direct} kişiyi yönetiyor (toplam {total})',
    Directory_ReportsCountWithTotal: '{direct} (toplam {total})',
    Directory_ColumnName: 'Ad',
    Directory_ColumnJobTitle: 'Unvan',
    Directory_ColumnDepartment: 'Departman',
    Directory_ColumnOffice: 'Ofis',
    Directory_ColumnEmail: 'E-posta',
    Directory_ColumnPhone: 'Telefon',
    Directory_ColumnReports: 'Bağlı Çalışanlar',
    Directory_ColumnChat: 'Sohbet',
    Directory_PrevPage: 'Önceki',
    Directory_NextPage: 'Sonraki',
    Directory_PreviousPageAria: 'Önceki sayfa',
    Directory_NextPageAria: 'Sonraki sayfa',
    Directory_SearchPlaceholder: 'Ada, unvana, e-postaya veya departmana göre ara...',
    Directory_SearchAria: 'Kişi ara',
    Directory_FilterByDepartmentAria: 'Departmana göre filtrele',
    Directory_FilterByOfficeAria: 'Ofise göre filtrele',
    Directory_ClearSearchTitle: 'Aramayı ve tüm filtreleri temizle',
    Directory_ClearButton: 'Temizle',
    Directory_ClearFiltersButton: 'Filtreleri temizle',
    Directory_ExportCsvTitle: 'Filtrelenmiş tüm sonuçları bir CSV dosyasına aktar (Excel\'de açılır)',
    Directory_ExportCsvButton: 'CSV\'ye Aktar',
    Directory_ViewModeAria: 'Görünüm modu',
    Directory_CardViewTitle: 'Kart görünümü',
    Directory_ListViewTitle: 'Liste görünümü',
    Directory_AlphabetFilterAria: 'Alfabe filtresi',
    Directory_ShowAllTitle: 'Tümünü göster',
    Directory_OtherLettersTitle: 'Bir sayı veya başka bir karakterle başlayan adlara göre filtrele',
    Directory_FilterByLetterTitle: '{letter} harfine göre filtrele',
    Directory_ResultCountSingular: 'kişi',
    Directory_ResultCountPlural: 'kişi',
    Directory_PageOf: ' · sayfa {page} / {totalPages}',
    Directory_FilterActiveSingular: '{count} filtre etkin',
    Directory_FilterActivePlural: '{count} filtre etkin',
    Directory_NoResults: 'Kişi bulunamadı',
    Directory_PaginationAria: 'Sayfalama',

    // ── Organizasyon şeması araç çubuğu / ortak şema arayüzü ──
    Chart_Layout_Drill: 'Detaya İnme',
    Chart_Layout_Vertical: 'Yukarıdan Aşağıya',
    Chart_Layout_Horizontal: 'Soldan Sağa',
    Chart_SearchPlaceholder: 'Kişi ara...',
    Chart_SearchAria: 'Kişi ara',
    Chart_MatchSingular: 'ağaçta eşleşme',
    Chart_MatchPlural: 'ağaçta eşleşme',
    Chart_ResultsListAria: 'Kişiler',
    Chart_ExpandAll: 'Tümünü Genişlet',
    Chart_CollapseAll: 'Tümünü Daralt',
    Chart_Expanding: 'Genişletiliyor…',
    Chart_Loading: 'Yükleniyor…',
    Chart_FindMeTitle: 'Beni organizasyon şemasında bul',
    Chart_ViewLayoutButton: 'Görünüm',
    Chart_ViewLayoutTitle: 'Görünüm düzenini değiştir',
    Chart_ViewLayoutPanelTitle: 'Görünüm düzeni',
    Chart_StatsSummaryTitle: 'Organizasyon istatistikleri özeti',
    Chart_FilterByDepartmentTitle: 'Departmana göre filtrele',
    Chart_FilterByDepartmentWithCountAria: 'Departmana göre filtrele ({count} seçildi)',
    Chart_FilterByDepartmentPanelTitle: 'Departmana göre filtrele',
    Chart_ClearAllFilters: 'Tüm filtreleri temizle',
    Chart_FilterUserTypesTitle: 'Kullanıcı türlerini filtrele',
    Chart_DownloadPdfTitle: 'PDF olarak indir',
    Chart_DownloadCsvTitle: 'CSV elektronik tablosu olarak indir',
    Chart_ResetRootTitle: 'Varsayılan köke sıfırla',
    Chart_ViewFromPersonPlaceholder: 'Bir kişiden itibaren görüntüle…',
    Chart_ViewFromPersonAria: 'Organizasyon şemasını bir kişiden itibaren görüntüle',
    Chart_ZoomOutTitle: 'Uzaklaştır',
    Chart_ZoomInTitle: 'Yakınlaştır',
    Chart_ZoomResetTitle: 'Yakınlaştırmayı sıfırla',
    Chart_ShowInChartAria: 'Şemada göster',
    Chart_ShowInChartTitle: 'Şemada göster',
    Chart_FilterMembers: 'Normal üyeler',
    Chart_FilterGuests: 'Konuk kullanıcılar',
    Chart_FilterDisabled: 'Devre dışı hesaplar',
    Chart_SetupTitle: 'Organizasyon Şemasını Ayarlayın',
    Chart_SetupSubtitle: 'Başlamak için üst düzey kişinin e-postasını veya UPN\'sini girin.',
    Chart_SetupPlaceholder: 'ceo@company.com',
    Chart_SetupInputAria: 'Üst düzey kişinin e-postası veya UPN\'si',
    Chart_SetupLoadButton: 'Yükle',
    Chart_SetupHint: 'Bunu web parçası ayarlarında (yönetici) kalıcı olarak da ayarlayabilirsiniz.',
    Chart_BuildingLabel: 'Organizasyon şeması oluşturuluyor...',
    Chart_RetryButton: 'Yeniden dene',
    Chart_NotFoundFromSetup: '"{identifier}" kullanıcısı bulunamadı.',
    Chart_NotFoundWithSettings: '"{identifier}" kullanıcısı bulunamadı. Ayarlar\'daki UPN veya e-postayı kontrol edin.',
    Chart_LoadFailedGeneric: 'Organizasyon şeması yüklenemedi.{detail}',
    Chart_LoadFailedPermissions: ' İzinleri kontrol edin.',
    Chart_LoadFailedForPerson: 'Bu kişi için organizasyon şeması yüklenemedi.',
    Chart_FindMeNotFound: 'Hesabınız bu organizasyonda bulunamadı.',
    Chart_StatPeople: 'Kişi',
    Chart_StatMembers: 'Üyeler',
    Chart_StatGuests: 'Konuklar',
    Chart_StatDepts: 'Departman',
    Chart_ReportingLineAria: 'Raporlama hattı',
    Chart_BackToFullOrgTitle: 'Tam organizasyon şemasına dön',
    Chart_FullOrgLabel: 'Tam organizasyon',
    Chart_FocusOnPerson: '{name} kişisine odaklan',
    Chart_OrgChartAria: 'Organizasyon şeması',
    Chart_ExportNote_DrillLevel: 'Geçerli detaya inme düzeyi (bir düzey doğrudan bağlı çalışan)',
    Chart_ExportNote_PartialLevels: 'Yalnızca yüklenmiş düzeyleri içerir — daha derin düzeyleri eklemek için dışa aktarmadan önce Tümünü Genişlet\'i kullanın',
    Chart_AllowPopupsForPdf: 'PDF olarak dışa aktarmak için lütfen açılır pencerelere izin verin.',

    // ── Kişi kartı ──
    PersonCard_ProfileAria: 'Profil: {name}',
    PersonCard_CloseTitle: 'Kapat',
    PersonCard_CloseAria: 'Profili kapat',
    PersonCard_StatusDisabled: 'Devre Dışı',
    PersonCard_StatusGuest: 'Konuk',
    PersonCard_DirectReportSingular: '{count} doğrudan bağlı çalışan',
    PersonCard_DirectReportPlural: '{count} doğrudan bağlı çalışan',
    PersonCard_TotalSuffix: ' · toplam {total}',
    PersonCard_CopyEmailTitle: 'E-posta adresini kopyala',
    PersonCard_EmailCopiedAria: 'E-posta adresi kopyalandı',
    PersonCard_ReportsTo: 'Raporlandığı kişi',
    PersonCard_FocusOnPerson: '{name} kişisine odaklan',
    PersonCard_FocusOrgChartOnPerson: 'Organizasyon şemasını {name} kişisine odakla',
    PersonCard_DottedLine: 'Kesikli çizgi',
    PersonCard_DottedLineManager: 'Kesikli çizgi yöneticisi: {name}',
    PersonCard_DottedLineReport: 'Kesikli çizgi bağlısı: {name}',
    PersonCard_ChatButton: 'Sohbet',
    PersonCard_EmailButton: 'E-posta',
    PersonCard_FocusButton: 'Odaklan',
    PersonCard_FocusTitle: 'Organizasyon şemasını bu kişiye odakla',

    // ── Organizasyon düğümü kartı ──
    OrgNode_ViewProfile: '{name} kişisinin profilini görüntüle',
    OrgNode_FocusOrgChartOn: 'Organizasyon şemasını {name} kişisine odakla',
    OrgNode_Collapse: 'Daralt',
    OrgNode_Expand: 'Genişlet',
    OrgNode_DirectReportsSuffix: '{name} kişisinin doğrudan bağlı çalışanları',
    OrgNode_StatusDisabled: 'Devre Dışı',
    OrgNode_StatusGuest: 'Konuk',
    OrgNode_TotalReportsAcrossLevels: '{name} kişisinin altındaki tüm düzeylerde {count} kişi',

    // ── Detaya inme görünümü ──
    Drill_ReportingLineAria: 'Raporlama hattı',
    Drill_BackToTopTitle: 'Başa dön',
    Drill_BackToTopAria: 'Organizasyon şemasının başına dön',
    Drill_GoBackTo: '{name} kişisine geri dön',
    Drill_ViewProfileTitle: 'Profili görüntüle',
    Drill_ViewProfileAria: '{name} kişisinin profilini görüntüle',
    Drill_ProfileButton: 'Profil',
    Drill_LoadingLabel: 'Yükleniyor...',
    Drill_DirectReports: 'Doğrudan Bağlı Çalışanlar',
    Drill_DirectReportsOfAria: '{name} kişisinin doğrudan bağlı çalışanları',
    Drill_DirectReportsAria: 'Doğrudan bağlı çalışanlar',
    Drill_ViewPersonProfile: '{name} kişisinin profilini görüntüle',
    Drill_ShowPersonReports: '{name} kişisinin doğrudan bağlı çalışanlarını göster',
    Drill_NoDirectReports: 'Doğrudan bağlı çalışan yok',

    // ── Ayarlar paneli ──
    Settings_AlphabetFirstName: 'Ad',
    Settings_AlphabetLastName: 'Soyad',
    Settings_CardSizeSmall: 'Küçük — kompakt, daha fazla kart görünür',
    Settings_CardSizeMedium: 'Orta — dengeli',
    Settings_CardSizeLarge: 'Büyük — geniş, daha az kart',
    Settings_HeaderText: 'Tercihler',
    Settings_SaveButton: 'Kaydet',
    Settings_CancelButton: 'İptal',
    Settings_DiscardButton: 'Değişiklikleri Yoksay',
    Settings_SectionDirectory: 'Dizin',
    Settings_AlphabetFilterByLabel: 'Alfabetik Filtreleme Ölçütü',
    Settings_CardSizeLabel: 'Kart Boyutu',
    Settings_FontSizeLabel: 'Yazı Tipi Boyutu',
    Settings_SectionCardsAndFields: 'Kartlar ve Alanlar',
    Settings_ShowOnCardsLabel: 'Çalışan kartlarında göster:',
    Settings_EmailAddressLabel: 'E-posta adresi',
    Settings_PhoneNumberLabel: 'Telefon numarası',
    Settings_DepartmentLabel: 'Departman',
    Settings_OfficeLocationLabel: 'Ofis konumu',
    Settings_SectionOrgChart: 'Organizasyon Şeması',
    Settings_ManagerLevelsLabel: 'Bir kişiye odaklanıldığında gösterilecek yönetici düzeyi sayısı: {levels}',
    Settings_CompactCardsLabel: 'Kompakt kartlar',
    Settings_CompactCardsOn: 'Açık — daha küçük kartlar, aynı anda daha fazlası görünür',
    Settings_CompactCardsOff: 'Kapalı — standart boyut',
    Settings_Hint: 'Bu tercihler tarayıcınıza kaydedilir ve yalnızca sizin için geçerlidir. Şema teması, varsayılan görünüm ve düzen, SharePoint yöneticiniz tarafından yapılandırılır.',
    Settings_SectionDemoData: 'Demo Verisi',
    Settings_DatasetSizeLabel: 'Veri kümesi boyutu',
    Settings_PeopleCountSuffix: '{count} kişi',

    // ── Dışa aktarma (CSV / PDF) ──
    Export_ColumnName: 'Ad',
    Export_ColumnJobTitle: 'Unvan',
    Export_ColumnDepartment: 'Departman',
    Export_ColumnOffice: 'Ofis',
    Export_ColumnEmail: 'E-posta',
    Export_ColumnPhone: 'Telefon',
    Export_ColumnManager: 'Yönetici',
    Export_ColumnLevel: 'Düzey',
    Export_PdfDocumentTitle: 'Organizasyon Şeması',
    Export_PdfHeading: 'Organizasyon Şeması',
    Export_PdfRootLabel: 'Kök: {name}',
  };
});
