define([], function () {
  return {
    // ── Property pane: pane header / groups ──
    PropertyPane_HeaderDescription: 'Параметри Smart Org Chart',
    PropertyPane_Group_General: 'Загальні',
    PropertyPane_Group_Branding: 'Брендування',
    PropertyPane_Group_VisualStyle: 'Візуальний стиль',
    PropertyPane_Group_DataSource: 'Джерело даних',
    PropertyPane_Group_CustomAttributes: 'Настроювані атрибути',
    PropertyPane_Group_UserFilters: 'Фільтри користувачів',
    PropertyPane_Group_OrgChart: 'Організаційна схема',
    PropertyPane_Group_OrgChartFeatures: 'Функції організаційної схеми',
    PropertyPane_Group_Directory: 'Довідник',
    PropertyPane_Group_Demo: 'Демоверсія',

    // ── Property pane: General ──
    PropertyPane_DefaultView_Label: 'Подання за замовчуванням',

    // ── Property pane: Branding ──
    PropertyPane_AppTitle_Label: 'Назва застосунку',
    PropertyPane_AppTitle_Placeholder: 'Організаційна схема Contoso',
    PropertyPane_AppTitle_Description: 'Відображається на панелі заголовка поруч із назвою подання',
    PropertyPane_LogoUrl_Label: 'URL-адреса логотипа',
    PropertyPane_LogoUrl_Placeholder: 'https://contoso.sharepoint.com/sites/yoursite/SiteAssets/logo.png',
    PropertyPane_LogoUrl_Description: 'Повна URL-адреса зображення у форматі PNG/SVG/JPG. Порада: відкрийте файл зображення в браузері та скопіюйте URL-адресу з рядка адреси. URL-адреси спільного доступу «Копіювати посилання» не працюватимуть.',
    PropertyPane_DirectoryLabel_Label: 'Підпис подання «Довідник співробітників»',
    PropertyPane_OrgChartLabel_Label: 'Підпис подання «Організаційна схема»',
    PropertyPane_ViewLabel_Description: 'Залиште порожнім, щоб використати назву за замовчуванням, або введіть "[blank]", щоб повністю приховати мітку.',

    // ── Property pane: Visual Style ──
    PropertyPane_ChartTheme_Label: 'Тема схеми',
    PropertyPane_Theme_Modern: 'Сучасна — кольори відділів на білому тлі',
    PropertyPane_Theme_Minimal: 'Мінімальна — плоский дизайн і низька контрастність',
    PropertyPane_Theme_Corporate: 'Корпоративна — єдиний синій колір',
    PropertyPane_Theme_Dark: 'Темна — темно-синій фон',
    PropertyPane_Theme_Custom: 'Настроювана — виберіть власний колір',
    PropertyPane_AccentColor_Label: 'Настроюваний акцентний колір',
    PropertyPane_AccentColor_PickerAriaLabel: 'Засіб вибору акцентного кольору',
    PropertyPane_AccentColor_HexLabel: 'Hex',
    PropertyPane_AccentColor_HexAriaLabel: 'Шістнадцяткове значення акцентного кольору',
    PropertyPane_AccentColor_RgbLabel: 'RGB',
    PropertyPane_AccentColor_ChannelAriaLabel: 'Канал {name} (від 0 до 255)',
    PropertyPane_AccentColor_ContrastWithWhite: 'Контрастність із білим: {ratio}:1 ({passes})',
    PropertyPane_AccentColor_PassesAA: 'відповідає рівню AA',
    PropertyPane_AccentColor_LargeTextOnly: 'лише для великого тексту',
    PropertyPane_AccentColor_LowContrast: 'низька контрастність',
    PropertyPane_AccentColor_DarkTextNote: 'Для кращої читабельності текст на цьому тлі буде темним.',
    PropertyPane_AccentColor_DarkerShadeNote: 'Для кращої читабельності заголовки та посилання використовуватимуть темніший відтінок ({hex}).',
    PropertyPane_AccentColor_InvalidHex: '«{typed}» не є дійсним шістнадцятковим кольором. Використовуйте значення на кшталт #0078d4 або #07d.',
    PropertyPane_DefaultFontSize_Label: 'Розмір шрифту за замовчуванням',
    PropertyPane_FontSize_75: '75% — Дуже малий',
    PropertyPane_FontSize_85: '85% — Малий',
    PropertyPane_FontSize_100: '100% — Звичайний',
    PropertyPane_FontSize_115: '115% — Великий',
    PropertyPane_FontSize_130: '130% — Дуже великий',
    PropertyPane_FontSize_150: '150% — Надвеликий',
    PropertyPane_FontSize_175: '175% — Максимальний',
    PropertyPane_DefaultLayout_Label: 'Макет організаційної схеми за замовчуванням',
    PropertyPane_Layout_Drill: 'Поглиблений перегляд',
    PropertyPane_Layout_Vertical: 'Зверху вниз',
    PropertyPane_Layout_Horizontal: 'Зліва направо',

    // ── Property pane: Data Source ──
    PropertyPane_DataSource_Label: 'Звідки завантажувати дані користувачів і організації',
    PropertyPane_DataSource_Auto: 'Автоматично — Graph API із резервним переходом на пошук SharePoint',
    PropertyPane_DataSource_Graph: 'Graph API — актуальні дані Azure AD (без затримки на індексування)',
    PropertyPane_DataSource_Search: 'Пошук SharePoint — застаріла поведінка',
    PropertyPane_DataSource_Note: 'Рекомендовано використовувати Graph API. Він читає дані безпосередньо з Azure Active Directory, тому нові користувачі та зміни керівників відображаються негайно. Потребує затвердження дозволів Microsoft Graph у каталозі застосунків SharePoint.',

    // ── Property pane: Custom Attributes ──
    PropertyPane_CustomAttributes_Note: 'Настроювані атрибути потребують Microsoft Graph (джерело даних: Graph або Автоматично). Пошук SharePoint не має універсального способу читання атрибутів Entra ID.',
    PropertyPane_CustomAttributes_Heading: 'Керування настроюваними атрибутами',
    PropertyPane_CustomAttributes_Empty: 'Настроювані атрибути не налаштовано.',
    PropertyPane_CustomAttributes_AddButton: '+ Додати атрибут',
    PropertyPane_CustomAttributes_MaxTooltip: 'Максимум {max} настроюваних атрибутів',
    PropertyPane_CustomAttributes_FieldNameLabel: 'Ім’я атрибута',
    PropertyPane_CustomAttributes_FieldPlaceholder: 'наприклад, companyName',
    PropertyPane_CustomAttributes_FieldError: 'Використовуйте employeeId, companyName, city тощо або extensionAttribute1-15',
    PropertyPane_CustomAttributes_DisplayLabelLabel: 'Відображуваний підпис',
    PropertyPane_CustomAttributes_LabelPlaceholder: 'наприклад, Центр витрат',
    PropertyPane_CustomAttributes_RemoveTitle: 'Видалити атрибут',
    PropertyPane_CustomAttributes_RemoveAriaLabel: 'Видалити атрибут {ordinal}',
    PropertyPane_CustomAttributes_ShowInDirectory: 'Показувати в довіднику',
    PropertyPane_CustomAttributes_ShowInOrgChart: 'Показувати в організаційній схемі',

    // ── Property pane: User Filters ──
    PropertyPane_ExcludedAccounts_Label: 'Виключити облікові записи',
    PropertyPane_ExcludedAccounts_Placeholder: 'conf-room, noreply, admin@, Service Account',
    PropertyPane_ExcludedAccounts_Description: 'Слова або шаблони через кому (без урахування регістру). Будь-який користувач, чиє відображуване ім’я, електронна пошта або UPN містить один із них, буде приховано в усіх поданнях.',
    PropertyPane_RestrictTenant_Label: 'Показувати лише користувачів клієнта',
    PropertyPane_RestrictTenant_On: 'Увімкнено — приховує облікові записи із зовнішніми доменами електронної пошти (наприклад, gmail.com, hotmail.com)',
    PropertyPane_RestrictTenant_Off: 'Вимкнено — показуються всі користувачі незалежно від домену електронної пошти',
    PropertyPane_HideGuest_Label: 'Приховати гостьові облікові записи Azure AD',
    PropertyPane_HideGuest_On: 'Увімкнено — гостьові облікові записи приховано',
    PropertyPane_HideGuest_Off: 'Вимкнено — гостьові облікові записи видимі (позначені міткою «Гість»)',
    PropertyPane_HideDisabled_Label: 'Приховати вимкнені облікові записи',
    PropertyPane_HideDisabled_On: 'Увімкнено — облікові записи із заблокованим входом приховано',
    PropertyPane_HideDisabled_Off: 'Вимкнено — вимкнені облікові записи видимі (позначені міткою «Вимкнено»)',
    PropertyPane_HideDisabled_Note: 'Примітка. Визначення гостьових і вимкнених облікових записів потребує джерела даних Graph API. Пошук SharePoint не повертає цю інформацію, тому ці два фільтри (а також мітки «Гість»/«Вимкнено») не діють, якщо дані надходять із пошуку.',
    PropertyPane_HideNoJobTitle_Label: 'Приховати облікові записи без посади',
    PropertyPane_HideNoJobTitle_On: 'Увімкнено — облікові записи без посади приховано',
    PropertyPane_HideNoJobTitle_Off: 'Вимкнено — показуються всі облікові записи незалежно від посади',
    PropertyPane_HideNoDept_Label: 'Приховати облікові записи без відділу',
    PropertyPane_HideNoDept_On: 'Увімкнено — облікові записи без відділу приховано',
    PropertyPane_HideNoDept_Off: 'Вимкнено — показуються всі облікові записи незалежно від відділу',

    // ── Property pane: Org Chart ──
    PropertyPane_TopLevelUser_Label: 'Користувач верхнього рівня (UPN або електронна пошта)',
    PropertyPane_TopLevelUser_Placeholder: 'ceo@yourcompany.com',
    PropertyPane_TopLevelUser_Description: 'Особа, яка відображається в корені організаційної схеми',
    PropertyPane_LevelsBelow_Label: 'Кількість рівнів для завантаження нижче кореня',
    PropertyPane_DottedLine_Label: 'Атрибут керівника за пунктирною лінією',
    PropertyPane_DottedLine_Placeholder: 'extensionAttribute10',
    PropertyPane_DottedLine_Description: 'Необов’язково. Ім’я локального розширеного атрибута Azure AD (extensionAttribute1-15), що зберігає електронну пошту або UPN додаткового керівника за «пунктирною лінією». Зв’язки за пунктирною лінією відображаються на картках профілю. Потребує джерела даних Graph API.',
    PropertyPane_DefaultZoom_Label: 'Масштаб організаційної схеми за замовчуванням',
    PropertyPane_Zoom_Auto: 'За замовчуванням (автопідбір)',
    PropertyPane_Zoom_50: '50%',
    PropertyPane_Zoom_75: '75%',
    PropertyPane_Zoom_100: '100%',
    PropertyPane_Zoom_125: '125%',
    PropertyPane_Zoom_150: '150%',

    // ── Property pane: Org Chart Features ──
    PropertyPane_FeatureToggles_Note: 'Показати або приховати кнопки панелі інструментів у поданні організаційної схеми.',
    PropertyPane_FindMe_Label: 'Кнопка «Знайти мене»',
    PropertyPane_LayoutToggle_Label: 'Перемикач макета (поглиблений / вертикальний / горизонтальний)',
    PropertyPane_Stats_Label: 'Панель статистики організації',
    PropertyPane_DeptFilter_Label: 'Фільтр за відділом',
    PropertyPane_UserFilter_Label: 'Фільтр за типом користувача (учасники / гості)',
    PropertyPane_Visible: 'Видимий',
    PropertyPane_Hidden: 'Прихований',

    // ── Property pane: Directory ──
    PropertyPane_PageSize_Label: 'Максимум співробітників на сторінці',
    PropertyPane_PageSize_AriaLabel: 'Максимум співробітників на сторінці (від 10 до 200)',
    PropertyPane_PageSize_Note: 'Розмір картки, видимі поля та інші параметри відображення налаштовуються окремо для кожного користувача через значок налаштувань у застосунку.',

    // ── Property pane: Demo ──
    PropertyPane_UseDemoData_Label: 'Використовувати демонстраційні дані',
    PropertyPane_UseDemoData_On: 'Увімкнено — відображаються приклади співробітників',
    PropertyPane_UseDemoData_Off: 'Вимкнено — актуальні дані Microsoft 365',

    // ── Presence status labels ──
    Presence_Available: 'Доступний',
    Presence_Busy: 'Зайнятий',
    Presence_DoNotDisturb: 'Не турбувати',
    Presence_BeRightBack: 'Скоро повернуся',
    Presence_Away: 'Відійшов',
    Presence_Offline: 'Не в мережі',

    // ── Header / top bar ──
    Header_DirectoryLabel: 'Довідник співробітників',
    Header_OrgChartLabel: 'Організаційна схема',
    Header_SwitchToView: 'Перейти до {view}',
    Header_CompanyLogoAlt: 'Логотип компанії',
    Header_RefreshingAria: 'Оновлення даних',
    Header_RefreshAria: 'Оновити дані',
    Header_RefreshTitle: 'Оновити дані (останнє оновлення: {when})',
    Header_NotLoadedYet: 'ще не завантажено',
    Header_JustNow: 'щойно',
    Header_MinutesAgo: '{mins} хв тому',
    Header_HoursAgo: '{hours} год тому',
    Header_PreferencesTitle: 'Параметри',
    Header_PreferencesAria: 'Відкрити панель параметрів',

    // ── Employee Directory ──
    Directory_LoadingLabel: 'Завантаження співробітників...',
    Directory_LoadFailedFallback: 'Переконайтеся, що веб-частина має дозвіл User.Read.All.',
    Directory_LoadFailedPrefix: 'Не вдалося завантажити співробітників. {detail}',
    Directory_AllDepartments: 'Усі відділи',
    Directory_AllOffices: 'Усі офіси',
    Directory_StatusDisabled: 'Вимкнено',
    Directory_StatusGuest: 'Гість',
    Directory_PresenceStatus: 'Стан: {status}',
    Directory_ChatInTeams: 'Чат у Teams',
    Directory_ChatWithInTeams: 'Написати {name} у Teams',
    Directory_ManagesCount: 'Керує {direct}',
    Directory_ManagesCountWithTotal: 'Керує {direct} (всього {total})',
    Directory_ReportsCountWithTotal: '{direct} (всього {total})',
    Directory_ColumnName: 'Ім’я',
    Directory_ColumnJobTitle: 'Посада',
    Directory_ColumnDepartment: 'Відділ',
    Directory_ColumnOffice: 'Офіс',
    Directory_ColumnEmail: 'Електронна пошта',
    Directory_ColumnPhone: 'Телефон',
    Directory_ColumnReports: 'Підлеглі',
    Directory_ColumnChat: 'Чат',
    Directory_PrevPage: 'Назад',
    Directory_NextPage: 'Далі',
    Directory_PreviousPageAria: 'Попередня сторінка',
    Directory_NextPageAria: 'Наступна сторінка',
    Directory_SearchPlaceholder: 'Пошук за ім’ям, посадою, електронною поштою або відділом...',
    Directory_SearchAria: 'Пошук людей',
    Directory_FilterByDepartmentAria: 'Фільтр за відділом',
    Directory_FilterByOfficeAria: 'Фільтр за офісом',
    Directory_ClearSearchTitle: 'Очистити пошук і всі фільтри',
    Directory_ClearButton: 'Очистити',
    Directory_ClearFiltersButton: 'Очистити фільтри',
    Directory_ExportCsvTitle: 'Експортувати всі відфільтровані результати у файл CSV (відкривається в Excel)',
    Directory_ExportCsvButton: 'Експортувати CSV',
    Directory_ViewModeAria: 'Режим перегляду',
    Directory_CardViewTitle: 'Перегляд картками',
    Directory_ListViewTitle: 'Перегляд списком',
    Directory_AlphabetFilterAria: 'Фільтр за алфавітом',
    Directory_ShowAllTitle: 'Показати всі',
    Directory_OtherLettersTitle: 'Фільтр за іменами, що починаються з цифри чи іншого символу',
    Directory_FilterByLetterTitle: 'Фільтр за літерою {letter}',
    Directory_ResultCountSingular: 'особа',
    Directory_ResultCountPlural: 'осіб',
    Directory_PageOf: ' · сторінка {page} з {totalPages}',
    Directory_FilterActiveSingular: 'Активний {count} фільтр',
    Directory_FilterActivePlural: 'Активні фільтри: {count}',
    Directory_NoResults: 'Людей не знайдено',
    Directory_PaginationAria: 'Розбиття на сторінки',

    // ── Org chart toolbar / shared chart chrome ──
    Chart_Layout_Drill: 'Поглиблений перегляд',
    Chart_Layout_Vertical: 'Зверху вниз',
    Chart_Layout_Horizontal: 'Зліва направо',
    Chart_SearchPlaceholder: 'Пошук людей...',
    Chart_SearchAria: 'Пошук людей',
    Chart_MatchSingular: 'збіг у структурі',
    Chart_MatchPlural: 'збіги у структурі',
    Chart_ResultsListAria: 'Люди',
    Chart_ExpandAll: 'Розгорнути все',
    Chart_CollapseAll: 'Згорнути все',
    Chart_Expanding: 'Розгортання…',
    Chart_Loading: 'Завантаження…',
    Chart_FindMeTitle: 'Знайти мене в організаційній схемі',
    Chart_ViewLayoutButton: 'Перегляд',
    Chart_ViewLayoutTitle: 'Змінити макет перегляду',
    Chart_ViewLayoutPanelTitle: 'Макет перегляду',
    Chart_StatsSummaryTitle: 'Зведена статистика організації',
    Chart_FilterByDepartmentTitle: 'Фільтр за відділом',
    Chart_FilterByDepartmentWithCountAria: 'Фільтр за відділом (вибрано: {count})',
    Chart_FilterByDepartmentPanelTitle: 'Фільтр за відділом',
    Chart_ClearAllFilters: 'Очистити всі фільтри',
    Chart_FilterUserTypesTitle: 'Фільтр за типами користувачів',
    Chart_DownloadPdfTitle: 'Завантажити як PDF',
    Chart_DownloadCsvTitle: 'Завантажити як таблицю CSV',
    Chart_ResetRootTitle: 'Скинути до кореня за замовчуванням',
    Chart_ViewFromPersonPlaceholder: 'Перегляд від особи…',
    Chart_ViewFromPersonAria: 'Переглянути організаційну схему від особи',
    Chart_ZoomOutTitle: 'Зменшити масштаб',
    Chart_ZoomInTitle: 'Збільшити масштаб',
    Chart_ZoomResetTitle: 'Скинути масштаб',
    Chart_ShowInChartAria: 'Показати на схемі',
    Chart_ShowInChartTitle: 'Показати на схемі',
    Chart_FilterMembers: 'Звичайні учасники',
    Chart_FilterGuests: 'Гостьові користувачі',
    Chart_FilterDisabled: 'Вимкнені облікові записи',
    Chart_SetupTitle: 'Налаштування організаційної схеми',
    Chart_SetupSubtitle: 'Щоб почати, введіть електронну пошту або UPN особи верхнього рівня.',
    Chart_SetupPlaceholder: 'ceo@company.com',
    Chart_SetupInputAria: 'Електронна пошта або UPN особи верхнього рівня',
    Chart_SetupLoadButton: 'Завантажити',
    Chart_SetupHint: 'Це також можна налаштувати постійно в параметрах веб-частини (для адміністраторів).',
    Chart_BuildingLabel: 'Побудова організаційної схеми...',
    Chart_RetryButton: 'Повторити',
    Chart_NotFoundFromSetup: 'Користувача «{identifier}» не знайдено.',
    Chart_NotFoundWithSettings: 'Користувача «{identifier}» не знайдено. Перевірте UPN або електронну пошту в параметрах.',
    Chart_LoadFailedGeneric: 'Не вдалося завантажити організаційну схему.{detail}',
    Chart_LoadFailedPermissions: ' Перевірте дозволи.',
    Chart_LoadFailedForPerson: 'Не вдалося завантажити організаційну схему для цієї особи.',
    Chart_FindMeNotFound: 'Ваш обліковий запис не знайдено в цій організації.',
    Chart_StatPeople: 'Люди',
    Chart_StatMembers: 'Учасники',
    Chart_StatGuests: 'Гості',
    Chart_StatDepts: 'Відділи',
    Chart_ReportingLineAria: 'Лінія підпорядкування',
    Chart_BackToFullOrgTitle: 'Повернутися до повної організаційної схеми',
    Chart_FullOrgLabel: 'Уся організація',
    Chart_FocusOnPerson: 'Зосередитися на {name}',
    Chart_OrgChartAria: 'Організаційна схема',
    Chart_ExportNote_DrillLevel: 'Поточний рівень поглибленого перегляду (один рівень прямих підлеглих)',
    Chart_ExportNote_PartialLevels: 'Включає лише завантажені рівні — щоб додати глибші рівні, перед експортом натисніть «Розгорнути все»',
    Chart_AllowPopupsForPdf: 'Дозвольте спливаючі вікна, щоб експортувати PDF.',

    // ── Person card ──
    PersonCard_ProfileAria: 'Профіль: {name}',
    PersonCard_CloseTitle: 'Закрити',
    PersonCard_CloseAria: 'Закрити профіль',
    PersonCard_StatusDisabled: 'Вимкнено',
    PersonCard_StatusGuest: 'Гість',
    PersonCard_DirectReportSingular: '{count} прямий підлеглий',
    PersonCard_DirectReportPlural: '{count} прямих підлеглих',
    PersonCard_TotalSuffix: ' · всього {total}',
    PersonCard_CopyEmailTitle: 'Копіювати електронну адресу',
    PersonCard_EmailCopiedAria: 'Електронну адресу скопійовано',
    PersonCard_ReportsTo: 'Підпорядковується',
    PersonCard_FocusOnPerson: 'Зосередитися на {name}',
    PersonCard_FocusOrgChartOnPerson: 'Зосередити організаційну схему на {name}',
    PersonCard_DottedLine: 'Пунктирна лінія',
    PersonCard_DottedLineManager: 'Керівник за пунктирною лінією: {name}',
    PersonCard_DottedLineReport: 'Підлеглий за пунктирною лінією: {name}',
    PersonCard_ChatButton: 'Чат',
    PersonCard_EmailButton: 'Пошта',
    PersonCard_FocusButton: 'Фокус',
    PersonCard_FocusTitle: 'Зосередити організаційну схему на цій особі',

    // ── Org node card ──
    OrgNode_ViewProfile: 'Переглянути профіль {name}',
    OrgNode_FocusOrgChartOn: 'Зосередити організаційну схему на {name}',
    OrgNode_Collapse: 'Згорнути',
    OrgNode_Expand: 'Розгорнути',
    OrgNode_DirectReportsSuffix: 'прямі підлеглі {name}',
    OrgNode_StatusDisabled: 'Вимкнено',
    OrgNode_StatusGuest: 'Гість',
    OrgNode_TotalReportsAcrossLevels: '{count} осіб на всіх рівнях нижче {name}',

    // ── Drill view ──
    Drill_ReportingLineAria: 'Лінія підпорядкування',
    Drill_BackToTopTitle: 'Повернутися нагору',
    Drill_BackToTopAria: 'Повернутися на початок організаційної схеми',
    Drill_GoBackTo: 'Повернутися до {name}',
    Drill_ViewProfileTitle: 'Переглянути профіль',
    Drill_ViewProfileAria: 'Переглянути профіль {name}',
    Drill_ProfileButton: 'Профіль',
    Drill_LoadingLabel: 'Завантаження...',
    Drill_DirectReports: 'Прямі підлеглі',
    Drill_DirectReportsOfAria: 'Прямі підлеглі {name}',
    Drill_DirectReportsAria: 'Прямі підлеглі',
    Drill_ViewPersonProfile: 'Переглянути профіль {name}',
    Drill_ShowPersonReports: 'Показати прямих підлеглих {name}',
    Drill_NoDirectReports: 'Немає прямих підлеглих',

    // ── Settings panel ──
    Settings_AlphabetFirstName: 'Ім’я',
    Settings_AlphabetLastName: 'Прізвище',
    Settings_CardSizeSmall: 'Малий — компактний, більше карток на екрані',
    Settings_CardSizeMedium: 'Середній — збалансований',
    Settings_CardSizeLarge: 'Великий — просторий, менше карток на екрані',
    Settings_HeaderText: 'Параметри',
    Settings_SaveButton: 'Зберегти',
    Settings_CancelButton: 'Скасувати',
    Settings_DiscardButton: 'Відхилити зміни',
    Settings_SectionDirectory: 'Довідник',
    Settings_AlphabetFilterByLabel: 'Фільтр за алфавітом за',
    Settings_CardSizeLabel: 'Розмір картки',
    Settings_FontSizeLabel: 'Розмір шрифту',
    Settings_SectionCardsAndFields: 'Картки та поля',
    Settings_ShowOnCardsLabel: 'Показувати на картках співробітників:',
    Settings_EmailAddressLabel: 'Електронна адреса',
    Settings_PhoneNumberLabel: 'Номер телефону',
    Settings_DepartmentLabel: 'Відділ',
    Settings_OfficeLocationLabel: 'Розташування офісу',
    Settings_SectionOrgChart: 'Організаційна схема',
    Settings_ManagerLevelsLabel: 'Кількість рівнів керівників при фокусуванні на особі: {levels}',
    Settings_CompactCardsLabel: 'Компактні картки',
    Settings_CompactCardsOn: 'Увімкнено — менші картки, більше видно одночасно',
    Settings_CompactCardsOff: 'Вимкнено — стандартний розмір',
    Settings_Hint: 'Ці параметри зберігаються у вашому браузері та застосовуються лише до вас. Тему схеми, подання за замовчуванням і макет налаштовує адміністратор SharePoint.',
    Settings_SectionDemoData: 'Демонстраційні дані',
    Settings_DatasetSizeLabel: 'Розмір набору даних',
    Settings_PeopleCountSuffix: '{count} осіб',

    // ── Export (CSV / PDF) ──
    Export_ColumnName: 'Ім’я',
    Export_ColumnJobTitle: 'Посада',
    Export_ColumnDepartment: 'Відділ',
    Export_ColumnOffice: 'Офіс',
    Export_ColumnEmail: 'Електронна пошта',
    Export_ColumnPhone: 'Телефон',
    Export_ColumnManager: 'Керівник',
    Export_ColumnLevel: 'Рівень',
    Export_PdfDocumentTitle: 'Організаційна схема',
    Export_PdfHeading: 'Організаційна схема',
    Export_PdfRootLabel: 'Корінь: {name}',
  };
});
