define([], function () {
  return {
    // ── Property pane: pane header / groups ──
    PropertyPane_HeaderDescription: 'Cài đặt Smart Org Chart',
    PropertyPane_Group_General: 'Chung',
    PropertyPane_Group_Branding: 'Thương hiệu',
    PropertyPane_Group_VisualStyle: 'Kiểu hiển thị',
    PropertyPane_Group_DataSource: 'Nguồn dữ liệu',
    PropertyPane_Group_CustomAttributes: 'Thuộc tính tùy chỉnh',
    PropertyPane_Group_UserFilters: 'Bộ lọc người dùng',
    PropertyPane_Group_OrgChart: 'Sơ đồ tổ chức',
    PropertyPane_Group_OrgChartFeatures: 'Tính năng sơ đồ tổ chức',
    PropertyPane_Group_Directory: 'Danh bạ',
    PropertyPane_Group_Demo: 'Demo',

    // ── Property pane: General ──
    PropertyPane_DefaultView_Label: 'Chế độ xem mặc định',

    // ── Property pane: Branding ──
    PropertyPane_AppTitle_Label: 'Tiêu đề ứng dụng',
    PropertyPane_AppTitle_Placeholder: 'Sơ đồ tổ chức Contoso',
    PropertyPane_AppTitle_Description: 'Hiển thị trên thanh tiêu đề cùng với tên chế độ xem',
    PropertyPane_LogoUrl_Label: 'URL logo',
    PropertyPane_LogoUrl_Placeholder: 'https://contoso.sharepoint.com/sites/yoursite/SiteAssets/logo.png',
    PropertyPane_LogoUrl_Description: 'URL đầy đủ đến hình ảnh PNG/SVG/JPG. Mẹo: mở tệp hình ảnh trong trình duyệt và sao chép URL trên thanh địa chỉ. URL chia sẻ dạng "Sao chép liên kết" sẽ không hoạt động.',
    PropertyPane_DirectoryLabel_Label: 'Nhãn chế độ xem Danh bạ nhân viên',
    PropertyPane_OrgChartLabel_Label: 'Nhãn chế độ xem Sơ đồ tổ chức',
    PropertyPane_ViewLabel_Description: 'Để trống để sử dụng tên mặc định, hoặc nhập "[blank]" để ẩn hoàn toàn nhãn.',

    // ── Property pane: Visual Style ──
    PropertyPane_ChartTheme_Label: 'Chủ đề sơ đồ',
    PropertyPane_Theme_Modern: 'Hiện đại — màu phòng ban trên nền trắng',
    PropertyPane_Theme_Minimal: 'Tối giản — phẳng & tương phản thấp',
    PropertyPane_Theme_Corporate: 'Doanh nghiệp — xanh dương đồng nhất',
    PropertyPane_Theme_Dark: 'Tối — nền xanh navy đậm',
    PropertyPane_Theme_Custom: 'Tùy chỉnh — chọn màu riêng của bạn',
    PropertyPane_AccentColor_Label: 'Màu nhấn tùy chỉnh',
    PropertyPane_AccentColor_PickerAriaLabel: 'Bộ chọn màu nhấn',
    PropertyPane_AccentColor_HexLabel: 'Hex',
    PropertyPane_AccentColor_HexAriaLabel: 'Giá trị hex của màu nhấn',
    PropertyPane_AccentColor_RgbLabel: 'RGB',
    PropertyPane_AccentColor_ChannelAriaLabel: 'Kênh {name} (0 đến 255)',
    PropertyPane_AccentColor_ContrastWithWhite: 'Độ tương phản với màu trắng: {ratio}:1 ({passes})',
    PropertyPane_AccentColor_PassesAA: 'đạt chuẩn AA',
    PropertyPane_AccentColor_LargeTextOnly: 'chỉ văn bản lớn',
    PropertyPane_AccentColor_LowContrast: 'tương phản thấp',
    PropertyPane_AccentColor_DarkTextNote: 'Văn bản trên màu này sẽ dùng chữ tối để dễ đọc hơn.',
    PropertyPane_AccentColor_DarkerShadeNote: 'Tiêu đề và liên kết sẽ dùng sắc độ tối hơn ({hex}) để dễ đọc hơn.',
    PropertyPane_AccentColor_InvalidHex: '"{typed}" không phải là mã màu hex hợp lệ. Hãy dùng giá trị như #0078d4 hoặc #07d.',
    PropertyPane_DefaultFontSize_Label: 'Cỡ chữ mặc định',
    PropertyPane_FontSize_75: '75% — Rất nhỏ',
    PropertyPane_FontSize_85: '85% — Nhỏ',
    PropertyPane_FontSize_100: '100% — Bình thường',
    PropertyPane_FontSize_115: '115% — Lớn',
    PropertyPane_FontSize_130: '130% — Rất lớn',
    PropertyPane_FontSize_150: '150% — XXL',
    PropertyPane_FontSize_175: '175% — XXXL',
    PropertyPane_DefaultLayout_Label: 'Bố cục sơ đồ tổ chức mặc định',
    PropertyPane_Layout_Drill: 'Duyệt theo cấp',
    PropertyPane_Layout_Vertical: 'Từ trên xuống',
    PropertyPane_Layout_Horizontal: 'Từ trái sang phải',

    // ── Property pane: Data Source ──
    PropertyPane_DataSource_Label: 'Nguồn tải dữ liệu người dùng & tổ chức',
    PropertyPane_DataSource_Auto: 'Tự động — Graph API, dự phòng bằng SharePoint Search',
    PropertyPane_DataSource_Graph: 'Graph API — dữ liệu Azure AD trực tiếp (không có độ trễ lập chỉ mục)',
    PropertyPane_DataSource_Search: 'SharePoint Search — hành vi cũ',
    PropertyPane_DataSource_Note: 'Nên sử dụng Graph API. Nó đọc trực tiếp từ Azure Active Directory nên người dùng mới và thay đổi người quản lý sẽ xuất hiện ngay lập tức. Yêu cầu quyền Microsoft Graph phải được phê duyệt trong SharePoint App Catalog.',

    // ── Property pane: Custom Attributes ──
    PropertyPane_CustomAttributes_Note: 'Thuộc tính tùy chỉnh yêu cầu Microsoft Graph (Nguồn dữ liệu: Graph hoặc Auto). SharePoint Search không có cách chung để đọc thuộc tính Entra ID.',
    PropertyPane_CustomAttributes_Heading: 'Quản lý thuộc tính tùy chỉnh',
    PropertyPane_CustomAttributes_Empty: 'Chưa cấu hình thuộc tính tùy chỉnh nào.',
    PropertyPane_CustomAttributes_AddButton: '+ Thêm thuộc tính',
    PropertyPane_CustomAttributes_MaxTooltip: 'Tối đa {max} thuộc tính tùy chỉnh',
    PropertyPane_CustomAttributes_FieldNameLabel: 'Tên thuộc tính',
    PropertyPane_CustomAttributes_FieldPlaceholder: 'ví dụ: companyName',
    PropertyPane_CustomAttributes_FieldError: 'Sử dụng employeeId, companyName, city, ... hoặc extensionAttribute1-15',
    PropertyPane_CustomAttributes_DisplayLabelLabel: 'Nhãn hiển thị',
    PropertyPane_CustomAttributes_LabelPlaceholder: 'ví dụ: Trung tâm chi phí',
    PropertyPane_CustomAttributes_RemoveTitle: 'Xóa thuộc tính',
    PropertyPane_CustomAttributes_RemoveAriaLabel: 'Xóa thuộc tính {ordinal}',
    PropertyPane_CustomAttributes_ShowInDirectory: 'Hiển thị trong Danh bạ',
    PropertyPane_CustomAttributes_ShowInOrgChart: 'Hiển thị trong Sơ đồ tổ chức',

    // ── Property pane: User Filters ──
    PropertyPane_ExcludedAccounts_Label: 'Loại trừ tài khoản',
    PropertyPane_ExcludedAccounts_Placeholder: 'conf-room, noreply, admin@, Service Account',
    PropertyPane_ExcludedAccounts_Description: 'Các từ hoặc mẫu cách nhau bằng dấu phẩy (không phân biệt hoa thường). Bất kỳ người dùng nào có tên hiển thị, email hoặc UPN chứa một trong các từ này sẽ bị ẩn khỏi tất cả chế độ xem.',
    PropertyPane_RestrictTenant_Label: 'Chỉ hiển thị người dùng trong tenant',
    PropertyPane_RestrictTenant_On: 'Bật — ẩn các tài khoản có miền email bên ngoài (ví dụ: gmail.com, hotmail.com)',
    PropertyPane_RestrictTenant_Off: 'Tắt — hiển thị tất cả người dùng bất kể miền email',
    PropertyPane_HideGuest_Label: 'Ẩn tài khoản khách của Azure AD',
    PropertyPane_HideGuest_On: 'Bật — ẩn tài khoản khách',
    PropertyPane_HideGuest_Off: 'Tắt — hiển thị tài khoản khách (kèm huy hiệu Khách)',
    PropertyPane_HideDisabled_Label: 'Ẩn tài khoản bị vô hiệu hóa',
    PropertyPane_HideDisabled_On: 'Bật — ẩn các tài khoản bị chặn đăng nhập',
    PropertyPane_HideDisabled_Off: 'Tắt — hiển thị tài khoản bị vô hiệu hóa (kèm huy hiệu Đã vô hiệu hóa)',
    PropertyPane_HideDisabled_Note: 'Lưu ý: việc phát hiện tài khoản khách và tài khoản bị vô hiệu hóa yêu cầu nguồn dữ liệu Graph API. SharePoint Search không trả về thông tin này, do đó hai bộ lọc này (và các huy hiệu Khách/Đã vô hiệu hóa) sẽ không có tác dụng khi dữ liệu đến từ Search.',
    PropertyPane_HideNoJobTitle_Label: 'Ẩn tài khoản không có chức danh',
    PropertyPane_HideNoJobTitle_On: 'Bật — ẩn các tài khoản không có chức danh',
    PropertyPane_HideNoJobTitle_Off: 'Tắt — hiển thị tất cả tài khoản bất kể chức danh',
    PropertyPane_HideNoDept_Label: 'Ẩn tài khoản không có phòng ban',
    PropertyPane_HideNoDept_On: 'Bật — ẩn các tài khoản không có phòng ban',
    PropertyPane_HideNoDept_Off: 'Tắt — hiển thị tất cả tài khoản bất kể phòng ban',

    // ── Property pane: Org Chart ──
    PropertyPane_TopLevelUser_Label: 'Người dùng cấp cao nhất (UPN hoặc Email)',
    PropertyPane_TopLevelUser_Placeholder: 'ceo@yourcompany.com',
    PropertyPane_TopLevelUser_Description: 'Người được hiển thị ở gốc của sơ đồ tổ chức',
    PropertyPane_LevelsBelow_Label: 'Số cấp cần tải bên dưới gốc',
    PropertyPane_DottedLine_Label: 'Thuộc tính người quản lý gián tiếp (đường chấm)',
    PropertyPane_DottedLine_Placeholder: 'extensionAttribute10',
    PropertyPane_DottedLine_Description: 'Tùy chọn. Tên của thuộc tính mở rộng Azure AD tại chỗ (extensionAttribute1-15) lưu trữ email hoặc UPN của người quản lý phụ theo "đường chấm". Mối quan hệ đường chấm sẽ hiển thị trên thẻ hồ sơ. Yêu cầu nguồn dữ liệu Graph API.',
    PropertyPane_DefaultZoom_Label: 'Mức thu phóng sơ đồ tổ chức mặc định',
    PropertyPane_Zoom_Auto: 'Mặc định (Tự động vừa khít)',
    PropertyPane_Zoom_50: '50%',
    PropertyPane_Zoom_75: '75%',
    PropertyPane_Zoom_100: '100%',
    PropertyPane_Zoom_125: '125%',
    PropertyPane_Zoom_150: '150%',

    // ── Property pane: Org Chart Features ──
    PropertyPane_FeatureToggles_Note: 'Hiển thị hoặc ẩn các nút thanh công cụ trong chế độ xem sơ đồ tổ chức.',
    PropertyPane_FindMe_Label: 'Nút Tìm tôi',
    PropertyPane_LayoutToggle_Label: 'Chuyển đổi bố cục (theo cấp / dọc / ngang)',
    PropertyPane_Stats_Label: 'Thanh thống kê tổ chức',
    PropertyPane_DeptFilter_Label: 'Bộ lọc phòng ban',
    PropertyPane_UserFilter_Label: 'Bộ lọc loại người dùng (thành viên / khách)',
    PropertyPane_Visible: 'Hiển thị',
    PropertyPane_Hidden: 'Ẩn',

    // ── Property pane: Directory ──
    PropertyPane_PageSize_Label: 'Số nhân viên tối đa mỗi trang',
    PropertyPane_PageSize_AriaLabel: 'Số nhân viên tối đa mỗi trang (10 đến 200)',
    PropertyPane_PageSize_Note: 'Kích thước thẻ, các trường hiển thị và các tùy chọn hiển thị khác được thiết lập riêng cho từng người dùng qua biểu tượng bánh răng Cài đặt trong ứng dụng.',

    // ── Property pane: Demo ──
    PropertyPane_UseDemoData_Label: 'Sử dụng dữ liệu demo',
    PropertyPane_UseDemoData_On: 'Bật — hiển thị nhân viên mẫu',
    PropertyPane_UseDemoData_Off: 'Tắt — dữ liệu Microsoft 365 trực tiếp',

    // ── Presence status labels ──
    Presence_Available: 'Sẵn sàng',
    Presence_Busy: 'Bận',
    Presence_DoNotDisturb: 'Không làm phiền',
    Presence_BeRightBack: 'Sẽ quay lại ngay',
    Presence_Away: 'Vắng mặt',
    Presence_Offline: 'Ngoại tuyến',

    // ── Header / top bar ──
    Header_DirectoryLabel: 'Danh bạ nhân viên',
    Header_OrgChartLabel: 'Sơ đồ tổ chức',
    Header_SwitchToView: 'Chuyển sang {view}',
    Header_CompanyLogoAlt: 'Logo công ty',
    Header_RefreshingAria: 'Đang làm mới dữ liệu',
    Header_RefreshAria: 'Làm mới dữ liệu',
    Header_RefreshTitle: 'Làm mới dữ liệu (cập nhật lần cuối {when})',
    Header_NotLoadedYet: 'chưa tải',
    Header_JustNow: 'vừa xong',
    Header_MinutesAgo: '{mins} phút trước',
    Header_HoursAgo: '{hours} giờ trước',
    Header_PreferencesTitle: 'Tùy chọn',
    Header_PreferencesAria: 'Mở bảng tùy chọn',

    // ── Employee Directory ──
    Directory_LoadingLabel: 'Đang tải nhân viên...',
    Directory_LoadFailedFallback: 'Đảm bảo web part có quyền User.Read.All.',
    Directory_LoadFailedPrefix: 'Không thể tải danh sách nhân viên. {detail}',
    Directory_AllDepartments: 'Tất cả phòng ban',
    Directory_AllOffices: 'Tất cả văn phòng',
    Directory_StatusDisabled: 'Đã vô hiệu hóa',
    Directory_StatusGuest: 'Khách',
    Directory_PresenceStatus: 'Trạng thái: {status}',
    Directory_ChatInTeams: 'Trò chuyện trong Teams',
    Directory_ChatWithInTeams: 'Trò chuyện với {name} trong Teams',
    Directory_ManagesCount: 'Quản lý {direct}',
    Directory_ManagesCountWithTotal: 'Quản lý {direct} (tổng {total})',
    Directory_ReportsCountWithTotal: '{direct} (tổng {total})',
    Directory_ColumnName: 'Tên',
    Directory_ColumnJobTitle: 'Chức danh',
    Directory_ColumnDepartment: 'Phòng ban',
    Directory_ColumnOffice: 'Văn phòng',
    Directory_ColumnEmail: 'Email',
    Directory_ColumnPhone: 'Điện thoại',
    Directory_ColumnReports: 'Cấp dưới',
    Directory_ColumnChat: 'Trò chuyện',
    Directory_PrevPage: 'Trước',
    Directory_NextPage: 'Sau',
    Directory_PreviousPageAria: 'Trang trước',
    Directory_NextPageAria: 'Trang sau',
    Directory_SearchPlaceholder: 'Tìm theo tên, chức danh, email hoặc phòng ban...',
    Directory_SearchAria: 'Tìm kiếm người dùng',
    Directory_FilterByDepartmentAria: 'Lọc theo phòng ban',
    Directory_FilterByOfficeAria: 'Lọc theo văn phòng',
    Directory_ClearSearchTitle: 'Xóa tìm kiếm và tất cả bộ lọc',
    Directory_ClearButton: 'Xóa',
    Directory_ClearFiltersButton: 'Xóa bộ lọc',
    Directory_ExportCsvTitle: 'Xuất tất cả kết quả đã lọc sang tệp CSV (mở bằng Excel)',
    Directory_ExportCsvButton: 'Xuất CSV',
    Directory_ViewModeAria: 'Chế độ xem',
    Directory_CardViewTitle: 'Xem dạng thẻ',
    Directory_ListViewTitle: 'Xem dạng danh sách',
    Directory_AlphabetFilterAria: 'Bộ lọc theo chữ cái',
    Directory_ShowAllTitle: 'Hiển thị tất cả',
    Directory_OtherLettersTitle: 'Lọc theo tên bắt đầu bằng số hoặc ký tự khác',
    Directory_FilterByLetterTitle: 'Lọc theo {letter}',
    Directory_ResultCountSingular: 'người',
    Directory_ResultCountPlural: 'người',
    Directory_PageOf: ' · trang {page}/{totalPages}',
    Directory_FilterActiveSingular: '{count} bộ lọc đang áp dụng',
    Directory_FilterActivePlural: '{count} bộ lọc đang áp dụng',
    Directory_NoResults: 'Không tìm thấy người nào',
    Directory_PaginationAria: 'Phân trang',

    // ── Org chart toolbar / shared chart chrome ──
    Chart_Layout_Drill: 'Duyệt theo cấp',
    Chart_Layout_Vertical: 'Từ trên xuống',
    Chart_Layout_Horizontal: 'Từ trái sang phải',
    Chart_SearchPlaceholder: 'Tìm kiếm người dùng...',
    Chart_SearchAria: 'Tìm kiếm người dùng',
    Chart_MatchSingular: 'kết quả khớp trong cây',
    Chart_MatchPlural: 'kết quả khớp trong cây',
    Chart_ResultsListAria: 'Danh sách người dùng',
    Chart_ExpandAll: 'Mở rộng tất cả',
    Chart_CollapseAll: 'Thu gọn tất cả',
    Chart_Expanding: 'Đang mở rộng…',
    Chart_Loading: 'Đang tải…',
    Chart_FindMeTitle: 'Tìm tôi trong sơ đồ tổ chức',
    Chart_ViewLayoutButton: 'Xem',
    Chart_ViewLayoutTitle: 'Chuyển đổi bố cục xem',
    Chart_ViewLayoutPanelTitle: 'Bố cục xem',
    Chart_StatsSummaryTitle: 'Tóm tắt thống kê tổ chức',
    Chart_FilterByDepartmentTitle: 'Lọc theo phòng ban',
    Chart_FilterByDepartmentWithCountAria: 'Lọc theo phòng ban (đã chọn {count})',
    Chart_FilterByDepartmentPanelTitle: 'Lọc theo phòng ban',
    Chart_ClearAllFilters: 'Xóa tất cả bộ lọc',
    Chart_FilterUserTypesTitle: 'Lọc theo loại người dùng',
    Chart_DownloadPdfTitle: 'Tải xuống dạng PDF',
    Chart_DownloadCsvTitle: 'Tải xuống dạng bảng tính CSV',
    Chart_ResetRootTitle: 'Đặt lại về gốc mặc định',
    Chart_ViewFromPersonPlaceholder: 'Xem từ người…',
    Chart_ViewFromPersonAria: 'Xem sơ đồ tổ chức từ một người',
    Chart_ZoomOutTitle: 'Thu nhỏ',
    Chart_ZoomInTitle: 'Phóng to',
    Chart_ZoomResetTitle: 'Đặt lại thu phóng',
    Chart_ShowInChartAria: 'Hiển thị trong sơ đồ',
    Chart_ShowInChartTitle: 'Hiển thị trong sơ đồ',
    Chart_FilterMembers: 'Thành viên chính thức',
    Chart_FilterGuests: 'Người dùng khách',
    Chart_FilterDisabled: 'Tài khoản đã vô hiệu hóa',
    Chart_SetupTitle: 'Thiết lập sơ đồ tổ chức',
    Chart_SetupSubtitle: 'Nhập email hoặc UPN của người ở cấp cao nhất để bắt đầu.',
    Chart_SetupPlaceholder: 'ceo@company.com',
    Chart_SetupInputAria: 'Email hoặc UPN của người ở cấp cao nhất',
    Chart_SetupLoadButton: 'Tải',
    Chart_SetupHint: 'Bạn cũng có thể thiết lập cố định trong cài đặt web part (dành cho quản trị viên).',
    Chart_BuildingLabel: 'Đang xây dựng sơ đồ tổ chức...',
    Chart_RetryButton: 'Thử lại',
    Chart_NotFoundFromSetup: 'Không tìm thấy người dùng "{identifier}".',
    Chart_NotFoundWithSettings: 'Không tìm thấy người dùng "{identifier}". Hãy kiểm tra UPN hoặc email trong Cài đặt.',
    Chart_LoadFailedGeneric: 'Không thể tải sơ đồ tổ chức.{detail}',
    Chart_LoadFailedPermissions: ' Hãy kiểm tra quyền truy cập.',
    Chart_LoadFailedForPerson: 'Không thể tải sơ đồ tổ chức cho người này.',
    Chart_FindMeNotFound: 'Không tìm thấy tài khoản của bạn trong tổ chức này.',
    Chart_StatPeople: 'Người',
    Chart_StatMembers: 'Thành viên',
    Chart_StatGuests: 'Khách',
    Chart_StatDepts: 'Phòng ban',
    Chart_ReportingLineAria: 'Chuỗi báo cáo',
    Chart_BackToFullOrgTitle: 'Quay lại sơ đồ tổ chức đầy đủ',
    Chart_FullOrgLabel: 'Toàn bộ tổ chức',
    Chart_FocusOnPerson: 'Tập trung vào {name}',
    Chart_OrgChartAria: 'Sơ đồ tổ chức',
    Chart_ExportNote_DrillLevel: 'Cấp hiện tại đang xem (một cấp cấp dưới trực tiếp)',
    Chart_ExportNote_PartialLevels: 'Chỉ bao gồm các cấp đã tải — hãy dùng Mở rộng tất cả trước khi xuất để bao gồm các cấp sâu hơn',
    Chart_AllowPopupsForPdf: 'Vui lòng cho phép cửa sổ bật lên để xuất PDF.',

    // ── Person card ──
    PersonCard_ProfileAria: 'Hồ sơ: {name}',
    PersonCard_CloseTitle: 'Đóng',
    PersonCard_CloseAria: 'Đóng hồ sơ',
    PersonCard_StatusDisabled: 'Đã vô hiệu hóa',
    PersonCard_StatusGuest: 'Khách',
    PersonCard_DirectReportSingular: '{count} cấp dưới trực tiếp',
    PersonCard_DirectReportPlural: '{count} cấp dưới trực tiếp',
    PersonCard_TotalSuffix: ' · tổng {total}',
    PersonCard_CopyEmailTitle: 'Sao chép địa chỉ email',
    PersonCard_EmailCopiedAria: 'Đã sao chép địa chỉ email',
    PersonCard_ReportsTo: 'Báo cáo cho',
    PersonCard_FocusOnPerson: 'Tập trung vào {name}',
    PersonCard_FocusOrgChartOnPerson: 'Tập trung sơ đồ tổ chức vào {name}',
    PersonCard_DottedLine: 'Đường chấm',
    PersonCard_DottedLineManager: 'Người quản lý gián tiếp: {name}',
    PersonCard_DottedLineReport: 'Cấp dưới gián tiếp: {name}',
    PersonCard_ChatButton: 'Trò chuyện',
    PersonCard_EmailButton: 'Email',
    PersonCard_FocusButton: 'Tập trung',
    PersonCard_FocusTitle: 'Tập trung sơ đồ tổ chức vào người này',

    // ── Org node card ──
    OrgNode_ViewProfile: 'Xem hồ sơ của {name}',
    OrgNode_FocusOrgChartOn: 'Tập trung sơ đồ tổ chức vào {name}',
    OrgNode_Collapse: 'Thu gọn',
    OrgNode_Expand: 'Mở rộng',
    OrgNode_DirectReportsSuffix: 'Cấp dưới trực tiếp của {name}',
    OrgNode_StatusDisabled: 'Đã vô hiệu hóa',
    OrgNode_StatusGuest: 'Khách',
    OrgNode_TotalReportsAcrossLevels: '{count} người ở tất cả các cấp bên dưới {name}',

    // ── Drill view ──
    Drill_ReportingLineAria: 'Chuỗi báo cáo',
    Drill_BackToTopTitle: 'Quay lại đầu',
    Drill_BackToTopAria: 'Quay lại đầu sơ đồ tổ chức',
    Drill_GoBackTo: 'Quay lại {name}',
    Drill_ViewProfileTitle: 'Xem hồ sơ',
    Drill_ViewProfileAria: 'Xem hồ sơ của {name}',
    Drill_ProfileButton: 'Hồ sơ',
    Drill_LoadingLabel: 'Đang tải...',
    Drill_DirectReports: 'Cấp dưới trực tiếp',
    Drill_DirectReportsOfAria: 'Cấp dưới trực tiếp của {name}',
    Drill_DirectReportsAria: 'Cấp dưới trực tiếp',
    Drill_ViewPersonProfile: 'Xem hồ sơ của {name}',
    Drill_ShowPersonReports: 'Hiển thị cấp dưới trực tiếp của {name}',
    Drill_NoDirectReports: 'Không có cấp dưới trực tiếp',

    // ── Settings panel ──
    Settings_AlphabetFirstName: 'Tên',
    Settings_AlphabetLastName: 'Họ',
    Settings_CardSizeSmall: 'Nhỏ — gọn, hiển thị được nhiều thẻ hơn',
    Settings_CardSizeMedium: 'Vừa — cân bằng',
    Settings_CardSizeLarge: 'Lớn — rộng rãi, ít thẻ hơn',
    Settings_HeaderText: 'Tùy chọn',
    Settings_SaveButton: 'Lưu',
    Settings_CancelButton: 'Hủy',
    Settings_DiscardButton: 'Hủy bỏ thay đổi',
    Settings_SectionDirectory: 'Danh bạ',
    Settings_AlphabetFilterByLabel: 'Lọc chữ cái theo',
    Settings_CardSizeLabel: 'Kích thước thẻ',
    Settings_FontSizeLabel: 'Cỡ chữ',
    Settings_SectionCardsAndFields: 'Thẻ & Trường thông tin',
    Settings_ShowOnCardsLabel: 'Hiển thị trên thẻ nhân viên:',
    Settings_EmailAddressLabel: 'Địa chỉ email',
    Settings_PhoneNumberLabel: 'Số điện thoại',
    Settings_DepartmentLabel: 'Phòng ban',
    Settings_OfficeLocationLabel: 'Vị trí văn phòng',
    Settings_SectionOrgChart: 'Sơ đồ tổ chức',
    Settings_ManagerLevelsLabel: 'Số cấp quản lý hiển thị khi tập trung vào một người: {levels}',
    Settings_CompactCardsLabel: 'Thẻ gọn',
    Settings_CompactCardsOn: 'Bật — thẻ nhỏ hơn, hiển thị được nhiều hơn cùng lúc',
    Settings_CompactCardsOff: 'Tắt — kích thước tiêu chuẩn',
    Settings_Hint: 'Các tùy chọn này được lưu trên trình duyệt của bạn và chỉ áp dụng cho riêng bạn. Chủ đề sơ đồ, chế độ xem mặc định và bố cục do quản trị viên SharePoint của bạn cấu hình.',
    Settings_SectionDemoData: 'Dữ liệu demo',
    Settings_DatasetSizeLabel: 'Kích thước tập dữ liệu',
    Settings_PeopleCountSuffix: '{count} người',

    // ── Export (CSV / PDF) ──
    Export_ColumnName: 'Tên',
    Export_ColumnJobTitle: 'Chức danh',
    Export_ColumnDepartment: 'Phòng ban',
    Export_ColumnOffice: 'Văn phòng',
    Export_ColumnEmail: 'Email',
    Export_ColumnPhone: 'Điện thoại',
    Export_ColumnManager: 'Người quản lý',
    Export_ColumnLevel: 'Cấp',
    Export_PdfDocumentTitle: 'Sơ đồ tổ chức',
    Export_PdfHeading: 'Sơ đồ tổ chức',
    Export_PdfRootLabel: 'Gốc: {name}',
  };
});
