define([], function () {
  return {
    // ── Property pane: pane header / groups ──
    PropertyPane_HeaderDescription: '智能组织结构图设置',
    PropertyPane_Group_General: '常规',
    PropertyPane_Group_Branding: '品牌',
    PropertyPane_Group_VisualStyle: '视觉样式',
    PropertyPane_Group_DataSource: '数据源',
    PropertyPane_Group_CustomAttributes: '自定义属性',
    PropertyPane_Group_UserFilters: '用户筛选器',
    PropertyPane_Group_OrgChart: '组织结构图',
    PropertyPane_Group_OrgChartFeatures: '组织结构图功能',
    PropertyPane_Group_Directory: '通讯录',
    PropertyPane_Group_Demo: '演示',

    // ── Property pane: General ──
    PropertyPane_DefaultView_Label: '默认视图',

    // ── Property pane: Branding ──
    PropertyPane_AppTitle_Label: '应用标题',
    PropertyPane_AppTitle_Placeholder: 'Contoso 组织结构图',
    PropertyPane_AppTitle_Description: '与视图名称一起显示在标题栏中',
    PropertyPane_LogoUrl_Label: '徽标 URL',
    PropertyPane_LogoUrl_Placeholder: 'https://contoso.sharepoint.com/sites/yoursite/SiteAssets/logo.png',
    PropertyPane_LogoUrl_Description: 'PNG/SVG/JPG 图像的完整 URL。提示：在浏览器中打开图像文件，然后复制地址栏中的 URL。"复制链接"生成的共享 URL 将无法使用。',
    PropertyPane_DirectoryLabel_Label: '员工通讯录视图标签',
    PropertyPane_OrgChartLabel_Label: '组织结构图视图标签',
    PropertyPane_ViewLabel_Description: '留空以使用默认名称，或输入"[blank]"以完全隐藏该标签。',

    // ── Property pane: Visual Style ──
    PropertyPane_ChartTheme_Label: '图表主题',
    PropertyPane_Theme_Modern: '现代风格 — 白底部门配色',
    PropertyPane_Theme_Minimal: '简约风格 — 扁平化、低对比度',
    PropertyPane_Theme_Corporate: '企业风格 — 统一蓝色',
    PropertyPane_Theme_Dark: '深色风格 — 深藏青色背景',
    PropertyPane_Theme_Custom: '自定义 — 选择您自己的颜色',
    PropertyPane_AccentColor_Label: '自定义强调色',
    PropertyPane_AccentColor_PickerAriaLabel: '强调色选择器',
    PropertyPane_AccentColor_HexLabel: '十六进制',
    PropertyPane_AccentColor_HexAriaLabel: '强调色十六进制值',
    PropertyPane_AccentColor_RgbLabel: 'RGB',
    PropertyPane_AccentColor_ChannelAriaLabel: '{name} 通道（0 到 255）',
    PropertyPane_AccentColor_ContrastWithWhite: '与白色的对比度：{ratio}:1（{passes}）',
    PropertyPane_AccentColor_PassesAA: '符合 AA 级标准',
    PropertyPane_AccentColor_LargeTextOnly: '仅适用于大号文本',
    PropertyPane_AccentColor_LowContrast: '对比度低',
    PropertyPane_AccentColor_DarkTextNote: '为提高可读性，此颜色上的文本将显示为深色。',
    PropertyPane_AccentColor_DarkerShadeNote: '为提高可读性，标题和链接将使用更深的色调（{hex}）。',
    PropertyPane_AccentColor_InvalidHex: '"{typed}" 不是有效的十六进制颜色值。请使用类似 #0078d4 或 #07d 的值。',
    PropertyPane_DefaultFontSize_Label: '默认字体大小',
    PropertyPane_FontSize_75: '75% — 超小',
    PropertyPane_FontSize_85: '85% — 小',
    PropertyPane_FontSize_100: '100% — 正常',
    PropertyPane_FontSize_115: '115% — 大',
    PropertyPane_FontSize_130: '130% — 超大',
    PropertyPane_FontSize_150: '150% — 特大 (XXL)',
    PropertyPane_FontSize_175: '175% — 超特大 (XXXL)',
    PropertyPane_DefaultLayout_Label: '默认组织结构图布局',
    PropertyPane_Layout_Drill: '逐级下钻',
    PropertyPane_Layout_Vertical: '自上而下',
    PropertyPane_Layout_Horizontal: '从左到右',

    // ── Property pane: Data Source ──
    PropertyPane_DataSource_Label: '用户和组织数据的加载来源',
    PropertyPane_DataSource_Auto: '自动 — 优先使用 Graph API，失败时回退到 SharePoint 搜索',
    PropertyPane_DataSource_Graph: 'Graph API — 实时 Azure AD 数据（无索引延迟）',
    PropertyPane_DataSource_Search: 'SharePoint 搜索 — 旧版行为',
    PropertyPane_DataSource_Note: '建议使用 Graph API。它直接从 Azure Active Directory 读取数据，因此新用户和经理变更会立即显示。需要在 SharePoint 应用目录中批准 Microsoft Graph 权限。',

    // ── Property pane: Custom Attributes ──
    PropertyPane_CustomAttributes_Note: '自定义属性需要使用 Microsoft Graph（数据源：Graph 或自动）。SharePoint 搜索没有通用方法可读取 Microsoft Entra ID 属性。',
    PropertyPane_CustomAttributes_Heading: '管理自定义属性',
    PropertyPane_CustomAttributes_Empty: '尚未配置任何自定义属性。',
    PropertyPane_CustomAttributes_AddButton: '+ 添加属性',
    PropertyPane_CustomAttributes_MaxTooltip: '最多可添加 {max} 个自定义属性',
    PropertyPane_CustomAttributes_FieldNameLabel: '属性名称',
    PropertyPane_CustomAttributes_FieldPlaceholder: '例如 companyName',
    PropertyPane_CustomAttributes_FieldError: '请使用 employeeId、companyName、city 等，或 extensionAttribute1-15',
    PropertyPane_CustomAttributes_DisplayLabelLabel: '显示标签',
    PropertyPane_CustomAttributes_LabelPlaceholder: '例如"成本中心"',
    PropertyPane_CustomAttributes_RemoveTitle: '删除属性',
    PropertyPane_CustomAttributes_RemoveAriaLabel: '删除属性 {ordinal}',
    PropertyPane_CustomAttributes_ShowInDirectory: '在通讯录中显示',
    PropertyPane_CustomAttributes_ShowInOrgChart: '在组织结构图中显示',

    // ── Property pane: User Filters ──
    PropertyPane_ExcludedAccounts_Label: '排除的帐户',
    PropertyPane_ExcludedAccounts_Placeholder: 'conf-room, noreply, admin@, Service Account',
    PropertyPane_ExcludedAccounts_Description: '以逗号分隔的单词或模式（不区分大小写）。凡显示名称、电子邮件或 UPN 中包含其中任一内容的用户，都将在所有视图中被隐藏。',
    PropertyPane_RestrictTenant_Label: '仅显示租户用户',
    PropertyPane_RestrictTenant_On: '开启 — 隐藏使用外部电子邮件域的帐户（例如 gmail.com、hotmail.com）',
    PropertyPane_RestrictTenant_Off: '关闭 — 无论电子邮件域为何，均显示所有用户',
    PropertyPane_HideGuest_Label: '隐藏 Azure AD 来宾帐户',
    PropertyPane_HideGuest_On: '开启 — 来宾帐户已隐藏',
    PropertyPane_HideGuest_Off: '关闭 — 显示来宾帐户（带有"来宾"徽章）',
    PropertyPane_HideDisabled_Label: '隐藏已禁用的帐户',
    PropertyPane_HideDisabled_On: '开启 — 已阻止登录的帐户将被隐藏',
    PropertyPane_HideDisabled_Off: '关闭 — 显示已禁用的帐户（带有"已禁用"徽章）',
    PropertyPane_HideDisabled_Note: '注意：检测来宾帐户和已禁用帐户需要使用 Graph API 数据源。SharePoint 搜索不会返回此类信息，因此当数据来自搜索时，这两个筛选器（以及"来宾/已禁用"徽章）将不起作用。',
    PropertyPane_HideNoJobTitle_Label: '隐藏没有职务的帐户',
    PropertyPane_HideNoJobTitle_On: '开启 — 没有职务的帐户将被隐藏',
    PropertyPane_HideNoJobTitle_Off: '关闭 — 无论是否设置职务，均显示所有帐户',
    PropertyPane_HideNoDept_Label: '隐藏没有部门的帐户',
    PropertyPane_HideNoDept_On: '开启 — 没有部门的帐户将被隐藏',
    PropertyPane_HideNoDept_Off: '关闭 — 无论是否设置部门，均显示所有帐户',

    // ── Property pane: Org Chart ──
    PropertyPane_TopLevelUser_Label: '顶级用户（UPN 或电子邮件）',
    PropertyPane_TopLevelUser_Placeholder: 'ceo@yourcompany.com',
    PropertyPane_TopLevelUser_Description: '显示在组织结构图根节点的人员',
    PropertyPane_LevelsBelow_Label: '根节点以下要加载的层级数',
    PropertyPane_DottedLine_Label: '虚线汇报经理属性',
    PropertyPane_DottedLine_Placeholder: 'extensionAttribute10',
    PropertyPane_DottedLine_Description: '可选。存储次要"虚线"汇报经理的电子邮件或 UPN 的 Azure AD 本地扩展属性名称（extensionAttribute1-15）。虚线关系会显示在个人资料卡上。需要使用 Graph API 数据源。',
    PropertyPane_DefaultZoom_Label: '组织结构图默认缩放比例',
    PropertyPane_Zoom_Auto: '默认（自动适应）',
    PropertyPane_Zoom_50: '50%',
    PropertyPane_Zoom_75: '75%',
    PropertyPane_Zoom_100: '100%',
    PropertyPane_Zoom_125: '125%',
    PropertyPane_Zoom_150: '150%',

    // ── Property pane: Org Chart Features ──
    PropertyPane_FeatureToggles_Note: '显示或隐藏组织结构图视图中的工具栏按钮。',
    PropertyPane_FindMe_Label: '查找我按钮',
    PropertyPane_LayoutToggle_Label: '布局切换（下钻 / 垂直 / 水平）',
    PropertyPane_Stats_Label: '组织统计栏',
    PropertyPane_DeptFilter_Label: '部门筛选器',
    PropertyPane_UserFilter_Label: '用户类型筛选器（成员 / 来宾）',
    PropertyPane_Visible: '显示',
    PropertyPane_Hidden: '隐藏',

    // ── Property pane: Directory ──
    PropertyPane_PageSize_Label: '每页最多显示的员工数',
    PropertyPane_PageSize_AriaLabel: '每页最多显示的员工数（10 到 200）',
    PropertyPane_PageSize_Note: '卡片大小、显示字段等其他显示首选项由每位用户通过应用中的"设置"齿轮图标自行设置。',

    // ── Property pane: Demo ──
    PropertyPane_UseDemoData_Label: '使用演示数据',
    PropertyPane_UseDemoData_On: '开启 — 显示示例员工',
    PropertyPane_UseDemoData_Off: '关闭 — 使用实时 Microsoft 365 数据',

    // ── Presence status labels ──
    Presence_Available: '空闲',
    Presence_Busy: '忙碌',
    Presence_DoNotDisturb: '请勿打扰',
    Presence_BeRightBack: '暂时离开',
    Presence_Away: '离开',
    Presence_Offline: '脱机',

    // ── Header / top bar ──
    Header_DirectoryLabel: '员工通讯录',
    Header_OrgChartLabel: '组织结构图',
    Header_SwitchToView: '切换到{view}',
    Header_CompanyLogoAlt: '公司徽标',
    Header_RefreshingAria: '正在刷新数据',
    Header_RefreshAria: '刷新数据',
    Header_RefreshTitle: '刷新数据（上次更新时间：{when}）',
    Header_NotLoadedYet: '尚未加载',
    Header_JustNow: '刚刚',
    Header_MinutesAgo: '{mins} 分钟前',
    Header_HoursAgo: '{hours} 小时前',
    Header_PreferencesTitle: '首选项',
    Header_PreferencesAria: '打开首选项面板',

    // ── Employee Directory ──
    Directory_LoadingLabel: '正在加载员工...',
    Directory_LoadFailedFallback: '请确保该 Web 部件已获得 User.Read.All 权限。',
    Directory_LoadFailedPrefix: '加载员工失败。{detail}',
    Directory_AllDepartments: '所有部门',
    Directory_AllOffices: '所有办公地点',
    Directory_StatusDisabled: '已禁用',
    Directory_StatusGuest: '来宾',
    Directory_PresenceStatus: '状态：{status}',
    Directory_ChatInTeams: '在 Teams 中聊天',
    Directory_ChatWithInTeams: '在 Teams 中与 {name} 聊天',
    Directory_ManagesCount: '管理 {direct} 人',
    Directory_ManagesCountWithTotal: '管理 {direct} 人（共 {total} 人）',
    Directory_ReportsCountWithTotal: '{direct}（共 {total}）',
    Directory_ColumnName: '姓名',
    Directory_ColumnJobTitle: '职务',
    Directory_ColumnDepartment: '部门',
    Directory_ColumnOffice: '办公地点',
    Directory_ColumnEmail: '电子邮件',
    Directory_ColumnPhone: '电话',
    Directory_ColumnReports: '下属',
    Directory_ColumnChat: '聊天',
    Directory_PrevPage: '上一页',
    Directory_NextPage: '下一页',
    Directory_PreviousPageAria: '上一页',
    Directory_NextPageAria: '下一页',
    Directory_SearchPlaceholder: '按姓名、职务、电子邮件或部门搜索...',
    Directory_SearchAria: '搜索人员',
    Directory_FilterByDepartmentAria: '按部门筛选',
    Directory_FilterByOfficeAria: '按办公地点筛选',
    Directory_ClearSearchTitle: '清除搜索和所有筛选器',
    Directory_ClearButton: '清除',
    Directory_ClearFiltersButton: '清除筛选器',
    Directory_ExportCsvTitle: '将所有筛选结果导出为 CSV 文件（可在 Excel 中打开）',
    Directory_ExportCsvButton: '导出 CSV',
    Directory_ViewModeAria: '视图模式',
    Directory_CardViewTitle: '卡片视图',
    Directory_ListViewTitle: '列表视图',
    Directory_AlphabetFilterAria: '字母筛选器',
    Directory_ShowAllTitle: '显示全部',
    Directory_OtherLettersTitle: '筛选以数字或其他字符开头的姓名',
    Directory_FilterByLetterTitle: '按字母 {letter} 筛选',
    Directory_ResultCountSingular: '人',
    Directory_ResultCountPlural: '人',
    Directory_PageOf: ' · 第 {page} 页，共 {totalPages} 页',
    Directory_FilterActiveSingular: '{count} 个筛选器已启用',
    Directory_FilterActivePlural: '{count} 个筛选器已启用',
    Directory_NoResults: '未找到任何人员',
    Directory_PaginationAria: '分页',

    // ── Org chart toolbar / shared chart chrome ──
    Chart_Layout_Drill: '逐级下钻',
    Chart_Layout_Vertical: '自上而下',
    Chart_Layout_Horizontal: '从左到右',
    Chart_SearchPlaceholder: '搜索人员...',
    Chart_SearchAria: '搜索人员',
    Chart_MatchSingular: '个匹配项（树中）',
    Chart_MatchPlural: '个匹配项（树中）',
    Chart_ResultsListAria: '人员',
    Chart_ExpandAll: '全部展开',
    Chart_CollapseAll: '全部折叠',
    Chart_Expanding: '正在展开…',
    Chart_Loading: '正在加载…',
    Chart_FindMeTitle: '在组织结构图中找到我',
    Chart_ViewLayoutButton: '视图',
    Chart_ViewLayoutTitle: '切换视图布局',
    Chart_ViewLayoutPanelTitle: '视图布局',
    Chart_StatsSummaryTitle: '组织统计摘要',
    Chart_FilterByDepartmentTitle: '按部门筛选',
    Chart_FilterByDepartmentWithCountAria: '按部门筛选（已选择 {count} 个）',
    Chart_FilterByDepartmentPanelTitle: '按部门筛选',
    Chart_ClearAllFilters: '清除所有筛选器',
    Chart_FilterUserTypesTitle: '筛选用户类型',
    Chart_DownloadPdfTitle: '下载为 PDF',
    Chart_DownloadCsvTitle: '下载为 CSV 电子表格',
    Chart_ResetRootTitle: '重置为默认根节点',
    Chart_ViewFromPersonPlaceholder: '从指定人员查看…',
    Chart_ViewFromPersonAria: '从指定人员开始查看组织结构图',
    Chart_ZoomOutTitle: '缩小',
    Chart_ZoomInTitle: '放大',
    Chart_ZoomResetTitle: '重置缩放',
    Chart_ShowInChartAria: '在图表中显示',
    Chart_ShowInChartTitle: '在图表中显示',
    Chart_FilterMembers: '普通成员',
    Chart_FilterGuests: '来宾用户',
    Chart_FilterDisabled: '已禁用的帐户',
    Chart_SetupTitle: '设置组织结构图',
    Chart_SetupSubtitle: '请输入顶级人员的电子邮件或 UPN 以开始使用。',
    Chart_SetupPlaceholder: 'ceo@company.com',
    Chart_SetupInputAria: '顶级人员的电子邮件或 UPN',
    Chart_SetupLoadButton: '加载',
    Chart_SetupHint: '您也可以在 Web 部件设置中永久设置此项（管理员）。',
    Chart_BuildingLabel: '正在生成组织结构图...',
    Chart_RetryButton: '重试',
    Chart_NotFoundFromSetup: '未找到用户"{identifier}"。',
    Chart_NotFoundWithSettings: '未找到用户"{identifier}"。请在设置中检查 UPN 或电子邮件。',
    Chart_LoadFailedGeneric: '加载组织结构图失败。{detail}',
    Chart_LoadFailedPermissions: ' 请检查权限。',
    Chart_LoadFailedForPerson: '加载此人员的组织结构图失败。',
    Chart_FindMeNotFound: '在此组织中未找到您的帐户。',
    Chart_StatPeople: '人员',
    Chart_StatMembers: '成员',
    Chart_StatGuests: '来宾',
    Chart_StatDepts: '部门',
    Chart_ReportingLineAria: '汇报线',
    Chart_BackToFullOrgTitle: '返回完整组织结构图',
    Chart_FullOrgLabel: '完整组织',
    Chart_FocusOnPerson: '聚焦于 {name}',
    Chart_OrgChartAria: '组织结构图',
    Chart_ExportNote_DrillLevel: '当前下钻层级（一级直接下属）',
    Chart_ExportNote_PartialLevels: '仅包含已加载的层级 — 如需包含更深层级，请在导出前使用"全部展开"',
    Chart_AllowPopupsForPdf: '请允许弹出窗口以导出 PDF。',

    // ── Person card ──
    PersonCard_ProfileAria: '个人资料：{name}',
    PersonCard_CloseTitle: '关闭',
    PersonCard_CloseAria: '关闭个人资料',
    PersonCard_StatusDisabled: '已禁用',
    PersonCard_StatusGuest: '来宾',
    PersonCard_DirectReportSingular: '{count} 名直接下属',
    PersonCard_DirectReportPlural: '{count} 名直接下属',
    PersonCard_TotalSuffix: ' · 共 {total} 人',
    PersonCard_CopyEmailTitle: '复制电子邮件地址',
    PersonCard_EmailCopiedAria: '电子邮件地址已复制',
    PersonCard_ReportsTo: '汇报对象',
    PersonCard_FocusOnPerson: '聚焦于 {name}',
    PersonCard_FocusOrgChartOnPerson: '将组织结构图聚焦于 {name}',
    PersonCard_DottedLine: '虚线关系',
    PersonCard_DottedLineManager: '虚线汇报经理：{name}',
    PersonCard_DottedLineReport: '虚线汇报下属：{name}',
    PersonCard_ChatButton: '聊天',
    PersonCard_EmailButton: '电子邮件',
    PersonCard_FocusButton: '聚焦',
    PersonCard_FocusTitle: '将组织结构图聚焦于此人员',

    // ── Org node card ──
    OrgNode_ViewProfile: '查看 {name} 的个人资料',
    OrgNode_FocusOrgChartOn: '将组织结构图聚焦于 {name}',
    OrgNode_Collapse: '折叠',
    OrgNode_Expand: '展开',
    OrgNode_DirectReportsSuffix: '{name} 的直接下属',
    OrgNode_StatusDisabled: '已禁用',
    OrgNode_StatusGuest: '来宾',
    OrgNode_TotalReportsAcrossLevels: '{name} 以下所有层级共 {count} 人',

    // ── Drill view ──
    Drill_ReportingLineAria: '汇报线',
    Drill_BackToTopTitle: '返回顶部',
    Drill_BackToTopAria: '返回组织结构图顶部',
    Drill_GoBackTo: '返回到 {name}',
    Drill_ViewProfileTitle: '查看个人资料',
    Drill_ViewProfileAria: '查看 {name} 的个人资料',
    Drill_ProfileButton: '个人资料',
    Drill_LoadingLabel: '正在加载...',
    Drill_DirectReports: '直接下属',
    Drill_DirectReportsOfAria: '{name} 的直接下属',
    Drill_DirectReportsAria: '直接下属',
    Drill_ViewPersonProfile: '查看 {name} 的个人资料',
    Drill_ShowPersonReports: '显示 {name} 的直接下属',
    Drill_NoDirectReports: '没有直接下属',

    // ── Settings panel ──
    Settings_AlphabetFirstName: '名字',
    Settings_AlphabetLastName: '姓氏',
    Settings_CardSizeSmall: '小 — 紧凑，可显示更多卡片',
    Settings_CardSizeMedium: '中 — 均衡',
    Settings_CardSizeLarge: '大 — 宽松，显示较少卡片',
    Settings_HeaderText: '首选项',
    Settings_SaveButton: '保存',
    Settings_CancelButton: '取消',
    Settings_DiscardButton: '放弃更改',
    Settings_SectionDirectory: '通讯录',
    Settings_AlphabetFilterByLabel: '字母筛选依据',
    Settings_CardSizeLabel: '卡片大小',
    Settings_FontSizeLabel: '字体大小',
    Settings_SectionCardsAndFields: '卡片和字段',
    Settings_ShowOnCardsLabel: '在员工卡片上显示：',
    Settings_EmailAddressLabel: '电子邮件地址',
    Settings_PhoneNumberLabel: '电话号码',
    Settings_DepartmentLabel: '部门',
    Settings_OfficeLocationLabel: '办公地点',
    Settings_SectionOrgChart: '组织结构图',
    Settings_ManagerLevelsLabel: '聚焦某人员时显示的经理层级数：{levels}',
    Settings_CompactCardsLabel: '紧凑卡片',
    Settings_CompactCardsOn: '开启 — 卡片更小，可同时显示更多',
    Settings_CompactCardsOff: '关闭 — 标准大小',
    Settings_Hint: '这些首选项将保存在您的浏览器中，仅对您本人生效。图表主题、默认视图和布局由您的 SharePoint 管理员配置。',
    Settings_SectionDemoData: '演示数据',
    Settings_DatasetSizeLabel: '数据集大小',
    Settings_PeopleCountSuffix: '{count} 人',

    // ── Export (CSV / PDF) ──
    Export_ColumnName: '姓名',
    Export_ColumnJobTitle: '职务',
    Export_ColumnDepartment: '部门',
    Export_ColumnOffice: '办公地点',
    Export_ColumnEmail: '电子邮件',
    Export_ColumnPhone: '电话',
    Export_ColumnManager: '经理',
    Export_ColumnLevel: '层级',
    Export_PdfDocumentTitle: '组织结构图',
    Export_PdfHeading: '组织结构图',
    Export_PdfRootLabel: '根节点：{name}',
  };
});
