define([], function () {
  return {
    // ── Property pane: pane header / groups ──
    PropertyPane_HeaderDescription: '智慧型組織圖設定',
    PropertyPane_Group_General: '一般',
    PropertyPane_Group_Branding: '品牌',
    PropertyPane_Group_VisualStyle: '視覺樣式',
    PropertyPane_Group_DataSource: '資料來源',
    PropertyPane_Group_CustomAttributes: '自訂屬性',
    PropertyPane_Group_UserFilters: '使用者篩選',
    PropertyPane_Group_OrgChart: '組織圖',
    PropertyPane_Group_OrgChartFeatures: '組織圖功能',
    PropertyPane_Group_Directory: '通訊錄',
    PropertyPane_Group_Demo: '展示',

    // ── Property pane: General ──
    PropertyPane_DefaultView_Label: '預設檢視',

    // ── Property pane: Branding ──
    PropertyPane_AppTitle_Label: '應用程式標題',
    PropertyPane_AppTitle_Placeholder: 'Contoso 組織圖',
    PropertyPane_AppTitle_Description: '與檢視名稱一併顯示在標題列中',
    PropertyPane_LogoUrl_Label: '標誌 URL',
    PropertyPane_LogoUrl_Placeholder: 'https://contoso.sharepoint.com/sites/yoursite/SiteAssets/logo.png',
    PropertyPane_LogoUrl_Description: 'PNG/SVG/JPG 圖片的完整 URL。提示：在瀏覽器中開啟圖片檔案，再複製網址列的 URL。「複製連結」產生的共用 URL 無法使用。',
    PropertyPane_DirectoryLabel_Label: '員工通訊錄檢視標籤',
    PropertyPane_OrgChartLabel_Label: '組織圖檢視標籤',
    PropertyPane_ViewLabel_Description: '留空以使用預設名稱，或輸入「[blank]」以完全隱藏該標籤。',

    // ── Property pane: Visual Style ──
    PropertyPane_ChartTheme_Label: '組織圖主題',
    PropertyPane_Theme_Modern: '現代風格 — 白底部門配色',
    PropertyPane_Theme_Minimal: '簡約風格 — 扁平化、低對比度',
    PropertyPane_Theme_Corporate: '企業風格 — 統一藍色',
    PropertyPane_Theme_Dark: '深色風格 — 深藏青色背景',
    PropertyPane_Theme_Custom: '自訂 — 自行選擇顏色',
    PropertyPane_AccentColor_Label: '自訂主題色',
    PropertyPane_AccentColor_PickerAriaLabel: '主題色選取器',
    PropertyPane_AccentColor_HexLabel: 'Hex',
    PropertyPane_AccentColor_HexAriaLabel: '主題色的十六進位值',
    PropertyPane_AccentColor_RgbLabel: 'RGB',
    PropertyPane_AccentColor_ChannelAriaLabel: '{name} 色版（0 至 255）',
    PropertyPane_AccentColor_ContrastWithWhite: '與白色的對比度：{ratio}:1（{passes}）',
    PropertyPane_AccentColor_PassesAA: '符合 AA 等級',
    PropertyPane_AccentColor_LargeTextOnly: '僅適用於大型文字',
    PropertyPane_AccentColor_LowContrast: '對比度偏低',
    PropertyPane_AccentColor_DarkTextNote: '為提升可讀性，此顏色上的文字將顯示為深色。',
    PropertyPane_AccentColor_DarkerShadeNote: '為提升可讀性，標題與連結將採用較深的色調（{hex}）。',
    PropertyPane_AccentColor_InvalidHex: '「{typed}」不是有效的十六進位色碼，請使用類似 #0078d4 或 #07d 的值。',
    PropertyPane_DefaultFontSize_Label: '預設字型大小',
    PropertyPane_FontSize_75: '75% — 特小',
    PropertyPane_FontSize_85: '85% — 小',
    PropertyPane_FontSize_100: '100% — 標準',
    PropertyPane_FontSize_115: '115% — 大',
    PropertyPane_FontSize_130: '130% — 特大',
    PropertyPane_FontSize_150: '150% — 加大 (XXL)',
    PropertyPane_FontSize_175: '175% — 特加大 (XXXL)',
    PropertyPane_DefaultLayout_Label: '組織圖預設版面配置',
    PropertyPane_Layout_Drill: '逐層展開',
    PropertyPane_Layout_Vertical: '由上而下',
    PropertyPane_Layout_Horizontal: '由左至右',

    // ── Property pane: Data Source ──
    PropertyPane_DataSource_Label: '使用者與組織資料的載入來源',
    PropertyPane_DataSource_Auto: '自動 — 優先使用 Graph API，失敗時改用 SharePoint 搜尋',
    PropertyPane_DataSource_Graph: 'Graph API — 即時 Azure AD 資料（無索引延遲）',
    PropertyPane_DataSource_Search: 'SharePoint 搜尋 — 舊版行為',
    PropertyPane_DataSource_Note: '建議使用 Graph API，因為它會直接從 Azure Active Directory 讀取資料，新使用者與主管異動能立即反映。需先在 SharePoint 應用程式目錄中核准 Microsoft Graph 權限。',

    // ── Property pane: Custom Attributes ──
    PropertyPane_CustomAttributes_Note: '自訂屬性需要使用 Microsoft Graph（資料來源：Graph 或自動）。SharePoint 搜尋沒有通用方式可讀取 Entra ID 屬性。',
    PropertyPane_CustomAttributes_Heading: '管理自訂屬性',
    PropertyPane_CustomAttributes_Empty: '尚未設定任何自訂屬性。',
    PropertyPane_CustomAttributes_AddButton: '+ 新增屬性',
    PropertyPane_CustomAttributes_MaxTooltip: '最多可設定 {max} 個自訂屬性',
    PropertyPane_CustomAttributes_FieldNameLabel: '屬性名稱',
    PropertyPane_CustomAttributes_FieldPlaceholder: '例如 companyName',
    PropertyPane_CustomAttributes_FieldError: '請使用 employeeId、companyName、city 等，或 extensionAttribute1-15',
    PropertyPane_CustomAttributes_DisplayLabelLabel: '顯示標籤',
    PropertyPane_CustomAttributes_LabelPlaceholder: '例如「成本中心」',
    PropertyPane_CustomAttributes_RemoveTitle: '移除屬性',
    PropertyPane_CustomAttributes_RemoveAriaLabel: '移除屬性 {ordinal}',
    PropertyPane_CustomAttributes_ShowInDirectory: '在通訊錄中顯示',
    PropertyPane_CustomAttributes_ShowInOrgChart: '在組織圖中顯示',

    // ── Property pane: User Filters ──
    PropertyPane_ExcludedAccounts_Label: '排除帳戶',
    PropertyPane_ExcludedAccounts_Placeholder: 'conf-room, noreply, admin@, Service Account',
    PropertyPane_ExcludedAccounts_Description: '以逗號分隔的字詞或模式（不區分大小寫）。只要顯示名稱、電子郵件或 UPN 包含其中任一項，該使用者就會在所有檢視中被隱藏。',
    PropertyPane_RestrictTenant_Label: '僅顯示此租用戶的使用者',
    PropertyPane_RestrictTenant_On: '開啟 — 隱藏使用外部電子郵件網域的帳戶（例如 gmail.com、hotmail.com）',
    PropertyPane_RestrictTenant_Off: '關閉 — 無論電子郵件網域為何，均顯示所有使用者',
    PropertyPane_HideGuest_Label: '隱藏 Azure AD 來賓帳戶',
    PropertyPane_HideGuest_On: '開啟 — 來賓帳戶已隱藏',
    PropertyPane_HideGuest_Off: '關閉 — 顯示來賓帳戶（附「來賓」徽章）',
    PropertyPane_HideDisabled_Label: '隱藏已停用的帳戶',
    PropertyPane_HideDisabled_On: '開啟 — 已封鎖登入的帳戶將被隱藏',
    PropertyPane_HideDisabled_Off: '關閉 — 顯示已停用的帳戶（附「已停用」徽章）',
    PropertyPane_HideDisabled_Note: '注意：偵測來賓與已停用帳戶需要使用 Graph API 資料來源。SharePoint 搜尋不會傳回這類資訊，因此當資料來源為搜尋時，這兩個篩選器（以及「來賓／已停用」徽章）不會產生作用。',
    PropertyPane_HideNoJobTitle_Label: '隱藏沒有職稱的帳戶',
    PropertyPane_HideNoJobTitle_On: '開啟 — 沒有職稱的帳戶將被隱藏',
    PropertyPane_HideNoJobTitle_Off: '關閉 — 無論是否設定職稱，均顯示所有帳戶',
    PropertyPane_HideNoDept_Label: '隱藏沒有部門的帳戶',
    PropertyPane_HideNoDept_On: '開啟 — 沒有部門的帳戶將被隱藏',
    PropertyPane_HideNoDept_Off: '關閉 — 無論是否設定部門，均顯示所有帳戶',

    // ── Property pane: Org Chart ──
    PropertyPane_TopLevelUser_Label: '最上層使用者（UPN 或電子郵件）',
    PropertyPane_TopLevelUser_Placeholder: 'ceo@yourcompany.com',
    PropertyPane_TopLevelUser_Description: '顯示在組織圖根節點的人員',
    PropertyPane_LevelsBelow_Label: '根節點以下要載入的層級數',
    PropertyPane_DottedLine_Label: '虛線主管屬性',
    PropertyPane_DottedLine_Placeholder: 'extensionAttribute10',
    PropertyPane_DottedLine_Description: '選填。用來儲存次要「虛線」主管電子郵件或 UPN 的 Azure AD 內部部署擴充屬性名稱（extensionAttribute1-15）。虛線關係會顯示在個人資料卡上。需要使用 Graph API 資料來源。',
    PropertyPane_DefaultZoom_Label: '組織圖預設縮放比例',
    PropertyPane_Zoom_Auto: '預設（自動符合大小）',
    PropertyPane_Zoom_50: '50%',
    PropertyPane_Zoom_75: '75%',
    PropertyPane_Zoom_100: '100%',
    PropertyPane_Zoom_125: '125%',
    PropertyPane_Zoom_150: '150%',

    // ── Property pane: Org Chart Features ──
    PropertyPane_FeatureToggles_Note: '顯示或隱藏組織圖檢視中的工具列按鈕。',
    PropertyPane_FindMe_Label: '「找到我」按鈕',
    PropertyPane_LayoutToggle_Label: '版面配置切換（逐層展開／垂直／水平）',
    PropertyPane_Stats_Label: '組織統計列',
    PropertyPane_DeptFilter_Label: '部門篩選',
    PropertyPane_UserFilter_Label: '使用者類型篩選（成員／來賓）',
    PropertyPane_Visible: '顯示',
    PropertyPane_Hidden: '隱藏',

    // ── Property pane: Directory ──
    PropertyPane_PageSize_Label: '每頁最多顯示的員工數',
    PropertyPane_PageSize_AriaLabel: '每頁最多顯示的員工數（10 至 200）',
    PropertyPane_PageSize_Note: '卡片大小、顯示欄位及其他顯示偏好設定，皆由每位使用者透過應用程式內的「設定」齒輪圖示自行調整。',

    // ── Property pane: Demo ──
    PropertyPane_UseDemoData_Label: '使用展示資料',
    PropertyPane_UseDemoData_On: '開啟 — 顯示範例員工',
    PropertyPane_UseDemoData_Off: '關閉 — 使用即時 Microsoft 365 資料',

    // ── Presence status labels ──
    Presence_Available: '線上',
    Presence_Busy: '忙碌中',
    Presence_DoNotDisturb: '請勿打擾',
    Presence_BeRightBack: '馬上回來',
    Presence_Away: '暫時離開',
    Presence_Offline: '離線',

    // ── Header / top bar ──
    Header_DirectoryLabel: '員工通訊錄',
    Header_OrgChartLabel: '組織圖',
    Header_SwitchToView: '切換到{view}',
    Header_CompanyLogoAlt: '公司標誌',
    Header_RefreshingAria: '正在重新整理資料',
    Header_RefreshAria: '重新整理資料',
    Header_RefreshTitle: '重新整理資料（上次更新時間：{when}）',
    Header_NotLoadedYet: '尚未載入',
    Header_JustNow: '剛剛',
    Header_MinutesAgo: '{mins} 分鐘前',
    Header_HoursAgo: '{hours} 小時前',
    Header_PreferencesTitle: '偏好設定',
    Header_PreferencesAria: '開啟偏好設定面板',

    // ── Employee Directory ──
    Directory_LoadingLabel: '正在載入員工...',
    Directory_LoadFailedFallback: '請確認此 Web 組件已取得 User.Read.All 權限。',
    Directory_LoadFailedPrefix: '載入員工失敗。{detail}',
    Directory_AllDepartments: '所有部門',
    Directory_AllOffices: '所有辦公室',
    Directory_StatusDisabled: '已停用',
    Directory_StatusGuest: '來賓',
    Directory_PresenceStatus: '狀態：{status}',
    Directory_ChatInTeams: '在 Teams 中聊天',
    Directory_ChatWithInTeams: '在 Teams 中與 {name} 聊天',
    Directory_ManagesCount: '管理 {direct} 人',
    Directory_ManagesCountWithTotal: '管理 {direct} 人（共 {total} 人）',
    Directory_ReportsCountWithTotal: '{direct}（共 {total}）',
    Directory_ColumnName: '姓名',
    Directory_ColumnJobTitle: '職稱',
    Directory_ColumnDepartment: '部門',
    Directory_ColumnOffice: '辦公室',
    Directory_ColumnEmail: '電子郵件',
    Directory_ColumnPhone: '電話',
    Directory_ColumnReports: '下屬',
    Directory_ColumnChat: '聊天',
    Directory_PrevPage: '上一頁',
    Directory_NextPage: '下一頁',
    Directory_PreviousPageAria: '上一頁',
    Directory_NextPageAria: '下一頁',
    Directory_SearchPlaceholder: '依姓名、職稱、電子郵件或部門搜尋...',
    Directory_SearchAria: '搜尋人員',
    Directory_FilterByDepartmentAria: '依部門篩選',
    Directory_FilterByOfficeAria: '依辦公室篩選',
    Directory_ClearSearchTitle: '清除搜尋與所有篩選條件',
    Directory_ClearButton: '清除',
    Directory_ClearFiltersButton: '清除篩選條件',
    Directory_ExportCsvTitle: '將所有篩選結果匯出為 CSV 檔案（可在 Excel 中開啟）',
    Directory_ExportCsvButton: '匯出 CSV',
    Directory_ViewModeAria: '檢視模式',
    Directory_CardViewTitle: '卡片檢視',
    Directory_ListViewTitle: '清單檢視',
    Directory_AlphabetFilterAria: '字母篩選',
    Directory_ShowAllTitle: '顯示全部',
    Directory_OtherLettersTitle: '篩選以數字或其他字元開頭的姓名',
    Directory_FilterByLetterTitle: '依字母 {letter} 篩選',
    Directory_ResultCountSingular: '人',
    Directory_ResultCountPlural: '人',
    Directory_PageOf: ' · 第 {page} 頁，共 {totalPages} 頁',
    Directory_FilterActiveSingular: '{count} 個篩選條件已套用',
    Directory_FilterActivePlural: '{count} 個篩選條件已套用',
    Directory_NoResults: '找不到符合的人員',
    Directory_PaginationAria: '分頁',

    // ── Org chart toolbar / shared chart chrome ──
    Chart_Layout_Drill: '逐層展開',
    Chart_Layout_Vertical: '由上而下',
    Chart_Layout_Horizontal: '由左至右',
    Chart_SearchPlaceholder: '搜尋人員...',
    Chart_SearchAria: '搜尋人員',
    Chart_MatchSingular: '筆符合項目（樹狀圖中）',
    Chart_MatchPlural: '筆符合項目（樹狀圖中）',
    Chart_ResultsListAria: '人員',
    Chart_ExpandAll: '全部展開',
    Chart_CollapseAll: '全部摺疊',
    Chart_Expanding: '展開中…',
    Chart_Loading: '載入中…',
    Chart_FindMeTitle: '在組織圖中找到我',
    Chart_ViewLayoutButton: '檢視',
    Chart_ViewLayoutTitle: '切換檢視版面配置',
    Chart_ViewLayoutPanelTitle: '檢視版面配置',
    Chart_StatsSummaryTitle: '組織統計摘要',
    Chart_FilterByDepartmentTitle: '依部門篩選',
    Chart_FilterByDepartmentWithCountAria: '依部門篩選（已選取 {count} 項）',
    Chart_FilterByDepartmentPanelTitle: '依部門篩選',
    Chart_ClearAllFilters: '清除所有篩選條件',
    Chart_FilterUserTypesTitle: '篩選使用者類型',
    Chart_DownloadPdfTitle: '下載為 PDF',
    Chart_DownloadCsvTitle: '下載為 CSV 試算表',
    Chart_ResetRootTitle: '重設為預設根節點',
    Chart_ViewFromPersonPlaceholder: '從指定人員檢視…',
    Chart_ViewFromPersonAria: '從指定人員開始檢視組織圖',
    Chart_ZoomOutTitle: '縮小',
    Chart_ZoomInTitle: '放大',
    Chart_ZoomResetTitle: '重設縮放比例',
    Chart_ShowInChartAria: '在組織圖中顯示',
    Chart_ShowInChartTitle: '在組織圖中顯示',
    Chart_FilterMembers: '一般成員',
    Chart_FilterGuests: '來賓使用者',
    Chart_FilterDisabled: '已停用的帳戶',
    Chart_SetupTitle: '設定組織圖',
    Chart_SetupSubtitle: '請輸入最上層人員的電子郵件或 UPN 以開始使用。',
    Chart_SetupPlaceholder: 'ceo@company.com',
    Chart_SetupInputAria: '最上層人員的電子郵件或 UPN',
    Chart_SetupLoadButton: '載入',
    Chart_SetupHint: '您也可以在 Web 組件設定（管理員）中永久設定此項目。',
    Chart_BuildingLabel: '正在建立組織圖...',
    Chart_RetryButton: '重試',
    Chart_NotFoundFromSetup: '找不到使用者「{identifier}」。',
    Chart_NotFoundWithSettings: '找不到使用者「{identifier}」，請在設定中確認 UPN 或電子郵件是否正確。',
    Chart_LoadFailedGeneric: '組織圖載入失敗。{detail}',
    Chart_LoadFailedPermissions: ' 請檢查權限設定。',
    Chart_LoadFailedForPerson: '載入此人員的組織圖失敗。',
    Chart_FindMeNotFound: '在此組織中找不到您的帳戶。',
    Chart_StatPeople: '人員',
    Chart_StatMembers: '成員',
    Chart_StatGuests: '來賓',
    Chart_StatDepts: '部門',
    Chart_ReportingLineAria: '回報線',
    Chart_BackToFullOrgTitle: '返回完整組織圖',
    Chart_FullOrgLabel: '完整組織',
    Chart_FocusOnPerson: '聚焦於 {name}',
    Chart_OrgChartAria: '組織圖',
    Chart_ExportNote_DrillLevel: '目前展開的層級（一層直屬下屬）',
    Chart_ExportNote_PartialLevels: '僅包含已載入的層級 — 若要納入更深的層級，請先使用「全部展開」再匯出',
    Chart_AllowPopupsForPdf: '請允許快顯視窗以匯出 PDF。',

    // ── Person card ──
    PersonCard_ProfileAria: '個人資料：{name}',
    PersonCard_CloseTitle: '關閉',
    PersonCard_CloseAria: '關閉個人資料',
    PersonCard_StatusDisabled: '已停用',
    PersonCard_StatusGuest: '來賓',
    PersonCard_DirectReportSingular: '{count} 名直屬下屬',
    PersonCard_DirectReportPlural: '{count} 名直屬下屬',
    PersonCard_TotalSuffix: ' · 共 {total} 人',
    PersonCard_CopyEmailTitle: '複製電子郵件地址',
    PersonCard_EmailCopiedAria: '電子郵件地址已複製',
    PersonCard_ReportsTo: '回報對象',
    PersonCard_FocusOnPerson: '聚焦於 {name}',
    PersonCard_FocusOrgChartOnPerson: '將組織圖聚焦於 {name}',
    PersonCard_DottedLine: '虛線關係',
    PersonCard_DottedLineManager: '虛線主管：{name}',
    PersonCard_DottedLineReport: '虛線下屬：{name}',
    PersonCard_ChatButton: '聊天',
    PersonCard_EmailButton: '電子郵件',
    PersonCard_FocusButton: '聚焦',
    PersonCard_FocusTitle: '將組織圖聚焦於此人員',

    // ── Org node card ──
    OrgNode_ViewProfile: '檢視 {name} 的個人資料',
    OrgNode_FocusOrgChartOn: '將組織圖聚焦於 {name}',
    OrgNode_Collapse: '摺疊',
    OrgNode_Expand: '展開',
    OrgNode_DirectReportsSuffix: '{name} 的直屬下屬',
    OrgNode_StatusDisabled: '已停用',
    OrgNode_StatusGuest: '來賓',
    OrgNode_TotalReportsAcrossLevels: '{name} 以下所有層級共 {count} 人',

    // ── Drill view ──
    Drill_ReportingLineAria: '回報線',
    Drill_BackToTopTitle: '返回頂端',
    Drill_BackToTopAria: '返回組織圖頂端',
    Drill_GoBackTo: '返回 {name}',
    Drill_ViewProfileTitle: '檢視個人資料',
    Drill_ViewProfileAria: '檢視 {name} 的個人資料',
    Drill_ProfileButton: '個人資料',
    Drill_LoadingLabel: '載入中...',
    Drill_DirectReports: '直屬下屬',
    Drill_DirectReportsOfAria: '{name} 的直屬下屬',
    Drill_DirectReportsAria: '直屬下屬',
    Drill_ViewPersonProfile: '檢視 {name} 的個人資料',
    Drill_ShowPersonReports: '顯示 {name} 的直屬下屬',
    Drill_NoDirectReports: '沒有直屬下屬',

    // ── Settings panel ──
    Settings_AlphabetFirstName: '名字',
    Settings_AlphabetLastName: '姓氏',
    Settings_CardSizeSmall: '小 — 精簡版面，可顯示較多卡片',
    Settings_CardSizeMedium: '中 — 均衡配置',
    Settings_CardSizeLarge: '大 — 版面寬鬆，顯示較少卡片',
    Settings_HeaderText: '偏好設定',
    Settings_SaveButton: '儲存',
    Settings_CancelButton: '取消',
    Settings_DiscardButton: '放棄變更',
    Settings_SectionDirectory: '通訊錄',
    Settings_AlphabetFilterByLabel: '字母篩選依據',
    Settings_CardSizeLabel: '卡片大小',
    Settings_FontSizeLabel: '字型大小',
    Settings_SectionCardsAndFields: '卡片與欄位',
    Settings_ShowOnCardsLabel: '在員工卡片上顯示：',
    Settings_EmailAddressLabel: '電子郵件地址',
    Settings_PhoneNumberLabel: '電話號碼',
    Settings_DepartmentLabel: '部門',
    Settings_OfficeLocationLabel: '辦公室位置',
    Settings_SectionOrgChart: '組織圖',
    Settings_ManagerLevelsLabel: '聚焦某人員時顯示的主管層級數：{levels}',
    Settings_CompactCardsLabel: '精簡卡片',
    Settings_CompactCardsOn: '開啟 — 卡片較小，可同時顯示更多',
    Settings_CompactCardsOff: '關閉 — 標準大小',
    Settings_Hint: '這些偏好設定會儲存在您的瀏覽器中，僅對您本人生效。組織圖主題、預設檢視與版面配置則由您的 SharePoint 管理員設定。',
    Settings_SectionDemoData: '展示資料',
    Settings_DatasetSizeLabel: '資料集大小',
    Settings_PeopleCountSuffix: '{count} 人',

    // ── Export (CSV / PDF) ──
    Export_ColumnName: '姓名',
    Export_ColumnJobTitle: '職稱',
    Export_ColumnDepartment: '部門',
    Export_ColumnOffice: '辦公室',
    Export_ColumnEmail: '電子郵件',
    Export_ColumnPhone: '電話',
    Export_ColumnManager: '主管',
    Export_ColumnLevel: '層級',
    Export_PdfDocumentTitle: '組織圖',
    Export_PdfHeading: '組織架構圖',
    Export_PdfRootLabel: '根節點：{name}',
  };
});
